-- Phase 2: Import venture debt investors into Supabase
-- Source: Venture_Debt.csv (12 records)
-- Date: 2026-04-03
-- Slug auto-generated by trg_investors_slug BEFORE INSERT trigger

BEGIN;

-- =====================================================================
-- 1. UPDATE existing record: Partners for Growth (already in DB)
-- =====================================================================
UPDATE investors SET
  description = 'PFG provides custom debt solutions wherever innovation emerges.',
  website = 'https://www.pfgrowth.com',
  location = 'San Francisco and Sydney',
  stage_focus = ARRAY['Series A','Series B','Series C','Series D+']::text[],
  check_size_min = 2000000,
  check_size_max = 2000000,
  contact_email = 'andy@pfgrowth.com',
  details = '{
    "cheque_size_raw": "$2m",
    "investment_criteria": "Global early stage and growth stage lender, focused on innovation sector companies from software and hardware, life sciences to fintech and asset backed lending.",
    "portfolio": ["Employment Hero","Koala","Techlend","Rezdy","EnviroSuite","Fluent Commerce","Splend","Roller","Damstra","Xplor","MedAdvisor","Prospa"],
    "country_region": "Australia"
  }'::jsonb,
  updated_at = now()
WHERE slug = 'partners-for-growth';

-- =====================================================================
-- 2. INSERT new venture debt investors
-- =====================================================================

-- Advanced.
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Advanced.',
  'R&D Funding and Venture Debt provider based in Queensland, Australia.',
  'venture_debt',
  'Queensland',
  'https://www.getadvanced.com.au',
  NULL,
  NULL,
  NULL,
  'Alex@getadvanced.com.au',
  '{"cheque_size_raw": null, "country_region": "Australia"}'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Dare Capital
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Dare Capital',
  'Provider of R&D Finance to deep-tech and life sciences companies.',
  'venture_debt',
  'Brisbane',
  'https://www.dareaustralia.com',
  NULL,
  NULL,
  NULL,
  'contact@darecapital.com.au',
  '{
    "cheque_size_raw": "No limit",
    "investment_criteria": "Provider of R&D Finance to deep-tech and life sciences companies",
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Founderpath
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Founderpath',
  'Typical terms are $500,000 paid back on a 24-month term at a 7-12% discount rate.',
  'venture_debt',
  'Austin',
  'https://founderpath.com',
  NULL,
  500000,
  500000,
  NULL,
  '{
    "cheque_size_raw": "~$500k",
    "investment_criteria": "SaaS companies doing at least $10,000 in monthly recurring revenue (MRR), with the typical company profile doing between $1 million and $5 million in ARR.",
    "country_region": "USA & North America"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Kashcade
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Kashcade',
  'We forward-fund R&D tax refunds.',
  'venture_debt',
  'Sydney',
  'https://www.kashcade.com',
  ARRAY['Seed','Series A','Series B','Series C','Series D+']::text[],
  20000,
  NULL,
  'hi@kashcade.com',
  '{
    "cheque_size_raw": "$20k+",
    "investment_criteria": "Eligible for R&D Tax Incentive refunds",
    "portfolio": ["Archistar","Great Wrap","Natural MedTech"],
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Lighter Capital
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Lighter Capital',
  'Lighter Capital is completely non-dilutive and takes no warrants or guarantees as security for the funding provided. We have been in the US for over a decade and are the premier revenue-based financer.',
  'venture_debt',
  'Sydney',
  'https://lightercapital.com/australia',
  NULL,
  50000,
  1000000,
  'bkrongold@lightercapital.com',
  '{
    "cheque_size_raw": "$50k-$1m",
    "investment_criteria": "B2B SaaS, 6 month runway",
    "application_url": "https://lightercapital.com/apply/",
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Mighty Partners
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Mighty Partners',
  'Mighty Partners provides flexible, non-dilutive capital to growth stage companies.',
  'venture_debt',
  'Sydney',
  'https://www.mightypartners.com.au',
  ARRAY['Series A','Series B','Series C','Series D+']::text[],
  1000000,
  10000000,
  'gracie@mightypartners.com.au',
  '{
    "cheque_size_raw": "$1m-$10m",
    "investment_criteria": "Technology",
    "portfolio": ["Deckard Technologies","Amber Electric","Butn","Spacer Technologies","WeMoney"],
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- NEU Capital
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'NEU Capital',
  'Anonymised dealroom for any structure equity, debt, hybrid, mezzanine. All investors are vetted with Australia''s largest list of alternative capital, UHNW, family offices, instos, and global investors. All deals on the platform are vetted by an IB Investment Committee.',
  'venture_debt',
  'Sydney',
  'https://www.neu.capital',
  ARRAY['Series D+']::text[],
  20000000,
  200000000,
  'enquiries@neu.capital',
  '{
    "cheque_size_raw": "$20m-$200m",
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Paddington St Finance
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Paddington St Finance',
  'Venture debt provider specialising in R&D Tax Incentive financing and growth capital for AU/NZ companies, with differentiated capability in clean energy and low carbon business models.',
  'venture_debt',
  'Sydney',
  'https://www.paddingtonfinance.com.au',
  NULL,
  500000,
  15000000,
  'ted.dow@paddingtonfinance.com.au',
  '{
    "cheque_size_raw": "$500k-15m",
    "investment_criteria": "AU/NZ companies receiving the R&D Tax Incentive OR ALTERNATIVELY expected to be cash flow breakeven within 6 months based on run-rated earnings or already achieving profitability. Sector agnostic, however, we have differentiated capability in understanding clean energy and low carbon business models.",
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Tractor Ventures
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Tractor Ventures',
  'Tractor Ventures was built to fund tech tractors (strong, reliable and sustainable businesses) in Australia and New Zealand.',
  'venture_debt',
  'Melbourne',
  'https://tractorventures.com',
  NULL,
  50000,
  1000000,
  'hello@tractorventures.com',
  '{
    "cheque_size_raw": "$50k - $1m",
    "investment_criteria": "ANZ based tech companies with strong recurring revenues (min $50k MRR or soon to be) and min 4 months current runway",
    "country_region": "Australia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Western Tech
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Western Tech',
  'Venture debt and growth capital provider investing in technology and life science companies ranging from early-stage private companies to publicly-traded companies.',
  'venture_debt',
  'California',
  'https://westerntech.com',
  NULL,
  250000,
  25000000,
  'andrew@westerntech.com',
  '{
    "cheque_size_raw": "$250k-$25M",
    "investment_criteria": "Invest in technology and life science companies ranging from early-stage private companies to publicly-traded companies",
    "country_region": "USA & North America"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Mars Growth Capital
INSERT INTO investors (name, description, investor_type, location, website, stage_focus, check_size_min, check_size_max, contact_email, details)
VALUES (
  'Mars Growth Capital',
  'Mars Growth Capital is one of the largest private credit platforms in Asia, headquartered in Singapore. With over USD 1 billion in committed capital, Mars was established in 2020 as a joint venture between Liquidity, a global private credit provider, and MUFG, Japan''s largest bank. Taking a global investment perspective, Mars has executed transactions across multiple jurisdictions and supported the growth of nearly 50 companies worldwide. We focus on providing non-dilutive private credit solutions to fast-growing, sponsor-backed enterprises, as well as mid-cap entities.',
  'venture_debt',
  'Singapore',
  'https://www.marsgrowth.com',
  ARRAY['Series A','Series B','Series C','Series D+']::text[],
  5000000,
  100000000,
  'reuben.lim@marsgrowth.com',
  '{
    "cheque_size_raw": "USD 5 million to USD 100 million",
    "portfolio_url": "https://www.marsgrowth.com/portfolio",
    "application_url": "https://www.marsgrowth.com/contact",
    "how_to_apply": "Drop a note on https://www.marsgrowth.com/contact OR send an email to reuben.lim@marsgrowth.com",
    "country_region": "Asia"
  }'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
