/**
 * Canonical LinkedIn sector reference (MES-110 Phase B step 1).
 *
 * GENERATED from the audit CSVs — do not hand-edit. Regenerate with the script
 * used in MES-110 if the source CSVs change:
 *   docs/audits/mes-110/linkedin-industry-codes-147.csv        -> LINKEDIN_INDUSTRY_CODES
 *   docs/audits/mes-110/mapping-v2-industry-groups-to-147.csv  -> V2_GROUP_TO_CODE
 *
 * The DB mirror is public.sectors / public.sector_group_crosswalk
 * (supabase/migrations/20260707141000_add_canonical_sector_reference.sql).
 * The V2 taxonomy the platform runs on stays in ./linkedinTaxonomy.ts; this module
 * adds the stable numeric-code layer and the V2-group -> code crosswalk.
 */

export interface LinkedInIndustryCode {
  /** Stable numeric identifier from the pinned legacy LinkedIn industry-codes table. */
  code: number;
  /** Canonical sector name, verbatim from the pinned table. */
  description: string;
  /** LinkedIn group tags (corp, fin, tech, ...) — optional two-level selector fuel. */
  groups: string[];
}

export const LINKEDIN_INDUSTRY_CODES: readonly LinkedInIndustryCode[] = [
  { code: 1, description: "Defense & Space", groups: ["gov", "tech"] },
  { code: 3, description: "Computer Hardware", groups: ["tech"] },
  { code: 4, description: "Computer Software", groups: ["tech"] },
  { code: 5, description: "Computer Networking", groups: ["tech"] },
  { code: 6, description: "Internet", groups: ["tech"] },
  { code: 7, description: "Semiconductors", groups: ["tech"] },
  { code: 8, description: "Telecommunications", groups: ["gov", "tech"] },
  { code: 9, description: "Law Practice", groups: ["leg"] },
  { code: 10, description: "Legal Services", groups: ["leg"] },
  { code: 11, description: "Management Consulting", groups: ["corp"] },
  { code: 12, description: "Biotechnology", groups: ["gov", "hlth", "tech"] },
  { code: 13, description: "Medical Practice", groups: ["hlth"] },
  { code: 14, description: "Hospital & Health Care", groups: ["hlth"] },
  { code: 15, description: "Pharmaceuticals", groups: ["hlth", "tech"] },
  { code: 16, description: "Veterinary", groups: ["hlth"] },
  { code: 17, description: "Medical Devices", groups: ["hlth"] },
  { code: 18, description: "Cosmetics", groups: ["good"] },
  { code: 19, description: "Apparel & Fashion", groups: ["good"] },
  { code: 20, description: "Sporting Goods", groups: ["good", "rec"] },
  { code: 21, description: "Tobacco", groups: ["good"] },
  { code: 22, description: "Supermarkets", groups: ["good"] },
  { code: 23, description: "Food Production", groups: ["good", "man", "serv"] },
  { code: 24, description: "Consumer Electronics", groups: ["good", "man"] },
  { code: 25, description: "Consumer Goods", groups: ["good", "man"] },
  { code: 26, description: "Furniture", groups: ["good", "man"] },
  { code: 27, description: "Retail", groups: ["good", "man"] },
  { code: 28, description: "Entertainment", groups: ["med", "rec"] },
  { code: 29, description: "Gambling & Casinos", groups: ["rec"] },
  { code: 30, description: "Leisure, Travel & Tourism", groups: ["rec", "serv", "tran"] },
  { code: 31, description: "Hospitality", groups: ["rec", "serv", "tran"] },
  { code: 32, description: "Restaurants", groups: ["rec", "serv"] },
  { code: 33, description: "Sports", groups: ["rec"] },
  { code: 34, description: "Food & Beverages", groups: ["rec", "serv"] },
  { code: 35, description: "Motion Pictures and Film", groups: ["art", "med", "rec"] },
  { code: 36, description: "Broadcast Media", groups: ["med", "rec"] },
  { code: 37, description: "Museums and Institutions", groups: ["art", "med", "rec"] },
  { code: 38, description: "Fine Art", groups: ["art", "med", "rec"] },
  { code: 39, description: "Performing Arts", groups: ["art", "med", "rec"] },
  { code: 40, description: "Recreational Facilities and Services", groups: ["rec", "serv"] },
  { code: 41, description: "Banking", groups: ["fin"] },
  { code: 42, description: "Insurance", groups: ["fin"] },
  { code: 43, description: "Financial Services", groups: ["fin"] },
  { code: 44, description: "Real Estate", groups: ["cons", "fin", "good"] },
  { code: 45, description: "Investment Banking", groups: ["fin"] },
  { code: 46, description: "Investment Management", groups: ["fin"] },
  { code: 47, description: "Accounting", groups: ["corp", "fin"] },
  { code: 48, description: "Construction", groups: ["cons"] },
  { code: 49, description: "Building Materials", groups: ["cons"] },
  { code: 50, description: "Architecture & Planning", groups: ["cons"] },
  { code: 51, description: "Civil Engineering", groups: ["cons", "gov"] },
  { code: 52, description: "Aviation & Aerospace", groups: ["gov", "man"] },
  { code: 53, description: "Automotive", groups: ["man"] },
  { code: 54, description: "Chemicals", groups: ["man"] },
  { code: 55, description: "Machinery", groups: ["man"] },
  { code: 56, description: "Mining & Metals", groups: ["man"] },
  { code: 57, description: "Oil & Energy", groups: ["man"] },
  { code: 58, description: "Shipbuilding", groups: ["man"] },
  { code: 59, description: "Utilities", groups: ["man"] },
  { code: 60, description: "Textiles", groups: ["man"] },
  { code: 61, description: "Paper & Forest Products", groups: ["man"] },
  { code: 62, description: "Railroad Manufacture", groups: ["man"] },
  { code: 63, description: "Farming", groups: ["agr"] },
  { code: 64, description: "Ranching", groups: ["agr"] },
  { code: 65, description: "Dairy", groups: ["agr"] },
  { code: 66, description: "Fishery", groups: ["agr"] },
  { code: 67, description: "Primary/Secondary Education", groups: ["edu"] },
  { code: 68, description: "Higher Education", groups: ["edu"] },
  { code: 69, description: "Education Management", groups: ["edu"] },
  { code: 70, description: "Research", groups: ["edu", "gov"] },
  { code: 71, description: "Military", groups: ["gov"] },
  { code: 72, description: "Legislative Office", groups: ["gov", "leg"] },
  { code: 73, description: "Judiciary", groups: ["gov", "leg"] },
  { code: 74, description: "International Affairs", groups: ["gov"] },
  { code: 75, description: "Government Administration", groups: ["gov"] },
  { code: 76, description: "Executive Office", groups: ["gov"] },
  { code: 77, description: "Law Enforcement", groups: ["gov", "leg"] },
  { code: 78, description: "Public Safety", groups: ["gov"] },
  { code: 79, description: "Public Policy", groups: ["gov"] },
  { code: 80, description: "Marketing and Advertising", groups: ["corp", "med"] },
  { code: 81, description: "Newspapers", groups: ["med", "rec"] },
  { code: 82, description: "Publishing", groups: ["med", "rec"] },
  { code: 83, description: "Printing", groups: ["med", "rec"] },
  { code: 84, description: "Information Services", groups: ["med", "serv"] },
  { code: 85, description: "Libraries", groups: ["med", "rec", "serv"] },
  { code: 86, description: "Environmental Services", groups: ["org", "serv"] },
  { code: 87, description: "Package/Freight Delivery", groups: ["serv", "tran"] },
  { code: 88, description: "Individual & Family Services", groups: ["org", "serv"] },
  { code: 89, description: "Religious Institutions", groups: ["org", "serv"] },
  { code: 90, description: "Civic & Social Organization", groups: ["org", "serv"] },
  { code: 91, description: "Consumer Services", groups: ["org", "serv"] },
  { code: 92, description: "Transportation/Trucking/Railroad", groups: ["tran"] },
  { code: 93, description: "Warehousing", groups: ["tran"] },
  { code: 94, description: "Airlines/Aviation", groups: ["man", "tech", "tran"] },
  { code: 95, description: "Maritime", groups: ["tran"] },
  { code: 96, description: "Information Technology and Services", groups: ["tech"] },
  { code: 97, description: "Market Research", groups: ["corp"] },
  { code: 98, description: "Public Relations and Communications", groups: ["corp"] },
  { code: 99, description: "Design", groups: ["art", "med"] },
  { code: 100, description: "Non-Profit Organization Management", groups: ["org"] },
  { code: 101, description: "Fund-Raising", groups: ["org"] },
  { code: 102, description: "Program Development", groups: ["corp", "org"] },
  { code: 103, description: "Writing and Editing", groups: ["art", "med", "rec"] },
  { code: 104, description: "Staffing and Recruiting", groups: ["corp"] },
  { code: 105, description: "Professional Training & Coaching", groups: ["corp"] },
  { code: 106, description: "Venture Capital & Private Equity", groups: ["fin", "tech"] },
  { code: 107, description: "Political Organization", groups: ["gov", "org"] },
  { code: 108, description: "Translation and Localization", groups: ["corp", "gov", "serv"] },
  { code: 109, description: "Computer Games", groups: ["med", "rec"] },
  { code: 110, description: "Events Services", groups: ["corp", "rec", "serv"] },
  { code: 111, description: "Arts and Crafts", groups: ["art", "med", "rec"] },
  { code: 112, description: "Electrical/Electronic Manufacturing", groups: ["good", "man"] },
  { code: 113, description: "Online Media", groups: ["med"] },
  { code: 114, description: "Nanotechnology", groups: ["gov", "man", "tech"] },
  { code: 115, description: "Music", groups: ["art", "rec"] },
  { code: 116, description: "Logistics and Supply Chain", groups: ["corp", "tran"] },
  { code: 117, description: "Plastics", groups: ["man"] },
  { code: 118, description: "Computer & Network Security", groups: ["tech"] },
  { code: 119, description: "Wireless", groups: ["tech"] },
  { code: 120, description: "Alternative Dispute Resolution", groups: ["leg", "org"] },
  { code: 121, description: "Security and Investigations", groups: ["corp", "org", "serv"] },
  { code: 122, description: "Facilities Services", groups: ["corp", "serv"] },
  { code: 123, description: "Outsourcing/Offshoring", groups: ["corp"] },
  { code: 124, description: "Health, Wellness and Fitness", groups: ["hlth", "rec"] },
  { code: 125, description: "Alternative Medicine", groups: ["hlth"] },
  { code: 126, description: "Media Production", groups: ["med", "rec"] },
  { code: 127, description: "Animation", groups: ["art", "med"] },
  { code: 128, description: "Commercial Real Estate", groups: ["cons", "corp", "fin"] },
  { code: 129, description: "Capital Markets", groups: ["fin"] },
  { code: 130, description: "Think Tanks", groups: ["gov", "org"] },
  { code: 131, description: "Philanthropy", groups: ["org"] },
  { code: 132, description: "E-Learning", groups: ["edu", "org"] },
  { code: 133, description: "Wholesale", groups: ["good"] },
  { code: 134, description: "Import and Export", groups: ["corp", "good", "tran"] },
  { code: 135, description: "Mechanical or Industrial Engineering", groups: ["cons", "gov", "man"] },
  { code: 136, description: "Photography", groups: ["art", "med", "rec"] },
  { code: 137, description: "Human Resources", groups: ["corp"] },
  { code: 138, description: "Business Supplies and Equipment", groups: ["corp", "man"] },
  { code: 139, description: "Mental Health Care", groups: ["hlth"] },
  { code: 140, description: "Graphic Design", groups: ["art", "med"] },
  { code: 141, description: "International Trade and Development", groups: ["gov", "org", "tran"] },
  { code: 142, description: "Wine and Spirits", groups: ["good", "man", "rec"] },
  { code: 143, description: "Luxury Goods & Jewelry", groups: ["good"] },
  { code: 144, description: "Renewables & Environment", groups: ["gov", "man", "org"] },
  { code: 145, description: "Glass, Ceramics & Concrete", groups: ["cons", "man"] },
  { code: 146, description: "Packaging and Containers", groups: ["good", "man"] },
  { code: 147, description: "Industrial Automation", groups: ["cons", "man"] },
  { code: 148, description: "Government Relations", groups: ["gov"] },
] as const;

/** LinkedIn V2 industry group (intake vocabulary) -> canonical code + matcher sector slug. */
export const V2_GROUP_TO_CODE: Readonly<Record<string, { code: number; v2SectorSlug: string }>> = {
  "Food and Beverage Services": { code: 34, v2SectorSlug: "accommodation-and-food-services" },
  "Hospitality": { code: 31, v2SectorSlug: "accommodation-and-food-services" },
  "Collection Agencies": { code: 43, v2SectorSlug: "administrative-and-support-services" },
  "Events Services": { code: 110, v2SectorSlug: "administrative-and-support-services" },
  "Facilities Services": { code: 122, v2SectorSlug: "administrative-and-support-services" },
  "Fundraising": { code: 101, v2SectorSlug: "administrative-and-support-services" },
  "Office Administration": { code: 123, v2SectorSlug: "administrative-and-support-services" },
  "Security and Investigations": { code: 121, v2SectorSlug: "administrative-and-support-services" },
  "Telephone Call Centers": { code: 123, v2SectorSlug: "administrative-and-support-services" },
  "Staffing and Recruiting": { code: 104, v2SectorSlug: "administrative-and-support-services" },
  "Translation and Localization": { code: 108, v2SectorSlug: "administrative-and-support-services" },
  "Travel Arrangements": { code: 30, v2SectorSlug: "administrative-and-support-services" },
  "Writing and Editing": { code: 103, v2SectorSlug: "administrative-and-support-services" },
  "Building Construction": { code: 48, v2SectorSlug: "construction" },
  "Civil Engineering": { code: 51, v2SectorSlug: "construction" },
  "Specialty Trade Contractors": { code: 48, v2SectorSlug: "construction" },
  "Civic and Social Organizations": { code: 90, v2SectorSlug: "consumer-services" },
  "Household Services": { code: 91, v2SectorSlug: "consumer-services" },
  "Non-profit Organizations": { code: 100, v2SectorSlug: "consumer-services" },
  "Personal and Laundry Services": { code: 91, v2SectorSlug: "consumer-services" },
  "Philanthropic Fundraising Services": { code: 131, v2SectorSlug: "consumer-services" },
  "Religious Institutions": { code: 89, v2SectorSlug: "consumer-services" },
  "Repair and Maintenance": { code: 91, v2SectorSlug: "consumer-services" },
  "E-Learning Providers": { code: 132, v2SectorSlug: "education" },
  "Higher Education": { code: 68, v2SectorSlug: "education" },
  "Primary and Secondary Education": { code: 67, v2SectorSlug: "education" },
  "Professional Training and Coaching": { code: 105, v2SectorSlug: "education" },
  "Technical and Vocational Training": { code: 105, v2SectorSlug: "education" },
  "Artists and Writers": { code: 38, v2SectorSlug: "entertainment-providers" },
  "Museums, Historical Sites, and Zoos": { code: 37, v2SectorSlug: "entertainment-providers" },
  "Musicians": { code: 115, v2SectorSlug: "entertainment-providers" },
  "Performing Arts and Spectator Sports": { code: 39, v2SectorSlug: "entertainment-providers" },
  "Recreational Facilities": { code: 40, v2SectorSlug: "entertainment-providers" },
  "Spectator Sports": { code: 33, v2SectorSlug: "entertainment-providers" },
  "Farming": { code: 63, v2SectorSlug: "farming-ranching-forestry" },
  "Ranching and Fisheries": { code: 64, v2SectorSlug: "farming-ranching-forestry" },
  "Forestry and Logging": { code: 61, v2SectorSlug: "farming-ranching-forestry" },
  "Capital Markets": { code: 129, v2SectorSlug: "financial-services" },
  "Credit Intermediation": { code: 41, v2SectorSlug: "financial-services" },
  "Funds and Trusts": { code: 46, v2SectorSlug: "financial-services" },
  "Insurance": { code: 42, v2SectorSlug: "financial-services" },
  "Administration of Justice": { code: 73, v2SectorSlug: "government-administration" },
  "Economic Programs": { code: 75, v2SectorSlug: "government-administration" },
  "Environmental Quality Programs": { code: 86, v2SectorSlug: "government-administration" },
  "Health and Human Services": { code: 75, v2SectorSlug: "government-administration" },
  "Housing and Community Development": { code: 75, v2SectorSlug: "government-administration" },
  "Military and International Affairs": { code: 71, v2SectorSlug: "government-administration" },
  "Public Policy": { code: 79, v2SectorSlug: "government-administration" },
  "Public Policy Offices": { code: 79, v2SectorSlug: "government-administration" },
  "Space Research and Technology": { code: 1, v2SectorSlug: "government-administration" },
  "Holding Companies": { code: 46, v2SectorSlug: "holding-companies" },
  "Community Services": { code: 88, v2SectorSlug: "hospitals-and-health-care" },
  "Hospitals, Individual and Family Services": { code: 14, v2SectorSlug: "hospitals-and-health-care" },
  "Medical Practices": { code: 13, v2SectorSlug: "hospitals-and-health-care" },
  "Nursing Homes and Residential Care Facilities": { code: 14, v2SectorSlug: "hospitals-and-health-care" },
  "Apparel Manufacturing": { code: 19, v2SectorSlug: "manufacturing" },
  "Appliances, Electrical, and Electronics Manufacturing": { code: 112, v2SectorSlug: "manufacturing" },
  "Chemical Manufacturing": { code: 54, v2SectorSlug: "manufacturing" },
  "Computers and Electronics Manufacturing": { code: 3, v2SectorSlug: "manufacturing" },
  "Fabricated Metal Products": { code: 55, v2SectorSlug: "manufacturing" },
  "Food and Beverage Manufacturing": { code: 23, v2SectorSlug: "manufacturing" },
  "Furniture and Home Furnishings Manufacturing": { code: 26, v2SectorSlug: "manufacturing" },
  "Glass, Ceramics and Concrete Manufacturing": { code: 145, v2SectorSlug: "manufacturing" },
  "Leather Product Manufacturing": { code: 19, v2SectorSlug: "manufacturing" },
  "Machinery Manufacturing": { code: 55, v2SectorSlug: "manufacturing" },
  "Medical Equipment Manufacturing": { code: 17, v2SectorSlug: "manufacturing" },
  "Oil and Coal Product Manufacturing": { code: 57, v2SectorSlug: "manufacturing" },
  "Paper and Forest Product Manufacturing": { code: 61, v2SectorSlug: "manufacturing" },
  "Plastics and Rubber Product Manufacturing": { code: 117, v2SectorSlug: "manufacturing" },
  "Primary Metal Manufacturing": { code: 56, v2SectorSlug: "manufacturing" },
  "Printing Services": { code: 83, v2SectorSlug: "manufacturing" },
  "Sporting Goods Manufacturing": { code: 20, v2SectorSlug: "manufacturing" },
  "Textile Manufacturing": { code: 60, v2SectorSlug: "manufacturing" },
  "Tobacco Manufacturing": { code: 21, v2SectorSlug: "manufacturing" },
  "Transportation Equipment Manufacturing": { code: 53, v2SectorSlug: "manufacturing" },
  "Wood Product Manufacturing": { code: 61, v2SectorSlug: "manufacturing" },
  "Mining": { code: 56, v2SectorSlug: "oil-gas-and-mining" },
  "Oil and Gas": { code: 57, v2SectorSlug: "oil-gas-and-mining" },
  "Accounting": { code: 47, v2SectorSlug: "professional-services" },
  "Advertising Services": { code: 80, v2SectorSlug: "professional-services" },
  "Architecture and Planning": { code: 50, v2SectorSlug: "professional-services" },
  "Business Consulting and Services": { code: 11, v2SectorSlug: "professional-services" },
  "Design Services": { code: 99, v2SectorSlug: "professional-services" },
  "Engineering Services": { code: 135, v2SectorSlug: "professional-services" },
  "IT Services and IT Consulting": { code: 96, v2SectorSlug: "professional-services" },
  "Legal Services": { code: 10, v2SectorSlug: "professional-services" },
  "Research Services": { code: 70, v2SectorSlug: "professional-services" },
  "Services for Renewable Energy": { code: 144, v2SectorSlug: "professional-services" },
  "Veterinary Services": { code: 16, v2SectorSlug: "professional-services" },
  "Equipment Rental Services": { code: 138, v2SectorSlug: "real-estate-and-equipment-rental-services" },
  "Real Estate": { code: 44, v2SectorSlug: "real-estate-and-equipment-rental-services" },
  "Food and Beverage Retail": { code: 22, v2SectorSlug: "retail" },
  "Online and Mail Order Retail": { code: 27, v2SectorSlug: "retail" },
  "Retail Apparel and Fashion": { code: 19, v2SectorSlug: "retail" },
  "Retail Appliances, Electrical, and Electronic Equipment": { code: 24, v2SectorSlug: "retail" },
  "Retail Art Dealers": { code: 38, v2SectorSlug: "retail" },
  "Retail Art Supplies": { code: 111, v2SectorSlug: "retail" },
  "Retail Books and Printed News": { code: 27, v2SectorSlug: "retail" },
  "Retail Building Materials and Garden Equipment": { code: 49, v2SectorSlug: "retail" },
  "Retail Florists": { code: 27, v2SectorSlug: "retail" },
  "Retail Furniture and Home Furnishings": { code: 26, v2SectorSlug: "retail" },
  "Retail Gasoline": { code: 57, v2SectorSlug: "retail" },
  "Retail Health and Personal Care Products": { code: 27, v2SectorSlug: "retail" },
  "Retail Luxury Goods and Jewelry": { code: 143, v2SectorSlug: "retail" },
  "Retail Motor Vehicles": { code: 53, v2SectorSlug: "retail" },
  "Retail Musical Instruments": { code: 27, v2SectorSlug: "retail" },
  "Retail Office Equipment": { code: 138, v2SectorSlug: "retail" },
  "Retail Office Supplies and Gifts": { code: 138, v2SectorSlug: "retail" },
  "Retail Recyclable Materials and Used Merchandise": { code: 27, v2SectorSlug: "retail" },
  "Book and Periodical Publishing": { code: 82, v2SectorSlug: "technology-information-and-media" },
  "Broadcast Media Production and Distribution": { code: 36, v2SectorSlug: "technology-information-and-media" },
  "Data Infrastructure and Analytics": { code: 84, v2SectorSlug: "technology-information-and-media" },
  "Information Services": { code: 84, v2SectorSlug: "technology-information-and-media" },
  "Internet Marketplace Platforms": { code: 6, v2SectorSlug: "technology-information-and-media" },
  "Movies, Videos, and Sound": { code: 35, v2SectorSlug: "technology-information-and-media" },
  "Social Networking Platforms": { code: 6, v2SectorSlug: "technology-information-and-media" },
  "Software Development": { code: 4, v2SectorSlug: "technology-information-and-media" },
  "Telecommunications": { code: 8, v2SectorSlug: "technology-information-and-media" },
  "Airlines and Aviation": { code: 94, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Freight and Package Transportation": { code: 87, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Ground Passenger Transportation": { code: 92, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Maritime Transportation": { code: 95, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Pipeline Transportation": { code: 57, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Postal Services": { code: 87, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Rail Transportation": { code: 92, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Truck Transportation": { code: 92, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Warehousing and Storage": { code: 93, v2SectorSlug: "transportation-logistics-supply-chain-and-storage" },
  "Electric Power Generation": { code: 59, v2SectorSlug: "utilities" },
  "Electric Power Transmission, Control, and Distribution": { code: 59, v2SectorSlug: "utilities" },
  "Natural Gas Distribution": { code: 59, v2SectorSlug: "utilities" },
  "Water, Waste, Steam, and Air Conditioning Services": { code: 59, v2SectorSlug: "utilities" },
  "Wholesale Alcoholic Beverages": { code: 142, v2SectorSlug: "wholesale" },
  "Wholesale Apparel and Sewing Supplies": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Appliances, Electrical, and Electronics": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Building Materials": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Chemical and Allied Products": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Computer Equipment": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Drugs and Sundries": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Food and Beverage": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Footwear": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Furniture and Home Furnishings": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Hardware, Plumbing, Heating Equipment": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Import and Export": { code: 134, v2SectorSlug: "wholesale" },
  "Wholesale Luxury Goods and Jewelry": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Machinery": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Metals and Minerals": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Motor Vehicles and Parts": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Paper Products": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Petroleum and Petroleum Products": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Photography Equipment and Supplies": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Raw Farm Products": { code: 133, v2SectorSlug: "wholesale" },
  "Wholesale Recyclable Materials": { code: 133, v2SectorSlug: "wholesale" },
};

const BY_CODE = new Map(LINKEDIN_INDUSTRY_CODES.map((c) => [c.code, c]));

export function getIndustryByCode(code: number): LinkedInIndustryCode | undefined {
  return BY_CODE.get(code);
}

/** Canonical code for a V2 industry-group label, or undefined for unknown values. */
export function getCodeForV2Group(group: string): number | undefined {
  return V2_GROUP_TO_CODE[group]?.code;
}
