BEGIN;

UPDATE community_members SET description = 'Leads Export Development Canada''s Oceania business development from Sydney, originating corporate loans and supporting Canadian exporters across energy, infrastructure and mining in Australia and New Zealand. A useful first port of call for Canadian companies evaluating ANZ market entry, project finance or local partnerships. · Highlights: 20+ years in international business development and financial services · Joined EDC in 1999; previously Regional Manager for Mexico and Africa · Board member, Canadian Australian Chamber of Commerce', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Export Finance', 'Project Finance', 'Canada-ANZ Trade'])), updated_at = now() WHERE slug = 'diane-belliveau';

UPDATE community_members SET description = 'Helps stand up and run Austrade''s Southeast Asia Landing Pads in Ho Chi Minh City and Jakarta, supporting Australian tech scaleups in fintech, AI, cyber, quantum and cleantech to expand into the region. Previously advised inbound investors from the Americas, Europe, Middle East and Africa on Australian market entry, FIRB processes and partner introductions. · Highlights: Helped launch Austrade Landing Pads in Jakarta and Ho Chi Minh City · Sector focus: Fintech, AI, Cyber, Quantum, Cleantech', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Soft Landing', 'Tech Scaleup', 'Southeast Asia'])), updated_at = now() WHERE slug = 'william-johnson';

UPDATE community_members SET description = 'Directs Austrade''s global Landing Pads program, which gives Australian tech companies hands-on market entry support, workspace and curated introductions across Singapore, San Francisco, the UK, Ho Chi Minh City and Jakarta. Useful contact for founders mapping international expansion pathways or seeking government-backed soft-landing infrastructure. · Highlights: Oversees 5 Landing Pads markets: Singapore, San Francisco, UK, Ho Chi Minh City, Jakarta · Previously Trade and Investment Commissioner roles in Vietnam, Cambodia and New York', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Soft Landing', 'Tech Scaleup', 'Global Expansion'])), updated_at = now() WHERE slug = 'madeline-ferguson';

UPDATE community_members SET description = 'Heads Investment NSW''s Investment and Industry function, leading attraction and acceleration of major projects into New South Wales, including work with the Investment Delivery Authority. Previously Austrade''s Senior Trade & Investment Commissioner for the UK and Ireland, with deep experience advising international corporates on Australian market entry across energy, advanced manufacturing and infrastructure. · Highlights: Former Austrade Senior Trade & Investment Commissioner, UK & Ireland · 16 years in the USA including President, North America at EGR Group · MSc Technology Commercialization, UT Austin McCombs', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['FDI Attraction', 'Major Projects', 'UK/Ireland-ANZ'])), updated_at = now() WHERE slug = 'david-camerlengo';

UPDATE community_members SET description = 'Leads precinct development at Investment NSW, building out innovation precincts and hubs (including the Western Sydney Startup Hub) to grow scaleups in NSW priority sectors. Originally from Ireland, Carol is a useful contact for international founders seeking landing-pad style infrastructure, ecosystem introductions and entrepreneurship programs in Sydney. · Highlights: Helped launch the Western Sydney Startup Hub · Previously Director, Arts & Entrepreneurship at Investment NSW · MA Dublin City University; BA NUI Maynooth', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Innovation Precincts', 'Startup Ecosystem', 'Soft Landing'])), updated_at = now() WHERE slug = 'carol-friel';

UPDATE community_members SET description = 'Sits within Investment NSW''s Investment Delivery Authority as Senior Associate, Investment Concierge & Strategic Advisory, providing case-managed support to international investors landing major projects in New South Wales. Background spans technology and cyber investment partnerships and private-sector investment management, making her a practical contact for inbound corporates navigating NSW approvals, sites and incentives. · Highlights: Part of NSW''s Investment Delivery Authority case management team · Previously Associate, Industry & Investment Partnerships (Tech & Cyber) at Investment NSW', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Investor Concierge', 'FDI Attraction', 'Cross-border'])), updated_at = now() WHERE slug = 'emily-cusick';

UPDATE community_members SET description = 'Runs program operations at Investment NSW, designing and delivering startup and scaleup programs for the NSW innovation ecosystem. Previously created and led startup programs at the University of Sydney''s INCUBATE accelerator, and brings founder and angel investor experience to advising early-stage companies on go-to-market, programs and capital pathways in Australia. · Highlights: Creator and Head of Startup Programs at USYD INCUBATE · Active angel investor and multi-time founder', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Startup Programs', 'Accelerator', 'Angel Investing'])), updated_at = now() WHERE slug = 'david-smith';

UPDATE community_members SET description = 'Operates dual roles as Senior Export Adviser at Investment NSW and a TradeStart Adviser delivered in partnership with Austrade, providing free, tailored coaching to NSW SMEs on entering and scaling in offshore markets. Useful counterpart for international advisers and chambers coordinating two-way trade with NSW exporters across goods, services and tech. · Highlights: 15+ years in international trade · TradeStart Adviser in partnership with Austrade · Based at Investment NSW, Martin Place Sydney', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Export Coaching', 'SME Trade', 'TradeStart'])), updated_at = now() WHERE slug = 'kutay-kesim';

UPDATE community_members SET description = 'Represents Scottish Development International from Melbourne as Senior Trade Specialist for Science and Technology, connecting Scottish companies (fintech, space, life sciences, advanced engineering) with Australian customers, partners and investors. Previously Senior Policy Analyst at Global Victoria, with prior roles at Trade and Investment Queensland, giving her broad cross-jurisdiction experience. · Highlights: 24+ years in trade and investment roles · Previously Senior Policy Analyst at Global Victoria · Earlier roles with Trade and Investment Queensland', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Scotland-ANZ', 'Science & Technology', 'Fintech'])), updated_at = now() WHERE slug = 'cindy-callander';

UPDATE community_members SET description = 'Leads Catalonia Trade & Investment''s Sydney office, the Catalan Government''s commercial arm in ANZ, supporting Catalan startups, SMEs and corporates entering Australia and New Zealand across priority sectors including ICT, life sciences, mobility and food. Connects Catalan exporters and investors with local partners, distributors, channels and government touchpoints across the region. · Highlights: Director of Catalonia Trade & Investment Sydney since 2015 · Former Trade General Director, Catalan Government · Master in Public Administration, ESADE Business School', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Catalonia-AU corridor', 'SME export support', 'FDI Promotion'])), updated_at = now() WHERE slug = 'gemma-puig';

UPDATE community_members SET description = 'Heads Enterprise Ireland''s Australia & New Zealand operation from Sydney, leading the Irish state agency''s mandate to help Irish-owned exporters scale into ANZ. Works across the portfolio of Irish companies in tech, fintech, agritech, construction tech and life sciences, opening doors to local buyers, channel partners and tier-one customers across both markets. · Highlights: Oversees ~300 Enterprise Ireland-supported clients exporting to Australia and ~150 to NZ · Cited Irish exports to ANZ growing nearly 60% over five years', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Ireland-ANZ corridor', 'Irish Exporter Support', 'Tech & Agritech'])), updated_at = now() WHERE slug = 'lydia-r';

UPDATE community_members SET description = 'Represents IDA Ireland, Ireland''s inward investment promotion agency, across Australia and New Zealand. Engages ANZ corporates and investors evaluating Ireland as a base for European operations, working across IDA''s priority sectors of technology, financial services, life sciences and engineering, and supporting site selection, talent and incentive pathways into Ireland. · Highlights: Director, Australia & New Zealand at IDA Ireland', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['ANZ-Ireland FDI', 'FDI Attraction', 'European HQ Setup'])), updated_at = now() WHERE slug = 'marko-previsic';

UPDATE community_members SET description = 'Deputy Director at KOTRA Sydney, the Korean Government''s trade and investment promotion agency, supporting Korean exporters and investors entering Australia and helping local buyers source from Korea. Works across KOTRA''s mandate of trade promotions, buyer matching, market entry research and inbound/outbound investment facilitation between Korea and ANZ. · Highlights: Deputy Director, KOTRA Sydney', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Korea-AU corridor', 'Buyer Matching', 'Trade Promotion'])), updated_at = now() WHERE slug = 'hanhanaellena-cho';

UPDATE community_members SET description = 'Senior Trade Adviser in the Technology & Services team at Investment NSW, the NSW Government''s trade and investment agency. Advises NSW-based tech and services exporters on market entry strategy, export readiness and in-market connections, with a focus on opening Korea and broader Asia channels for Australian companies scaling internationally. · Highlights: Export/Trade Advisory, Technology & Services, Investment NSW', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Korea-AU corridor', 'Tech Exports', 'Export Advisory'])), updated_at = now() WHERE slug = 'sarah-kim';

UPDATE community_members SET description = 'Directs the Hong Kong Trade Development Council''s operation across Australia and New Zealand from Sydney, promoting two-way trade, investment and SME partnerships between Hong Kong and ANZ. Connects Hong Kong exporters, manufacturers and service firms to Australian buyers and channels, and supports ANZ companies using Hong Kong as a gateway into Greater China and ASEAN. · Highlights: Director, Australia & New Zealand at HKTDC · 30+ years in Asia-Pacific marketing and business development · AGSM @ UNSW Business School', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Hong Kong-ANZ corridor', 'Greater China Gateway', 'SME Trade'])), updated_at = now() WHERE slug = 'bonnie-shek';

UPDATE community_members SET description = 'Market Advisor for Agribusiness and Waste Sustainability at Enterprise Ireland''s Melbourne office, supporting Irish companies entering ANZ across agricultural machinery, agritech software and devices, animal health, veterinary pharmaceuticals, and waste-sector equipment and technology. Connects Irish exporters with ANZ farmers, processors, distributors and waste operators. · Highlights: Market Advisor, Agribusiness & Waste Sustainability, Enterprise Ireland A/NZ · Based in Melbourne covering Australia and New Zealand', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Ireland-ANZ corridor', 'Agritech', 'Waste & Sustainability'])), updated_at = now() WHERE slug = 'eoin-hughes';

UPDATE community_members SET description = 'Advisory Board Member to Enterprise Ireland Australia & New Zealand, based in the Waikato, advising on Irish exporter strategy into the NZ market. Brings a venture and scale-up lens from roles across deep tech investment, startup accelerators and innovation ecosystems spanning Ireland, the US, China, Hong Kong and New Zealand, useful for Irish founders entering ANZ. · Highlights: Advisory Board Member, Enterprise Ireland A/NZ · Investment Manager at WNT Ventures (NZ deep tech) · BComm (Intl) UCD; MSc HKUST Business School', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Ireland-NZ corridor', 'Deep Tech & Scaleup', 'Venture & Innovation'])), updated_at = now() WHERE slug = 'niamh-given';

UPDATE community_members SET description = 'Director, International Investment - Asia & MENA at Invest Victoria, the Victorian Government''s FDI agency. Leads investment attraction from Asia and the Middle East into Victoria, working with corporates, sovereign investors and family offices on site selection, expansion and JV opportunities across Melbourne''s priority sectors including food, advanced manufacturing, health and tech. · Highlights: Director, International Investment Asia & MENA at Invest Victoria', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Asia-Victoria FDI', 'MENA-Victoria FDI', 'Investment Attraction'])), updated_at = now() WHERE slug = 'annie-jiang';

UPDATE community_members SET description = 'Trade Manager - Technology at Global Victoria, the Victorian Government''s trade agency, supporting Victorian tech companies expanding into international markets. Designs and leads outbound trade missions and in-market programs across cybersecurity, software, sportstech and digital, connecting Victorian scaleups to overseas buyers, partners and flagship events such as VivaTech and RSA Conference. · Highlights: Manager, Trade Technology at Global Victoria · Former Austrade EMDG consultant · Bachelor of Commerce, Deakin University', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Victoria Tech Exports', 'Cyber & SportsTech', 'Trade Missions'])), updated_at = now() WHERE slug = 'troy-toohey';

UPDATE community_members SET description = 'Sharesies is a NZ-born micro-investing platform that opened share market access from a $5 minimum. As Co-Founder and Director, Roberts brings frontline experience scaling a regulated fintech across NZ and Australia, raising capital, and building a brand around financial inclusion. Useful for founders tackling consumer fintech, trans-Tasman expansion, and product-led growth. · Highlights: Co-founded Sharesies in 2017 · Platform reached ~700,000 active users across NZ and Australia · Joint winner, 2020 NZ Women of Influence Award (Business Enterprise)', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Fintech Founder Mentor', 'Trans-Tasman Expansion', 'Consumer Product Scaling'])), updated_at = now() WHERE slug = 'brooke-roberts';

UPDATE community_members SET description = 'WeBridge Partners is a Sydney-based consultancy helping asset management, wealth management and fund admin firms scope and execute platform transformations. As Founder, Marsham draws on a London-New York-Sydney career across asset management trading desks, hedge fund operations and middle-market financial services. Helpful for UK and European fintech and wealth firms entering Australia.', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Wealth & Asset Management', 'UK to Australia Expansion', 'Fintech Operations'])), updated_at = now() WHERE slug = 'jason-marsham';

UPDATE community_members SET description = 'Techvisa is an Australian migration agency specialising in visa and global mobility solutions for technology companies and talent across Australia, Singapore, the US and the UK. As Head of Community, Zocher works with founders and scale-ups to navigate Australian immigration law, sponsor international hires, and unlock global talent pools. A practical resource for any tech company relocating staff into Australia.', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Global Mobility', 'Tech Visas & Immigration', 'Startup Ecosystem'])), updated_at = now() WHERE slug = 'zach-zocher';

UPDATE community_members SET description = 'Foley is a Sydney and Brisbane-based international trade and investment advisory that helps companies succeed in cross-border markets. As Principal Consultant, Price advises on market entry, business development and stakeholder engagement, drawing on a UK-to-Australia career across government, university and private-sector roles in the education and training sector. Holds a Master of Development Studies from UNSW.', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['International Trade Advisory', 'Market Entry Strategy', 'Stakeholder Engagement'])), updated_at = now() WHERE slug = 'laurie-price';

UPDATE community_members SET description = 'Squeeze is a SaaS platform for the accounting profession, helping firms and small business owners run smoother operations. As Co-Founder and Group COO, Connolly leads operations, scales teams and brings over a decade of digital and people transformation across the accounting sector. Also Founder at Practice Connections Advisory and a GAICD; a strong resource for Irish and European SaaS founders moving into Australia. · Highlights: GAICD (Australian Institute of Company Directors) · Masters in Accounting, University of Galway', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['SaaS Operations', 'Ireland to Australia Expansion', 'Accounting Tech'])), updated_at = now() WHERE slug = 'olwyn-connolly';

UPDATE community_members SET description = 'East West World Private Equity is a Sydney-based firm focused on capital formation for the animation, digital media and creative industries, structuring co-venture alliances across production, technology and finance. Founder Brian Walsh brings a US-to-Australia career spanning venture capital, growth-stage capital raising and creative-industry deal-making. Useful for founders in animation, gaming, IP-led media and other creative sectors.', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Creative Industries', 'US to Australia Expansion', 'Venture & Growth Capital'])), updated_at = now() WHERE slug = 'brian-walsh';

UPDATE community_members SET description = 'AgriTech New Zealand is the membership-funded industry body for NZ''s agritech sector, launched in 2018 to grow the country''s agricultural technology ecosystem. As Chief Executive, O''Connell leads sector strategy, international missions and member growth, drawing on 16+ years in the primary sector and a prior role as NZ Pathfinder at Enterprise Ireland. A strong contact for Irish and European agritech founders eyeing ANZ. · Highlights: Chief Executive of AgriTech New Zealand · Former NZ Pathfinder at Enterprise Ireland · 16+ years in the primary sector', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['Agritech', 'Ireland to ANZ', 'Industry Body Leadership'])), updated_at = now() WHERE slug = 'brendan-oconnell';

UPDATE community_members SET description = 'LaunchPad is positioned as APAC''s leading GTM community, helping tech sales professionals advance their careers and SaaS companies build strong go-to-market teams. Co-Founder Daniel Grindrod brings a UK-to-Sydney path across talent acquisition and SaaS scaling, and also runs 4Twenty Consulting and Tech Talks Australia. Useful for UK and European SaaS founders building APAC GTM teams from Sydney. · Highlights: Co-Founder of LaunchPad · Co-Founder & Director of 4Twenty Consulting (since 2016) · Founder of Tech Talks Australia', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['GTM & Tech Sales', 'UK to APAC Expansion', 'SaaS Talent'])), updated_at = now() WHERE slug = 'daniel-grindrod';

UPDATE community_members SET description = 'FACCI, the French-Australian Chamber of Commerce & Industry, is the bilateral business network connecting French and Australian companies through events, advocacy and trade services. As General Manager since 2019, Fournand leads operations across FACCI''s chapters and coordinates with Team France (Embassy, Consulate, Alliance Francaise). Brings a French-to-Australia career spanning Microsoft France, startups and Sydney operations leadership. · Highlights: General Manager of FACCI since March 2019 · Former Head of Operations, GDR Group (Sydney) · Began career at Microsoft France', specialties = ARRAY(SELECT DISTINCT unnest(specialties || ARRAY['France to Australia Expansion', 'Bilateral Trade', 'Chamber & Network Leadership'])), updated_at = now() WHERE slug = 'jerome-fournand';

COMMIT;
