INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Bryan Cleary', 'Founder - eCommerce Growth Consultant & CRO Specialist', 'Founder | eCommerce Growth Consultant | Shopify/Shopify Plus expert | Ecommerce Coach at BOOM · Ecommerce growth consultant with over 14 years of experience in digital product, project and account management while working across scoping, UX/Design, web development, branding and digital marketing I have become an expert in ensuring that clients achieve their goals. I have worked with a diverse range of clients from the E-Commerce, NFP, Education and Pharmaceutical sectors helping each to transform their organisations through technology.I now focus on 1 to 1 e-commerce consulting taking a ho', 'Greater Sydney Area', '14+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Sales / GTM'], 'https://linkedin.com/in/bryan-cleary-2080208a', NULL, NULL, 'Va-va Voom Digital', FALSE, '[{"name": "Va-va Voom Digital"}, {"name": "Boom - Aussie Ecommerce Training"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'bryan-cleary', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Daniel Cannizzaro', 'Founding Partner', 'Advisor | Entrepreneur | Investor · Hey there I’m a trusted strategic advisor, entrepreneur, and former regulated fintech founder and CEO and global financial services management consultant, with a unique mix of ~20 years advisory, founder, operator & investor experience.I was recently the founder & CEO of Parpera, a B2B fintech that aspired to improve global economic prosperity by making it easier for people to do business.I’m passionate about solving challenging strategy, operations, technology and risk issues – particularly th', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/danielcannizzaro', NULL, NULL, 'Vida Venture Partners', FALSE, '[{"name": "Vida Venture Partners"}, {"name": "Global Growth Partners"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'daniel-cannizzaro', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Dion Chamberlain', 'General Manager, Engagement Data and Innovation (Secondment)', 'Director International and Product Strategy | Digital Travel Credentials | Chief Advisor - Traveller Identification | Chair ICAO ICBWG | Biometrics | ICAO FAL & TAG TRIP | International Relations | Identity and Passports · Experienced senior leader responsible for developing and maintaining the strategic direction of identity products, services and investments, representing national and strategic views on traveller identification and facilitation, and forming partnerships domestically and internationally to make passports and border facilitation better and safer for New Zealanders, the Pacific and the wider traveller and identity ecosystem.', 'Wellington, Wellington, New Zealand', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Technology / Product', 'Cross-border'], 'https://linkedin.com/in/dion-chamberlain-b853a97b', NULL, NULL, 'Department of Internal Affairs (NZ)', FALSE, '[{"name": "Department of Internal Affairs (NZ)"}, {"name": "International Civil Aviation Organization"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'dion-chamberlain', 'Scaled Founder', ARRAY['both'], TRUE, FALSE),
  ('Stevie-Ann Dovico', 'Group Executive Technology', 'Group Executive Technology | CIO50 2024 & 2025 | IT News Financial Services Technology Leader of the Year 2025 | Executive Leader of the Year 2022 Women in Digital | GAICD · Stevie is a dynamic and visionary Business and Technology leader with 20 years of experience in Banking, Financial Services, Telecommunications and Consulting. She has proven experience as a Group Executive, Chief Information Officer (CIO), Board Director, Advisory Board and Committee Member and as an Executive General Manager of Technology for some of Australia’s largest organisations. Stevie has successfully led large, cross functional, global teams of over 600 employees, across Technology, Di', 'Sydney, New South Wales, Australia', '20+ years operating experience in ANZ and international markets.', ARRAY['Scaled Founder', 'Financial Services', 'Recognised Industry Leader'], 'https://linkedin.com/in/stevieanndovico', NULL, NULL, 'Beyond Bank Australia', FALSE, '[{"name": "Beyond Bank Australia"}, {"name": "NAB"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'stevie-ann-dovico', 'Scaled Founder', ARRAY['both'], TRUE, FALSE),
  ('Kate Whitehead', 'Managing Director', 'Managing Director @ Avant Group Pty Ltd | Business Advisory, Marketing Strategy, Government Grant and Incentives Professional Services · Kate is the founder and Managing Director of Avant Group, a leading business strategy and government grant consulting firm. The business provides services including project management, grant identification and application management and reporting, business restructuring and advice, finance equity sourcing, contract negotiation and business marketing strategy planning.In her previous roles, Kate has worked in the Aerospace and Defence sector. Kate managed the Commercial Division of a major aerosp', 'Malvern, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Market Research / Strategy'], 'https://linkedin.com/in/kate-whitehead', NULL, NULL, 'Avant Group', FALSE, '[{"name": "Avant Group"}, {"name": "Export Chamber of Australia Incorporated"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'kate-whitehead', 'Scaled Founder', ARRAY['both'], TRUE, FALSE),
  ('Colm Dolan', 'Chief Executive Officer', 'Entrepreneur | Advisor | Investor · Experience• Founder & CEO of Publift (10 years)• Scaled a technology business from zero to $20m ARR• Built and led global teams across Australia, Ireland, and the Philippines• Delivered sustained ~40% YoY growth with strong profitability• Successfully exited and supported the business post-acquisition⸻Key Skills• Scaling businesses and simplifying complexity• Building high-performance teams and future leaders• Creating strong, values-led cultures• Driving disciplined growth with real profit• Lea', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/colm-dolan', NULL, NULL, 'Dolo Ventures', FALSE, '[{"name": "Dolo Ventures"}, {"name": "Publift"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'colm-dolan', 'Scaled Founder', ARRAY['both'], TRUE, FALSE),
  ('James Bergl', 'Co-Founder & Managing Partner Bluebird APAC', 'Ex-SaaS Operators | 100+ SaaS Sales Hires | Helping SaaS Leaders Recruit Australia’s Top 1% AEs & Sales Leaders · Most SaaS leaders don’t struggle to “hire”.They struggle to find the people who can actually sell.After 17 years building and leading high-performing SaaS and MSP sales teams (Datto, Pax8, N-able), I realised something:The best AEs, SDRs, and Sales Leaders in Australia are almost never applying to job ads. They’re too busy performing.That’s where we come in.At Bluebird, we’re ex-operators turned talent partners, helping SaaS leaders recruit Australia’s top 1 percent - the people who ramp fast, c', 'Greater Sydney Area', '17+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Fundraising / Investment'], 'https://linkedin.com/in/jbergl', NULL, NULL, 'Bluebird', FALSE, '[{"name": "Bluebird"}, {"name": "Pavilion"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'james-bergl', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Mark Lynch', 'Expert Circle (Advisor)', 'Co-Founder at Learnosity, Technology Entrepreneur and Advisor · An innate problem-solver with a love of learning, Mark is the founder and CTO of Learnosity. With over a two decades of experience in technology and edTech, Mark has been responsible for the technical inception and development of Learnosity’s market leading solutions. A B2B, Software as a Service offering, Learnosity provides the core elements required for any assessment solution - from Authoring and Assessment delivery, right through to Reporting. Highly scalable & extensible by design, our goa', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/marklynch', NULL, NULL, 'Climate Tech Partners', FALSE, '[{"name": "Climate Tech Partners"}, {"name": "Airtree"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'mark-lynch', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Chia-Yi Cheng', 'Regional Officer, Trade & Investment, ANZ', 'Invest Northern Ireland, Regional Officer, Trade and Investment ANZ · I am Regional Officer for Trade and Investment in Australia and New Zealand at Invest Northern Ireland (Invest NI), the economic development agency of Northern Ireland. I support and promote the interests of NI businesses in the region, as well as attract and facilitate FDI from ANZ region. Invest Northern Ireland has presence in 5 regions in Asia Pacific: Mainland China, Hong Kong & Macau, North East Asia, South East Asia, and Australia & New Zealand. Our International Business offices are stra', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/chia-yi-cheng', NULL, NULL, 'Invest Northern Ireland', FALSE, '[{"name": "Invest Northern Ireland"}, {"name": "C.Y. International"}]'::jsonb, 'other_asia', ARRAY['other_asia', 'australia'], NULL, 'chia-yi-cheng', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Nigel Williams', 'Strategic Advisor', 'Non-Executive Director, recently retired as Commonwealth Bank Chief Risk Officer. Director ASB Bank, Director Cancer Council NSW & Chair Audit, Risk & Technology Committee. MAICD · I joined Commonwealth Bank in 2018 as Group Chief Risk Officer after the APRA Prudential Review to improve the Group’s Risk Management, Culture and Governance. It has been great being part of the leadership team that has made CBA the success it is today delivering industry leading Total Shareholder Return in this period.I have had 20+ years experience in both C-Suite roles and on Boards. The Board roles have been across Australia, NZ, China and Switzerland. This includes three different banks, e', 'Sydney, New South Wales, Australia', '20+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Compliance / Risk', 'Recognised Industry Leader'], 'https://linkedin.com/in/williams-nigel', NULL, NULL, 'Clayton Utz', FALSE, '[{"name": "Clayton Utz"}, {"name": "ASB Bank"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'nigel-williams', 'Active Advisor', ARRAY['both'], TRUE, FALSE),
  ('Kerrick Lehman', 'Regional Director & GM - Australia & New Zealand', 'Managing Director, Global Sales & Commercial leader at BT · I’m a purpose led executive leader with a passion for technology, delivering customer outcomes, developing talent, and building a sustainable, high performance business.I work with organisations to enable their digitalisation strategy, connect securely, enhance employee collaboration, and optimise customer engagement across every touchpoint.I have a successful track record of delivering profitable growth, leading high performing teams, driving change, and managing complex P&Ls. My experience spa', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Sales / GTM', 'Cross-border'], 'https://linkedin.com/in/kerricklehman', NULL, NULL, 'BT Group', FALSE, '[{"name": "BT Group"}, {"name": "Orange Business"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'kerrick-lehman', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();