INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Duco van Breemen', 'Chief Executive Officer', 'Helping companies expand into Australia with proven GTM and sales systems | 1,000+ founders supported · I help startups and SMEs grow their business.That might mean entering a new market, building a stronger sales system, or turning scattered leads into a repeatable pipeline.At Haymarket HQ, I’ve worked with more than 1,000 companies expanding into and across APAC. We’re the partner of the Singapore Government for their tech companies entering Australia, and we’ve supported organisations like Alibaba, Australia Post, and Tech Central to help more founders and teams grow across the region.I’ve seen', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/ducovanbreemen', NULL, NULL, 'Haymarket HQ', FALSE, '[{"name": "Haymarket HQ"}, {"name": "Stoov"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'duco-van-breemen', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Kelsey Hill', 'Assistant Program Director, Accessing New Markets Initiative (ANMI) - Americas & EMEA', 'Supporting Australian exporters to diversify and grow in the Americas & EMEA International Trade & Investment · I’m a trade and investment professional currently supporting Australian exporters to diversify and grow in new export markets under the Australian Government''s A$50 million Accessing New Markets Initiative (ANMI).As ANMI Assistant Program Director - Americas & EMEA, I collaborate with Austrade''s Business Development teams, government and industry partners, and bilateral associations to help Australian businesses grow their global footprint and export sales. My career spans Australia, the UK, Ger', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/kelseyhill1', NULL, NULL, 'Australian Trade and Investment Commission (Austrade)', FALSE, '[{"name": "Australian Trade and Investment Commission (Austrade)"}, {"name": "Self employed"}]'::jsonb, 'germany', ARRAY['germany', 'australia'], NULL, 'kelsey-hill', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Paul Wright', 'Chief Commercial Officer', 'Chief Commercial Officer at Australian British Chamber of Commerce · I am a sales professional with 15 years of experience in leading global organisations. My roles have focused on acquiring and providing strategic account management to national and international multi-million dollar accounts across a wide range of industries.I am an expert networker with an extensive network of quality connections. My personal networking philosophy focuses on building genuine long term relationships rather than simply chasing a sale and this has seen me achieve great success.I a', 'Greater Sydney Area', '15+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government', 'Sales / GTM'], 'https://linkedin.com/in/paulawright', NULL, NULL, 'Australian British Chamber of Commerce', FALSE, '[{"name": "Australian British Chamber of Commerce"}, {"name": "RateSetter"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'paul-wright', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Cheryl Mack', 'CEO', 'CEO at Aussie Angels, CMACK Ventures, 361 Angel Club · I help founders & angel investors, read on...I’m a community builder at heart, always driving value and genuine connections within the many small and large communities I’ve built and managed. As a natural connector, I love bringing people together and as an extrovert, I love meeting new people and learning new things. I believe that life is about the people you meet and the things you create with them. I love to be helpful, my motto is: “If I can help, I will.” So don’t be afraid to ask.I help s', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Fundraising / Investment'], 'https://linkedin.com/in/cherylmack', NULL, NULL, 'Aussie Angels', FALSE, '[{"name": "Aussie Angels"}, {"name": "Startmate"}]'::jsonb, 'canada', ARRAY['canada', 'australia'], NULL, 'cheryl-mack', 'Active Advisor', ARRAY['international_entrant'], TRUE, TRUE),
  ('Blair Lucas', 'Group Commercial Director', 'Group Commercial Director | AcclimeSpeaker | Mentor | Impact/VC/Angel Investor · As Group Commercial Director and Partner of Acclime I am responsible for driving strategic growth, marketing, and sales activities across the Acclime group, whilst continuing to lead our business development in Australia and New Zealand. I lead the team making the complex simple for offshore companies coming to Australia or the USA to undertake research and development, sell their product or invest in a business. I have also been a director of more than 100 companies from over 40 countries and a', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Sales / GTM'], 'https://linkedin.com/in/blairalucas', NULL, NULL, 'Acclime', FALSE, '[{"name": "Acclime"}, {"name": "Acclime Australia"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'blair-lucas', 'Active Advisor', ARRAY['international_entrant'], TRUE, TRUE),
  ('Giovanni Munoz', 'Managing Director', 'Helping companies succeed in international markets! · For more than two decades, Foley has been helping international companies and governments turn opportunity into success across Australia and New Zealand.As a bespoke international business advisory consultancy, Foley specialises in trade development and investment attraction, working closely with economic development agencies, industry associations, and private sector clients to build meaningful partnerships and long-term growth.Our work combines local insight with global reach. With an extensiv', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Trade & Government', 'Cross-border'], 'https://linkedin.com/in/giovanni-munoz', NULL, NULL, 'Foley', FALSE, '[{"name": "Foley"}, {"name": "Great Lakes St. Lawrence Governors & Premiers"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'giovanni-munoz', 'Scaled Founder', ARRAY['international_entrant'], TRUE, TRUE),
  ('Emmanuel Bisi', 'Founder & Managing Director', 'Founder I Director I Board member | Country representative | Non-executive Director | Resident Director · Leading Expandys as the Founder & Managing Director, my mission is to foster international growth for over 500 clients, utilising decades of expertise in strategy, market research, and distribution. Our team''s success is anchored in multicultural and multilingual collaboration, ensuring seamless global expansion for businesses entering or strengthening their presence in the UK, Australia, and India.My role as Co-Founder & Director at SpaDays Pty Ltd showcases my commitment to innovation in the w', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/emmanuelbisi', NULL, NULL, 'Expandys', FALSE, '[{"name": "Expandys"}, {"name": "SpaDays.com.au"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'emmanuel-bisi', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Rafal Jarosz', 'Global Engagement Manager', 'Head @ Polish Investment and Trade Agency (Sydney, Australia) · Here''s my story:I started my professional career as an academic lecturer, gradually took on more leadership roles at the university where I worked. Then, I moved to government where I spent over 15 years building my career in international business, diplomacy and trade across Europe, United States and recently Australia. Currently, from our office in Sydney, I identify and deliver trade and investment opportunities to businesses across the Asia&Pacific region.I am passionate about impact investm', 'Canberra, Australian Capital Territory, Australia', '15+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/rafal-jarosz-04216280', NULL, NULL, 'Polish Investment and Trade Agency (PAIH)', FALSE, '[{"name": "Polish Investment and Trade Agency (PAIH)"}, {"name": "The Australian National University"}]'::jsonb, 'other_eu', ARRAY['other_eu', 'australia'], NULL, 'rafal-jarosz', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Catherine Hughes', 'Associate Director', 'International Business Connector · People would say that I am a highly motivated, professional with strong interpersonal and networking skills, who demonstrates high attention to client and company values. This I believe to be true, as my extensive professional experience transitioning across various industries has equipped me with invaluable transferrable skills and knowledge, both in highly structured corporate and non-corporate environments across Ireland, Australia (Sydney CBD and Regional Queensland) and USA. Industry experi', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/catherine-hughes', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Club Hibernia"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'catherine-hughes', 'Trade & Government', ARRAY['functional_expert'], TRUE, TRUE),
  ('Sam Bricknell', 'CEO', 'Visa solutions for Tech start-ups & scale-ups scaling across APAC, UK & USA · Techvisa is a specialist Immigration consultancy focused on global mobility for the IT market in Australia, US, UK and Singapore. We have combined our experience to fill a gap in the Migration market tailored specifically to assisting IT professionals with their visa process across all industries.Techvisa works with start ups, scale ups and established businesses to navigate the always changing legislation to ensure the best possible outcome.With a narrow focus, we can offer up to date immediate', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Immigration / Visa / Mobility', 'Cross-border'], 'https://linkedin.com/in/sambricknell', NULL, NULL, 'Techvisa', FALSE, '[{"name": "Techvisa"}, {"name": "Catalysr - Accelerator for Migrants & Refugees"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'sam-bricknell', 'Active Advisor', ARRAY['international_entrant'], TRUE, TRUE),
  ('Robert Gallup', 'Founder', 'Oz2US Ventures Founder, 25-year US & AU CxO, Int’l Growth Agency Lead, Serial Founder, and VC Advisor · 20 years of international corporate and agency growth marketing leadership, strategy, and execution delivering exceptional revenue and profitability to dozens of Australian and U.S. startups and national brands.GALLUP’S CAREER VALUE AND EXPERTISE Multimillion-Dollar Growth Architect Transformative Marketing, Sales, and Brand Strategist Digital Marketing Rainmaker Exceeder of Founder and Board Targets and Expectations Industry Innovator and Disruptor Customer Service and Sales Development E', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/exceptionalgrowthprofitability', NULL, NULL, 'Oz2US Ventures', FALSE, '[{"name": "Oz2US Ventures"}, {"name": "BootstrapLabs, an Ares company"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'robert-gallup', 'International Founder', ARRAY['international_entrant'], TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();