INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Daniel Grindrod', 'Co-Founder', 'Co-Founder & Director | Building APAC''s leading GTM Community ️ · Hello, I''m Dan! Originally from Devon, UK, I proudly call Sydney (Bondi) home. My passion for Technology and Connecting great people led me to Co-Found Launchpad Academy, 4Twenty Consulting & Tech Talks Australia. In my downtime, I''m either planning my next trip (️️️), enjoying good foods, or doing anything outdoors and sports-related (️)Over the last decade, I''ve partnered with numerous leaders of Global and Local Technology Businesses to advise and build their GTM teams across ANZ and APA', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder'], 'https://linkedin.com/in/dangrindrod', NULL, NULL, 'LaunchPad', FALSE, '[{"name": "LaunchPad"}, {"name": "4Twenty Consulting"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'daniel-grindrod', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Liz van Zyl', 'Head of Partnerships', 'Board member. Advisor. Head of Partnerships @ Tractor Ventures. Community builder. Founding team. Partner @ Aussie Founders Club. Nominated as Female Startup Leader of the Year ‘24 (Aus) · I operate at the junction of founders, funding, and the networks that surround them: connecting capital, grassroots communities, industry partners, and policymakers to ensure high‑potential startups have the resources and relationships they need to grow.As Head of Partnerships at Tractor Ventures, I work to expand access to non‑dilutive funding across Australia and New Zealand. Tractor has provided more than A$100 million in revenue‑aligned capital to 250+ companies and is targeting A$1 billion', 'Prahran, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Sales / GTM', 'Recognised Industry Leader'], 'https://linkedin.com/in/liz-van-zyl', NULL, NULL, 'Tractor Ventures', FALSE, '[{"name": "Tractor Ventures"}, {"name": "Aussie Founders Club"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'liz-van-zyl', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Bonnie Shek', 'Director, Australia & New Zealand', 'Director, AU & NZ, Hong Kong Trade Development Council · Bonnie is a seasoned professional with marketing, business development and management experience in Asia/Pacific. Before joining the HKTDC, she spent over ten years in the telecommunications industry, being responsible for developing marketing strategy and leading the Asia/Pacific consumer team.Having grown up in Hong Kong, then living in Australia and travelling back & forth to New Zealand for over 30 years, Bonnie understands the business dynamics among the three economies. With an extensive n', 'Greater Sydney Area', '30+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government'], 'https://linkedin.com/in/bonnie-shek-a728a934', NULL, NULL, 'Hong Kong Trade Development Council', FALSE, '[{"name": "Hong Kong Trade Development Council"}, {"name": "AT&T"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'bonnie-shek', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Madeline Ferguson', 'Landing Pads - Program Director', 'Landing Pads Program Director Australian Trade and Investment Commission (Austrade)', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/madeline-ferguson-530a39a7', NULL, NULL, 'Australian Trade and Investment Commission (Austrade)', FALSE, '[{"name": "Australian Trade and Investment Commission (Austrade)"}, {"name": "The Fred Hollows Foundation"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'madeline-ferguson', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('William Johnson', 'Senior Adviser', 'Senior Trade Adviser | Australian Trade and Investment Commission (Austrade)', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/william-johnson-0bb20596', NULL, NULL, 'Australian Trade and Investment Commission (Austrade)', FALSE, '[{"name": "Australian Trade and Investment Commission (Austrade)"}, {"name": "Department of Jobs, Skills, Industry and Regions"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'william-johnson', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Niamh Given', 'Advisory Board Member', 'Innovative Business Strategist | Driving Growth & Operational Excellence in Scaling Companies · Innovative thinker and strategist, thrives on growing business and breaking new ground. With a decade of experience in the dynamic and fast-paced product development and manufacturing industries, proven ability at driving strategic growth and pioneering operational improvements with a fresh and energetic perspective. Results orientated, proven track record in translating strategy into execution. Key drivers of success have been the ability to effectively build relationships, motivate cross funct', 'Waikato, New Zealand', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/niamhgiven', NULL, NULL, 'Enterprise Ireland Australia & New Zealand', FALSE, '[{"name": "Enterprise Ireland Australia & New Zealand"}, {"name": "Hale Animal Health"}]'::jsonb, 'hong_kong', ARRAY['hong_kong', 'australia'], NULL, 'niamh-given', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Ian Corbally', 'CEO & Co-Founder', 'CEO @ Morfless | Automating Cloud Savings · I''m passionate about helping teams optimise their cloud spending and performance, while reducing complexity and risk. Morfless is my vehicle for fulfilling this passion and excitingly its savings teams Millions in cloud spend each year.', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/iancorbally', NULL, NULL, 'Morfless', FALSE, '[{"name": "Morfless"}, {"name": "Antler"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'ian-corbally', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Dónal Brady', 'Co-Founder, Head of Product', 'Powering global teams to Work From Anywhere | Top 100 Future of Work Leaders | Co-Founder · After fifteen years in commercial finance across the US, EMEA and APAC, I took the leap into entrepreneurship and co-founded Work From Anywhere, a remote work compliance SaaS platform. We help Fortune 500 and enterprise clients safely offer international remote work as a benefit to millions of their staff. Two of our first four customers were Fortune 500 organisations which set the bar high from the beginning.As Head of Product, I have guided our journey from idea to launch, through pivots, rebu', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product', 'Cross-border'], 'https://linkedin.com/in/donalbrady1', NULL, NULL, 'Work From Anywhere', FALSE, '[{"name": "Work From Anywhere"}, {"name": "Bus Stop Films"}]'::jsonb, 'singapore', ARRAY['singapore', 'australia'], NULL, 'donal-brady', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Jeannette Connon', 'Commercial Business Advisor', 'Business Advisor I Supporting tech companies to scale and grow internationally · With more than 20 years in the tech sector, I’ve led projects and teams across marketing strategy, planning and execution as well as in sales and business development. A lateral thinker, I’ve proven expertise in identifying and securing market and partnership opportunities, building market presence and in new client acquisition, events and digital marketing programs. Having worked in Australia and overseas across several industries and companies big and small, enhancing customer experience and e', 'Sydney, New South Wales, Australia', '20+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government'], 'https://linkedin.com/in/jeannetteconnon', NULL, NULL, 'New Zealand Trade and Enterprise', FALSE, '[{"name": "New Zealand Trade and Enterprise"}, {"name": "Marketing Services"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'jeannette-connon', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Kirk Drage', 'CEO & Co-founder', 'Coaching startup founders from 0 --> 1st million in revenue. Proven approaches, personalised. Avoid the 95% failure rate. ️Customer Acquisition | Team | Product | Operations | Capital⬅️ CEO & Co-Founder LeapSheep · As a startup founder, you’ve committed to building something big.You’ve identified a problem that needs solving and dedicated significant time, money, and energy to it.Rewarding as it might be, you may also find the journey is more difficult than expected.What’s more, your attempts to find the right support have come up short.Where startup advice is concerned, there are many opinions out there – but proven approaches for startup success are lacking.The generic one-size-fits-all incubator and acc', 'Adelaide, South Australia, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Technology / Product'], 'https://linkedin.com/in/kirkdrage', NULL, NULL, 'LeapSheep', FALSE, '[{"name": "LeapSheep"}, {"name": "VADARO PTE LTD"}]'::jsonb, 'singapore', ARRAY['singapore', 'australia'], NULL, 'kirk-drage', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Brian Cooke', 'Co-Founder', 'Founder – MooCoo Ventures | Managing Director - Cooke Capital | Angel Investor | Non-Executive Director · A results-driven angel investor and founder with a proven track record in consulting and a deep commitment to advancing early-stage technology ventures. As Co-Founder of MooCoo Ventures, I lead the development of a syndicate investment platform designed to democratise access to high potential early-stage opportunities for sophisticated investors. We empower deal-by-deal investing in rigorously vetted Australian startups.At Cooke Capital Pty Ltd, I specialise in advising, mentoring, and investing', 'Brisbane, Queensland, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/briancooke', NULL, NULL, 'MooCoo Ventures', FALSE, '[{"name": "MooCoo Ventures"}, {"name": "Cooke Capital"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'brian-cooke', 'International Founder', ARRAY['both'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();