INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Christine Andryszczak GAICD', 'Head of Working Capital & Bank Guarantee Solutions', 'Executive Leader of Leaders | Strategy & Innovation | Customer Centricity & Business Growth | Product Owner | Working Capital, Trade & Commodity Finance · I love helping customers grow their businesses by creating solutions that work. Whether it’s developing new products, improving existing ones or innovating financing structures, there is nothing more satisfying than knowing you’ve helped your customer grow their business or keep their doors open.My ethos is, opportunity creates capability (not vice versa). A colleague once said “I love my job in strategy. We say allot but do very little”. I thought, “how can I get his job!?” In all seriousness,', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Technology / Product'], 'https://linkedin.com/in/christine-andryszczak', NULL, NULL, 'NAB', FALSE, '[{"name": "NAB"}, {"name": "Commonwealth Bank"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'christine-andryszczak-gaicd', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Sam Cust', 'Managing Director', 'Managing Director at Hyper · Hyper is a Global Startup Studio dedicated to turning founders'' ideas into thriving businesses. We guide them from concept to capital raising, through full design and development, to the successful launch of their startup. With over a decade of experience in the tech industry, I specialise in nurturing startups from their inception to high-growth success. I serve on multiple startup boards and am deeply committed to fostering the Australian startup ecosystem.I’m always open to new opportunities', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Fundraising / Investment'], 'https://linkedin.com/in/samcust', NULL, NULL, 'Hyper Startup Studio', FALSE, '[{"name": "Hyper Startup Studio"}, {"name": "LOKE - Branded Ordering, Delivery & Loyalty Apps"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'sam-cust', 'Active Advisor', ARRAY['both'], TRUE, FALSE),
  ('Navaid Khatib', 'Board Member', 'Head of Product Management, Global Payments Solutions, HSBC Australia and New Zealand · With 20 years of experience across Asia-Pacific, I bring deep domain expertise in Transaction Banking — spanning Payments, FX, Liquidity, and Cards — combined with a passion for client advisory, fintech partnerships, and solution innovation.Currently leading the Global Payments Solutions product team at HSBC Australia & New Zealand, oversee a high-performing team, and have delivered some of our region’s most strategic wins — from doubling business through a 3-year transformation plan to securing', 'Greater Sydney Area', '20+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Technology / Product', 'Cross-border'], 'https://linkedin.com/in/navaid-khatib-21218821', NULL, NULL, 'Australian Payments Network (AusPayNet)', FALSE, '[{"name": "Australian Payments Network (AusPayNet)"}, {"name": "HSBC"}]'::jsonb, 'singapore', ARRAY['singapore', 'australia'], NULL, 'navaid-khatib', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Cam Stevens', 'CEO', 'Safety Technologist & Chartered Safety Professional | AI, Critical Risk & Digital Transformation Strategist | Founder & CEO | LinkedIn Top Voice & Keynote Speaker on AI, SafetyTech, Work Design & the Future of Work · I’m Cam Stevens. Technologist, Chartered Fellow of the Australian Institute of Health & Safety, Physio & Human Factors Specialist by training & Founder of PKG. I help high-risk organisations improve human & organisational performance by integrating AI, digital transformation, critical risk management & human factors into the flow of work.My work sits at the intersection of health & safety (WHS/HSEQ), AI, data strategy, systems thinking, safety innovation & operational risk management. I support', 'Perth, Western Australia, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Market Research / Strategy', 'Recognised Industry Leader'], 'https://linkedin.com/in/cameronmstevens', NULL, NULL, 'PKG Safety Innovation', FALSE, '[{"name": "PKG Safety Innovation"}, {"name": "Safety Innovation Academy"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'cam-stevens', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Joe Young', 'Co-Founder', 'Co-founder Mayfly Ventures | Co-building the AI ventures of tomorrow with industry insiders. · After a number of years of trial by error, I have found a career that I feel truly connected to. At Mayfly, we partner with passionate founders working on game changing platforms and help them navigate the three big mountains they have to climb:️ Product Development: We build apps with no code tech to launch faster. Traction: Sending the right message, to the right people at the right time. Capital: We help founders reach out to and close investors.Working alongside a superstar team which I', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/joe-tm-young', NULL, NULL, 'Mayfly Ventures', FALSE, '[{"name": "Mayfly Ventures"}, {"name": "Networks X"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'joe-young', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Bryan Williams', 'Founder', 'Enabling partnership opportunities to fuel growth · We work with ambitious tech founders, C-suite, partner leaders and emerging platforms to - develop, curate and enable partnership opportunities to fuel growth- establish partnership ecosystems enabling network effects and virality - platform development to become orchestrators and drive critical mass of customers - coach & mentor leaders to utilise a partner led approach If you can help partners truly thrive, offer more to your mutual & future customers, then your company will benefit to. It’s a', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Market Research / Strategy'], 'https://linkedin.com/in/bryanwilliamsaus', NULL, NULL, 'Hockey Stick Advisory', FALSE, '[{"name": "Hockey Stick Advisory"}, {"name": "New Zealand Trade and Enterprise"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'bryan-williams', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Claire Bull', 'Head of Growth and Investment', 'Helping founders scale through global networks | Angel Investor | Mentor | Growth & Investment at ACS | Co-Founder Invest Rural · Claire started off her career in B2B Marketing focussed on Sustainability at Visy in Melbourne before anyone knew what the letters ESG stood for. She then got hooked on startup land as the first COO at Frank Green, the now cult-brand making reusable, sustainable products. On moving to Singapore she made a career shift into the Trade and Investment space helping global tech businesses expand into the Asia Pacific region and partnering with Microsoft and Governments to run global expansion program', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment', 'Cross-border'], 'https://linkedin.com/in/clairelouisebull', NULL, NULL, 'ACS (Australian Computer Society)', FALSE, '[{"name": "ACS (Australian Computer Society)"}, {"name": "Invest Rural"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'claire-bull', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Aaron Birkby', 'CEO & Co-Founder', 'Managing Partner at Tribe Global Ventures - venture capital investor for Australian B2B technology ventures scaling to the UK or USA · With over 20 years of experience in building and supporting technology companies to go global, I am a co-founder of Tribe Global Ventures, a B2B venture capital firm that invests in Australian and New Zealand tech companies and helps them scale to the UK and USA.', 'Brisbane, Queensland, Australia', '20+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Fundraising / Investment', 'Cross-border'], 'https://linkedin.com/in/aaronbirkby', NULL, NULL, 'Tribe Global Ventures', FALSE, '[{"name": "Tribe Global Ventures"}, {"name": "Farmers2Founders"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'aaron-birkby', 'Active Advisor', ARRAY['local_startup'], TRUE, FALSE),
  ('Liza Noonan', 'Chief Executive Officer', 'Innovation for Industry Development, Talent and Investment Attraction · 20+ years of experience in strategy, innovation management, ecosystem development and deep tech. Significant experience in building and leading teams comprised of multiple organisational disciplines with a strongly affilitative style. Extensive network across Australia’s Start-Up and Innovation Community. Key Capabilities:Innovation Management: embraces new approaches to solve problems or realise new opportunities; facilitating of ideation to commercialisation process, effective agent of impleme', 'Greater Sydney Area', '20+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Startup Advisor'], 'https://linkedin.com/in/lizanoonan', NULL, NULL, 'Cicada Innovations', FALSE, '[{"name": "Cicada Innovations"}, {"name": "Investment NSW"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'liza-noonan', 'Active Advisor', ARRAY['both'], TRUE, FALSE),
  ('Simone Dossetor', 'Chief Executive Officer', 'Leadership | Strategy | Transformation | Innovation · I am an experienced Executive leader who has spent my career in the financial services and consulting industry. My recent roles have focused on developing and transforming businesses to be fit for an increasingly competitive future.After studying law, I spent eight years as a management consulting working in Australia and the UK. I have experience across a broad range of roles and functions including Claims, Information Technology, Mergers & Acquisitions, Strategy and Project Management.I am pas', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Fintech Founder'], 'https://linkedin.com/in/simone-dossetor', NULL, NULL, 'Insurtech Australia', FALSE, '[{"name": "Insurtech Australia"}, {"name": "Sunnyhaven Disability Services Ltd"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'simone-dossetor', 'Active Advisor', ARRAY['functional_expert'], TRUE, FALSE),
  ('Ben Morrisroe', 'Chief Executive Officer', 'Founder & CEO at Oxbow · Building modern financial infrastructure for commerce.Focused on improving payments, cashflow visibility, and financial operations for inventory-driven businesses.', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/ben-morrisroe', NULL, NULL, 'Oxbow', FALSE, '[{"name": "Oxbow"}, {"name": "Publift"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'ben-morrisroe', 'International Founder', ARRAY['both'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();