INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Dan Jovevski', 'Founder & CEO', 'Founder & CEO at WeMoney · We’re #HIRING at WeMoney!Build with us. Helping Aussies pay down debt faster. Over 1M+ downloads and growing.If you''re keen to solve real problems and build with purpose — come join us.Read Building Australia’s Financial Future — www.wemoney.com.au/letter-to-buildersDM me or check out open roles!#WeMoney #Hiring #Fintech #BuildWithUsPassionate FinTech entrepreneur (with an exit), transformational leader, technologist, focused on driving results across end-to-end value chains in financial se', 'Greater Perth Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder'], 'https://linkedin.com/in/danieljovevski', NULL, NULL, 'WeMoney', FALSE, '[{"name": "WeMoney"}, {"name": "Strategica.io"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'dan-jovevski', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Martin McCann', 'Founder and CEO', 'Founder and CEO @ Trade Ledger™ | Driving Business Growth · I am an entrepreneur and strategic advisor dedicated to helping commercial banks modernise through Enterprise AI. As the Founder and CEO of Trade Ledger™ for nearly a decade, I built a digital platform that redefined cash flow lending through unparalleled access to real-time B2B transaction data.My mission has evolved alongside the technology: I lead AI vision and strategy, helping banks transition from traditional lending models to AI-driven enterprise architectures. By drawing on my expertise', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/mccannmartin', NULL, NULL, 'Trade Ledger™', FALSE, '[{"name": "Trade Ledger\u2122"}, {"name": "The Digital Institute"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'martin-mccann', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Paul Dimond', 'Head of GTM (APAC)', 'Exec Hiring & GTM Team Builder | SaaS and Tech | Asia-Pacific · As Head of GTM Recruitment at Halcyon Knights, I lead an experienced team dedicated to building high-performing go-to-market functions across the technology ecosystem. We partner with VC-backed, fast-growth startups, established technology companies, and leading service providers to recruit exceptional CROs, VP Sales, Account Executives, Pre-Sales Specialists, and Customer Success leaders.Our team has created more partnerships with groundbreaking startups and tech powerhouses than any other in t', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'HR / Talent'], 'https://linkedin.com/in/apactech', NULL, NULL, 'Halcyon Knights', FALSE, '[{"name": "Halcyon Knights"}, {"name": "Certus Recruitment Group"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'paul-dimond', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Cindy Callander', 'Senior Trade Specialist', 'Senior Trade Specialist, Science and Technology · I am an economic development, trade, strategy and governance expert with 24 years'' experience in public and private sector service delivery industries and 18 years'' in management. During my career, I have utilised networks and cross agency relationships to deliver advice and projects and operationalise strategy in the fields of precinct development, international education, trade and investment and governance. I have managed government budgets in local and state sectors and successfully led team', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/cindycallander', NULL, NULL, 'Scottish Development International', FALSE, '[{"name": "Scottish Development International"}, {"name": "Global Victoria"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'cindy-callander', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Samantha Warner', 'Assistant Market Advisor', 'Assistant Market Advisor at Enterprise Ireland · I am an Assistant Market Advisor at Enterprise Ireland, the trade and innovation agency of the Irish government.My core competencies include Communication, market research, and project management. I assist in identifying and developing market opportunities, creating and executing market entry and expansion strategies, and building and maintaining strong relationships with key stakeholders. I also assist in coordinating events for Enterprise Ireland ANZ and am Office Manager for the Sydney office', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/samantha-warner-3b326591', NULL, NULL, 'Enterprise Ireland', FALSE, '[{"name": "Enterprise Ireland"}, {"name": "SMEC"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'samantha-warner', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Tess Thomas', 'Associate Director', 'Associate Director, Strategic Advisory & Concierge, Investment Delivery Authority · An accomplished leader with over 10 years’ experience across the UK, Australia, NZ and South America in project management, facilitation, strategic thinking and business development. I apply business acumen and analytical rigour to assist organisations with their international expansion plans. I have a deep understanding of the Aus-UK business synergies, particularly in FinTech and Capital Investment. In my current role, I manage small teams to provide tailored solutions to businesses of differe', 'Greater Sydney Area', '10+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/tlaroo', NULL, NULL, 'Premier''s Department NSW', FALSE, '[{"name": "Premier''s Department NSW"}, {"name": "Investment NSW"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'tess-thomas', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Mantas Aleksiejevas', 'CEO & Co-Founder', 'CEO & Co-Founder at Cor | Building Obi, Voice AI Agent for Customer Onboarding & Activation · I started my career helping startups grow. At Google, I built and ran startup growth programs across Europe, working with companies in fintech, e-commerce, travel, gaming, cybersecurity, and SaaS. Later, I moved into commercial leadership roles at three growth-stage ventures in finance, real estate, and marketplaces.One thing became clear: customer retention and expansion were always the hardest problems. Companies threw people at the problem, but it didn’t scale.That’s why I co-founded Cor. We’', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/mantasaleks', NULL, NULL, 'Cor', FALSE, '[{"name": "Cor"}, {"name": "Breezit"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'mantas-aleksiejevas', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Brendan Widdowson', 'Chief Commercial Officer', 'Chief Commercial Officer at Banjo · An established business development leader in the fintech sector, with proven experience across payments, open banking, lending and data & analytics in Australia and Europe.Entrepreneurially driven and passionate about helping businesses, has defined and implemented go-to-market strategies, built sales and marketing teams, developed partnerships and won new business at SME to enterprise level – helping to establish and scale multiple fintech businesses.M: 0409433910 E: bwiddowson@banjoloans.com', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Sales / GTM'], 'https://linkedin.com/in/bjwiddowson', NULL, NULL, 'Banjo - Business Loans', FALSE, '[{"name": "Banjo - Business Loans"}, {"name": "Fire"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'brendan-widdowson', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Andrew Porter', 'Chief Commercial Officer', 'Chief Commercial Officer | Non-Executive Director | Advisor | Investor · Experienced business leader, company director, and board advisor, with particular expertise in developing and driving disruptive Fintech startups. A proven track record of working closely with smart and innovative entrepreneurs and CEOs, to scale small startups into large organisations. Have established and run overseas offices for three global Fintech businesses.Active early stage investor and advisor working with innovative Fintech, Lawtech and Blockchain startups.⭐️ Played a key role in helpi', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Sales / GTM'], 'https://linkedin.com/in/andrewiporter', NULL, NULL, 'Flash Payments', FALSE, '[{"name": "Flash Payments"}, {"name": "OKX"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'andrew-porter', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Mark Ellis', 'Chief of Staff', 'Chief of Staff @ Salient | Recruitment | SaaS | Tech | GTM | Start Ups | VCs | Partnerships · I''m a Belfast-born Recruiter now based in Sydney, working with Salient — APAC’s first SaaS recruitment agency.What We Do at Salient:We’re a specialist tech and sales recruitment partner for SaaS and tech-centred companies across Australia, Southeast Asia, Japan & the Middle East.From seed stage to scale-up, we help high-growth businesses find exceptional talent across:• Sales• Product• Engineering• Customer Success• Post-SalesFounded in 2008, we’ve been at the forefront of tech hiring in APAC fo', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Sector Expert: SaaS'], 'https://linkedin.com/in/markadamellis', NULL, NULL, 'Salient Group', FALSE, '[{"name": "Salient Group"}, {"name": "Lendlease"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'mark-ellis', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Yanir Yakutiel ️', 'Founder & CEO', 'Founder & CEO at Lumi · We have a saying at Lumi: "With us, you''re not a loan." We''re a FinTech disruptor that doesn''t speak, think or act like a bank. This is the essence of what drives us to offer superior funding solutions to our clients. We harness real-time big data to assess creditworthiness for SMEs that are experiencing difficulty securing finance from banks and traditional lenders. This allows us to offer an alternative source of capital to small business; a new way to manage their cash flow and enable future', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder'], 'https://linkedin.com/in/yaniryakutiel', NULL, NULL, 'Lumi', FALSE, '[{"name": "Lumi"}, {"name": "Sail Finance"}]'::jsonb, 'france', ARRAY['france', 'australia'], NULL, 'yanir-yakutiel', 'International Founder', ARRAY['both'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();