INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Brian O''Farrell', 'Co-Founder - Chief Revenue Officer', 'Co-Founder @ Furthr - Australia''s Largest Card Linked Loyalty Network · Currently focused on pioneering payment linked loyalty with Furthr by enabling banking-partners customers to earn cashback easier than any other solution in the world. Raised $2.2 million seed capital with near term Series A plans to raise growth capital. Check us out : www.Furthr.comPreviously Co-Founded Talentpool Group, working with clients like Canva, ebay, Zip, Airwallex & AfterPay opened offices in Sydney, Melbourne, Brisbane & San Francisco and at its peak averaging 8 figures in annual re', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Sales / GTM'], 'https://linkedin.com/in/brianofarelltalentpool', NULL, NULL, 'Furthr', FALSE, '[{"name": "Furthr"}, {"name": "AfterWork Ventures"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'brian-ofarrell', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Richard Brooks', 'Co-founder & Chief Commercial Officer', 'Chief Commercial Officer | Lending & Account Origination | Decisioning | Fraud & Biometrics | · Building business critical systems that provide superior customer experiences and robust risk and origination processes though proprietary no-code technology.', 'Auckland, Auckland, New Zealand', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Sales / GTM'], 'https://linkedin.com/in/richardbrooksnz', NULL, NULL, 'Credisense', FALSE, '[{"name": "Credisense"}, {"name": "Credisense Australia"}]'::jsonb, 'other_asia', ARRAY['other_asia', 'australia'], NULL, 'richard-brooks', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Brooke Roberts', 'Co-Founder and Director', 'Co-Founder, Co-CEO and Director at Sharesies · At Sharesies we believe everyone deserves the opportunity to grow their wealth.', 'New Zealand', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder'], 'https://linkedin.com/in/brooketanderson', NULL, NULL, 'Sharesies', FALSE, '[{"name": "Sharesies"}, {"name": "NZ Hi-Tech Awards"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'brooke-roberts', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Marko Previšić', 'Director, Australia & New Zealand at IDA Ireland', 'Director, Australia & New Zealand at IDA Ireland · Collaboration-oriented Project Manager with a demonstrated record of building and negotiating new business within targeted and assigned portfolios. A motivated, self-driven, and adaptable individual who maintains a strong working relationship with stakeholders to achieve desired outcomes.', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/markoprevisic14', NULL, NULL, 'IDA Ireland', FALSE, '[{"name": "IDA Ireland"}, {"name": "Tesco"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'marko-previsic', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Gemma Puig', 'Executive Director', 'Executive Director Catalonia Trade & Investment Office', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/gemmapuigpanadero', NULL, NULL, 'Catalonia Trade & Investment', FALSE, '[{"name": "Catalonia Trade & Investment"}, {"name": "ACCI\u00d3"}]'::jsonb, 'other_eu', ARRAY['other_eu', 'australia'], NULL, 'gemma-puig', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('David Camerlengo', 'Executive Director, Investment and Industry', 'Executive Director, Investment and Industry - Premier’s Department', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/david-camerlengo-22ba971a', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Australian Trade and Investment Commission (Austrade)"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'david-camerlengo', 'Trade & Government', ARRAY['functional_expert'], TRUE, FALSE),
  ('Derek Sheerin', 'Group General Manager / Managing Partner', 'Chief Executive | Founder | Director · I am the Group General Manager for Davidson Technology Consulting - a boutique consulting company offering strategic advisory, large scale delivery, and talent solutions for enterprises across Australia.Davidson is a proud Australian company with over 30 years of experience helping clients across many sectors including financial services, public sector, energy and utilities, transport and FMCG.Davidson''s strength is providing deeply experienced teams to help people and clients achieve real chang', 'Greater Melbourne Area', '30+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/derek-sheerin-6656083', NULL, NULL, 'Davidson', FALSE, '[{"name": "Davidson"}, {"name": "Lagrange Point Consulting"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'derek-sheerin', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Clayton Howes', 'CEO', 'Managing Director, Founder, CEO of MoneyMe | Fintech leader | 2019 AFR Most Innovative Companies | Deloitte Tech Fast 50 · Clayton Howes is the CEO, co-founder and driving force behind MoneyMe (ASX:MME), a high-growth, agile and multi-award-winning fintech that embraces the power of technology to deliver fair, transparent and frictionless consumer credit products to a tech-savvy generation with changing banking behaviours. Not content with building the nation’s most innovative fintech, Clayton has disrupted his own business, launching FreeStyle - the first virtual credit card that lives on your smartphone. He is in', 'New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder', 'Recognised Industry Leader'], 'https://linkedin.com/in/clhowes', NULL, NULL, 'MONEYME', FALSE, '[{"name": "MONEYME"}, {"name": "ListReady"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'clayton-howes', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Roby Sharon-Zipser', 'CEO, Co-Founder and Executive Director', 'Entrepreneur. Technologies for growth. Creator of the Tradie Ecosystem · I am CEO and Co-Founder of hipages Group, an Australian-born technology company that creates effortless solutions to help tradies streamline and grow their business and delight their customers. I am driven by a passion to empower people to create and invest in technology companies that liberate others to free up their time for higher-value business activities, leading to their growth. hipages Group encapsulates this, driven by our purpose of transforming the trade industry, making better lives f', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Technology / Product'], 'https://linkedin.com/in/roby-sharon-zipser-8417401b', NULL, NULL, 'hipages Group', FALSE, '[{"name": "hipages Group"}, {"name": "Advanced Audit Solutions"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'roby-sharon-zipser', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Fiona Stevens', 'Chief Commercial Officer', 'CCO | CMO | Commercial leader | Marketing and business strategist · Internationally experienced business, marketing and people leader, with 25+ years across agency and client environments.I love working with organisations who use tech to change a category; creating and harnessing the power of technology to change the way people buy, sell, engage with, or experience products or services.I spent 15 years in an award-winning boutique London agency; establishing and then leading the Strategy and Client Services teams, as well as creating and nurturing relationships', 'Sydney, New South Wales, Australia', '15+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government', 'Sales / GTM', 'Recognised Industry Leader'], 'https://linkedin.com/in/fionastevens', NULL, NULL, 'Airtasker', FALSE, '[{"name": "Airtasker"}, {"name": "Lendi Group"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'fiona-stevens', 'Trade & Government', ARRAY['both'], TRUE, FALSE),
  ('Gavin O''Kane', 'Co-Founder / CTO', 'AgenticAI: Where Automation Meets Autonomy - Co-founder (DoozerAI) · As technology evolves, so do the possibilities for reshaping businesses. At DoozerAI, we''re leading the charge into the AgenticAI frontier, where intelligent, autonomous virtual agents revolutionize business operations.With over 20 years of experience in the software industry, I have dedicated my career to harnessing the power of technology and automation to solve complex challenges. From crafting intuitive solutions to mentoring visionary teams, my passion lies in blending cutting-edge technolo', 'Brisbane, Queensland, Australia', '20+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/gavinokane', NULL, NULL, 'Doozer AI', FALSE, '[{"name": "Doozer AI"}, {"name": "Efficiency Leaders"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'gavin-okane', 'International Founder', ARRAY['both'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();