INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Brian Walsh', 'Founder', 'Founder, EastWestWorld Private Equity Pty Ltd · Brian Walsh is the Founder of East West. He has had a lifelong interest in the animated film industry and is now focusing on bringing together the skills of teams across an international base to cultivate a creative corporate environment. Brian also brings a wide range of experience to East West gained as an entrepreneur including financial strategies and corporate alliances. Some of the highlights of his career include securing a purchase buy-back agreement with a major utility company in the a', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/bwccppr', NULL, NULL, 'East West World Private Equity Pty Ltd', FALSE, '[{"name": "East West World Private Equity Pty Ltd"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'brian-walsh', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Stephen Biesty', 'Founder & CEO', 'Founder & CEO @ Parlai | Where Artificial Intelligence (AI) meets Secure Correctional Communications · Founder and executive technology leader at Parlai, an Australian Communications Services Provider (CSP) providing AI-driven, secure communications through a SaaS platform trusted by Enterprise and Government customers across the correctional services industry.Specialising in advanced voice, video, and messaging solutions powered by AI to deliver real-time insights, behavioral analysis, and intelligent moderation at scale.Passionate about transforming how organizations communicate — securely, int', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/stephenbiesty', NULL, NULL, 'Parlai Communications Group', FALSE, '[{"name": "Parlai Communications Group"}, {"name": "Nuamedia"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'stephen-biesty', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Alan FitzGerald', 'Founder & Fractional CTO for accounting firms', 'Helping accounting firms access the technology guidance they deserve with a solution-agnostic approach. · "An hour with me can save your firm weeks of wasted time, money, and stress."For over 10 years, I’ve helped accounting and advisory firms upgrade from outdated systems like MYOB, APS, and Handisoft to modern, best-in-breed solutions that actually work for their business — without vendor bias, commissions, or hidden agendas.Too often, I’m called in after a failed or over-budget rollout. My advice? Involve me before you sign contracts or commit to a technology change — it’s the difference between', 'Melbourne, Victoria, Australia', '10+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/alanrfitzgerald', NULL, NULL, 'Practice Connections Advisory', FALSE, '[{"name": "Practice Connections Advisory"}, {"name": "Intapp"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'alan-fitzgerald', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Órla Harkin', 'Founder & Principal', 'Strategic Executive | Digital Trust & Identity | Future-Focused Leadership | COO-Style Advisor | Global Strategy & Governance · Strategic Executive | Digital Trust & Identity | Future-Focused Leadership | COO-Style Advisor | Global Strategy & GovernanceI’m a strategic executive and governance expert with nearly 20 years of experience leading large-scale transformation, digital investment, and policy reform across government, infrastructure, and finance sectors — in Aotearoa New Zealand and globally.Originally trained as a barrister, I bring deep expertise in risk, compliance, and corporate governance — evolving into a CO', 'Wellington, Wellington, New Zealand', '20+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Market Research / Strategy', 'Cross-border'], 'https://linkedin.com/in/orla-harkin', NULL, NULL, 'Harkin Consulting', FALSE, '[{"name": "Harkin Consulting"}, {"name": "Stats NZ"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'orla-harkin', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Laurie Price', 'Principal Consultant, International Trade & Investment', 'Strategic Trade & Investment Advisory | Business Growth & Expansion Specialist', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Trade & Government', 'Cross-border'], 'https://linkedin.com/in/lauriecprice', NULL, NULL, 'Foley', FALSE, '[{"name": "Foley"}, {"name": "IBG Global"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'laurie-price', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Troy Toohey', 'Trade Manager', 'Trade Manager | Technology at Global Victoria Based in ANZ, working with Troy''s network across the region.', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/troytoohey', NULL, NULL, 'Global Victoria', FALSE, '[{"name": "Global Victoria"}, {"name": "Troy Toohey"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'troy-toohey', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Sarah Quigley', 'A/Consul General of Canada', 'A/ Consul General at the Consulate General of Canada, Sydney at Global Affairs Canada | Affaires mondiales Canada · Through our presence in more than 160 cities worldwide, the Canadian Trade Commissioner Service (TCS) provides Canadian organizations with on-the-ground intelligence and practical advice on foreign markets that help thousands of companies each year tackle concrete problems and pursue opportunities in foreign markets. We have privileged access to foreign governments, key business leaders and decision-makers because we are part of Canada’s embassies and consulates. Our business contacts include po', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/sarah-quigley-03a2511b0', NULL, NULL, 'Global Affairs Canada | Affaires mondiales Canada', FALSE, '[{"name": "Global Affairs Canada | Affaires mondiales Canada"}, {"name": "Blake, Cassels & Graydon LLP"}]'::jsonb, 'canada', ARRAY['canada', 'australia'], NULL, 'sarah-quigley', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Cian Mcloughlin', 'CEO', 'Founder & CEO Trinity | Amazon Bestselling Author | LinkedIn Top Voice | Top 50 Sales Keynote Speaker | Global Win Loss Expert On Complex, High Vale Enterprise Sales · With over 20 years of B2B sales experience, I have a passion for helping sales-focused organizations improve their performance and profitability. I founded Usetrinity.com, a SaaS platform that automates win/loss analysis and customer feedback, and Trinity Perspectives, a consulting firm that provides sales transformation and training services.As an Amazon #1 bestselling author, award-winning blogger, and Top 50 sales keynote speaker, I share my insights and expertise on topics such as social sel', 'Greater Sydney Area', '20+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Sector Expert: SaaS', 'Cross-border', 'Recognised Industry Leader'], 'https://linkedin.com/in/cianmcloughlin', NULL, NULL, 'Trinity', FALSE, '[{"name": "Trinity"}, {"name": "SAP"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'cian-mcloughlin', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Cameron Owens', 'Co-Founder & Chief Operating Officer', 'Founder / Investor / Advisor to early stage and scale up technology businesses across AI, finance, property and martech operating in Australian and international markets including the USA and Japan · As a seasoned founder and growth executive, I bring over 20 years of expertise in driving strategic sales and successfully scaling businesses across diverse industries and global regions, with a particular focus on the Australian, USA and Japanese markets. My track record includes impactful roles at renowned organizations such as Shell, GE, and Nab, coupled with a passion for founding and scaling startup ventures. I am not only an investor in early-stage ventures, specializing in Ai, fintech, pr', 'Melbourne, Victoria, Australia', '20+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Fintech Founder', 'Cross-border'], 'https://linkedin.com/in/cameronowens', NULL, NULL, 'Rello', FALSE, '[{"name": "Rello"}, {"name": "Shirofune"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'cameron-owens', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Andrea Plawutsky', 'Director', 'Helping people, places & businesses thrive | Director, Amplify Me, GAICD · I''ve had the privilege of working with a really diverse and exciting range of clients, large and small, over the past 20+ years - and I hope to continue for the next 20!I''ve brought them an equally diverse skill set... with experience in international business expansion, travel and tourism strategy, training and facilitation, marketing, public relations and communications, and engagement with Asia. I''ve delivered festivals and events, acting in an executive producer capacity to reactive spaces a', 'Greater Newcastle Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'HR / Talent', 'Cross-border', 'Recognised Industry Leader'], 'https://linkedin.com/in/andreaplawutsky', NULL, NULL, 'Amplify Me Pty Ltd', FALSE, '[{"name": "Amplify Me Pty Ltd"}, {"name": "Haymarket HQ"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'andrea-plawutsky', 'Trade & Government', ARRAY['functional_expert'], TRUE, FALSE),
  ('Lydia R.', 'Director, Australia / New Zealand', 'Director, Australia / New Zealand at Enterprise Ireland', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/lydia-r', NULL, NULL, 'Enterprise Ireland', FALSE, '[{"name": "Enterprise Ireland"}, {"name": "Aurivo Co-operative Society Limited"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'lydia-r', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();