INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Nick Jenkin', 'Director / Founder', 'Director at Jenkin Beattie - helping tech vendors & consultancies secure the best GTM talent in ANZ | Executive Recruitment, IT Sales, Presales, Marketing, CS & PS | 25 years’ experience & going strong | 800 + placements · With more than 23 years'' IT recruitment experience, my primary area of expertise is in placing executive sales, marketing and senior leadership professionals with technology vendors, service providers, systems integrators, professional services firms and digital consultancies.I specialise in recruiting sales, marketing and executive level roles within the following areas: Digital, Cloud Computing (SaaS, IaaS, PaaS), Managed Services, IT and Business Process Outsourcing, professional services, co', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Sector Expert: SaaS'], 'https://linkedin.com/in/njenkin', NULL, NULL, 'Jenkin Beattie', FALSE, '[{"name": "Jenkin Beattie"}, {"name": "GOW Recruitment"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'nick-jenkin', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Tony Chan', 'Founder & CEO', 'Founder & CEO at Wagepay · I am the Founder and CEO of Wagepay, a fintech company revolutionising the pay cycle and wage payment process. We harness technology to transform how people access and manage their income, bringing financial empowerment to all.With a passion for financial inclusion, an MBA from Melbourne Business School, and membership in the AICD, I am dedicated to driving positive change in the industry.', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder'], 'https://linkedin.com/in/tonychanwagepay', NULL, NULL, 'Wagepay', FALSE, '[{"name": "Wagepay"}, {"name": "PINTEC (\u54c1\u949b\uff09"}]'::jsonb, 'china', ARRAY['china', 'australia'], NULL, 'tony-chan', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Louise Furlong', 'Founder and Director', 'Rec2Rec''ing in #Construction and #Tech with a Difference · Who am I? I am from Dublin, Ireland (Failte) I''m the definition of an extravert. I love PEOPLE and socialising whilst keeping active. Completing a bachelor’s degree in Social Science and Psychology, I packed my bags and relocated to Australia in 2017. My recruitment career took off in Perth where I joined a high-performing recruitment agency, specialising in labour hire whilst I learned all things recruitment. In 2019, I relocated to Sydney to build a construction division. This role was wher', 'Bondi, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'HR / Talent'], 'https://linkedin.com/in/louise-furlong-98a980150', NULL, NULL, 'Emerald Recruitment Consultancy', FALSE, '[{"name": "Emerald Recruitment Consultancy"}, {"name": "TalentWeb | B Corp"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'louise-furlong', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Ciaran O''Connell', 'Founder, Managing Partner', 'Founder | @ Thoroughly Modern Journeys; nex-icon · Over 25 years of business and technology consulting experience, providing transformation advisory and large-scale program delivery with C-suite executives and public sector leaders. I specialise in helping executives cut through complexity, activate business strategy and operating models with technology in the right places, the right way, at the right time.Founder of Thoroughly Modern Journeys - A specialist consultancy that works exclusively with senior executive teams to get the best value fro', 'Brisbane, Queensland, Australia', '25+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/ciaranoconnell', NULL, NULL, 'Thoroughly Modern Journeys', FALSE, '[{"name": "Thoroughly Modern Journeys"}, {"name": "nex-icon"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'ciaran-oconnell', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('David Whelan', 'Founder/ Chief Executive Officer', 'Founder & CEO at Urban Rest · Ex-finance professional turned entrepreneur, founder of a technology/real estate platform Urban Rest.Urban Rest is redefining accommodation by providing different way to stay. At the core is a technology driven operating platform enabling previously unsuitable asset classes (Build to Rent, Residential, Boutique Hotels and office conversions) to be unlocked for use as corporate accommodation.Urban Rest operates a global platform with locations around Australia, New Zealand and Europe, including s', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Sector Expert: Real Estate'], 'https://linkedin.com/in/david-whelan-86aa3840', NULL, NULL, 'Urban Rest', FALSE, '[{"name": "Urban Rest"}, {"name": "MFS Investment Management"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'david-whelan', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Sarah Kim', 'Senior Trade Adviser (Technology & Services), Trade/Export Advisory', 'Export/Trade Advisory @ Investment NSW Based in ANZ, working with Sarah''s network across the region.', 'Barangaroo, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/sarah-yun-kim', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Australian Trade and Investment Commission (Austrade)"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'sarah-kim', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Darren Rogan', 'CEO & CoFounder', 'CEO & Founder @ Film Labs | Web3 & AI Innovator | Advisory - Rogues Lab · I create the future at the intersection of artificial intelligence, blockchain, and digital experiences.Currently building Film Labs, a groundbreaking Web3 platform that democratizes video creation through AI. Our technology empowers creators to generate professional-quality videos with just text prompts, while maintaining ownership and monetization rights on the blockchain.My experience spans founding several startups, scaling teams, and advising numerous ventures across Australia, UK, and the', 'Gold Coast, Queensland, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product'], 'https://linkedin.com/in/darrenrogan', NULL, NULL, 'Film Labs', FALSE, '[{"name": "Film Labs"}, {"name": "Rogues Lab"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'darren-rogan', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Cameron Dart', 'CEO & Founder', 'Founder: The FinTech Company = Australian FinTech | In AI Today | International FinTech | US FinTech | UK FinTech | Ireland FinTech | UAE FinTech | Australian Blockchain & Cryptocurrency | PropTech News | StartUp ScaleUp · Having worked in Australia (Sydney, Brisbane, Gold Coast), U.S.A. (Dallas, TX) and the United Kingdom (London), I have international experience in various fields of technology, investment and development covering areas such as fintech, banking, finance, property development, property finance, mining investment and technology start ups.My expertise has always been to find a business and work out ways to improve it - make the entity more streamlined, more efficient, more effective and more profita', 'Gold Coast, Queensland, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/camerongdart', NULL, NULL, 'Australian FinTech', FALSE, '[{"name": "Australian FinTech"}, {"name": "In AI Today"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'cameron-dart', 'Trade & Government', ARRAY['both'], TRUE, FALSE),
  ('Paul Minton', 'Co-Founder and Director', 'Ex Accountant headhunting the best Finance talent in Australia · I''m a Chartered Accountant and Co-founder of Lemon Talent, where I work with finance leaders to source market leading talent in Sydney.Finance Leaders - Would it be helpful to have an accountant screening candidates before you are engaged? - Do you get frustrated when recruiters don''t understand the job brief and what you are really after?- Are you spending too much time in the hiring process only to find that the talent doesn''t match your expectations? Job seekers - Would you like to partner wi', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Accounting / Tax'], 'https://linkedin.com/in/paul-minton-4b7899107', NULL, NULL, 'Lemon Talent', FALSE, '[{"name": "Lemon Talent"}, {"name": "EY"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'paul-minton', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Pablo Avaria', 'Executive Board Member', 'Harvard PLD 2025 | Board Member · Pablo Avaria is a globally focused business strategist with an MBA from Monash University and the Program for Leadership Development (Harvards Executive MBA Alternative) at Harvard Business School. His academic pathway has been intentionally designed to prepare for high-impact consulting in marketing, growth, and corporate strategy.At Harvard, Pablo is trained in the case method used by top global firms developing decision-making, leadership, and strategic problem-solving skills under the guidan', 'The Rocks, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Trade & Government'], 'https://linkedin.com/in/pablo-avaria', NULL, NULL, 'Professionals in International Trade (PIT)', FALSE, '[{"name": "Professionals in International Trade (PIT)"}, {"name": "Israel Trade and Economic Commission Australia"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'pablo-avaria', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Nagender Chetti', 'Founder', 'Fractional Executive | Founder @ Neura Vision | Data, Analytics & AI Strategy | Generative AI & Digital Transformation Leader | Driving Business Growth & Innovation | Top 25 Analytics Leader (IAPA 2023)| · Recognised as one of Australia’s Top 25 Analytics Leaders (IAPA 2023), I am a strategic and impact-focused executive with over 20 years experience at the intersection of data, analytics, AI, digital transformation, and business strategy. I help forward-thinking organisations unlock growth, accelerate innovation, and embed future-ready capabilities across insurance, financial services, and technology.With deep expertise in data strategy, analytics, AI adoption, digital innovation, business transf', 'Greater Melbourne Area', '20+ years operating experience in ANZ and international markets.', ARRAY['International Founder', 'Market Research / Strategy'], 'https://linkedin.com/in/nagenderchetti', NULL, NULL, 'Neura Vision', FALSE, '[{"name": "Neura Vision"}, {"name": "Suncorp Group"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'nagender-chetti', 'International Founder', ARRAY['both'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();