INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Zach Zocher', 'Head of Community', 'Head of Community @ Techvisa | Helping Tech Startups Successfully Scale by Unlocking Global Talent Pools', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Events / Community', 'Cross-border'], 'https://linkedin.com/in/zach-zocher', NULL, NULL, 'Techvisa', FALSE, '[{"name": "Techvisa"}, {"name": "The Community Collective"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'zach-zocher', 'Active Advisor', ARRAY['international_entrant'], TRUE, TRUE),
  ('Sachi Wickramage', 'Co-Founder & Board Member', 'CoFounder & Board Member at i4T Global | Board Director & Grand Jury Member at UN WSA (SDGs & WSIS) | Social Impact, Sustainability & ESG Advocate | PropTech, FSM, Retail & eCommerce Innovator | SaaS, AI, HCI Connoisseur · “𝘿𝙚𝙙𝙞𝙘𝙖𝙩𝙚𝙙 𝙩𝙤 𝘾𝙤𝙣𝙩𝙞𝙣𝙪𝙤𝙪𝙨 𝙄𝙢𝙥𝙧𝙤𝙫𝙚𝙢𝙚𝙣𝙩 𝙖𝙣𝙙 𝘾𝙧𝙚𝙖𝙩𝙞𝙣𝙜 𝙄𝙣𝙨𝙥𝙞𝙧𝙞𝙣𝙜 𝘾𝙪𝙨𝙩𝙤𝙢𝙚𝙧 𝙀𝙭𝙥𝙚𝙧𝙞𝙚𝙣𝙘𝙚𝙨” - 𝘚𝘢𝘤𝘩𝘪 𝘞𝘪𝘤𝘬𝘳𝘢𝘮𝘢𝘨𝘦With an extensive 20+ year career at the intersection of technology & innovation, I''ve cultivated a profound expertise in leading high-performance teams to deliver award-winning mobile apps, web apps, & scalable cloud SaaS platforms. My visionary & collaborative leadership style has enabled me to build Product, Engineering & Design teams that consistently produce disruptive innovations, setting ne', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Technology / Product', 'Cross-border', 'Recognised Industry Leader'], 'https://linkedin.com/in/sachiwickramage', NULL, NULL, 'i4T Global', FALSE, '[{"name": "i4T Global"}, {"name": "The digiDirect Group"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'sachi-wickramage', 'International Founder', ARRAY['international_entrant'], TRUE, TRUE),
  ('Carol Friel', 'Associate Director, Precinct Development, Investment NSW', 'Associate Director, Precinct Development, Investment NSW · A passionate leader and entrepreneurship advocate with a demonstrated history of working in the innovation and media sectors. Skilled in communications, relationship management, program management, administration, writing, and cross-sector collaboration. A strong presenter and relationship manager with a Master''s degree in Multimedia from Dublin City University.', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/carol-friel', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "NSW Treasury"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'carol-friel', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Jerome Fournand', 'General Manager', 'General Manager at FACCI - French-Australian Chamber of Commerce & Industry · Experienced General Manager with over 15 years of leadership across marketing, logistics, and international trade. I began my career in the marketing and digital industry, where embracing innovation and new technologies quickly became essential. This early exposure shaped my conviction that creativity and forward-thinking are key drivers of business transformation.I then gained extensive experience in the logistics sector, managing large-scale projects and thousands of contractors. By focusing o', 'Sydney, New South Wales, Australia', '15+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government'], 'https://linkedin.com/in/jeromefournand', NULL, NULL, 'FACCI - French-Australian Chamber of Commerce & Industry', FALSE, '[{"name": "FACCI - French-Australian Chamber of Commerce & Industry"}, {"name": "GDR Media Group"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'jerome-fournand', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('Daniel Spencer', 'Head of Partnerships', 'Sales & Partnerships Leader | APAC Go to Market Expert · Dynamic sales leader with 15+ years of experience driving growth for tech and professional services firms across Australia, Asia, and Europe. Proven record of scaling sales revenue, building and leading high-performing teams, and developing new markets. Fluent in English and French and expert in B2B sales strategy, CRM optimisation, and partnership-driven revenue. Recognised for consistently exceeding targets, fostering client loyalty, and developing scalable sales operations from the ground up.', 'Darlinghurst, New South Wales, Australia', '15+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Sales / GTM'], 'https://linkedin.com/in/danielrayspencer', NULL, NULL, 'Sleek', FALSE, '[{"name": "Sleek"}, {"name": "Professionals in International Trade (PIT)"}]'::jsonb, 'france', ARRAY['france', 'australia'], NULL, 'daniel-spencer', 'Active Advisor', ARRAY['international_entrant'], TRUE, TRUE),
  ('Claire Marriott', 'APAC CEO', 'APAC CEO at Newfound | Co-Founder #TechDiversity Australia · I lead global headhunting projects for high growth technology companies, and have successfully delivered projects for clients across Asia Pacific, Europe and North America.I co-founded the Australia''s #Tech Diversity awards, leading 13 industry groups and businesses to drive a culture of inclusion in the Australian technology industries.', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Trade & Government', 'Cross-border'], 'https://linkedin.com/in/clairemarriott', NULL, NULL, 'Newfound', FALSE, '[{"name": "Newfound"}, {"name": "Startupbootcamp"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'claire-marriott', 'Scaled Founder', ARRAY['international_entrant'], TRUE, TRUE),
  ('Sam Kothari', 'Cofounder, COO', 'Cofounder at Everlab · I enjoy working on challenging business problems with great people. I helped grow and scale Airwallex in Australia as employee number 3 in the commercial team. I''m now building Everlab to help detect and manage chronic disease. I''m always keen to connect with business owners, founders, startups and entreprenuers. Please let me know how I can help!', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Trade & Government'], 'https://linkedin.com/in/kotharisam', NULL, NULL, 'Everlab', FALSE, '[{"name": "Everlab"}, {"name": "Airwallex"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'sam-kothari', 'International Founder', ARRAY['both'], TRUE, TRUE),
  ('Lawrence Christoffelsz', 'Founder and Host of the Global Trade Show (expert interviewer & MC for industry events)', 'Global Trade, Logistics & Supply Chain Entrepreneur. Founder of ATLC, Import Export TV, Ethical Trade Alliance, Co-Founder Global Hub Advisory Partners · With over 25 years of experience in global trade and supply chains, I’ve worked across diverse industries to deliver innovative logistics solutions and drive strategic growth. As the founder and CEO of the Australian Trade & Logistics Corporation (ATLC), I’m passionate about empowering SMEs with the tools, insights, and connections needed to thrive in global markets. Regularly engaged as a speaker and advisor to trade agencies, consulates, and industry bodies, I’m committed to advancing ethical,', 'Melbourne, Victoria, Australia', '25+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Marketing / PR / Comms', 'Cross-border'], 'https://linkedin.com/in/lawrence-christoffelsz-global-trade', NULL, NULL, 'Import Export TV', FALSE, '[{"name": "Import Export TV"}, {"name": "Australian Trade & Logistics Corporation"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'lawrence-christoffelsz', 'Active Advisor', ARRAY['international_entrant'], TRUE, TRUE),
  ('Sinead Connolly', 'Founder/ Board Member', 'Founder | SEEK Recruitment Leader of the Year | Australia''s top recruitment agency; delivering exceptional HR, talent and business support recruitment · Would you like to attract and retain the best talent, knowing the process will be smooth, straightforward, and impactful? Do you crave external market knowledge and intel to help navigate today’s changing world of work? Does your ability to deliver rely on a strong people and culture strategy?If you answered yes to any of these, read on.I launched Lotus People in 2015 to fill a gap in the market — for an agency that genuinely cared. One that combined deep expertise with heart, passion, and p', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'HR / Talent', 'Recognised Industry Leader'], 'https://linkedin.com/in/sineadconnolly', NULL, NULL, 'Lotus People', FALSE, '[{"name": "Lotus People"}, {"name": "Cox Purtell Staffing Services"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'sinead-connolly', 'International Founder', ARRAY['international_entrant'], TRUE, TRUE),
  ('Suzanne M.', 'Senior Business Development Manager Trade & Investment', 'Trade & Investment Strategist | Asia–EU Market Growth | Digital & AI Fluent | Helping Organisations Expand Globally · With a strong track record across Australia, the UK, and Asia-Pacific, I specialise in trade and investment promotion, stakeholder engagement, and market expansion, particularly in high-growth sectors like digital health, precision medicine, and agrifood.Recent highlights include: • Securing inbound investment and export deals in healthtech and agribusiness • Leading trade missions and B2B engagement across Europe and Asia • Supporting startups and scaling companies with market entry and growth', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/suzanne-m-bb81578', NULL, NULL, 'Enterprise Singapore', FALSE, '[{"name": "Enterprise Singapore"}, {"name": "Invest Northern Ireland"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'suzanne-m', 'Trade & Government', ARRAY['international_entrant'], TRUE, TRUE),
  ('David Smith', 'Associate Director - Program Operations', 'Associate Director at Investment NSW. 3x founder. Ex WeWork, INCUBATE, Coventured. Angel investor (Airtree Explorer Cohort 6). · Startup Co-Founder, Accelerator Manager, Angel investor, MBA.I am a passionate startup professional and angel investor who has extensive experience in accelerator and startup programs, and as a founder. In 2015 ,I followed my passion for entrepreneurship and created Knokal a marketplace startup that won several awards (including Westpac Businesses of Tomorrow 2017) and raised multiple funding rounds and Atmin, a bootstrapped startup in 2018. I then worked in the accelerator space (launching WeWo', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/davidsmithknokal', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Academy of Entrepreneurs"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'david-smith', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();