INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Binh Rey', 'General Manager', 'Managing Director, Applied Marks ● Trade Mark Attorney with branding expertise ● Expertise in branding, former marketer turned Trade Mark Attorney ● Queen of Trade Marks® ● Speaker & Trainer ● Executive Board member · When you protect your brand, you protect your future success. That’s why trademarks and brand protections are not just for big, multi-national companies. Every business has the right to operate without the fear of infringement. With over 15 years of marketing industry experience, 12 years of trademark industry experience, and over 1,500 trademarks filed, I inform, empower, and protect businesses of all sizes as General Manager at Applied Marks. Applied Marks is a leading provider of online trade', 'Melbourne, Victoria, Australia', '15+ years operating experience in ANZ and international markets.', ARRAY['Active Advisor', 'Legal'], 'https://linkedin.com/in/binhrey', NULL, NULL, 'Applied Marks', FALSE, '[{"name": "Applied Marks"}, {"name": "Business Blueprint"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'binh-rey', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Louise Lysaght', 'Global Head of Digital Engagment', 'VP CX and Digital Experience | GTM | Revenue Growth | Customer Success and Account Management | Strategy | Executive Leadership · Customer Experience Professional and Evangelist, Passionate Customer and People centred Business Transformation Leader', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Company Setup / EOR', 'Cross-border'], 'https://linkedin.com/in/louise-lysaght-60845822', NULL, NULL, 'Employment Hero', FALSE, '[{"name": "Employment Hero"}, {"name": "HotDoc"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'louise-lysaght', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Jaco Veldsman', 'Global Head of Non-FX Revenue', 'Taking Spend Management Global with OFX | Co Founder of Paytron | Receive, Manage, Approve, Spend | Twitter: @jacoveldsman · There are few things in life more rewarding than helping another human being.', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder', 'Cross-border'], 'https://linkedin.com/in/jacov', NULL, NULL, 'OFX', FALSE, '[{"name": "OFX"}, {"name": "Paytron"}]'::jsonb, 'south_africa', ARRAY['south_africa', 'australia'], NULL, 'jaco-veldsman', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Bertrand Raoult', 'Senior Regional Manager - Australia', 'Senior Regional Manager - Australia at Export Development Canada · A MBA qualified senior accounts and sales professional with 26 years international experience, I have a proven track record of delivering growth and profitability through building long-term relationships with clients, based on credibility, trust and openness.Comfortable working at all levels of organisations, I have developed strong negotiation, presentation and stakeholder management skills that have been key factors in delivering value to both my employers and clients. Commercially astute, wit', 'Clovelly, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/bertrandraoult', NULL, NULL, 'Export Development Canada | Exportation et développement Canada', FALSE, '[{"name": "Export Development Canada | Exportation et d\u00e9veloppement Canada"}, {"name": "Trade Commissioner Service | Service des d\u00e9l\u00e9gu\u00e9s commerciaux"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'bertrand-raoult', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Melissa Wharton', 'Chief Executive Officer', 'CEO | Helping Business & Government Leaders Navigate Cross-Border Trade With Speed, Clarity & Commercial Impact · Melissa Wharton is the CEO of the Canadian-Australian Chamber of Commerce (CACC) — the only bilateral trade organisation operating in both countries — connecting a cross-border network of 6,500+ business leaders, innovators, and policymakers.For over 20 years, the CACC has been a trusted bridge between policy and commerce, helping governments and corporates navigate the complexities of international trade. Backed by a team of 100 active volunteers across Canada and Australia, the Chamber deliver', 'Greater Sydney Area', '20+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/melissawharton', NULL, NULL, 'Canadian Australian Chamber of Commerce', FALSE, '[{"name": "Canadian Australian Chamber of Commerce"}, {"name": "Mad Mex"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'melissa-wharton', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Sarah Nolet', 'Co-Founder & General Partner', 'Co-Founder and Managing Partner — Tenacious Ventures Group · Sarah Nolet is an internationally recognized food systems innovation expert and co-founder of Tenacious Ventures, a high-support, high conviction, sector-specific agrifood tech venture firm. Sarah has been instrumental in building the early stage agtech ecosystem - from advising dozens of startups, designing accelerator programs and consulting to established agribusinesses, to helping industry, universities and government develop and implement forward-looking initiatives in food system innovatio', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/svnolet', NULL, NULL, 'Tenacious Ventures', FALSE, '[{"name": "Tenacious Ventures"}, {"name": "AgTech...So What? Podcast"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'sarah-nolet', 'International Founder', ARRAY['local_startup'], TRUE, FALSE),
  ('Ram Gorlamandala', 'Founder & CEO', 'Founder & CEO @ Tat Capital | Non Executive Director I Family Offices I Venture Capital & Private Equity I Australia and India -Market access I Investment Banking I Angel Investor · As the Founder &amp; CEO of Tat Capital, I bring over 12 years of experience in cross-border advisory and investment, specializing in capital raising, M&amp;A, and market entry strategies between Australia, New Zealand, and the Indian subcontinent. Tat Capital’s ecosystem of family offices, institutional investors, and venture funds supports transformative growth opportunities and fosters strategic global partnerships. Currently serving as a Non Executive Director at 20Cube Logistics, I offer gu', 'Greater Sydney Area', '12+ years operating experience in ANZ and international markets.', ARRAY['Scaled Founder', 'Fundraising / Investment', 'Cross-border'], 'https://linkedin.com/in/ramnaresh', NULL, NULL, 'Tat Capital - Powering Growth with Purpose', FALSE, '[{"name": "Tat Capital - Powering Growth with Purpose"}, {"name": "20Cube Logistics"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'ram-gorlamandala', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Eoin Hughes', 'Market Advisor - Agribusiness & Waste Sustainability', 'Market Advisor - Agribusiness & Waste Sustainability at Enterprise Ireland Australia/New Zealand · Enterprise Ireland is the Irish government agency responsible for the development and growth of Irish enterprises in world markets. The EI A/NZ team assists innovative Irish companies from a wide range of industry sectors with market entry and support services across Australia and New Zealand.In my current role, I support Irish companies servicing the Agriculture sectors in Australia and New Zealand with agricultural machinery and equipment, agritech devices and software, animal products and sup', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/eoinhughes', NULL, NULL, 'Enterprise Ireland Australia & New Zealand', FALSE, '[{"name": "Enterprise Ireland Australia & New Zealand"}]'::jsonb, 'france', ARRAY['france', 'australia'], NULL, 'eoin-hughes', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Eoin Keating', 'Regional Director - Sales - A/NZ Region', 'Delivering AI-Powered FinCrime Operating Systems · Enterprise AI / SaaS Sales GTM Leader | Trusted Partner for Transformation | C-Suite AdvisorWith 20+ years’ experience scaling enterprise technology across Australia, New Zealand, and Europe, I help organisations adopt breakthrough solutions that deliver business impact. My specialisation lies in enterprise SaaS, AI, generative AI adoption, regulatory/financial tech, healthcare and public sector. In my current role leading sales for the A/NZ region at Fenergo, I’ve closed multi-year Enterprise S', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Sales / GTM', 'Cross-border'], 'https://linkedin.com/in/eoinkeating', NULL, NULL, 'Fenergo', FALSE, '[{"name": "Fenergo"}, {"name": "DXC Practice for Oracle"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'eoin-keating', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Peter van Bruchem', 'Chief Startup Evangelist and Co-Founder', 'Building Australia''s best data service on investment and investors in Startup and Tech cos, blending announced deal data with data from companies'' non-confidential lodgements the Australia''s Corporate Regulator. · I am passionate about growing the Australian tech startup scene.I am an excellent lateral thinker with great skills in assisting founders refine their business ideas and where necessary pivoting an idea or concept to one that has much better chance of flying. I have a good understanding of how to structure startup businesses into something that investors are going to find more interesting and I can help you refine your pitch to get that investment as well as introduce you to potential investors.', 'Greater Perth Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/petervanb', NULL, NULL, 'Techboard', FALSE, '[{"name": "Techboard"}, {"name": "Tech Council of Australia"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'peter-van-bruchem', 'Scaled Founder', ARRAY['both'], TRUE, FALSE),
  ('Charlie Crozier', 'Director', 'Founder & CEO | Web3 Evangelist | · Charlie holds extensive experience across the impact, blockchain technology, and finance industries. He has a depth of startup experience that adds a pedigree of understanding that cannot be taught but must be experienced firsthand. Having led teams throughout his entire career, he has developed a vast array of skills in business development, marketing, sales, capital raising, and technology.Charlie developed a personal interest in equities from a young age. This evolved to successfully raising', 'Greater Melbourne Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Market Research / Strategy'], 'https://linkedin.com/in/charliecrozier', NULL, NULL, 'CCG', FALSE, '[{"name": "CCG"}, {"name": "VOLI"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'charlie-crozier', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();