INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Ronan Lehane', 'Co-Founder & Executive Director', 'Investment Management - Independent Advisor - Private Investor - Board Member · Ronan is the Founder & Director of Capital Collaboration – a private investment firm working with companies, family offices and co-investors globally. Capital Collaboration builds value through long term relationships with its partners and continues to build and invest in a portfolio of successful ventures globally.In 2022, Ronan together with a highly experienced group of investment professionals established and launched Carrara Capital.Carrara manages the Carrara Global Opportunities Fund (CGO', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fundraising / Investment'], 'https://linkedin.com/in/ronanlehane', NULL, NULL, 'Carrara Capital', FALSE, '[{"name": "Carrara Capital"}, {"name": "Capital Collaboration"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'ronan-lehane', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Brendan O''Connell', 'Chief Executive', 'Chief Executive at AgriTechNZ | Founder of Crannora Consulting | helping all thrive through the creation and smart application of technology in primary industries · Creative, energetic and passionate about product creation and the people who do it. I am all about identifying new business opportunities, scaling businesses internationally and the collective power and sustainability of ecosystems.“Feet on the ground, eyes on the horizon,” is a phrase I’ve borrowed from John Deere, an agricultural machinery company, to explain what drives me.I’ve worked in several technology sectors and really identify with the potential and purpose found in Agritech. There’s n', 'Auckland, Auckland, New Zealand', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/brendanoconnell', NULL, NULL, 'AgriTech New Zealand', FALSE, '[{"name": "AgriTech New Zealand"}, {"name": "Enterprise Ireland"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'brendan-oconnell', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Hanhana(Ellena) Cho', 'Deputy Director', 'Deputy director at KOTRA Based in ANZ, working with Hanhana(Ellena)''s network across the region.', 'The Rocks, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/hanhana-ellena-cho-63696b287', NULL, NULL, 'KOTRA Sydney AU', FALSE, '[{"name": "KOTRA Sydney AU"}, {"name": "KOTRA"}]'::jsonb, 'korea', ARRAY['korea', 'australia'], NULL, 'hanhanaellena-cho', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Jacqui Duncan', 'General Manager, NSW', 'General Manager | Emerging Tech Startups | CEMS Alumna · Driving the growth of Australia’s largest innovation community.I’m a business leader with experience in international trade, tech, and startups, driving growth and innovation across the country’s business and tech ecosystem.At Stone & Chalk Group, I lead the NSW business, running the front door to the state’s innovation sector through our Tech Central Innovation Hub - part of Australia’s newest precinct backed by $38.5 million in government investment. The 8,000SQM hub is home to 1,000+ founde', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Startup Advisor'], 'https://linkedin.com/in/jacqui-duncan', NULL, NULL, 'Stone & Chalk', FALSE, '[{"name": "Stone & Chalk"}, {"name": "IdeaFloat"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'jacqui-duncan', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Emily Cusick', 'Senior Associate, Investment Concierge & Strategic Advisory, Investment Delivery Authority', 'Senior Associate, Investment Concierge & Strategic Advisory, Investment Delivery Authority | Premier’s Department NSW · Associate at Investment NSW, specialising in attracting investment in key sectors crucial for the economic development of New South Wales, through fostering both domestic and foreign direct investment. With over six years'' experience in real estate, I successfully managed a diverse residential property portfolio. My qualifications include a Bachelor of Business with majors in Marketing and Tourism from the University of Newcastle, Certificate IV in Retail Management, and a Certificate of Registr', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/emily-cusick-1899b882', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Stone Real Estate."}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'emily-cusick', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Kutay Kesim', 'Senior Export Adviser', 'Senior Export Adviser at Investment NSW | TradeStart Adviser at Austrade · An experienced and results driven international trade professional with over 15 years of extensive experience in trade facilitation, customs and international trade law compliance, stakeholder engagement and project management gained in government and education sectors. Equipped with superior client and stakeholder engagement capabilities, accentuated by solid business acumen, strategic and analytical thinking, influencing, negotiating and problem-solving skills', 'Greater Sydney Area', '15+ years operating experience in ANZ and international markets.', ARRAY['Trade & Government'], 'https://linkedin.com/in/kutaykesim', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Australian Trade and Investment Commission (Austrade)"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'kutay-kesim', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('April Palmerlee', 'CEO', 'CEO @ AmCham Australia | Chairman, AmChams of Asia Pacific · As the CEO of the American Chamber of Commerce in Australia, April leads the largest and most influential international business organisation in the country, with over 600 member companies representing one million-plus businesspeople. AmCham''s mission is to promote trade, commerce, and investment between the US and Australia, and to support the interests and needs of its membership base. She also serves as Chairman of the AmChams of Asia Pacific (29 individual AmChams across the region). With ov', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Active Advisor', 'Trade & Government', 'Cross-border'], 'https://linkedin.com/in/april-palmerlee-%f0%9f%87%ba%f0%9f%87%b8%f0%9f%87%a6%f0%9f%87%ba-02265b71', NULL, NULL, 'AmCham Australia', FALSE, '[{"name": "AmCham Australia"}, {"name": "AmChams of Asia Pacific"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'april-palmerlee', 'Active Advisor', ARRAY['international_entrant'], TRUE, FALSE),
  ('Olwyn Connolly', 'Co-Founder & Group COO', 'Professional Dot-Joiner | Chaos Co-Ordinator | SAAS Executive | Innovation Seeker | Certified Board Chair™ | GAICD', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Accounting / Tax', 'Recognised Industry Leader'], 'https://linkedin.com/in/oconnolly', NULL, NULL, 'Squeeze', FALSE, '[{"name": "Squeeze"}, {"name": "Practice Connections Advisory"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'olwyn-connolly', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('James McEniery', 'Co-Founder Dosh NZ', 'Co-Founder Dosh NZ at DOSH New Zealand · Experienced Managing Director with a demonstrated history of working in the food & beverages industry. Skilled in Leading Global Sales and Marketing teams, developing talent and people, Board Management, FMCG, Trade Marketing, and Key Account Development.', 'Auckland, Auckland, New Zealand', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder', 'Cross-border'], 'https://linkedin.com/in/james-mceniery-0547712b', NULL, NULL, 'Dosh New Zealand', FALSE, '[{"name": "Dosh New Zealand"}, {"name": "Lion"}]'::jsonb, 'other_asia', ARRAY['other_asia', 'australia'], NULL, 'james-mceniery', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Annie Jiang', 'Director - Investment Asia & MENA', 'Director - International Investment Asia & MENA at Invest Victoria', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/annie-jiang-872253', NULL, NULL, 'Invest Victoria', FALSE, '[{"name": "Invest Victoria"}, {"name": "Department of Education"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'annie-jiang', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Bradley Gilbert', 'Founder & CEO', 'Founder & CEO at Traders4Traders · Brad is the Director & Founder of Traders4Traders, a Forex trading education company. T4T has a specialised training program designed to produce high performance FX traders, of which the best of the best are recruited into the T4T trading team.He is a registered Commodity Trading Advisor with the NFA (USA) and is licensed by ASIC to Manage Forex Discretionary accounts for wholesale clients. Brad has been a professional Forex Trader since 1990, having worked for Citibank (Sydney, London, New York', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder', 'Cross-border'], 'https://linkedin.com/in/bradley-gilbert-63755b23', NULL, NULL, 'Traders4Traders', FALSE, '[{"name": "Traders4Traders"}, {"name": "Traders GCF LLC - Commodity Trading Advisor (0464419)"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'bradley-gilbert', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();