INSERT INTO community_members (
  name, title, description, location, experience, specialties, website, contact, image, company, is_anonymous, experience_tiles, origin_country, associated_countries, location_id, slug, archetype, persona_fit, is_active, is_featured
) VALUES
  ('Diane Belliveau', 'Chief Representative, Australia & New Zealand', 'Chief Representative, Australia & NZ at Export Development Canada / Exportation et développement Canada', 'Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government'], 'https://linkedin.com/in/diane-belliveau-ba924256', NULL, NULL, 'Export Development Canada | Exportation et développement Canada', FALSE, '[{"name": "Export Development Canada | Exportation et d\u00e9veloppement Canada"}]'::jsonb, 'canada', ARRAY['canada', 'australia'], NULL, 'diane-belliveau', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Charlie Hamer', 'Chief Strategy Officer & Co-Founder', 'Chief Strategy Officer | Co-Founder | Connector | GovTech | Public Sector · Building the future of government through connection, capability, and community.I’m driven by a simple idea: government can, and must, work better. For the people it serves. For the people who serve in it. And for the future we’re all building together.As Co-Founder of Public Sector Network (PSN), I’ve spent the last 10 years growing a global platform that brings together government leaders, innovators, and change makers across Australia, New Zealand, Canada, the US, and the UK. Through PSN’s tr', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Market Research / Strategy'], 'https://linkedin.com/in/charliehamer', NULL, NULL, 'Future Government Institute', FALSE, '[{"name": "Future Government Institute"}, {"name": "Public Sector Network"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'charlie-hamer', 'International Founder', ARRAY['both'], TRUE, FALSE),
  ('Emma Stevens', 'Country Director - Australia & New Zealand', 'Trade & Investment | Marketer | Customer focused | Forever curious · I am a strategic & commercially minded professional who has worked across both the public and private sectors. I have worked across a number of sectors including financial services, technology, media & entertainment, with both multinational companies and startups & scale ups. I have held a number of regionally and locally focused roles, including across Australia, the United Kingdom and Europe. I believe we should all be working towards creating a sustainable future for the world. A fulfilling c', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/emmastevens', NULL, NULL, 'Basque Trade & Investment / Agencia Vasca de Internacionalización', FALSE, '[{"name": "Basque Trade & Investment / Agencia Vasca de Internacionalizaci\u00f3n"}, {"name": "Investment NSW"}]'::jsonb, 'usa', ARRAY['usa', 'australia'], NULL, 'emma-stevens', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Jason Marsham', 'Founder', 'Founder/CEO - WeBridge Partners | Technology Consultancy Providing Innovation and Design Services to Distributors, LPs, GPs and Fund Administration in the Multi Asset Space. Portals, AI, Data, Integration and CX', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Market Research / Strategy'], 'https://linkedin.com/in/jason-marsham-57ba44128', NULL, NULL, 'WeBridge Partners', FALSE, '[{"name": "WeBridge Partners"}, {"name": "LAB Group"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'jason-marsham', 'International Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Alan Tsen', 'General Manager', 'Operator | Revenue Strategy | International Expansion | Commercial Strategy | Fintech · Alan is an accomplished commercial strategy leader with extensive experience in driving revenue growth and strategic innovation within the fintech and insurance sectors. He excels in developing market expansion strategies, driving revenue growth, and leading cross-functional teams in highly regulated environments.Alan has held key roles across various functions in the financial services sector. He served as the Director of Revenue Strategy at Chipper Cash, led a corporate accelerator program for', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Market Entry Specialist', 'Cross-border'], 'https://linkedin.com/in/alan-tsen-22742716', NULL, NULL, 'Cremorne Digital Hub', FALSE, '[{"name": "Cremorne Digital Hub"}, {"name": "Fintech Radar"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'alan-tsen', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Dickie Currer', 'Founder', 'Victorian Startup Ecosystem Hero of the Year 2025 I connect Global Startup Ecosystems through Storytelling, Community building and cross border initiatives Founder | Investor | Emcee | Mentor · When I was 18, I left the safety blanket of my very Northern English upbringing behind and spent six eye opening months backpacking through the wilds of South America- in a time before social media (bar myspace) was really even a thing.Throughout this life changing adventure I questioned what I was doing approximately 5,000 times. Dealing with sickness thousands of miles from home, abstract loneliness, language barriers and unstable political regions provided a constant challenge, though I never', 'Melbourne, Victoria, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Technology / Product', 'Cross-border', 'Recognised Industry Leader'], 'https://linkedin.com/in/dickiecurrer', NULL, NULL, 'Hype Man Media', FALSE, '[{"name": "Hype Man Media"}, {"name": "Hyped:Global"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'dickie-currer', 'Scaled Founder', ARRAY['both'], TRUE, FALSE),
  ('Chris O''Connell', 'Chief Business Officer', 'Growing the Tech Council of Australia · Strategy and Growth leader with over a decade of experience spanning roles in Ireland, Germany, USA, New Zealand and Australia, and a strong blend of high level executive advisory and execution.As Chief Business Officer at the Tech Council of Australia I''m helping to build a diverse ecosystem of tech creators, adopters and advisors to strengthen Australia''s tech landscape through policy, advocacy and research. Please reach out you''d like to be a part of this effort!', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Scaled Founder', 'Trade & Government'], 'https://linkedin.com/in/oconnech', NULL, NULL, 'Tech Council of Australia', FALSE, '[{"name": "Tech Council of Australia"}, {"name": "Growth & Product Strategy"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'chris-oconnell', 'Scaled Founder', ARRAY['international_entrant'], TRUE, FALSE),
  ('Richard Ennis', 'Regional Director, Australia and New Zealand', 'Invest Northern Ireland, Regional Director - Australia & New Zealand · As Regional Director I have the overall responsibility for delivering Invest Northern Ireland''s trade and FDI strategy across Australia and New Zealand. Invest Northern Ireland is the region’s economic development agency. It assists Northern Irish companies with accessing new markets and business opportunities to grow their exports; and attracts new foreign direct investment to Northern Ireland. Invest Northern Ireland has presence in 4 regions in Asia Pacific: China, Northeast Asia, Southeast A', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/richard-ennis', NULL, NULL, 'Invest Northern Ireland', FALSE, '[{"name": "Invest Northern Ireland"}, {"name": "Digital Irish"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'richard-ennis', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Aik Kanhalykham', 'Senior Business Development Manager', 'Senior Business Development Manager at Enterprise Singapore · Career experience in Australian State and Foreign Governments, with a focus on business development, foreign direct investment, trade promotion, economic development, and international engagement. Key strengths in providing strategic advice, establishing global connections and project management. Qualifications in International Business, University of South Australia, Australia.', 'Greater Sydney Area', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/aik-kan', NULL, NULL, 'Enterprise Singapore', FALSE, '[{"name": "Enterprise Singapore"}, {"name": "Department of State Development"}]'::jsonb, NULL, ARRAY['australia'], NULL, 'aik-kanhalykham', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Tom Ward', 'Senior Export Advisor', 'International Trade and Development | International Relations and Policy | Professionals in International Trade · I am passionate about international business. I am fascinated by the contemporary trends and interplay of factors which influence the success and prosperity of multinational organisations and their decision to expand overseas. I have built a strong understanding of the UK, European and Israeli business and cultural landscapes, which enables me to building meaningful relationships and act as a public sector expert for these markets. I also have an advanced understanding of operating in Asia, havi', 'Sydney, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['Trade & Government', 'Cross-border'], 'https://linkedin.com/in/tom-ward-19b397215', NULL, NULL, 'Investment NSW', FALSE, '[{"name": "Investment NSW"}, {"name": "Australian Trade and Investment Commission (Austrade)"}]'::jsonb, 'uk', ARRAY['uk', 'australia'], NULL, 'tom-ward', 'Trade & Government', ARRAY['international_entrant'], TRUE, FALSE),
  ('Conor Keenan', 'CEO', 'Founder, CEO, CFHO at NIOSMO Group Pty Ltd | MyMoneyMedic | Financial Health Expert · NIOSMO Group (MyMoneyMedic) is redefining financial health & wellness under my leadership as CEO & Founder. With over twenty years of leadership experience in financial strategy and consulting, I empower individuals & businesses with innovative tools like PulseCheck™ to align their finances & overall wellbeing with their personal and professional goals. My mission is to transform financial wellness into an accessible, actionable movement. By focusing on strategic financial planning, operational', 'Randwick, New South Wales, Australia', 'Senior operator with extensive ANZ market experience.', ARRAY['International Founder', 'Fintech Founder'], 'https://linkedin.com/in/conor-keenan-sydney', NULL, NULL, 'NIOSMO Group', FALSE, '[{"name": "NIOSMO Group"}, {"name": "SimplifySME"}]'::jsonb, 'ireland', ARRAY['ireland', 'australia'], NULL, 'conor-keenan', 'International Founder', ARRAY['both'], TRUE, FALSE)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  specialties = EXCLUDED.specialties,
  website = EXCLUDED.website,
  company = EXCLUDED.company,
  experience_tiles = EXCLUDED.experience_tiles,
  origin_country = EXCLUDED.origin_country,
  associated_countries = EXCLUDED.associated_countries,
  archetype = EXCLUDED.archetype,
  persona_fit = EXCLUDED.persona_fit,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();