// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-service-providers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/tools/_shared.ts
function sanitizeFilterValue(v) {
  return (v || "").replace(/[\\,().*"'%\r\n]/g, " ").trim();
}
var genericSearchError = {
  content: [{ type: "text", text: "search_failed" }],
  isError: true
};

// src/lib/mcp/tools/search-service-providers.ts
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_service_providers_default = defineTool({
  name: "search_service_providers",
  title: "Search service providers",
  description: "Search Market Entry Secrets' directory of vetted service providers helping companies enter the Australian/ANZ market. Filter by free-text query, location, or service.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search across name and description."),
    location: z.string().optional().describe("Australian city or region, e.g. 'Sydney'."),
    service: z.string().optional().describe("Service keyword, e.g. 'legal', 'marketing'."),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, location, service, limit }) => {
    let q = sb().from("service_providers").select("name, location, services, description, website").limit(limit);
    if (query) {
      const s = sanitizeFilterValue(query);
      if (s) q = q.or(`name.ilike.%${s}%,description.ilike.%${s}%`);
    }
    if (location) q = q.ilike("location", `%${sanitizeFilterValue(location)}%`);
    if (service) q = q.contains("services", [service]);
    const { data, error } = await q;
    if (error) {
      console.error("search_service_providers query failed", error);
      return genericSearchError;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-mentors.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_mentors_default = defineTool2({
  name: "search_mentors",
  title: "Search mentors",
  description: "Search Market Entry Secrets' mentor directory (experienced operators helping companies enter the ANZ market). Filter by specialty, location, or origin country.",
  inputSchema: {
    query: z2.string().optional().describe("Free-text search across name, title, and company."),
    specialty: z2.string().optional().describe("Specialty keyword, e.g. 'fintech', 'sales'."),
    location: z2.string().optional(),
    origin_country: z2.string().optional().describe("Mentor's country of origin, e.g. 'Ireland'."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, specialty, location, origin_country, limit }) => {
    let q = sb2().from("community_members_public").select("name, title, company, specialties, location, origin_country, associated_countries").limit(limit);
    if (query) {
      const s = sanitizeFilterValue(query);
      if (s) q = q.or(`name.ilike.%${s}%,title.ilike.%${s}%,company.ilike.%${s}%`);
    }
    if (specialty) q = q.contains("specialties", [specialty]);
    if (location) q = q.ilike("location", `%${sanitizeFilterValue(location)}%`);
    if (origin_country) q = q.ilike("origin_country", `%${sanitizeFilterValue(origin_country)}%`);
    const { data, error } = await q;
    if (error) {
      console.error("search_mentors query failed", error);
      return genericSearchError;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function sb3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_events_default = defineTool3({
  name: "list_events",
  title: "List events",
  description: "List upcoming Australian/ANZ market entry events (conferences, meetups, trade missions) from the Market Entry Secrets directory.",
  inputSchema: {
    query: z3.string().optional().describe("Free-text search across title and organizer."),
    sector: z3.string().optional(),
    location: z3.string().optional(),
    upcoming_only: z3.boolean().default(true),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, sector, location, upcoming_only, limit }) => {
    let q = sb3().from("events").select("title, slug, date, location, category, type, organizer, sector").order("date", { ascending: true }).limit(limit);
    if (upcoming_only) q = q.gte("date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    if (query) {
      const s = sanitizeFilterValue(query);
      if (s) q = q.or(`title.ilike.%${s}%,organizer.ilike.%${s}%`);
    }
    if (sector) q = q.ilike("sector", `%${sanitizeFilterValue(sector)}%`);
    if (location) q = q.ilike("location", `%${sanitizeFilterValue(location)}%`);
    const { data, error } = await q;
    if (error) {
      console.error("list_events query failed", error);
      return genericSearchError;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-content.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function sb4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_content_default = defineTool4({
  name: "search_content",
  title: "Search guides and case studies",
  description: "Search Market Entry Secrets articles, guides, and case studies about entering the Australian/ANZ market. Returns titles and slugs \u2014 build URLs as https://marketentrysecrets.com/content/<slug> or /case-studies/<slug>.",
  inputSchema: {
    query: z4.string().describe("Free-text search across title and excerpt."),
    content_type: z4.enum(["article", "guide", "case_study"]).optional(),
    limit: z4.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, content_type, limit }) => {
    let q = sb4().from("content_items").select("title, slug, content_type, category_id, sector_tags, status").eq("status", "published").ilike("title", `%${sanitizeFilterValue(query)}%`).limit(limit);
    if (content_type) q = q.eq("content_type", content_type);
    const { data, error } = await q;
    if (error) {
      console.error("search_content query failed", error);
      return genericSearchError;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-leads.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
function sb5() {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_leads_default = defineTool5({
  name: "search_lead_databases",
  title: "Search B2B lead databases",
  description: "Search Market Entry Secrets' catalog of B2B lead databases for Australian market entry (targeting industries, roles, and regions).",
  inputSchema: {
    query: z5.string().optional().describe("Free-text search across name and description."),
    industry: z5.string().optional(),
    location: z5.string().optional(),
    limit: z5.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, industry, location, limit }) => {
    let q = sb5().from("leads").select("name, industry, location, category, price, record_count, provider_name").limit(limit);
    if (query) q = q.ilike("name", `%${sanitizeFilterValue(query)}%`);
    if (industry) q = q.ilike("industry", `%${sanitizeFilterValue(industry)}%`);
    if (location) q = q.ilike("location", `%${sanitizeFilterValue(location)}%`);
    const { data, error } = await q;
    if (error) {
      console.error("search_lead_databases query failed", error);
      return genericSearchError;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "market-entry-secrets-mcp",
  title: "Market Entry Secrets",
  version: "0.1.0",
  instructions: "Read-only tools over the Market Entry Secrets directory of Australian/ANZ market entry resources: vetted service providers, mentors, events, B2B lead databases, and published guides/case studies. Use these to answer questions about entering the Australian market or to find real providers, people, and events for a given industry or location.",
  tools: [
    search_service_providers_default,
    search_mentors_default,
    list_events_default,
    search_content_default,
    search_leads_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
