
-- Insert new service providers
INSERT INTO public.service_providers (name, description, location, founded, employees, services, website, contact, experience_tiles, contact_persons) VALUES

-- TechVisa
('TechVisa', 'Specialist Australian immigration law firm focused on helping tech professionals and companies navigate visa requirements. We provide expert guidance on skilled migration, employer-sponsored visas, and business visas for the technology sector.', 'Melbourne, VIC', '2015', '10-25', '{"Immigration Law", "Visa Services", "Tech Worker Visas", "Employer Sponsorship", "Business Immigration"}', 'http://www.techvisa.com.au', 'info@techvisa.com.au', '[{"id": "1", "name": "Google", "logo": "/placeholder.svg"}, {"id": "2", "name": "Atlassian", "logo": "/placeholder.svg"}, {"id": "3", "name": "Xero", "logo": "/placeholder.svg"}]', '[{"id": "1", "name": "David Chen", "role": "Principal Immigration Lawyer", "image": "/placeholder.svg"}, {"id": "2", "name": "Sarah Kim", "role": "Senior Migration Agent", "image": "/placeholder.svg"}]'),

-- Sleek
('Sleek', 'Digital platform for business incorporation and compliance across Asia-Pacific. We help international companies establish and manage their Australian entities with end-to-end business formation, accounting, and regulatory compliance services.', 'Sydney, NSW', '2017', '100-250', '{"Company Formation", "Business Registration", "Accounting Services", "Tax Compliance", "Corporate Secretarial"}', 'https://sleek.com', 'hello@sleek.com', '[{"id": "1", "name": "Shopify", "logo": "/placeholder.svg"}, {"id": "2", "name": "Wise", "logo": "/placeholder.svg"}, {"id": "3", "name": "Revolut", "logo": "/placeholder.svg"}]', '[{"id": "1", "name": "Julian Hou", "role": "Country Manager Australia", "image": "/placeholder.svg"}, {"id": "2", "name": "Emma Zhang", "role": "Business Development Lead", "image": "/placeholder.svg"}]'),

-- LegalVision
('LegalVision', 'Leading online legal platform providing affordable legal services to businesses across Australia. We offer fixed-fee legal solutions covering commercial law, employment law, intellectual property, and corporate compliance.', 'Sydney, NSW', '2012', '200-500', '{"Commercial Law", "Employment Law", "Intellectual Property", "Contract Drafting", "Corporate Compliance", "Startup Legal Services"}', 'https://legalvision.com.au', 'hello@legalvision.com.au', '[{"id": "1", "name": "Canva", "logo": "/placeholder.svg"}, {"id": "2", "name": "Afterpay", "logo": "/placeholder.svg"}, {"id": "3", "name": "Airtasker", "logo": "/placeholder.svg"}]', '[{"id": "1", "name": "Lachlan McKnight", "role": "CEO & Founder", "image": "/placeholder.svg"}, {"id": "2", "name": "Kate Cormack", "role": "Head of Legal", "image": "/placeholder.svg"}]'),

-- Cloud Recruit
('Cloud Recruit', 'Specialist technology recruitment firm connecting international companies with top Australian tech talent. We focus on cloud computing, software engineering, data science, and emerging technology roles across the Australian market.', 'Melbourne, VIC', '2018', '25-50', '{"Technology Recruitment", "Cloud Engineering", "Software Development", "Data Science Recruiting", "IT Consulting", "Talent Acquisition"}', 'https://www.linkedin.com/company/cloud-recruit/', 'careers@cloudrecruit.com.au', '[{"id": "1", "name": "AWS", "logo": "/placeholder.svg"}, {"id": "2", "name": "Microsoft", "logo": "/placeholder.svg"}, {"id": "3", "name": "Salesforce", "logo": "/placeholder.svg"}]', '[{"id": "1", "name": "Mark Thompson", "role": "Managing Director", "image": "/placeholder.svg"}, {"id": "2", "name": "Lisa Roberts", "role": "Senior Technology Recruiter", "image": "/placeholder.svg"}]'),

-- Rippling Australia
('Rippling Australia', 'Global workforce management platform helping companies hire, pay, and manage employees and contractors in Australia. We provide comprehensive HR, payroll, benefits, and compliance solutions for international businesses expanding to Australia.', 'Sydney, NSW', '2016', '1000+', '{"HR Management", "Payroll Services", "Employee Benefits", "Contractor Management", "Compliance", "Global Workforce Solutions"}', 'https://www.rippling.com/en-AU/country-hiring/australia-contractors', 'sales@rippling.com', '[{"id": "1", "name": "Zendesk", "logo": "/placeholder.svg"}, {"id": "2", "name": "Scale AI", "logo": "/placeholder.svg"}, {"id": "3", "name": "OpenAI", "logo": "/placeholder.svg"}]', '[{"id": "1", "name": "James Wilson", "role": "Country Director Australia", "image": "/placeholder.svg"}, {"id": "2", "name": "Rachel Chen", "role": "Head of Sales APAC", "image": "/placeholder.svg"}]');
