-- MES-110 Phase B step 3: remap raw sector columns onto the approved merged cluster labels.
--
-- Source of truth: the merge mapping tables in docs/audits/mes-110/ (approved via
-- PR #320; canonical reference layer added in PR #321). Rules applied here:
--   * mapped values      -> the merged cluster label (deduplicating casing/spelling/'&' variants)
--   * agnostic values    -> removed from arrays + the row's sector_agnostic flag set
--                           (scalar columns get the literal 'Sector Agnostic')
--   * non-sector values  -> removed from arrays (audience / funding-stage / thesis /
--                           corrupted fragments); scalar theme labels keep their merged label
--   * unknown values     -> left untouched (values added after the audit are not guessed at)
-- Every original value is preserved first in a <column>_legacy copy, and every remap is
-- computed FROM that snapshot (a pure function of the original), so re-running cannot
-- chain outputs through the mapping (e.g. 'DTC Brands' -> 'DTC' must not then hit the
-- raw 'DTC' drop rule). Idempotent; does nothing on an empty preview database.
-- Reversal = copy <column>_legacy back.
-- user_intake_forms and sector_tags coverage are deliberately NOT touched here
-- (audit §9 steps 4-5).

drop table if exists mes110_map;
create temporary table mes110_map (
  surface text not null,
  raw text not null,
  merged text not null,
  action text not null check (action in ('map', 'agnostic', 'drop')),
  primary key (surface, raw)
);

insert into mes110_map (surface, raw, merged, action) values
  ('investors.sector_focus', 'SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Consumer', 'Consumer', 'map'),
  ('investors.sector_focus', 'FinTech', 'FinTech', 'map'),
  ('investors.sector_focus', 'Marketplace', 'Marketplace', 'map'),
  ('investors.sector_focus', 'Generalist', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'HealthTech', 'HealthTech', 'map'),
  ('investors.sector_focus', 'AI', 'AI & Data', 'map'),
  ('investors.sector_focus', 'B2B', 'B2B', 'drop'),
  ('investors.sector_focus', 'Tech', 'Technology', 'map'),
  ('investors.sector_focus', 'EdTech', 'EdTech', 'map'),
  ('investors.sector_focus', 'Technology', 'Technology', 'map'),
  ('investors.sector_focus', 'B2B SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Fintech', 'FinTech', 'map'),
  ('investors.sector_focus', 'Sustainability', 'CleanTech', 'map'),
  ('investors.sector_focus', 'E-commerce', 'E-commerce', 'map'),
  ('investors.sector_focus', 'Impact', 'Impact', 'drop'),
  ('investors.sector_focus', 'DeepTech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Energy', 'Energy', 'map'),
  ('investors.sector_focus', 'Climate Tech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'MedTech', 'MedTech', 'map'),
  ('investors.sector_focus', 'PropTech', 'PropTech', 'map'),
  ('investors.sector_focus', 'Deep Tech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Climate', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Software', 'Software', 'map'),
  ('investors.sector_focus', 'Health', 'Healthcare', 'map'),
  ('investors.sector_focus', 'EnergyTech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'CleanTech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Enterprise Software', 'Software', 'map'),
  ('investors.sector_focus', 'Web3', 'Web3', 'map'),
  ('investors.sector_focus', 'Cybersecurity', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'DevTools', 'Software', 'map'),
  ('investors.sector_focus', 'Enterprise SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'AgTech', 'AgTech', 'map'),
  ('investors.sector_focus', 'Blockchain', 'Web3', 'map'),
  ('investors.sector_focus', 'Capital Markets', 'Capital Markets', 'map'),
  ('investors.sector_focus', 'Hardware', 'Hardware', 'map'),
  ('investors.sector_focus', 'Infrastructure', 'Infrastructure', 'map'),
  ('investors.sector_focus', 'Healthcare', 'Healthcare', 'map'),
  ('investors.sector_focus', 'IoT', 'IoT', 'map'),
  ('investors.sector_focus', 'Logistics', 'Logistics', 'map'),
  ('investors.sector_focus', 'RegTech', 'RegTech', 'map'),
  ('investors.sector_focus', 'Technology (agnostic)', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Biotech', 'Biotechnology', 'map'),
  ('investors.sector_focus', 'ClimateTech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Crypto', 'Web3', 'map'),
  ('investors.sector_focus', 'Education', 'Education', 'map'),
  ('investors.sector_focus', 'MarTech', 'MarTech', 'map'),
  ('investors.sector_focus', 'Mobile', 'Software', 'map'),
  ('investors.sector_focus', 'Renewables', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Software Development', 'Software', 'map'),
  ('investors.sector_focus', 'Agriculture', 'Agriculture', 'map'),
  ('investors.sector_focus', 'Cross-border', 'Cross-border', 'drop'),
  ('investors.sector_focus', 'DTC', 'DTC', 'drop'),
  ('investors.sector_focus', 'Future of Work', 'Future of Work', 'drop'),
  ('investors.sector_focus', 'InsurTech', 'InsurTech', 'map'),
  ('investors.sector_focus', 'Marketplaces', 'Marketplace', 'map'),
  ('investors.sector_focus', 'Medical Practices', 'Medical Practice', 'map'),
  ('investors.sector_focus', 'Robotics', 'Robotics', 'map'),
  ('investors.sector_focus', 'Social Impact', 'Impact', 'drop'),
  ('investors.sector_focus', 'Defence', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Developer Tools', 'Software', 'map'),
  ('investors.sector_focus', 'Digital Health', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Female Founders', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'FoodTech', 'FoodTech', 'map'),
  ('investors.sector_focus', 'LegalTech', 'LegalTech', 'map'),
  ('investors.sector_focus', 'Life Sciences', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'Services for Renewable Energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Social Enterprise', 'Impact', 'drop'),
  ('investors.sector_focus', 'AgriTech', 'AgTech', 'map'),
  ('investors.sector_focus', 'All Sectors', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'BioTech', 'Biotechnology', 'map'),
  ('investors.sector_focus', 'Compliance', 'RegTech', 'map'),
  ('investors.sector_focus', 'Gaming', 'Gaming', 'map'),
  ('investors.sector_focus', 'Health Tech', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Hospitality Tech', 'Hospitality', 'map'),
  ('investors.sector_focus', 'Payments', 'FinTech', 'map'),
  ('investors.sector_focus', 'Renewable Energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Space', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Wellness', 'Wellness', 'map'),
  ('investors.sector_focus', 'Women-Led', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'AdTech', 'AdTech', 'map'),
  ('investors.sector_focus', 'Advanced Manufacturing', 'Advanced Manufacturing', 'map'),
  ('investors.sector_focus', 'Circular Economy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Cleantech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Data Infrastructure and Analytics', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Diversity', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Energy Transition', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Fashion', 'Apparel', 'map'),
  ('investors.sector_focus', 'Government Tech', 'GovTech', 'map'),
  ('investors.sector_focus', 'Hospitality', 'Hospitality', 'map'),
  ('investors.sector_focus', 'Internet', 'Internet', 'map'),
  ('investors.sector_focus', 'Mining Tech', 'Mining & Metals', 'map'),
  ('investors.sector_focus', 'Mobility', 'Mobility', 'map'),
  ('investors.sector_focus', 'Open Source', 'Software', 'map'),
  ('investors.sector_focus', 'Retail', 'Retail', 'map'),
  ('investors.sector_focus', 'Retail Tech', 'Retail', 'map'),
  ('investors.sector_focus', 'Sport Tech', 'SportTech', 'map'),
  ('investors.sector_focus', 'Telco', 'Telecommunications', 'map'),
  ('investors.sector_focus', 'Telehealth', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Travel Tech', 'TravelTech', 'map'),
  ('investors.sector_focus', 'Aerospace', 'Aerospace', 'map'),
  ('investors.sector_focus', 'B2C', 'B2C', 'drop'),
  ('investors.sector_focus', 'Clean Energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Climate tech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Consumer Goods', 'Consumer Goods', 'map'),
  ('investors.sector_focus', 'Consumer Tech', 'Consumer', 'map'),
  ('investors.sector_focus', 'ConTech', 'ConstructionTech', 'map'),
  ('investors.sector_focus', 'D2C', 'DTC', 'drop'),
  ('investors.sector_focus', 'DeFi', 'Web3', 'map'),
  ('investors.sector_focus', 'Design', 'Design', 'map'),
  ('investors.sector_focus', 'Digital Assets', 'Web3', 'map'),
  ('investors.sector_focus', 'Engineering', 'Engineering', 'map'),
  ('investors.sector_focus', 'Enterprise Tech', 'Software', 'map'),
  ('investors.sector_focus', 'EV Charging', 'CleanTech', 'map'),
  ('investors.sector_focus', 'EventTech', 'Events Tech', 'map'),
  ('investors.sector_focus', 'Food', 'Food & Beverage', 'map'),
  ('investors.sector_focus', 'HRTech', 'HR Tech', 'map'),
  ('investors.sector_focus', 'Industrial', 'Industrial', 'map'),
  ('investors.sector_focus', 'Innovation', 'Innovation', 'drop'),
  ('investors.sector_focus', 'Medical Devices', 'MedTech', 'map'),
  ('investors.sector_focus', 'ML', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Regional Tech', 'Technology', 'map'),
  ('investors.sector_focus', 'Regtech', 'RegTech', 'map'),
  ('investors.sector_focus', 'Security', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Solar', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Studio', 'Venture Studio', 'drop'),
  ('investors.sector_focus', 'Tech-Enabled Services', 'Tech-Enabled Services', 'drop'),
  ('investors.sector_focus', 'VR/AR Health', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Accounting Tech', 'Accounting', 'map'),
  ('investors.sector_focus', 'Ad Tech', 'AdTech', 'map'),
  ('investors.sector_focus', 'Aged Care', 'Aged Care', 'map'),
  ('investors.sector_focus', 'Agri-food tech', 'AgTech', 'map'),
  ('investors.sector_focus', 'Agrifood', 'AgTech', 'map'),
  ('investors.sector_focus', 'AI/ML', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Automation', 'Software', 'map'),
  ('investors.sector_focus', 'Beauty', 'Cosmetics', 'map'),
  ('investors.sector_focus', 'Beverage', 'Food & Beverage', 'map'),
  ('investors.sector_focus', 'Biochar', 'CleanTech', 'map'),
  ('investors.sector_focus', 'biotech', 'Biotechnology', 'map'),
  ('investors.sector_focus', 'Biotechnology', 'Biotechnology', 'map'),
  ('investors.sector_focus', 'Bitcoin', 'Web3', 'map'),
  ('investors.sector_focus', 'BNPL', 'FinTech', 'map'),
  ('investors.sector_focus', 'Carbon Removal', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Clean energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'cleantech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Clinical Decision Support', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Construction', 'Construction', 'map'),
  ('investors.sector_focus', 'Consumer Internet', 'Internet', 'map'),
  ('investors.sector_focus', 'Creator Economy', 'Creator Economy', 'map'),
  ('investors.sector_focus', 'Cyber', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Data Analytics', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Decarbonization', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Deep tech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Deeptech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Developer Tooling', 'Software', 'map'),
  ('investors.sector_focus', 'DevOps', 'Software', 'map'),
  ('investors.sector_focus', 'Digital Games', 'Gaming', 'map'),
  ('investors.sector_focus', 'Diversified', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'E-Learning Providers', 'EdTech', 'map'),
  ('investors.sector_focus', 'eCommerce', 'E-commerce', 'map'),
  ('investors.sector_focus', 'Energy Efficiency', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Energy Storage', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Entertainment', 'Entertainment', 'map'),
  ('investors.sector_focus', 'ESG', 'Impact', 'drop'),
  ('investors.sector_focus', 'Family Tech', 'FamilyTech', 'drop'),
  ('investors.sector_focus', 'FemTech', 'FemTech', 'map'),
  ('investors.sector_focus', 'Financial Services', 'Financial Services', 'map'),
  ('investors.sector_focus', 'fintech', 'FinTech', 'map'),
  ('investors.sector_focus', 'FMCG', 'Consumer Goods', 'map'),
  ('investors.sector_focus', 'Food Tech', 'FoodTech', 'map'),
  ('investors.sector_focus', 'Frontier Tech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'GreenTech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Insurtech', 'InsurTech', 'map'),
  ('investors.sector_focus', 'Interactive Media', 'Media', 'map'),
  ('investors.sector_focus', 'Internet Marketplace Platforms', 'Marketplace', 'map'),
  ('investors.sector_focus', 'IT', 'Technology', 'map'),
  ('investors.sector_focus', 'Life sciences', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'logistics', 'Logistics', 'map'),
  ('investors.sector_focus', 'Manufacturing', 'Manufacturing', 'map'),
  ('investors.sector_focus', 'Marketing', 'Marketing', 'map'),
  ('investors.sector_focus', 'Media', 'Media', 'map'),
  ('investors.sector_focus', 'Medical Equipment Manufacturing', 'MedTech', 'map'),
  ('investors.sector_focus', 'Observability', 'Software', 'map'),
  ('investors.sector_focus', 'Online Marketplaces', 'Marketplace', 'map'),
  ('investors.sector_focus', 'Productivity', 'Software', 'map'),
  ('investors.sector_focus', 'Productivity SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Property Tech', 'PropTech', 'map'),
  ('investors.sector_focus', 'Quantum', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Real Estate', 'Real Estate', 'map'),
  ('investors.sector_focus', 'Recruitment', 'HR & Recruiting', 'map'),
  ('investors.sector_focus', 'Research Commercialisation', 'Research', 'map'),
  ('investors.sector_focus', 'Rural Industries', 'Agriculture', 'map'),
  ('investors.sector_focus', 'Semiconductor', 'Semiconductors', 'map'),
  ('investors.sector_focus', 'Services', 'Services', 'drop'),
  ('investors.sector_focus', 'Social Innovation', 'Impact', 'drop'),
  ('investors.sector_focus', 'SportTech', 'SportTech', 'map'),
  ('investors.sector_focus', 'Streaming', 'Media', 'map'),
  ('investors.sector_focus', 'Technology (global scale)', 'Technology', 'map'),
  ('investors.sector_focus', 'Wearables', 'Consumer Electronics', 'map'),
  ('investors.sector_focus', 'Wine/FoodTech', 'Wine & Food', 'map'),
  ('investors.sector_focus', 'Women-led', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Workforce Tech', 'HR Tech', 'map'),
  ('investors.sector_focus', '4th Industrial Revolution', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Accessibility', 'Accessibility', 'drop'),
  ('investors.sector_focus', 'Accounting Integrations', 'Accounting', 'map'),
  ('investors.sector_focus', 'Advanced Compute', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Advanced Computing', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Advanced manufacturing', 'Advanced Manufacturing', 'map'),
  ('investors.sector_focus', 'Advanced Materials', 'Advanced Materials', 'map'),
  ('investors.sector_focus', 'Aerospace/Autonomy', 'Aerospace', 'map'),
  ('investors.sector_focus', 'Aged Care Tech', 'Aged Care', 'map'),
  ('investors.sector_focus', 'Agile/PM Tools', 'Software', 'map'),
  ('investors.sector_focus', 'Agnostic', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Agnostic (bias to big markets)', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Agnostic (healthcare', 'Sector Agnostic', 'drop'),
  ('investors.sector_focus', 'Agnostic (Sustainable Tech', 'Sector Agnostic', 'drop'),
  ('investors.sector_focus', 'Agnostic (women founders', 'Sector Agnostic', 'drop'),
  ('investors.sector_focus', 'Agri', 'Agriculture', 'map'),
  ('investors.sector_focus', 'Agri-Food', 'AgTech', 'map'),
  ('investors.sector_focus', 'Agricultural technology', 'AgTech', 'map'),
  ('investors.sector_focus', 'agriculture', 'Agriculture', 'map'),
  ('investors.sector_focus', 'agrifood', 'AgTech', 'map'),
  ('investors.sector_focus', 'agtech', 'AgTech', 'map'),
  ('investors.sector_focus', 'Agtech', 'AgTech', 'map'),
  ('investors.sector_focus', 'AI Coding Agents', 'AI & Data', 'map'),
  ('investors.sector_focus', 'AI Services', 'AI & Data', 'map'),
  ('investors.sector_focus', 'AI-enabled B2B software', 'AI & Data', 'map'),
  ('investors.sector_focus', 'AI-first software', 'AI & Data', 'map'),
  ('investors.sector_focus', 'AI-first technology (operator-led', 'AI & Data', 'map'),
  ('investors.sector_focus', 'AI)', 'AI & Data', 'map'),
  ('investors.sector_focus', 'AI/Robotics', 'AI & Data', 'map'),
  ('investors.sector_focus', 'All especially Fintech', 'FinTech', 'map'),
  ('investors.sector_focus', 'Alt Proteins', 'FoodTech', 'map'),
  ('investors.sector_focus', 'Analytics', 'AI & Data', 'map'),
  ('investors.sector_focus', 'ANU Spinoffs', 'University Spinouts', 'drop'),
  ('investors.sector_focus', 'Artificial Intelligence (ANZ)', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Atlassian Marketplace', 'Software', 'map'),
  ('investors.sector_focus', 'Audio/Podcast', 'Media', 'map'),
  ('investors.sector_focus', 'Authentication', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Auto Finance', 'FinTech', 'map'),
  ('investors.sector_focus', 'Automotive', 'Automotive', 'map'),
  ('investors.sector_focus', 'Autonomous Vehicles', 'Automotive', 'map'),
  ('investors.sector_focus', 'B2B Marketplaces', 'Marketplace', 'map'),
  ('investors.sector_focus', 'B2B SAAS', 'SaaS', 'map'),
  ('investors.sector_focus', 'B2B SaaS (mission-critical', 'SaaS', 'map'),
  ('investors.sector_focus', 'B2B SaaS (via Black Nova VC)', 'SaaS', 'map'),
  ('investors.sector_focus', 'B2B Software', 'Software', 'map'),
  ('investors.sector_focus', 'B2B Technology (SE Asia)', 'Technology', 'map'),
  ('investors.sector_focus', 'B2B2C SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Banking Tech', 'FinTech', 'map'),
  ('investors.sector_focus', 'Batteries', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Beauty Tech', 'Cosmetics', 'map'),
  ('investors.sector_focus', 'Beverages', 'Food & Beverage', 'map'),
  ('investors.sector_focus', 'Bio', 'Biotechnology', 'map'),
  ('investors.sector_focus', 'Bioplastics', 'CleanTech', 'map'),
  ('investors.sector_focus', 'BIPOC Founders', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Bitcoin Financial Services', 'Web3', 'map'),
  ('investors.sector_focus', 'Bitcoin Mining', 'Web3', 'map'),
  ('investors.sector_focus', 'Branding', 'Marketing', 'map'),
  ('investors.sector_focus', 'Brands', 'Consumer Goods', 'map'),
  ('investors.sector_focus', 'built environment', 'Construction', 'map'),
  ('investors.sector_focus', 'Business Services', 'Professional Services', 'map'),
  ('investors.sector_focus', 'carbon markets', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Career Tech', 'HR & Recruiting', 'map'),
  ('investors.sector_focus', 'carve-outs', 'Deal Type', 'drop'),
  ('investors.sector_focus', 'Charity Tech', 'Non-Profit', 'map'),
  ('investors.sector_focus', 'Childcare', 'Childcare', 'map'),
  ('investors.sector_focus', 'circular economy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Clean Economy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'clean energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Clean Tech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Clean technology', 'CleanTech', 'map'),
  ('investors.sector_focus', 'CleanEnergy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'cleantech)', 'CleanTech', 'map'),
  ('investors.sector_focus', 'climate', 'CleanTech', 'map'),
  ('investors.sector_focus', 'climate tech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Climate tech — energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Climate tech (clean energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'climate.', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Climate/Energy/Health/Society', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Clinical AI', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Clinical Trials', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'Cloud', 'Software', 'map'),
  ('investors.sector_focus', 'Cloud Infrastructure', 'Software', 'map'),
  ('investors.sector_focus', 'Cloud Security', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Cloud Storage', 'Software', 'map'),
  ('investors.sector_focus', 'Co-working / PropTech', 'PropTech', 'map'),
  ('investors.sector_focus', 'Commerce APIs', 'Software', 'map'),
  ('investors.sector_focus', 'CommunicationsAPI', 'Software', 'map'),
  ('investors.sector_focus', 'Comparison Tech', 'Internet', 'map'),
  ('investors.sector_focus', 'Complex Systems', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Computer Vision', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Connectivity', 'Telecommunications', 'map'),
  ('investors.sector_focus', 'Construction Tech', 'ConstructionTech', 'map'),
  ('investors.sector_focus', 'Consulting Tech', 'Professional Services', 'map'),
  ('investors.sector_focus', 'Consumer Electronics', 'Consumer Electronics', 'map'),
  ('investors.sector_focus', 'Consumer Experience', 'Consumer', 'map'),
  ('investors.sector_focus', 'Consumer Fintech', 'FinTech', 'map'),
  ('investors.sector_focus', 'Consumer Hardware', 'Consumer Electronics', 'map'),
  ('investors.sector_focus', 'Consumer Health', 'Healthcare', 'map'),
  ('investors.sector_focus', 'Consumer Products', 'Consumer Goods', 'map'),
  ('investors.sector_focus', 'Consumer Software', 'Software', 'map'),
  ('investors.sector_focus', 'consumer tech)', 'Consumer', 'map'),
  ('investors.sector_focus', 'Consumer Technology', 'Consumer', 'map'),
  ('investors.sector_focus', 'consumer)', 'Consumer', 'map'),
  ('investors.sector_focus', 'Content', 'Media', 'map'),
  ('investors.sector_focus', 'Contingent Labour tech', 'HR & Recruiting', 'map'),
  ('investors.sector_focus', 'Corporate Finance', 'Financial Services', 'map'),
  ('investors.sector_focus', 'Creative Tech', 'Creative Industries', 'map'),
  ('investors.sector_focus', 'Critical tech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Crowdfunding', 'FinTech', 'map'),
  ('investors.sector_focus', 'Cryptography', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'CX/Feedback Analytics', 'Software', 'map'),
  ('investors.sector_focus', 'Cyber Security', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'cybersecurity', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'D2C Health', 'Healthcare', 'map'),
  ('investors.sector_focus', 'Data', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Data Infrastructure', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Data Privacy', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Data Science', 'AI & Data', 'map'),
  ('investors.sector_focus', 'decarbonisation', 'CleanTech', 'map'),
  ('investors.sector_focus', 'defence', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Defence Tech', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'DefenceTech)', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Design Tech', 'Design', 'map'),
  ('investors.sector_focus', 'Developer Infrastructure', 'Software', 'map'),
  ('investors.sector_focus', 'DevSecOps', 'Software', 'map'),
  ('investors.sector_focus', 'Diagnostics', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'Digital health', 'HealthTech', 'map'),
  ('investors.sector_focus', 'Digital Media', 'Media', 'map'),
  ('investors.sector_focus', 'Digital Signage', 'Media', 'map'),
  ('investors.sector_focus', 'Digital Technologies', 'Technology', 'map'),
  ('investors.sector_focus', 'Disability Tech', 'Disability Tech', 'map'),
  ('investors.sector_focus', 'Disruptive Tech', 'Technology', 'map'),
  ('investors.sector_focus', 'Diversified (global)', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Diversified investment', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'diversified investments', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Diversified private expansion capital', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Diversity-led', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Document Management', 'Software', 'map'),
  ('investors.sector_focus', 'Document SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Document Tech', 'Software', 'map'),
  ('investors.sector_focus', 'Drone', 'Drones', 'map'),
  ('investors.sector_focus', 'Drone/Mapping', 'Drones', 'map'),
  ('investors.sector_focus', 'DTC Brands', 'DTC', 'map'),
  ('investors.sector_focus', 'DTC Health', 'Healthcare', 'map'),
  ('investors.sector_focus', 'E-Gaming', 'Gaming', 'map'),
  ('investors.sector_focus', 'Early Education', 'Education', 'map'),
  ('investors.sector_focus', 'early stage', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'early stage)', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Early-stage Tech', 'Technology', 'map'),
  ('investors.sector_focus', 'eCommerce/DTC', 'E-commerce', 'map'),
  ('investors.sector_focus', 'EcoTech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'edtech', 'EdTech', 'map'),
  ('investors.sector_focus', 'education', 'Education', 'map'),
  ('investors.sector_focus', 'EldTech', 'Aged Care', 'map'),
  ('investors.sector_focus', 'Emerging Sectors', 'Emerging Sectors', 'drop'),
  ('investors.sector_focus', 'Emissions reduction', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Employment Tech', 'HR & Recruiting', 'map'),
  ('investors.sector_focus', 'Enduring businesses', 'Investment Thesis', 'drop'),
  ('investors.sector_focus', 'energy', 'Energy', 'map'),
  ('investors.sector_focus', 'Energy Tech', 'CleanTech', 'map'),
  ('investors.sector_focus', 'energy transition', 'CleanTech', 'map'),
  ('investors.sector_focus', 'energy transition)', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Engineering Tech', 'Engineering', 'map'),
  ('investors.sector_focus', 'Engineering Tooling', 'Software', 'map'),
  ('investors.sector_focus', 'Engineering Tools', 'Software', 'map'),
  ('investors.sector_focus', 'Enterprise', 'B2B', 'drop'),
  ('investors.sector_focus', 'Enterprise Search', 'Software', 'map'),
  ('investors.sector_focus', 'Enterprise Security', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Environment', 'Environment', 'map'),
  ('investors.sector_focus', 'Environmental', 'Environment', 'map'),
  ('investors.sector_focus', 'environmental impact', 'Impact', 'drop'),
  ('investors.sector_focus', 'Environmental impact — circular economy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'esports', 'Gaming', 'map'),
  ('investors.sector_focus', 'eSports', 'Gaming', 'map'),
  ('investors.sector_focus', 'Ethereum', 'Web3', 'map'),
  ('investors.sector_focus', 'EV', 'Automotive', 'map'),
  ('investors.sector_focus', 'Event Tech', 'Events Tech', 'map'),
  ('investors.sector_focus', 'Family Office', 'Investor Type', 'drop'),
  ('investors.sector_focus', 'FamTech', 'FamilyTech', 'drop'),
  ('investors.sector_focus', 'Farming', 'Agriculture', 'map'),
  ('investors.sector_focus', 'Female-founded technology', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Fertility', 'Fertility', 'map'),
  ('investors.sector_focus', 'Film', 'Film', 'map'),
  ('investors.sector_focus', 'fintech)', 'FinTech', 'map'),
  ('investors.sector_focus', 'Fitness', 'Fitness', 'map'),
  ('investors.sector_focus', 'Food Systems', 'FoodTech', 'map'),
  ('investors.sector_focus', 'food/agriculture', 'AgTech', 'map'),
  ('investors.sector_focus', 'Foodtech', 'FoodTech', 'map'),
  ('investors.sector_focus', 'Fraud Detection', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'Frontier Research', 'Research', 'map'),
  ('investors.sector_focus', 'FrontierTech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Generalist (healthtech', 'Sector Agnostic', 'drop'),
  ('investors.sector_focus', 'Generalist/agnostic (technology', 'Sector Agnostic', 'drop'),
  ('investors.sector_focus', 'Genomics', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'GeoTech', 'GeoTech', 'map'),
  ('investors.sector_focus', 'Geothermal', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Gig Economy', 'Marketplace', 'map'),
  ('investors.sector_focus', 'Global Expansion', 'Investment Thesis', 'drop'),
  ('investors.sector_focus', 'Government', 'Government', 'map'),
  ('investors.sector_focus', 'Grid', 'Utilities', 'map'),
  ('investors.sector_focus', 'Grid Tech', 'Utilities', 'map'),
  ('investors.sector_focus', 'Group Buying', 'E-commerce', 'map'),
  ('investors.sector_focus', 'growth companies', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Growth Stage', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Growth Stage Tech', 'Technology', 'map'),
  ('investors.sector_focus', 'Hard Tech', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'hard-to-abate emissions)', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Hard-to-abate industry decarbonisation', 'CleanTech', 'map'),
  ('investors.sector_focus', 'hardware (broad)', 'Hardware', 'map'),
  ('investors.sector_focus', 'Health & Life Sciences', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'health IT', 'HealthTech', 'map'),
  ('investors.sector_focus', 'health)', 'Healthcare', 'map'),
  ('investors.sector_focus', 'Health/Medtech', 'HealthTech', 'map'),
  ('investors.sector_focus', 'healthcare', 'Healthcare', 'map'),
  ('investors.sector_focus', 'Healthcare — pharma', 'Pharmaceuticals', 'map'),
  ('investors.sector_focus', 'Healthcare Talent', 'HR & Recruiting', 'map'),
  ('investors.sector_focus', 'Healthtech', 'HealthTech', 'map'),
  ('investors.sector_focus', 'healthtech priority)', 'HealthTech', 'map'),
  ('investors.sector_focus', 'High Growth Tech', 'Technology', 'map'),
  ('investors.sector_focus', 'High-growth', 'Investment Thesis', 'drop'),
  ('investors.sector_focus', 'High-growth global tech (agnostic)', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Highly scalable breakthrough technology (global)', 'Technology', 'map'),
  ('investors.sector_focus', 'Highly thematic technology', 'Technology', 'map'),
  ('investors.sector_focus', 'HighTech', 'Technology', 'map'),
  ('investors.sector_focus', 'Hotel Tech', 'Hospitality', 'map'),
  ('investors.sector_focus', 'Household', 'Consumer Goods', 'map'),
  ('investors.sector_focus', 'housing', 'Real Estate', 'map'),
  ('investors.sector_focus', 'HR SaaS', 'HR Tech', 'map'),
  ('investors.sector_focus', 'HR Tech', 'HR Tech', 'map'),
  ('investors.sector_focus', 'Human augmentation', 'Deep Tech', 'map'),
  ('investors.sector_focus', 'Human Health', 'Healthcare', 'map'),
  ('investors.sector_focus', 'Impact (Climate', 'Impact', 'drop'),
  ('investors.sector_focus', 'Impact (climate justice', 'Impact', 'drop'),
  ('investors.sector_focus', 'Indigenous/Aboriginal Tech', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Industrial AI', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Industrial Machinery', 'Machinery', 'map'),
  ('investors.sector_focus', 'Industrial Tech', 'Industrial', 'map'),
  ('investors.sector_focus', 'Influencer Marketing', 'Marketing', 'map'),
  ('investors.sector_focus', 'Information technology — SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Infrastructure Software', 'Software', 'map'),
  ('investors.sector_focus', 'Innovation Commercialisation', 'Research', 'map'),
  ('investors.sector_focus', 'InsightTech', 'AI & Data', 'map'),
  ('investors.sector_focus', 'IT Automation', 'Software', 'map'),
  ('investors.sector_focus', 'Labour', 'HR & Recruiting', 'map'),
  ('investors.sector_focus', 'LatAm cross-border', 'Geography', 'drop'),
  ('investors.sector_focus', 'Legal', 'Legal', 'map'),
  ('investors.sector_focus', 'LGBTQIA+ Founders', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'life sciences', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'Life Sciences (therapeutics', 'Life Sciences', 'map'),
  ('investors.sector_focus', 'Lifestyle', 'Consumer', 'map'),
  ('investors.sector_focus', 'Lightning Network', 'Web3', 'map'),
  ('investors.sector_focus', 'Location Tech', 'GeoTech', 'map'),
  ('investors.sector_focus', 'Loyalty', 'MarTech', 'map'),
  ('investors.sector_focus', 'M&A', 'Deal Type', 'drop'),
  ('investors.sector_focus', 'Maritime', 'Maritime', 'map'),
  ('investors.sector_focus', 'Marketing Measurement', 'MarTech', 'map'),
  ('investors.sector_focus', 'MarketPlace', 'Marketplace', 'map'),
  ('investors.sector_focus', 'marketplaces', 'Marketplace', 'map'),
  ('investors.sector_focus', 'Material Science', 'Advanced Materials', 'map'),
  ('investors.sector_focus', 'MediaTech', 'Media', 'map'),
  ('investors.sector_focus', 'Medical', 'Healthcare', 'map'),
  ('investors.sector_focus', 'medical devices', 'MedTech', 'map'),
  ('investors.sector_focus', 'medical technology)', 'MedTech', 'map'),
  ('investors.sector_focus', 'Medtech', 'MedTech', 'map'),
  ('investors.sector_focus', 'Methane reduction', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Microelectronics', 'Semiconductors', 'map'),
  ('investors.sector_focus', 'migration)', 'Fragment', 'drop'),
  ('investors.sector_focus', 'mining', 'Mining & Metals', 'map'),
  ('investors.sector_focus', 'Mining', 'Mining & Metals', 'map'),
  ('investors.sector_focus', 'mining focus)', 'Mining & Metals', 'map'),
  ('investors.sector_focus', 'mobility', 'Mobility', 'map'),
  ('investors.sector_focus', 'MOOC', 'EdTech', 'map'),
  ('investors.sector_focus', 'National security', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'National Security', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Network Security', 'Cybersecurity', 'map'),
  ('investors.sector_focus', 'NetZero', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Obstetrics', 'Medical Practice', 'map'),
  ('investors.sector_focus', 'Online and Mail Order Retail', 'E-commerce', 'map'),
  ('investors.sector_focus', 'Online Learning', 'EdTech', 'map'),
  ('investors.sector_focus', 'online marketplaces', 'Marketplace', 'map'),
  ('investors.sector_focus', 'Open Banking', 'FinTech', 'map'),
  ('investors.sector_focus', 'Operations Tech', 'Software', 'map'),
  ('investors.sector_focus', 'Outdoor', 'Consumer Goods', 'map'),
  ('investors.sector_focus', 'Parenting', 'FamilyTech', 'map'),
  ('investors.sector_focus', 'Parenting Tech', 'FamilyTech', 'map'),
  ('investors.sector_focus', 'Patents', 'IP Services', 'map'),
  ('investors.sector_focus', 'People)', 'Fragment', 'drop'),
  ('investors.sector_focus', 'Pet Tech', 'Pet Tech', 'map'),
  ('investors.sector_focus', 'PFM', 'FinTech', 'map'),
  ('investors.sector_focus', 'Pharma', 'Pharmaceuticals', 'map'),
  ('investors.sector_focus', 'Pharmaceuticals', 'Pharmaceuticals', 'map'),
  ('investors.sector_focus', 'Physical Sciences', 'Research', 'map'),
  ('investors.sector_focus', 'Physical World (climate/environment)', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Platform', 'Platform', 'drop'),
  ('investors.sector_focus', 'PLG', 'PLG', 'drop'),
  ('investors.sector_focus', 'Power Infrastructure', 'Utilities', 'map'),
  ('investors.sector_focus', 'PR/Comms', 'PR & Communications', 'map'),
  ('investors.sector_focus', 'Pre-IPO', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Pre-seed', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Procurement', 'Procurement', 'map'),
  ('investors.sector_focus', 'Product-Led', 'PLG', 'drop'),
  ('investors.sector_focus', 'Property', 'Real Estate', 'map'),
  ('investors.sector_focus', 'Proptech', 'PropTech', 'map'),
  ('investors.sector_focus', 'PropTech (real estate technology)', 'PropTech', 'map'),
  ('investors.sector_focus', 'PropTech (strata/apartment communities)', 'PropTech', 'map'),
  ('investors.sector_focus', 'Public equities', 'Asset Class', 'drop'),
  ('investors.sector_focus', 'QLD-focused (also B2B SaaS', 'Geography', 'drop'),
  ('investors.sector_focus', 'Quant', 'FinTech', 'map'),
  ('investors.sector_focus', 'Real estate', 'Real Estate', 'map'),
  ('investors.sector_focus', 'RealTech (real estate', 'PropTech', 'map'),
  ('investors.sector_focus', 'Regenerative economy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'regulated industries)', 'Fragment', 'drop'),
  ('investors.sector_focus', 'Regulatory Tech', 'RegTech', 'map'),
  ('investors.sector_focus', 'Renewable energy', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Renewable energy (REVC Fund)', 'CleanTech', 'map'),
  ('investors.sector_focus', 'Resources', 'Mining & Metals', 'map'),
  ('investors.sector_focus', 'Retail Technology', 'Retail', 'map'),
  ('investors.sector_focus', 'Revenue-generating businesses', 'Investment Thesis', 'drop'),
  ('investors.sector_focus', 'SaaS Marketplaces', 'SaaS', 'map'),
  ('investors.sector_focus', 'scalable businesses', 'Investment Thesis', 'drop'),
  ('investors.sector_focus', 'Scalable technology (early-stage)', 'Technology', 'map'),
  ('investors.sector_focus', 'SDG', 'Impact', 'drop'),
  ('investors.sector_focus', 'Search', 'Software', 'map'),
  ('investors.sector_focus', 'Secondary', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Sector Agnostic', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Seed', 'Funding Stage', 'drop'),
  ('investors.sector_focus', 'Self-Custody', 'Web3', 'map'),
  ('investors.sector_focus', 'Self-Driving', 'Automotive', 'map'),
  ('investors.sector_focus', 'Semiconductors', 'Semiconductors', 'map'),
  ('investors.sector_focus', 'services M&A (cross-border advisory)', 'Deal Type', 'drop'),
  ('investors.sector_focus', 'smart cities', 'Smart Cities', 'map'),
  ('investors.sector_focus', 'SMB', 'SMB', 'drop'),
  ('investors.sector_focus', 'SMBs (PE)', 'SMB', 'drop'),
  ('investors.sector_focus', 'SME Finance', 'FinTech', 'map'),
  ('investors.sector_focus', 'SMSF', 'FinTech', 'map'),
  ('investors.sector_focus', 'Social', 'Social Platforms', 'map'),
  ('investors.sector_focus', 'Social enterprise', 'Impact', 'drop'),
  ('investors.sector_focus', 'Social impact', 'Impact', 'drop'),
  ('investors.sector_focus', 'Social Media', 'Social Platforms', 'map'),
  ('investors.sector_focus', 'Sole-Trader Tech', 'SMB', 'map'),
  ('investors.sector_focus', 'South-East Asia connected', 'Geography', 'drop'),
  ('investors.sector_focus', 'Sovereign capability', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'space', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Space Research and Technology', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Space Tech', 'Defence & Space', 'map'),
  ('investors.sector_focus', 'Special situations', 'Deal Type', 'drop'),
  ('investors.sector_focus', 'Spend Management', 'FinTech', 'map'),
  ('investors.sector_focus', 'Sport', 'Sports', 'map'),
  ('investors.sector_focus', 'Sports & EventTech', 'SportTech', 'map'),
  ('investors.sector_focus', 'Sports Tech', 'SportTech', 'map'),
  ('investors.sector_focus', 'Strategy Consulting', 'Consulting', 'map'),
  ('investors.sector_focus', 'Student founders (sector agnostic)', 'Sector Agnostic', 'agnostic'),
  ('investors.sector_focus', 'Subscription', 'Subscription', 'drop'),
  ('investors.sector_focus', 'subscription-based internet', 'Internet', 'map'),
  ('investors.sector_focus', 'supply chain', 'Logistics', 'map'),
  ('investors.sector_focus', 'Supply Chain', 'Logistics', 'map'),
  ('investors.sector_focus', 'sustainable agriculture', 'AgTech', 'map'),
  ('investors.sector_focus', 'sustainable aviation fuel', 'CleanTech', 'map'),
  ('investors.sector_focus', 'TaaS', 'Transport-as-a-Service', 'map'),
  ('investors.sector_focus', 'tax reform', 'Theme', 'drop'),
  ('investors.sector_focus', 'Tech (AI', 'Technology', 'map'),
  ('investors.sector_focus', 'Tech Enabled', 'Tech-Enabled Services', 'drop'),
  ('investors.sector_focus', 'Tech Infrastructure', 'Software', 'map'),
  ('investors.sector_focus', 'Technology (Asia-Pacific)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (AU early stage)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (Australia–Japan bridge)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (fast-growth)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (growth-stage)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (high-growth)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (NZ-focused)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Technology (SE Asia / India)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (secondaries)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (thematic)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (UQ research commercialisation', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology (VC)', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology growth companies', 'Technology', 'map'),
  ('investors.sector_focus', 'Technology-enabled businesses', 'Tech-Enabled Services', 'drop'),
  ('investors.sector_focus', 'Technology-enabled companies globally', 'Tech-Enabled Services', 'drop'),
  ('investors.sector_focus', 'Telecoms', 'Telecommunications', 'map'),
  ('investors.sector_focus', 'Telephony', 'Telecommunications', 'map'),
  ('investors.sector_focus', 'Television', 'Broadcast Media', 'map'),
  ('investors.sector_focus', 'Tokenisation', 'Web3', 'map'),
  ('investors.sector_focus', 'Tourism Tech', 'TravelTech', 'map'),
  ('investors.sector_focus', 'Trade Services', 'Trade Services', 'map'),
  ('investors.sector_focus', 'Trading', 'Capital Markets', 'map'),
  ('investors.sector_focus', 'transport', 'Logistics', 'map'),
  ('investors.sector_focus', 'Transport', 'Logistics', 'map'),
  ('investors.sector_focus', 'Transport-as-a-Service', 'Transport-as-a-Service', 'map'),
  ('investors.sector_focus', 'TravelTech', 'TravelTech', 'map'),
  ('investors.sector_focus', 'University commercialisation (broad technology sectors)', 'University Spinouts', 'map'),
  ('investors.sector_focus', 'University Spinoffs', 'University Spinouts', 'map'),
  ('investors.sector_focus', 'US-footprint Australian', 'Geography', 'drop'),
  ('investors.sector_focus', 'Vacation Rental', 'TravelTech', 'map'),
  ('investors.sector_focus', 'Vaccines', 'Pharmaceuticals', 'map'),
  ('investors.sector_focus', 'VC (historical)', 'Investor Type', 'drop'),
  ('investors.sector_focus', 'Vertical AI', 'AI & Data', 'map'),
  ('investors.sector_focus', 'Vertical SaaS', 'SaaS', 'map'),
  ('investors.sector_focus', 'Virtual Experience', 'VR/AR', 'map'),
  ('investors.sector_focus', 'VR', 'VR/AR', 'map'),
  ('investors.sector_focus', 'Water', 'Water', 'map'),
  ('investors.sector_focus', 'Wealth Management', 'Investment Management', 'map'),
  ('investors.sector_focus', 'Wealth Tech', 'FinTech', 'map'),
  ('investors.sector_focus', 'Wireless Infrastructure', 'Telecommunications', 'map'),
  ('investors.sector_focus', 'Women''s Business', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'Women''s Health', 'FemTech', 'map'),
  ('investors.sector_focus', 'Women''s Leadership', 'Founder Audience', 'drop'),
  ('investors.sector_focus', 'workflow-led', 'Fragment', 'drop'),
  ('events.sector', 'Founders & Startups', 'Founders & Startups', 'map'),
  ('events.sector', 'AI & Data', 'AI & Data', 'map'),
  ('events.sector', 'Technology & Innovation', 'Technology', 'map'),
  ('events.sector', 'Professional Services', 'Professional Services', 'map'),
  ('events.sector', 'Business Consulting and Services', 'Professional Services', 'map'),
  ('events.sector', 'Marketing & Growth', 'Marketing', 'map'),
  ('events.sector', 'Human Resources', 'Human Resources', 'map'),
  ('events.sector', 'Mining & Resources', 'Mining & Metals', 'map'),
  ('events.sector', 'Investing & Capital', 'Venture Capital', 'map'),
  ('events.sector', 'Workplace Safety', 'Workplace Safety', 'map'),
  ('events.sector', 'Fintech & Financial Services', 'FinTech', 'map'),
  ('events.sector', 'Logistics & Supply Chain', 'Logistics', 'map'),
  ('events.sector', 'CRM & Enterprise Technology', 'Software', 'map'),
  ('events.sector', 'Accounting & Finance', 'Accounting', 'map'),
  ('events.sector', 'Construction & Design', 'Construction', 'map'),
  ('events.sector', 'Utilities', 'Utilities', 'map'),
  ('events.sector', 'Mining & Critical Minerals', 'Mining & Metals', 'map'),
  ('events.sector', 'Food & Beverage Manufacturing', 'Food Production', 'map'),
  ('events.sector', 'Superannuation & Financial Services', 'Investment Management', 'map'),
  ('events.sector', 'Venture Capital & Investment', 'Venture Capital', 'map'),
  ('events.sector', 'Aged Care', 'Aged Care', 'map'),
  ('events.sector', 'Insurance & Reinsurance', 'Insurance', 'map'),
  ('events.sector', 'Pharmacy', 'Pharmacy', 'map'),
  ('events.sector', 'Accounting Technology', 'Accounting', 'map'),
  ('events.sector', 'Quantum Computing & Deep Tech', 'Deep Tech', 'map'),
  ('events.sector', 'Software Development', 'Software Development', 'map'),
  ('events.sector', 'Retail & eCommerce', 'E-commerce', 'map'),
  ('events.sector', 'Legal Technology', 'LegalTech', 'map'),
  ('events.sector', 'Health & MedTech', 'HealthTech', 'map'),
  ('events.sector', 'Construction', 'Construction', 'map'),
  ('events.sector', 'Financial Services', 'Financial Services', 'map'),
  ('events.sector', 'Small Business', 'Small Business', 'map'),
  ('events.sector', 'SaaS & Tech Startups', 'SaaS', 'map'),
  ('events.sector', 'Urban Development & Smart Cities', 'Smart Cities', 'map'),
  ('events.sector', 'Property & Valuation', 'Real Estate', 'map'),
  ('events.sector', 'Events & Business Tourism', 'Events & Tourism', 'map'),
  ('events.sector', 'Property & Real Estate', 'Real Estate', 'map'),
  ('events.sector', 'Corporate Governance', 'Governance', 'map'),
  ('events.sector', 'Procurement & Supply Chain', 'Logistics', 'map'),
  ('events.sector', 'Data, Analytics & AI', 'AI & Data', 'map'),
  ('events.sector', 'Digital Health', 'HealthTech', 'map'),
  ('events.sector', 'Cloud Computing & AI', 'AI & Data', 'map'),
  ('events.sector', 'Food & Beverage', 'Food & Beverage', 'map'),
  ('events.sector', 'Manufacturing & Automation', 'Industrial Automation', 'map'),
  ('events.sector', 'Marketing & Media', 'Marketing', 'map'),
  ('events.sector', 'Energy & Renewables', 'CleanTech', 'map'),
  ('events.sector', 'Startups & Venture Capital', 'Venture Capital', 'map'),
  ('events.sector', 'Aerospace & Defence', 'Defence & Space', 'map'),
  ('events.sector', 'Agriculture & Agribusiness', 'Agriculture', 'map'),
  ('events.sector', 'Freight & Logistics', 'Logistics', 'map'),
  ('events.sector', 'Health IT & Digital Health', 'HealthTech', 'map'),
  ('events.sector', 'Startups & Innovation', 'Founders & Startups', 'map'),
  ('events.sector', 'Manufacturing & Engineering', 'Manufacturing', 'map'),
  ('events.sector', 'Natural & Health Products', 'Consumer Goods', 'map'),
  ('events.sector', 'Government Technology', 'GovTech', 'map'),
  ('events.sector', 'Mortgage & Finance', 'Banking', 'map'),
  ('events.sector', 'Small Business & Entrepreneurship', 'Small Business', 'map'),
  ('events.sector', 'Startups & Scaleups', 'Founders & Startups', 'map'),
  ('events.sector', 'Education Technology', 'EdTech', 'map'),
  ('events.sector', 'Information Technology', 'Technology', 'map'),
  ('events.sector', 'Technology, Information and Media', 'Technology', 'map'),
  ('events.sector', 'Mining Technology', 'Mining & Metals', 'map'),
  ('events.sector', 'Manufacturing & Industry', 'Manufacturing', 'map'),
  ('events.sector', 'Residential Property & Build-to-Rent', 'Real Estate', 'map'),
  ('events.sector', 'Agriculture & Farming', 'Agriculture', 'map'),
  ('events.sector', 'Manufacturing', 'Manufacturing', 'map'),
  ('events.sector', 'Hospitals and Health Care', 'Healthcare', 'map'),
  ('events.sector', 'Online and Mail Order Retail', 'E-commerce', 'map'),
  ('events.sector', 'Mental Health & Healthcare', 'Mental Health', 'map'),
  ('events.sector', 'Digital Marketing', 'Marketing', 'map'),
  ('events.sector', 'Water & Utilities', 'Utilities', 'map'),
  ('events.sector', 'Deep Tech & Innovation', 'Deep Tech', 'map'),
  ('events.sector', 'Retirement Living & Property', 'Real Estate', 'map'),
  ('events.sector', 'Defence & Maritime', 'Defence & Space', 'map'),
  ('events.sector', 'Foodservice & Hospitality', 'Hospitality', 'map'),
  ('events.category', 'Founders & Startups', 'Founders & Startups', 'map'),
  ('events.category', 'Technology & Innovation', 'Technology', 'map'),
  ('events.category', 'AI & Data', 'AI & Data', 'map'),
  ('events.category', 'Professional Services', 'Professional Services', 'map'),
  ('events.category', 'Human Resources', 'Human Resources', 'map'),
  ('events.category', 'Marketing & Growth', 'Marketing', 'map'),
  ('events.category', 'Investing & Capital', 'Venture Capital', 'map'),
  ('events.category', 'Mining & Resources', 'Mining & Metals', 'map'),
  ('events.category', 'Workplace Safety', 'Workplace Safety', 'map'),
  ('events.category', 'Fintech & Financial Services', 'FinTech', 'map'),
  ('events.category', 'Logistics & Supply Chain', 'Logistics', 'map'),
  ('events.category', 'Superannuation & Financial Services', 'Investment Management', 'map'),
  ('events.category', 'Mining & Critical Minerals', 'Mining & Metals', 'map'),
  ('events.category', 'Accounting & Finance', 'Accounting', 'map'),
  ('events.category', 'Aged Care', 'Aged Care', 'map'),
  ('events.category', 'Construction & Design', 'Construction', 'map'),
  ('events.category', 'Venture Capital & Investment', 'Venture Capital', 'map'),
  ('events.category', 'CRM & Enterprise Technology', 'Software', 'map'),
  ('events.category', 'Food & Beverage Manufacturing', 'Food Production', 'map'),
  ('events.category', 'Construction', 'Construction', 'map'),
  ('events.category', 'Manufacturing', 'Manufacturing', 'map'),
  ('events.category', 'Corporate Governance', 'Governance', 'map'),
  ('events.category', 'Information Technology', 'Technology', 'map'),
  ('events.category', 'Retail & eCommerce', 'E-commerce', 'map'),
  ('events.category', 'Residential Property & Build-to-Rent', 'Real Estate', 'map'),
  ('events.category', 'Property & Valuation', 'Real Estate', 'map'),
  ('events.category', 'Insurance & Reinsurance', 'Insurance', 'map'),
  ('events.category', 'Data, Analytics & AI', 'AI & Data', 'map'),
  ('events.category', 'Defence & Maritime', 'Defence & Space', 'map'),
  ('events.category', 'Health IT & Digital Health', 'HealthTech', 'map'),
  ('events.category', 'Mortgage & Finance', 'Banking', 'map'),
  ('events.category', 'Small Business & Entrepreneurship', 'Small Business', 'map'),
  ('events.category', 'Digital Marketing', 'Marketing', 'map'),
  ('events.category', 'Healthcare', 'Healthcare', 'map'),
  ('events.category', 'Education Technology', 'EdTech', 'map'),
  ('events.category', 'Mental Health & Healthcare', 'Mental Health', 'map'),
  ('events.category', 'Finance', 'Financial Services', 'map'),
  ('events.category', 'Energy & Renewables', 'CleanTech', 'map'),
  ('events.category', 'Mining Technology', 'Mining & Metals', 'map'),
  ('events.category', 'Agribusiness', 'Agriculture', 'map'),
  ('events.category', 'Manufacturing & Industry', 'Manufacturing', 'map'),
  ('events.category', 'Agriculture & Agribusiness', 'Agriculture', 'map'),
  ('events.category', 'Government Technology', 'GovTech', 'map'),
  ('events.category', 'Startups & Venture Capital', 'Venture Capital', 'map'),
  ('events.category', 'SaaS & Tech Startups', 'SaaS', 'map'),
  ('events.category', 'Pharmacy', 'Pharmacy', 'map'),
  ('events.category', 'Startups & Scaleups', 'Founders & Startups', 'map'),
  ('events.category', 'Mining', 'Mining & Metals', 'map'),
  ('events.category', 'Small Business', 'Small Business', 'map'),
  ('events.category', 'Technology', 'Technology', 'map'),
  ('events.category', 'Events & Business Tourism', 'Events & Tourism', 'map'),
  ('events.category', 'Legal Technology', 'LegalTech', 'map'),
  ('events.category', 'Deep Tech & Innovation', 'Deep Tech', 'map'),
  ('events.category', 'Water & Utilities', 'Utilities', 'map'),
  ('events.category', 'Retail', 'Retail', 'map'),
  ('events.category', 'Food & Beverage', 'Food & Beverage', 'map'),
  ('events.category', 'Property & Real Estate', 'Real Estate', 'map'),
  ('events.category', 'Manufacturing & Engineering', 'Manufacturing', 'map'),
  ('events.category', 'Manufacturing & Automation', 'Industrial Automation', 'map'),
  ('events.category', 'Natural & Health Products', 'Consumer Goods', 'map'),
  ('events.category', 'Digital Health', 'HealthTech', 'map'),
  ('events.category', 'Foodservice & Hospitality', 'Hospitality', 'map'),
  ('events.category', 'Health & MedTech', 'HealthTech', 'map'),
  ('events.category', 'Procurement & Supply Chain', 'Logistics', 'map'),
  ('events.category', 'Accounting Technology', 'Accounting', 'map'),
  ('events.category', 'Retirement Living & Property', 'Real Estate', 'map'),
  ('events.category', 'Marketing & Media', 'Marketing', 'map'),
  ('events.category', 'Cybersecurity', 'Cybersecurity', 'map'),
  ('events.category', 'Urban Development & Smart Cities', 'Smart Cities', 'map'),
  ('events.category', 'Software Development', 'Software Development', 'map'),
  ('events.category', 'Energy', 'Energy', 'map'),
  ('events.category', 'Aerospace & Defence', 'Defence & Space', 'map'),
  ('events.category', 'Startups & Innovation', 'Founders & Startups', 'map'),
  ('events.category', 'Fitness', 'Fitness', 'map'),
  ('events.category', 'Cloud Computing & AI', 'AI & Data', 'map'),
  ('events.category', 'Marketing', 'Marketing', 'map'),
  ('events.category', 'Logistics', 'Logistics', 'map'),
  ('events.category', 'Freight & Logistics', 'Logistics', 'map'),
  ('events.category', 'Agriculture & Farming', 'Agriculture', 'map'),
  ('events.category', 'Quantum Computing & Deep Tech', 'Deep Tech', 'map'),
  ('country_case_studies.sector', 'Cybersecurity', 'Cybersecurity', 'map'),
  ('country_case_studies.sector', 'Fintech', 'FinTech', 'map'),
  ('country_case_studies.sector', 'RegTech', 'RegTech', 'map'),
  ('country_case_studies.sector', 'HealthTech', 'HealthTech', 'map'),
  ('country_case_studies.sector', 'Fintech / Payments', 'FinTech', 'map'),
  ('country_case_studies.sector', 'InsurTech', 'InsurTech', 'map'),
  ('country_case_studies.sector', 'Cloud Data Platform', 'Software', 'map'),
  ('country_case_studies.sector', 'Video Communications / UCaaS', 'Software', 'map'),
  ('country_case_studies.sector', 'HR & Finance SaaS', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Digital Customer Experience / BPO', 'Outsourcing', 'map'),
  ('country_case_studies.sector', 'Core Banking', 'Software', 'map'),
  ('country_case_studies.sector', 'Fraud / AI', 'Cybersecurity', 'map'),
  ('country_case_studies.sector', 'Legal Technology / SaaS', 'LegalTech', 'map'),
  ('country_case_studies.sector', 'PropTech', 'PropTech', 'map'),
  ('country_case_studies.sector', 'Marketing & CRM SaaS', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Conversational AI / CX Automation', 'AI & Data', 'map'),
  ('country_case_studies.sector', 'Identity & Access Management', 'Cybersecurity', 'map'),
  ('country_case_studies.sector', 'E-commerce Platform / SaaS', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Automotive & Retail Software', 'Software', 'map'),
  ('country_case_studies.sector', 'Recommerce Marketplace', 'Marketplace', 'map'),
  ('country_case_studies.sector', 'B2B Payments Infrastructure', 'FinTech', 'map'),
  ('country_case_studies.sector', 'Cloud Monitoring / Observability', 'Software', 'map'),
  ('country_case_studies.sector', 'AI Search / Enterprise SaaS', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Identity', 'Cybersecurity', 'map'),
  ('country_case_studies.sector', 'Mobile Security', 'Cybersecurity', 'map'),
  ('country_case_studies.sector', 'CRM / Cloud Software', 'Software', 'map'),
  ('country_case_studies.sector', 'Vertical Market Software', 'Software', 'map'),
  ('country_case_studies.sector', 'Retail & Hospitality POS / SaaS', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Cloud Communications / CPaaS', 'Software', 'map'),
  ('country_case_studies.sector', 'Payments', 'FinTech', 'map'),
  ('country_case_studies.sector', 'Gaming Payments', 'FinTech', 'map'),
  ('country_case_studies.sector', 'Enterprise Information Management / Software', 'Software', 'map'),
  ('country_case_studies.sector', 'Gaming Hardware / DTC', 'Gaming Hardware', 'map'),
  ('country_case_studies.sector', 'Enterprise SaaS / IP Analytics', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Social Media Management / SaaS', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Consumer Fintech / Cashback', 'FinTech', 'map'),
  ('country_case_studies.sector', 'Cloud / DevOps', 'Software', 'map'),
  ('country_case_studies.sector', 'Enterprise SaaS / ITSM', 'SaaS', 'map'),
  ('country_case_studies.sector', 'Gaming Hardware', 'Gaming Hardware', 'map'),
  ('country_case_studies.sector', 'Digital Publishing / Consumer Platform', 'Digital Media', 'map'),
  ('country_case_studies.sector', 'Data & AI', 'AI & Data', 'map'),
  ('country_case_studies.sector', 'Payments / Fintech', 'FinTech', 'map'),
  ('country_case_studies.sector', 'Transport / Mobility', 'Mobility', 'map'),
  ('country_case_studies.sector', 'EdTech', 'EdTech', 'map'),
  ('country_case_studies.sector', 'AccountingTech', 'Accounting', 'map'),
  ('country_case_studies.sector', 'E-commerce', 'E-commerce', 'map'),
  ('content_company_profiles.industry', 'Fintech', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Construction Tech', 'ConstructionTech', 'map'),
  ('content_company_profiles.industry', 'Cybersecurity', 'Cybersecurity', 'map'),
  ('content_company_profiles.industry', 'Fashion Retail', 'Apparel Retail', 'map'),
  ('content_company_profiles.industry', 'Fintech / BNPL', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Automation', 'Software', 'map'),
  ('content_company_profiles.industry', 'Financial Technology', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Food Delivery / Marketplace', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'QSR / Food', 'Restaurants', 'map'),
  ('content_company_profiles.industry', 'RegTech', 'RegTech', 'map'),
  ('content_company_profiles.industry', 'Technology', 'Technology', 'map'),
  ('content_company_profiles.industry', 'AI Safety and Enterprise AI Platform', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'Artificial Intelligence Platform', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'CI/CD Developer Tools', 'Software', 'map'),
  ('content_company_profiles.industry', 'Cloud Accounting Software', 'Software', 'map'),
  ('content_company_profiles.industry', 'Cloud Communications Platform', 'Software', 'map'),
  ('content_company_profiles.industry', 'Cloud Computing and AI Infrastructure', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'Cloud CRM and Enterprise AI Platform', 'Software', 'map'),
  ('content_company_profiles.industry', 'Cloud Data Platform and AI', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'Cloud IT Service Management and Enterprise Automation', 'Software', 'map'),
  ('content_company_profiles.industry', 'Cloud Services', 'Software', 'map'),
  ('content_company_profiles.industry', 'Consumer Fintech', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Consumer Hardware / Gaming', 'Gaming Hardware', 'map'),
  ('content_company_profiles.industry', 'Consumer Tech / Fitness', 'Fitness', 'map'),
  ('content_company_profiles.industry', 'Corporate learning marketplace, EdTech', 'EdTech', 'map'),
  ('content_company_profiles.industry', 'Creative Digital Marketplace', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'Cultivated meat (deep tech biotech)', 'Biotechnology', 'map'),
  ('content_company_profiles.industry', 'Data Analytics, AI, and National Security', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'Data and AI Analytics Platform', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'Department Store Retail', 'Retail', 'map'),
  ('content_company_profiles.industry', 'Design & Visual Communication Platform', 'Software', 'map'),
  ('content_company_profiles.industry', 'Digital Agreement and Contract Management', 'Software', 'map'),
  ('content_company_profiles.industry', 'Digital health, telehealth, direct-to-consumer virtual clinics', 'HealthTech', 'map'),
  ('content_company_profiles.industry', 'Digital Identity & Biometrics', 'Cybersecurity', 'map'),
  ('content_company_profiles.industry', 'Digital Distribution / Gaming', 'Gaming', 'map'),
  ('content_company_profiles.industry', 'E-commerce / Marketplace', 'E-commerce', 'map'),
  ('content_company_profiles.industry', 'E-commerce and Retail Technology', 'E-commerce', 'map'),
  ('content_company_profiles.industry', 'E-commerce technology, transaction moment optimization', 'E-commerce', 'map'),
  ('content_company_profiles.industry', 'Edtech', 'EdTech', 'map'),
  ('content_company_profiles.industry', 'EdTech / Career Training (tech sales bootcamps)', 'EdTech', 'map'),
  ('content_company_profiles.industry', 'Electric Vehicles and Clean Energy', 'CleanTech', 'map'),
  ('content_company_profiles.industry', 'Employee Experience / HR Tech', 'HR Tech', 'map'),
  ('content_company_profiles.industry', 'Enterprise Automation and AI', 'AI & Data', 'map'),
  ('content_company_profiles.industry', 'Enterprise Software', 'Software', 'map'),
  ('content_company_profiles.industry', 'Event Ticketing Platform (Social Enterprise)', 'Events Tech', 'map'),
  ('content_company_profiles.industry', 'F&B / Retail', 'Food & Beverage', 'map'),
  ('content_company_profiles.industry', 'Fintech / Crypto Derivatives', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Fintech / Neobank', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Fintech Infrastructure', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Green Energy Fintech', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Healthcare AI', 'HealthTech', 'map'),
  ('content_company_profiles.industry', 'Healthcare AI - Medical Imaging', 'HealthTech', 'map'),
  ('content_company_profiles.industry', 'Healthtech', 'HealthTech', 'map'),
  ('content_company_profiles.industry', 'Home Improvement / Retail', 'Retail', 'map'),
  ('content_company_profiles.industry', 'Hotel Technology SaaS', 'SaaS', 'map'),
  ('content_company_profiles.industry', 'HR, Payroll & Hiring SaaS', 'HR Tech', 'map'),
  ('content_company_profiles.industry', 'Identity Verification', 'Cybersecurity', 'map'),
  ('content_company_profiles.industry', 'Insurance Software', 'InsurTech', 'map'),
  ('content_company_profiles.industry', 'Insurtech', 'InsurTech', 'map'),
  ('content_company_profiles.industry', 'InsurTech', 'InsurTech', 'map'),
  ('content_company_profiles.industry', 'Marketplace', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'Marketplace / Deals', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'Marketplace / Tickets', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'Media & Entertainment', 'Media & Entertainment', 'map'),
  ('content_company_profiles.industry', 'Mobility / Car Sharing', 'Mobility', 'map'),
  ('content_company_profiles.industry', 'Mobility & Transport', 'Mobility', 'map'),
  ('content_company_profiles.industry', 'Online marketplace for local services and gig economy', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'PropTech', 'PropTech', 'map'),
  ('content_company_profiles.industry', 'Proptech / Coworking', 'PropTech', 'map'),
  ('content_company_profiles.industry', 'Rapid Grocery Delivery', 'E-commerce', 'map'),
  ('content_company_profiles.industry', 'RegTech / Client Lifecycle Management', 'RegTech', 'map'),
  ('content_company_profiles.industry', 'Revenue-Based Financing / E-Commerce Growth Capital', 'FinTech', 'map'),
  ('content_company_profiles.industry', 'Rideshare', 'Mobility', 'map'),
  ('content_company_profiles.industry', 'Semiconductors (Wi-Fi HaLow chips for IoT)', 'Semiconductors', 'map'),
  ('content_company_profiles.industry', 'Social Media Tools / Creator Economy', 'Software', 'map'),
  ('content_company_profiles.industry', 'Software Development Platform and AI-Powered Developer Tools', 'Software', 'map'),
  ('content_company_profiles.industry', 'Supermarket / Retail', 'Supermarkets', 'map'),
  ('content_company_profiles.industry', 'Technology / Sharing Economy Platform', 'Marketplace', 'map'),
  ('content_company_profiles.industry', 'Unified Communications and AI-First Collaboration Platform', 'Software', 'map'),
  ('content_company_profiles.industry', 'Web3 gaming infrastructure, Layer 2 blockchain, NFT platform', 'Web3', 'map'),
  ('content_company_profiles.industry', 'Workflow Automation / Security Automation', 'Software', 'map'),
  ('content_company_profiles.industry', 'Workforce Management SaaS', 'SaaS', 'map'),
  ('content_company_profiles.industry', 'Workplace Safety & Operations SaaS', 'SaaS', 'map'),
  ('lead_databases.sector', 'Cross-Industry', 'Sector Agnostic', 'map'),
  ('lead_databases.sector', 'Technology, Information and Media', 'Technology', 'map'),
  ('lead_databases.sector', 'Financial Services', 'Financial Services', 'map'),
  ('lead_databases.sector', 'Business Consulting and Services', 'Professional Services', 'map'),
  ('lead_databases.sector', 'Government Administration', 'Government', 'map'),
  ('lead_databases.sector', 'Retail', 'Retail', 'map'),
  ('lead_databases.sector', 'Accommodation and Food Services', 'Hospitality', 'map'),
  ('lead_databases.sector', 'Banking', 'Banking', 'map'),
  ('lead_databases.sector', 'Construction', 'Construction', 'map'),
  ('lead_databases.sector', 'Defense & Space', 'Defence & Space', 'map'),
  ('lead_databases.sector', 'Education', 'Education', 'map'),
  ('lead_databases.sector', 'Entertainment Providers', 'Entertainment', 'map'),
  ('lead_databases.sector', 'Farming, Ranching, Forestry', 'Agriculture', 'map'),
  ('lead_databases.sector', 'Hospitals and Health Care', 'Healthcare', 'map'),
  ('lead_databases.sector', 'Insurance', 'Insurance', 'map'),
  ('lead_databases.sector', 'Manufacturing', 'Manufacturing', 'map'),
  ('lead_databases.sector', 'Mining & Metals', 'Mining & Metals', 'map'),
  ('lead_databases.sector', 'Non-profit Organizations', 'Non-Profit', 'map'),
  ('lead_databases.sector', 'Online and Mail Order Retail', 'E-commerce', 'map'),
  ('lead_databases.sector', 'Pharmaceutical Manufacturing', 'Pharmaceuticals', 'map'),
  ('lead_databases.sector', 'Real Estate', 'Real Estate', 'map'),
  ('lead_databases.sector', 'Telecommunications', 'Telecommunications', 'map'),
  ('lead_databases.sector', 'Transportation, Logistics, Supply Chain and Storage', 'Logistics', 'map'),
  ('lead_databases.sector', 'Utilities', 'Utilities', 'map'),
  ('lead_databases.sector', 'Venture Capital and Private Equity', 'Venture Capital', 'map'),
  ('lead_databases.sector', 'Wholesale', 'Wholesale', 'map'),
  ('leads.industry', 'Construction', 'Construction', 'map'),
  ('leads.industry', 'Financial Services', 'Financial Services', 'map'),
  ('leads.industry', 'Financial Technology', 'FinTech', 'map'),
  ('leads.industry', 'Healthcare Technology', 'HealthTech', 'map'),
  ('leads.industry', 'Professional Services', 'Professional Services', 'map'),
  ('leads.industry', 'Retail & E-commerce', 'E-commerce', 'map'),
  ('leads.industry', 'Technology', 'Technology', 'map'),
  ('leads.category', 'banking', 'Banking', 'map'),
  ('leads.category', 'Construction', 'Construction', 'map'),
  ('leads.category', 'cybersecurity', 'Cybersecurity', 'map'),
  ('leads.category', 'ecommerce', 'E-commerce', 'map'),
  ('leads.category', 'fintech', 'FinTech', 'map'),
  ('leads.category', 'forensic', 'Forensics', 'map'),
  ('leads.category', 'healthcare', 'Healthcare', 'map'),
  ('lead_submissions.sector', 'FinTech', 'FinTech', 'map'),
  ('lead_submissions.sector', 'MedTech', 'MedTech', 'map'),
  ('innovation_ecosystem.sectors', 'Sector Agnostic', 'Sector Agnostic', 'agnostic'),
  ('innovation_ecosystem.sectors', 'Cleantech', 'CleanTech', 'map'),
  ('innovation_ecosystem.sectors', 'Deep Tech', 'Deep Tech', 'map'),
  ('innovation_ecosystem.sectors', 'Healthtech', 'HealthTech', 'map'),
  ('innovation_ecosystem.sectors', 'AI', 'AI', 'map'),
  ('innovation_ecosystem.sectors', 'Agritech', 'AgTech', 'map'),
  ('innovation_ecosystem.sectors', 'Space', 'Space', 'map'),
  ('innovation_ecosystem.sectors', 'Fintech', 'FinTech', 'map'),
  ('innovation_ecosystem.sectors', 'Foodtech', 'FoodTech', 'map'),
  ('innovation_ecosystem.sectors', 'Cybersecurity', 'Cybersecurity', 'map'),
  ('innovation_ecosystem.sectors', 'Defence', 'Defence & Space', 'map'),
  ('innovation_ecosystem.sectors', 'Edtech', 'EdTech', 'map'),
  ('innovation_ecosystem.sectors', 'Manufacturing', 'Manufacturing', 'map'),
  ('innovation_ecosystem.sectors', 'Insurtech', 'InsurTech', 'map'),
  ('innovation_ecosystem.sectors', 'IoT', 'IoT', 'map'),
  ('innovation_ecosystem.sectors', 'Mining', 'Mining & Metals', 'map'),
  ('innovation_ecosystem.sectors', 'Property', 'Real Estate', 'map'),
  ('innovation_ecosystem.sectors', 'RegTech', 'RegTech', 'map'),
  ('innovation_ecosystem.sectors', 'Smart Cities', 'Smart Cities', 'map'),
  ('innovation_ecosystem.sectors', 'Agtech', 'AgTech', 'map'),
  ('innovation_ecosystem.sectors', 'Biotech', 'Biotechnology', 'map'),
  ('innovation_ecosystem.sectors', 'Black and Women of Colour', 'Audience Focus', 'drop'),
  ('innovation_ecosystem.sectors', 'climate', 'CleanTech', 'map'),
  ('innovation_ecosystem.sectors', 'Clinical Entrepreneurs', 'Audience Focus', 'drop'),
  ('innovation_ecosystem.sectors', 'Deeptech', 'Deep Tech', 'map'),
  ('innovation_ecosystem.sectors', 'defence', 'Defence & Space', 'map'),
  ('innovation_ecosystem.sectors', 'health', 'Healthcare', 'map'),
  ('innovation_ecosystem.sectors', 'health, disability and wellbeing', 'Theme', 'drop'),
  ('innovation_ecosystem.sectors', 'Healthcare', 'Healthcare', 'map'),
  ('innovation_ecosystem.sectors', 'Ocean health', 'Theme', 'drop'),
  ('innovation_ecosystem.sectors', 'sector agnostic', 'Sector Agnostic', 'agnostic'),
  ('innovation_ecosystem.sectors', 'social entrepreneurs', 'Audience Focus', 'drop'),
  ('innovation_ecosystem.sectors', 'Web3', 'Web3', 'map'),
  ('innovation_ecosystem.sectors', 'women', 'Audience Focus', 'drop'),
  ('innovation_ecosystem.sectors', 'Women and non-binary founders', 'Audience Focus', 'drop'),
  ('trade_investment_agencies.sectors_supported', 'Sector Agnostic', 'Sector Agnostic', 'agnostic'),
  ('trade_investment_agencies.sectors_supported', 'Manufacturing', 'Manufacturing', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Financial Services', 'Financial Services', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Mining', 'Mining & Metals', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Foodtech', 'FoodTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Cleantech', 'CleanTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Edtech', 'EdTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Healthtech', 'HealthTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Agritech', 'AgTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Defence', 'Defence & Space', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Construction', 'Construction', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Deep Tech', 'Deep Tech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Fintech', 'FinTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Tourism', 'Tourism', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Creative Industries', 'Creative Industries', 'map'),
  ('trade_investment_agencies.sectors_supported', 'technology', 'Technology', 'map'),
  ('trade_investment_agencies.sectors_supported', 'all', 'Sector Agnostic', 'agnostic'),
  ('trade_investment_agencies.sectors_supported', 'manufacturing', 'Manufacturing', 'map'),
  ('trade_investment_agencies.sectors_supported', 'Space', 'Space', 'map'),
  ('trade_investment_agencies.sectors_supported', 'agritech', 'AgTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'fintech', 'FinTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'professional_services', 'Professional Services', 'map'),
  ('trade_investment_agencies.sectors_supported', 'construction', 'Construction', 'map'),
  ('trade_investment_agencies.sectors_supported', 'deeptech', 'Deep Tech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'defence', 'Defence & Space', 'map'),
  ('trade_investment_agencies.sectors_supported', 'energy', 'Energy', 'map'),
  ('trade_investment_agencies.sectors_supported', 'healthtech', 'HealthTech', 'map'),
  ('trade_investment_agencies.sectors_supported', 'resources', 'Mining & Metals', 'map'),
  ('trade_investment_agencies.sectors_supported', 'tourism', 'Tourism', 'map'),
  ('trade_investment_agencies.sectors_supported', 'transport', 'Logistics', 'map'),
  ('locations.key_industries', 'Technology', 'Technology', 'map'),
  ('locations.key_industries', 'Tourism', 'Tourism', 'map'),
  ('locations.key_industries', 'Agriculture', 'Agriculture', 'map'),
  ('locations.key_industries', 'Education', 'Education', 'map'),
  ('locations.key_industries', 'Defence', 'Defence & Space', 'map'),
  ('locations.key_industries', 'Manufacturing', 'Manufacturing', 'map'),
  ('locations.key_industries', 'Renewable Energy', 'CleanTech', 'map'),
  ('locations.key_industries', 'Healthcare', 'Healthcare', 'map'),
  ('locations.key_industries', 'Space', 'Space', 'map'),
  ('locations.key_industries', 'Film & Creative', 'Film & Creative', 'map'),
  ('locations.key_industries', 'Financial Services', 'Financial Services', 'map'),
  ('locations.key_industries', 'Food & Beverage', 'Food & Beverage', 'map'),
  ('locations.key_industries', 'Government', 'Government', 'map'),
  ('locations.key_industries', 'Mining', 'Mining & Metals', 'map'),
  ('locations.key_industries', 'Creative Industries', 'Creative Industries', 'map'),
  ('locations.key_industries', 'Health & Medical', 'Healthcare', 'map'),
  ('locations.key_industries', 'Professional Services', 'Professional Services', 'map'),
  ('locations.key_industries', 'Agritech', 'AgTech', 'map'),
  ('locations.key_industries', 'Cyber Security', 'Cybersecurity', 'map'),
  ('locations.key_industries', 'Engineering', 'Engineering', 'map'),
  ('locations.key_industries', 'Marine', 'Maritime', 'map'),
  ('locations.key_industries', 'Mining & Resources', 'Mining & Metals', 'map'),
  ('locations.key_industries', 'Oil & Gas', 'Oil & Gas', 'map'),
  ('locations.key_industries', 'Aerospace', 'Aerospace', 'map'),
  ('locations.key_industries', 'Aviation', 'Aerospace', 'map'),
  ('locations.key_industries', 'Creative', 'Creative Industries', 'map'),
  ('locations.key_industries', 'Dairy', 'Dairy', 'map'),
  ('locations.key_industries', 'Dairy Processing', 'Dairy', 'map'),
  ('locations.key_industries', 'Energy', 'Energy', 'map'),
  ('locations.key_industries', 'Film & Post-production', 'Film & Creative', 'map'),
  ('locations.key_industries', 'Marine Science', 'Marine Science', 'map'),
  ('locations.key_industries', 'Media', 'Media', 'map'),
  ('locations.key_industries', 'Mining Services', 'Mining & Metals', 'map'),
  ('locations.key_industries', 'Real Estate', 'Real Estate', 'map'),
  ('locations.key_industries', 'Wine & Agriculture', 'Wine & Food', 'map'),
  ('locations.key_industries', 'Wine & Food', 'Wine & Food', 'map'),
  ('countries.key_industries', 'Technology', 'Technology', 'map'),
  ('countries.key_industries', 'Financial Services', 'Financial Services', 'map'),
  ('countries.key_industries', 'Manufacturing', 'Manufacturing', 'map'),
  ('countries.key_industries', 'Energy', 'Energy', 'map'),
  ('countries.key_industries', 'Agriculture', 'Agriculture', 'map'),
  ('countries.key_industries', 'Automotive', 'Automotive', 'map'),
  ('countries.key_industries', 'Mining', 'Mining & Metals', 'map'),
  ('countries.key_industries', 'Aerospace & Defence', 'Aerospace', 'map'),
  ('countries.key_industries', 'Clean Energy', 'CleanTech', 'map'),
  ('countries.key_industries', 'Electronics', 'Electronics Manufacturing', 'map'),
  ('countries.key_industries', 'Energy & Resources', 'Energy', 'map'),
  ('countries.key_industries', 'Healthcare', 'Healthcare', 'map'),
  ('countries.key_industries', 'Infrastructure', 'Infrastructure', 'map'),
  ('countries.key_industries', 'Logistics', 'Logistics', 'map'),
  ('countries.key_industries', 'Luxury & Consumer', 'Luxury & Consumer', 'map'),
  ('countries.key_industries', 'Pharmaceuticals', 'Pharmaceuticals', 'map'),
  ('countries.key_industries', 'Professional Services', 'Professional Services', 'map'),
  ('countries.key_industries', 'Retail', 'Retail', 'map'),
  ('countries.key_industries', 'Steel & Metals', 'Mining & Metals', 'map'),
  ('countries.key_industries', 'Trade', 'Trade', 'map'),
  ('industry_sectors.industries', 'Banking', 'Banking', 'map'),
  ('industry_sectors.industries', 'Biotechnology', 'Biotechnology', 'map'),
  ('industry_sectors.industries', 'Connectivity', 'Telecommunications', 'map'),
  ('industry_sectors.industries', 'Digital Health', 'HealthTech', 'map'),
  ('industry_sectors.industries', 'Financial Services', 'Financial Services', 'map'),
  ('industry_sectors.industries', 'FinTech', 'FinTech', 'map'),
  ('industry_sectors.industries', 'Healthcare', 'Healthcare', 'map'),
  ('industry_sectors.industries', 'Infrastructure', 'Infrastructure', 'map'),
  ('industry_sectors.industries', 'Insurance', 'Insurance', 'map'),
  ('industry_sectors.industries', 'Investment', 'Venture Capital', 'map'),
  ('industry_sectors.industries', 'IoT', 'IoT', 'map'),
  ('industry_sectors.industries', 'Medical Technology', 'MedTech', 'map'),
  ('industry_sectors.industries', 'Pharmaceuticals', 'Pharmaceuticals', 'map'),
  ('industry_sectors.industries', 'Technology', 'Technology', 'map'),
  ('industry_sectors.industries', 'Telecommunications', 'Telecommunications', 'map');

-- ---- investors.sector_focus (array) ----
alter table public.investors add column if not exists sector_focus_legacy text[];
comment on column public.investors.sector_focus_legacy is 'MES-110 backup of pre-remap sector_focus; drop after sign-off.';
update public.investors set sector_focus_legacy = sector_focus where sector_focus_legacy is null and sector_focus is not null and array_length(sector_focus, 1) is not null;
with expanded as (
  select t.id,
         case when m.surface is null then u.val
              when m.action = 'map' then m.merged
              else null end as out_val,
         (m.action = 'agnostic') as is_agn
  from public.investors t
  cross join lateral unnest(t.sector_focus_legacy) as u(val)
  left join mes110_map m on m.surface = 'investors.sector_focus' and m.raw = u.val
),
rebuilt as (
  select e.id,
         array_agg(distinct e.out_val order by e.out_val) filter (where e.out_val is not null) as new_arr,
         coalesce(bool_or(e.is_agn), false) as has_agn
  from expanded e
  group by e.id
)
update public.investors t
  set sector_focus = coalesce(r.new_arr, '{}'),
      sector_agnostic = t.sector_agnostic or r.has_agn
  from rebuilt r
  where r.id = t.id;

-- ---- innovation_ecosystem.sectors (array) ----
alter table public.innovation_ecosystem add column if not exists sectors_legacy text[];
comment on column public.innovation_ecosystem.sectors_legacy is 'MES-110 backup of pre-remap sectors; drop after sign-off.';
update public.innovation_ecosystem set sectors_legacy = sectors where sectors_legacy is null and sectors is not null and array_length(sectors, 1) is not null;
with expanded as (
  select t.id,
         case when m.surface is null then u.val
              when m.action = 'map' then m.merged
              else null end as out_val,
         (m.action = 'agnostic') as is_agn
  from public.innovation_ecosystem t
  cross join lateral unnest(t.sectors_legacy) as u(val)
  left join mes110_map m on m.surface = 'innovation_ecosystem.sectors' and m.raw = u.val
),
rebuilt as (
  select e.id,
         array_agg(distinct e.out_val order by e.out_val) filter (where e.out_val is not null) as new_arr,
         coalesce(bool_or(e.is_agn), false) as has_agn
  from expanded e
  group by e.id
)
update public.innovation_ecosystem t
  set sectors = coalesce(r.new_arr, '{}'),
      sector_agnostic = t.sector_agnostic or r.has_agn
  from rebuilt r
  where r.id = t.id;

-- ---- trade_investment_agencies.sectors_supported (array) ----
alter table public.trade_investment_agencies add column if not exists sectors_supported_legacy text[];
comment on column public.trade_investment_agencies.sectors_supported_legacy is 'MES-110 backup of pre-remap sectors_supported; drop after sign-off.';
update public.trade_investment_agencies set sectors_supported_legacy = sectors_supported where sectors_supported_legacy is null and sectors_supported is not null and array_length(sectors_supported, 1) is not null;
with expanded as (
  select t.id,
         case when m.surface is null then u.val
              when m.action = 'map' then m.merged
              else null end as out_val,
         (m.action = 'agnostic') as is_agn
  from public.trade_investment_agencies t
  cross join lateral unnest(t.sectors_supported_legacy) as u(val)
  left join mes110_map m on m.surface = 'trade_investment_agencies.sectors_supported' and m.raw = u.val
),
rebuilt as (
  select e.id,
         array_agg(distinct e.out_val order by e.out_val) filter (where e.out_val is not null) as new_arr,
         coalesce(bool_or(e.is_agn), false) as has_agn
  from expanded e
  group by e.id
)
update public.trade_investment_agencies t
  set sectors_supported = coalesce(r.new_arr, '{}'),
      sector_agnostic = t.sector_agnostic or r.has_agn
  from rebuilt r
  where r.id = t.id;

-- ---- locations.key_industries (array) ----
alter table public.locations add column if not exists key_industries_legacy text[];
comment on column public.locations.key_industries_legacy is 'MES-110 backup of pre-remap key_industries; drop after sign-off.';
update public.locations set key_industries_legacy = key_industries where key_industries_legacy is null and key_industries is not null and array_length(key_industries, 1) is not null;
with expanded as (
  select t.id,
         case when m.surface is null then u.val
              when m.action = 'map' then m.merged
              else null end as out_val,
         (m.action = 'agnostic') as is_agn
  from public.locations t
  cross join lateral unnest(t.key_industries_legacy) as u(val)
  left join mes110_map m on m.surface = 'locations.key_industries' and m.raw = u.val
),
rebuilt as (
  select e.id,
         array_agg(distinct e.out_val order by e.out_val) filter (where e.out_val is not null) as new_arr,
         false as has_agn
  from expanded e
  group by e.id
)
update public.locations t
  set key_industries = coalesce(r.new_arr, '{}')
  from rebuilt r
  where r.id = t.id;

-- ---- countries.key_industries (array) ----
alter table public.countries add column if not exists key_industries_legacy text[];
comment on column public.countries.key_industries_legacy is 'MES-110 backup of pre-remap key_industries; drop after sign-off.';
update public.countries set key_industries_legacy = key_industries where key_industries_legacy is null and key_industries is not null and array_length(key_industries, 1) is not null;
with expanded as (
  select t.id,
         case when m.surface is null then u.val
              when m.action = 'map' then m.merged
              else null end as out_val,
         (m.action = 'agnostic') as is_agn
  from public.countries t
  cross join lateral unnest(t.key_industries_legacy) as u(val)
  left join mes110_map m on m.surface = 'countries.key_industries' and m.raw = u.val
),
rebuilt as (
  select e.id,
         array_agg(distinct e.out_val order by e.out_val) filter (where e.out_val is not null) as new_arr,
         false as has_agn
  from expanded e
  group by e.id
)
update public.countries t
  set key_industries = coalesce(r.new_arr, '{}')
  from rebuilt r
  where r.id = t.id;

-- ---- industry_sectors.industries (array) ----
alter table public.industry_sectors add column if not exists industries_legacy text[];
comment on column public.industry_sectors.industries_legacy is 'MES-110 backup of pre-remap industries; drop after sign-off.';
update public.industry_sectors set industries_legacy = industries where industries_legacy is null and industries is not null and array_length(industries, 1) is not null;
with expanded as (
  select t.id,
         case when m.surface is null then u.val
              when m.action = 'map' then m.merged
              else null end as out_val,
         (m.action = 'agnostic') as is_agn
  from public.industry_sectors t
  cross join lateral unnest(t.industries_legacy) as u(val)
  left join mes110_map m on m.surface = 'industry_sectors.industries' and m.raw = u.val
),
rebuilt as (
  select e.id,
         array_agg(distinct e.out_val order by e.out_val) filter (where e.out_val is not null) as new_arr,
         false as has_agn
  from expanded e
  group by e.id
)
update public.industry_sectors t
  set industries = coalesce(r.new_arr, '{}')
  from rebuilt r
  where r.id = t.id;

-- ---- events.sector (scalar) ----
alter table public.events add column if not exists sector_legacy text;
comment on column public.events.sector_legacy is 'MES-110 backup of pre-remap sector; drop after sign-off.';
update public.events set sector_legacy = sector where sector_legacy is null and sector is not null;
update public.events t
  set sector = m.merged
  from mes110_map m
  where m.surface = 'events.sector' and m.raw = t.sector_legacy and t.sector is distinct from m.merged;

-- ---- events.category (scalar) ----
alter table public.events add column if not exists category_legacy text;
comment on column public.events.category_legacy is 'MES-110 backup of pre-remap category; drop after sign-off.';
update public.events set category_legacy = category where category_legacy is null and category is not null;
update public.events t
  set category = m.merged
  from mes110_map m
  where m.surface = 'events.category' and m.raw = t.category_legacy and t.category is distinct from m.merged;

-- ---- lead_databases.sector (scalar) ----
alter table public.lead_databases add column if not exists sector_legacy text;
comment on column public.lead_databases.sector_legacy is 'MES-110 backup of pre-remap sector; drop after sign-off.';
update public.lead_databases set sector_legacy = sector where sector_legacy is null and sector is not null;
update public.lead_databases t
  set sector = m.merged
  from mes110_map m
  where m.surface = 'lead_databases.sector' and m.raw = t.sector_legacy and t.sector is distinct from m.merged;

-- ---- leads.industry (scalar) ----
alter table public.leads add column if not exists industry_legacy text;
comment on column public.leads.industry_legacy is 'MES-110 backup of pre-remap industry; drop after sign-off.';
update public.leads set industry_legacy = industry where industry_legacy is null and industry is not null;
update public.leads t
  set industry = m.merged
  from mes110_map m
  where m.surface = 'leads.industry' and m.raw = t.industry_legacy and t.industry is distinct from m.merged;

-- ---- leads.category (scalar) ----
alter table public.leads add column if not exists category_legacy text;
comment on column public.leads.category_legacy is 'MES-110 backup of pre-remap category; drop after sign-off.';
update public.leads set category_legacy = category where category_legacy is null and category is not null;
update public.leads t
  set category = m.merged
  from mes110_map m
  where m.surface = 'leads.category' and m.raw = t.category_legacy and t.category is distinct from m.merged;

-- ---- lead_submissions.sector (scalar) ----
alter table public.lead_submissions add column if not exists sector_legacy text;
comment on column public.lead_submissions.sector_legacy is 'MES-110 backup of pre-remap sector; drop after sign-off.';
update public.lead_submissions set sector_legacy = sector where sector_legacy is null and sector is not null;
update public.lead_submissions t
  set sector = m.merged
  from mes110_map m
  where m.surface = 'lead_submissions.sector' and m.raw = t.sector_legacy and t.sector is distinct from m.merged;

-- ---- country_case_studies.sector (scalar) ----
alter table public.country_case_studies add column if not exists sector_legacy text;
comment on column public.country_case_studies.sector_legacy is 'MES-110 backup of pre-remap sector; drop after sign-off.';
update public.country_case_studies set sector_legacy = sector where sector_legacy is null and sector is not null;
update public.country_case_studies t
  set sector = m.merged
  from mes110_map m
  where m.surface = 'country_case_studies.sector' and m.raw = t.sector_legacy and t.sector is distinct from m.merged;

-- ---- content_company_profiles.industry (scalar) ----
alter table public.content_company_profiles add column if not exists industry_legacy text;
comment on column public.content_company_profiles.industry_legacy is 'MES-110 backup of pre-remap industry; drop after sign-off.';
update public.content_company_profiles set industry_legacy = industry where industry_legacy is null and industry is not null;
update public.content_company_profiles t
  set industry = m.merged
  from mes110_map m
  where m.surface = 'content_company_profiles.industry' and m.raw = t.industry_legacy and t.industry is distinct from m.merged;

drop table if exists mes110_map;
