-- Import VC investors batch 1 (IDs 1-10) from Perplexity-enriched CSV
-- Source: docs/MES_VC_Database_IDs1-10_Updated.csv
-- Date: 2026-04-07
-- 10 records: 9 new inserts + 1 upsert (Airtree Ventures)
-- Slug auto-generated by trg_investors_slug BEFORE INSERT trigger (overridden here with explicit slugs)

BEGIN;

-- =====================================================================
-- Phase 2: Import 10 VC investors
-- =====================================================================

INSERT INTO investors (
  name, slug, description, investor_type, location, website,
  sector_focus, stage_focus, check_size_min, check_size_max,
  currently_investing, leads_deals, country, application_url,
  fund_size, year_fund_closed, portfolio_companies, details
) VALUES

-- 1. 1V (OneVentures)
(
  '1V (OneVentures)',
  '1v-oneventures',
  'Later-stage Australian VC managing AU$1B+ FUM across 7 funds since 2010. Founded by Michelle Deaker. Invests in high-growth Australian and US tech/healthcare companies.',
  'vc',
  'Sydney, NSW',
  'https://one-ventures.com.au',
  ARRAY['Technology','Healthcare','Deep Tech'],
  ARRAY['Growth','Series B+'],
  NULL, NULL,
  true, true,
  'Australia',
  'https://one-ventures.com.au/portfolio/',
  'AU$1B+ total FUM across 7 funds; Fund VII targeting AU$200M (launched Aug 2024)',
  'Fund VII: currently raising (launched Aug 2024); Fund I closed 2024',
  ARRAY['Vaxxas','BiVACOR','Employment Hero (exited)','Shippit','Phocas (exited Oct 2025)','Buildkite','Fleet Space','Lumary','Kepler Analytics','6clicks','AmazingCo','AMP','InDebted','Harmoney','ImmVirX','Zoomo','Blade Therapeutics','Axial Therapeutics','MyPass','HIVERY (acquired Jan 2025)'],
  '{"fund_size_raw":"AU$1B+ total FUM across 7 funds; Fund VII targeting AU$200M (launched Aug 2024)","year_fund_closed":"Fund VII: currently raising (launched Aug 2024); Fund I closed 2024","sources":{"fund_size":"https://dynamicbusiness.com/topics/news/oneventures-launches-its-seventh-fund-targeting-200-million.html","portfolio":"https://www.cbinsights.com/investor/oneventures","general":"https://one-ventures.com.au/"},"latest_news":[{"headline":"OneVentures launches seventh fund targeting AU$200M","url":"https://dynamicbusiness.com/topics/news/oneventures-launches-its-seventh-fund-targeting-200-million.html","date":"August 2024"},{"headline":"MyPass raises $7.5M Series A (1V portfolio)","url":"https://one-ventures.com.au/portfolio/","date":"February 2025"},{"headline":"AMP raises $12.57M Series B (1V portfolio)","url":"https://one-ventures.com.au/portfolio/","date":"March 2025"}],"corrections":"Fund size: broader than single fund figures — AU$1B+ total FUM across 7 funds. Fund VII launched Aug 2024 targeting AU$200M, still raising."}'::jsonb
),

-- 2. 77 Partners
(
  '77 Partners',
  '77-partners',
  'Early-stage VC backed by Silicon Valley-based Bee Partners. Runs the ''77 Challenge'' open application program for founders. Minimum investment AU$100k.',
  'vc',
  'Unknown',
  'https://www.77partners.vc',
  ARRAY['Technology'],
  ARRAY['Pre-seed','Seed'],
  100000, NULL,
  true, NULL,
  'Australia',
  'https://www.77partners.vc/challenge',
  NULL, NULL, NULL,
  '{"sources":{"fund_size":"https://www.77partners.vc/","portfolio":"https://www.77partners.vc/","general":"https://www.77partners.vc/challenge"},"latest_news":[{"headline":"77 Challenge open applications — invest from $100k","url":"https://www.77partners.vc/challenge","date":"Ongoing (as at April 2026)"}]}'::jsonb
),

-- 3. 808 Ventures
(
  '808 Ventures',
  '808-ventures',
  'Founded 2016 by Gary Macbeth and Art Caisse. Perth-based VC with global deal-flow via the Global Alliance Fund (USD$1B+ across 243 companies). Focus on frontier/deep tech.',
  'vc',
  'Claremont, WA',
  'https://www.808ventures.vc',
  ARRAY['Deep Tech','Space','Energy','CleanTech','HealthTech'],
  ARRAY['Early-stage','Growth'],
  NULL, NULL,
  true, NULL,
  'Australia',
  NULL,
  'Global Alliance Fund: USD$1B+ invested across 243 companies',
  'Founded 2016; ongoing',
  ARRAY['Rentberry','GuestReady','Byte Foods','Inhalio','Mmuze','Boundlss','Wellteq','Equal1','Oklo','Cemvita','Gold Hydrogen','Infinium','Circ','Quaise','Regent','Exowatt','Armada','Atomic Industries','Varda Space','D-Orbit','StretchSense','Partful'],
  '{"fund_size_raw":"Global Alliance Fund: USD$1B+ invested across 243 companies","year_fund_closed":"Founded 2016; ongoing","sources":{"fund_size":"https://venturecapitalarchive.com/venture-funds/808-ventures-808ventures-vc","portfolio":"https://inforcapital.com/companies/808-ventures/","general":"https://www.808ventures.vc/"},"latest_news":[{"headline":"808 Ventures Global Alliance Fund surpasses USD$1B invested across 243 companies","url":"https://venturecapitalarchive.com/venture-funds/808-ventures-808ventures-vc","date":"Not publicly dated"}],"corrections":"HQ: Claremont WA (Level 1, 28-36 Bay View Terrace, Claremont WA 6010) — not generic Perth."}'::jsonb
),

-- 4. AfterWork Ventures
(
  'AfterWork Ventures',
  'afterwork-ventures',
  'Community-powered early-stage VC. Network of 100+ tech operators who actively support portfolio. Sector-agnostic with focus on ANZ founders.',
  'vc',
  'Sydney, NSW',
  'https://www.afterwork.vc',
  ARRAY['Technology'],
  ARRAY['Pre-seed','Seed'],
  100000, 500000,
  true, true,
  'Australia',
  'https://www.afterwork.vc/apply',
  '~AU$18M (Fund III; first close AU$10M Aug 2021, target AU$30M)',
  'Fund III: first close August 2021 (still investing)',
  ARRAY['Cover Genius','Car Next Door','90 Seconds','Onfido','Hectre','Vitruvian','Send Payments','Stropro','OwnHome','Prophero','OfferFit','Klikit','Blakthumb','Cake Equity','Wagetap','Functionly','GridCognition','Swingvision','Insite AI','Samphire Neuroscience','Lyka','Switchboard','Cotiss','Zenphi','Primary','Aerotruth','Kanopi','Medoo','Everlab','Rocco','SearchEye','Avarni','Indemn','Turnto'],
  '{"fund_size_raw":"~AU$18M (Fund III; first close AU$10M Aug 2021, target AU$30M)","year_fund_closed":"Fund III: first close August 2021 (still investing)","sources":{"fund_size":"https://www.privateequitymedia.com.au/news/new-funds-and-fundraising/early-stage-venture-fund-reaches-10m-first-close/","portfolio":"https://www.afterwork.vc/portfolio","general":"https://www.afterwork.vc/"},"latest_news":[{"headline":"AfterWork Ventures Fund III reaches AU$10M first close","url":"https://www.privateequitymedia.com.au/news/new-funds-and-fundraising/early-stage-venture-fund-reaches-10m-first-close/","date":"August 2021"}],"corrections":"Cheque size upper bound: AU$500k (not just $100k minimum — website confirms range AU$100k-$500k)."}'::jsonb
),

-- 5. AgriZeroNZ
(
  'AgriZeroNZ',
  'agrizeroz',
  'NZ public-private partnership (50% NZ Crown/MPI + 50% industry: a2 Milk, ANZ, ASB, BNZ, ANZCO, Fonterra, Rabobank, Ravensdown, Silver Fern Farms, Synlait). Invests in technologies to reduce agricultural greenhouse gas emissions.',
  'vc',
  'Auckland, New Zealand',
  'https://www.agrizero.nz',
  ARRAY['Agricultural technology','Methane reduction','Emissions reduction'],
  ARRAY['Pre-seed','Seed','Series A','Series B'],
  1000000, 10000000,
  true, true,
  'New Zealand',
  'https://www.agrizero.nz/how-we-invest',
  'NZD$73.4M committed across 16 ventures (as at Dec 2025)',
  'Ongoing (public-private partnership established 2022)',
  ARRAY['Agteria Biotech','ArkeaBio','BiomEdit','Hoofprint Biome','Ruminant BioTech','Bovotica','Rumin8','BioLumic','Nbryo','Agroceuticals Products NZ'],
  '{"fund_size_raw":"NZD$73.4M committed across 16 ventures (as at Dec 2025)","year_fund_closed":"Ongoing (public-private partnership established 2022)","sources":{"fund_size":"https://www.datocms-assets.com/108924/1762374399-agrizeronz-year-in-review-2024-2025.pdf","portfolio":"https://www.cbinsights.com/investor/agrizeronz","general":"https://www.agrizero.nz/"},"latest_news":[{"headline":"AgriZeroNZ invests in Rumin8 to reduce livestock methane","url":"https://www.agrizero.nz/news","date":"March 2026"},{"headline":"BiomEdit raises Series B (AgriZeroNZ portfolio)","url":"https://www.agrizero.nz/news","date":"July 2025"},{"headline":"AgriZeroNZ Year in Review 2024-2025: NZD$73.4M committed across 16 ventures","url":"https://www.datocms-assets.com/108924/1762374399-agrizeronz-year-in-review-2024-2025.pdf","date":"December 2025"}]}'::jsonb
),

-- 6. Airtree Ventures (UPSERT — already exists in DB)
(
  'Airtree Ventures',
  'airtree-ventures',
  'Founded 2014 by Daniel Petre AO and Craig Blair. Australia''s largest VC by FUM (~AU$2B). LPs include Harvard Management Company, MetLife Investment Management, major Australian superannuation funds. 9 unicorns in portfolio.',
  'vc',
  'Surry Hills, NSW',
  'https://www.airtree.vc',
  ARRAY['Technology','SaaS','Fintech','Marketplace','Deep Tech'],
  ARRAY['Seed','Series A','Series B','Growth','Series C+'],
  500000, 30000000,
  true, true,
  'Australia',
  'https://www.airtree.vc/pitch',
  'AU$650M (Fund V: AU$250M Seed + AU$400M Growth, closed August 2025); total FUM ~AU$2B',
  'Fund V: August 2025',
  ARRAY['Canva','Employment Hero','Linktree','Immutable','Go1','Airwallex','Pet Circle','SafetyCulture','ProcurePro','Lorikeet'],
  '{"fund_size_raw":"AU$650M (Fund V: AU$250M Seed + AU$400M Growth, closed August 2025); total FUM ~AU$2B","year_fund_closed":"Fund V: August 2025","sources":{"fund_size":"https://www.airtree.vc/open-source-vc/introducing-airtree-fund-v","portfolio":"https://www.airtree.vc/portfolio","general":"https://www.bloomberg.com/news/articles/2025-08-07/global-investors-back-australian-startups-in-425-million-fund"},"latest_news":[{"headline":"Airtree closes AU$650M Fund V — Australia''s largest VC fund","url":"https://www.airtree.vc/open-source-vc/introducing-airtree-fund-v","date":"August 2025"},{"headline":"Airtree launches AU$250M Seed fund","url":"https://www.airtree.vc/open-source-vc/introducing-airtree-fund-v","date":"January 2025"},{"headline":"Lorikeet raises AU$54M Series A (Airtree portfolio)","url":"https://www.airtree.vc/portfolio","date":"August 2025"}],"corrections":"Fund V closed August 2025 (not just 2025); total FUM ~AU$2B."}'::jsonb
),

-- 7. Alberts Impact Ventures
(
  'Alberts Impact Ventures',
  'alberts-impact-ventures',
  'Impact-focused VC arm of the fifth-generation Albert family (founders of AC/DC''s original label). Led by Kirsty Albert. Invests in companies with measurable social/environmental impact alongside financial returns. 25% female-led capital invested (Dec 2025).',
  'vc',
  'Sydney, NSW',
  'https://www.alberts.co/impact-ventures/',
  ARRAY['Impact','Health','Sustainability','Future of Work','Education'],
  ARRAY['Pre-seed','Seed','Series A'],
  NULL, NULL,
  true, NULL,
  'Australia',
  'https://www.alberts.co/impact-ventures/',
  'AU$16M dedicated at launch (June 2021); total size not publicly updated',
  'June 2021 (launch); ongoing',
  ARRAY['Hatch','Harvest B','Samphire Neuroscience','Circle In (exited)','Mindset Health','Verve (acquired Nov 2023)','Abby Health','Conserving Beauty','RapidAIM','Throughline','Baymatob','Pivot','ULUU','MGA Thermal','Amber','Tixel','Surreal','Like Family','Sendle','AirRobe','Gridcog','CommandPost','Bygen'],
  '{"fund_size_raw":"AU$16M dedicated at launch (June 2021); total size not publicly updated","year_fund_closed":"June 2021 (launch); ongoing","sources":{"fund_size":"https://www.alberts.co/impact-ventures/","portfolio":"https://www.cbinsights.com/investor/alberts-impact-capital","general":"https://www.alberts.co/impact-ventures/"},"latest_news":[{"headline":"Alberts Impact Ventures portfolio: 25% female-led capital invested","url":"https://www.alberts.co/impact-ventures/","date":"December 2025"},{"headline":"Verve acquired (Alberts portfolio exit)","url":"https://www.cbinsights.com/investor/alberts-impact-capital","date":"November 2023"}]}'::jsonb
),

-- 8. Alchemy Ventures (website offline, limited data)
(
  'Alchemy Ventures',
  'alchemy-ventures',
  'Conditionally registered ESVCLP. ABN: 52 612 502 548, active from 20 May 2016. Website offline as at April 2026 (DNS error). Limited public information available.',
  'vc',
  'Sydney, NSW',
  NULL,
  ARRAY['Fintech','Proptech','Consumer Internet','Mining Tech','AgTech'],
  ARRAY['Early-stage'],
  NULL, NULL,
  NULL, NULL,
  'Australia',
  NULL,
  NULL,
  'Active from 20 May 2016 (ABN registered)',
  NULL,
  '{"year_fund_closed":"Active from 20 May 2016 (ABN registered)","sources":{"fund_size":"https://abr.business.gov.au/ABN/View/52612502548","portfolio":"https://privateequitylist.com/investors/alchemy-ventures","general":"https://www.bloomberg.com/profile/company/1417719D:AU"},"latest_news":[{"headline":"Alchemy Ventures conditionally registered as ESVCLP","url":"https://privateequitylist.com/investors/alchemy-ventures","date":"Not publicly dated"}],"corrections":"Sector focus broader than some listings: also includes Mining Tech and AgTech per Bloomberg/ABR. Website offline as at April 2026."}'::jsonb
),

-- 9. ALIAVIA Ventures
(
  'ALIAVIA Ventures',
  'aliavia-ventures',
  'Founded 2021 by Marisa Warren and Kate Vale. Invests in female-founded/led tech startups across ANZ and US. LPs include Tattarang (Forrest Family), Wollemi Capital (Robyn Denholm), Trawalla (Carol Schwartz), Dom Pym, Cynthia Scott. Runs ELEVACAO pre-accelerator.',
  'vc',
  'California, USA',
  'https://www.aliavia.vc',
  ARRAY['Female-founded technology'],
  ARRAY['Pre-seed','Seed'],
  NULL, NULL,
  true, true,
  'Australia',
  'https://www.aliavia.vc/apply',
  'Fund I: AU$13.5M (closed Oct 2023); Fund II: targeting ~AU$25M (currently raising)',
  'Fund I: October 2023; Fund II: raising',
  ARRAY['Eugene','HowToo','Othelia','GoFIGR','Ginko','Taelor','Loupe (exited to Stingray)','Human Health'],
  '{"fund_size_raw":"Fund I: AU$13.5M (closed Oct 2023); Fund II: targeting ~AU$25M (currently raising)","year_fund_closed":"Fund I: October 2023; Fund II: raising","sources":{"fund_size":"https://www.innovationaus.com/aliavia-closes-13-5m-female-focused-venture-fund/","portfolio":"https://techcrunch.com/2023/10/09/aliavia-ventures/","general":"https://billiondollarmoves.com/podcast-episode/why-australias-leading-family-offices-are-backing-aliavia-ventures-cross-border-vc-strategy-w-marisa-warren/"},"latest_news":[{"headline":"ALIAVIA Ventures Fund II targeting AU$25M — currently raising","url":"https://billiondollarmoves.com/podcast-episode/why-australias-leading-family-offices-are-backing-aliavia-ventures-cross-border-vc-strategy-w-marisa-warren/","date":"July 2025"},{"headline":"ALIAVIA LP/Founder Summit — Laguna Beach","url":"https://www.aliavia.vc/","date":"October 2025"},{"headline":"ALIAVIA closes AU$13.5M Fund I — female-focused venture fund","url":"https://www.innovationaus.com/aliavia-closes-13-5m-female-focused-venture-fund/","date":"October 2023"}],"corrections":"Fund I = AU$13.5M (closed Oct 2023). Fund II targeting ~AU$25M, currently raising."}'::jsonb
),

-- 10. Altered Capital
(
  'Altered Capital',
  'altered-capital',
  'Founded 2022 by McGregor Fea, Craig Mawdsley, and Marcus Traill. Auckland-based growth VC investing in NZ-connected companies with global ambition. Fund I tracking >40% gross IRR. Partnership with Pie Funds announced Feb 2026.',
  'vc',
  'Auckland, New Zealand',
  'https://www.alteredcapital.com',
  ARRAY['Technology','SaaS','Fintech','Maritime','EdTech','Healthcare','Financial Services'],
  ARRAY['Series A','Series B'],
  NULL, NULL,
  true, true,
  'New Zealand',
  'https://www.alteredcapital.com/contact',
  'Fund I: NZD$100M; Fund II: USD$100M (raising; NZGCP Elevate committed USD$25M Feb 2026). Total committed: $350M+ across 5+ funds.',
  'Fund I: closed (11 portfolio companies); Fund II: currently raising',
  ARRAY['Crimson Education','Starboard Maritime Intelligence','Emerge','Contented','Oritain','ZILO','First Table','Oraame','Starling Bank'],
  '{"fund_size_raw":"Fund I: NZD$100M; Fund II: USD$100M (raising; NZGCP Elevate committed USD$25M Feb 2026). Total committed: $350M+ across 5+ funds.","year_fund_closed":"Fund I: closed (11 portfolio companies); Fund II: currently raising","sources":{"fund_size":"https://cfotech.co.nz/story/elevate-backs-altered-capital-s-usd-25m-growth-fund-push","portfolio":"https://www.alteredcapital.com/case-studies/starboard-series-a","general":"https://www.goodreturns.co.nz/article/976525254/pie-adds-new-ingredient-to-its-funds.html"},"latest_news":[{"headline":"NZGCP Elevate commits USD$25M to Altered Capital Fund II","url":"https://cfotech.co.nz/story/elevate-backs-altered-capital-s-usd-25m-growth-fund-push","date":"February 2026"},{"headline":"Altered Capital partners with Pie Funds","url":"https://www.goodreturns.co.nz/article/976525254/pie-adds-new-ingredient-to-its-funds.html","date":"February 2026"},{"headline":"Contented raises NZ$4.1M seed (Altered Capital portfolio)","url":"https://www.alteredcapital.com/case-studies/","date":"February 2026"}],"corrections":"Stage focus should be primarily Series A/B. Fund II is USD$100M (not NZD)."}'::jsonb
)

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  investor_type = EXCLUDED.investor_type,
  location = EXCLUDED.location,
  website = EXCLUDED.website,
  sector_focus = EXCLUDED.sector_focus,
  stage_focus = EXCLUDED.stage_focus,
  check_size_min = EXCLUDED.check_size_min,
  check_size_max = EXCLUDED.check_size_max,
  currently_investing = EXCLUDED.currently_investing,
  leads_deals = EXCLUDED.leads_deals,
  country = EXCLUDED.country,
  application_url = EXCLUDED.application_url,
  fund_size = EXCLUDED.fund_size,
  year_fund_closed = EXCLUDED.year_fund_closed,
  portfolio_companies = EXCLUDED.portfolio_companies,
  details = EXCLUDED.details,
  updated_at = now();

-- =====================================================================
-- Phase 3: Backfill existing VCs with new column defaults
-- =====================================================================

-- Promote existing jsonb data to new top-level columns for 5 existing VCs
UPDATE investors
SET
  country = 'Australia',
  currently_investing = true,
  fund_size = details->>'fund_size',
  portfolio_companies = CASE
    WHEN details->'portfolio_companies' IS NOT NULL
    THEN ARRAY(SELECT jsonb_array_elements_text(details->'portfolio_companies'))
    ELSE NULL
  END
WHERE investor_type = 'vc'
AND slug NOT IN (
  '1v-oneventures','77-partners','808-ventures','afterwork-ventures',
  'agrizeroz','airtree-ventures','alberts-impact-ventures',
  'alchemy-ventures','aliavia-ventures','altered-capital'
);

-- Set default country for all records that have null country
UPDATE investors SET country = 'Australia' WHERE country IS NULL;

COMMIT;
