-- Create the linkedin_industries reference table
CREATE TABLE IF NOT EXISTS public.linkedin_industries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sector text NOT NULL,
  industry_group text NOT NULL,
  sub_industry text,
  display_name text NOT NULL,
  slug text NOT NULL UNIQUE,
  sector_slug text NOT NULL,
  display_order int NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_linkedin_industries_sector ON public.linkedin_industries (sector);
CREATE INDEX IF NOT EXISTS idx_linkedin_industries_industry_group ON public.linkedin_industries (industry_group);
CREATE INDEX IF NOT EXISTS idx_linkedin_industries_sector_slug ON public.linkedin_industries (sector_slug);
CREATE INDEX IF NOT EXISTS idx_linkedin_industries_display_name ON public.linkedin_industries (display_name);

-- Enable RLS (public read, admin write)
ALTER TABLE public.linkedin_industries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read linkedin_industries"
  ON public.linkedin_industries FOR SELECT
  USING (true);

-- Seed the table
INSERT INTO public.linkedin_industries (sector, industry_group, sub_industry, display_name, slug, sector_slug, display_order)
VALUES
  ('Accommodation and Food Services', 'Food and Beverage Services', NULL, 'Food and Beverage Services', 'food-and-beverage-services', 'accommodation-and-food-services', 1),
  ('Accommodation and Food Services', 'Food and Beverage Services', 'Bars, Taverns, and Nightclubs', 'Bars, Taverns, and Nightclubs', 'bars-taverns-and-nightclubs', 'accommodation-and-food-services', 2),
  ('Accommodation and Food Services', 'Food and Beverage Services', 'Caterers', 'Caterers', 'caterers', 'accommodation-and-food-services', 3),
  ('Accommodation and Food Services', 'Food and Beverage Services', 'Mobile Food Services', 'Mobile Food Services', 'mobile-food-services', 'accommodation-and-food-services', 4),
  ('Accommodation and Food Services', 'Food and Beverage Services', 'Restaurants', 'Restaurants', 'restaurants', 'accommodation-and-food-services', 5),
  ('Accommodation and Food Services', 'Hospitality', NULL, 'Hospitality', 'hospitality', 'accommodation-and-food-services', 6),
  ('Accommodation and Food Services', 'Hospitality', 'Bed-and-Breakfasts, Hostels, Homestays', 'Bed-and-Breakfasts, Hostels, Homestays', 'bed-and-breakfasts-hostels-homestays', 'accommodation-and-food-services', 7),
  ('Accommodation and Food Services', 'Hospitality', 'Hotels and Motels', 'Hotels and Motels', 'hotels-and-motels', 'accommodation-and-food-services', 8),
  ('Administrative and Support Services', 'Collection Agencies', NULL, 'Collection Agencies', 'collection-agencies', 'administrative-and-support-services', 9),
  ('Administrative and Support Services', 'Events Services', NULL, 'Events Services', 'events-services', 'administrative-and-support-services', 10),
  ('Administrative and Support Services', 'Facilities Services', NULL, 'Facilities Services', 'facilities-services', 'administrative-and-support-services', 11),
  ('Administrative and Support Services', 'Fundraising', NULL, 'Fundraising', 'fundraising', 'administrative-and-support-services', 12),
  ('Administrative and Support Services', 'Office Administration', NULL, 'Office Administration', 'office-administration', 'administrative-and-support-services', 13),
  ('Administrative and Support Services', 'Security and Investigations', NULL, 'Security and Investigations', 'security-and-investigations', 'administrative-and-support-services', 14),
  ('Administrative and Support Services', 'Staffing and Recruiting', NULL, 'Staffing and Recruiting', 'staffing-and-recruiting', 'administrative-and-support-services', 15),
  ('Administrative and Support Services', 'Telephone Call Centers', NULL, 'Telephone Call Centers', 'telephone-call-centers', 'administrative-and-support-services', 16),
  ('Administrative and Support Services', 'Translation and Localization', NULL, 'Translation and Localization', 'translation-and-localization', 'administrative-and-support-services', 17),
  ('Administrative and Support Services', 'Travel Arrangements', NULL, 'Travel Arrangements', 'travel-arrangements', 'administrative-and-support-services', 18),
  ('Administrative and Support Services', 'Writing and Editing', NULL, 'Writing and Editing', 'writing-and-editing', 'administrative-and-support-services', 19),
  ('Construction', 'Building Construction', NULL, 'Building Construction', 'building-construction', 'construction', 20),
  ('Construction', 'Civil Engineering', NULL, 'Civil Engineering', 'civil-engineering', 'construction', 21),
  ('Construction', 'Specialty Trade Contractors', NULL, 'Specialty Trade Contractors', 'specialty-trade-contractors', 'construction', 22),
  ('Consumer Services', 'Civic and Social Organizations', NULL, 'Civic and Social Organizations', 'civic-and-social-organizations', 'consumer-services', 23),
  ('Consumer Services', 'Household Services', NULL, 'Household Services', 'household-services', 'consumer-services', 24),
  ('Consumer Services', 'Non-profit Organizations', NULL, 'Non-profit Organizations', 'non-profit-organizations', 'consumer-services', 25),
  ('Consumer Services', 'Personal and Laundry Services', NULL, 'Personal and Laundry Services', 'personal-and-laundry-services', 'consumer-services', 26),
  ('Consumer Services', 'Philanthropic Fundraising Services', NULL, 'Philanthropic Fundraising Services', 'philanthropic-fundraising-services', 'consumer-services', 27),
  ('Consumer Services', 'Religious Institutions', NULL, 'Religious Institutions', 'religious-institutions', 'consumer-services', 28),
  ('Consumer Services', 'Repair and Maintenance', NULL, 'Repair and Maintenance', 'repair-and-maintenance', 'consumer-services', 29),
  ('Education', 'E-Learning Providers', NULL, 'E-Learning Providers', 'e-learning-providers', 'education', 30),
  ('Education', 'Higher Education', NULL, 'Higher Education', 'higher-education', 'education', 31),
  ('Education', 'Primary and Secondary Education', NULL, 'Primary and Secondary Education', 'primary-and-secondary-education', 'education', 32),
  ('Education', 'Professional Training and Coaching', NULL, 'Professional Training and Coaching', 'professional-training-and-coaching', 'education', 33),
  ('Education', 'Technical and Vocational Training', NULL, 'Technical and Vocational Training', 'technical-and-vocational-training', 'education', 34),
  ('Entertainment Providers', 'Artists and Writers', NULL, 'Artists and Writers', 'artists-and-writers', 'entertainment-providers', 35),
  ('Entertainment Providers', 'Museums, Historical Sites, and Zoos', NULL, 'Museums, Historical Sites, and Zoos', 'museums-historical-sites-and-zoos', 'entertainment-providers', 36),
  ('Entertainment Providers', 'Museums, Historical Sites, and Zoos', 'Historical Sites', 'Historical Sites', 'historical-sites', 'entertainment-providers', 37),
  ('Entertainment Providers', 'Museums, Historical Sites, and Zoos', 'Museums', 'Museums', 'museums', 'entertainment-providers', 38),
  ('Entertainment Providers', 'Museums, Historical Sites, and Zoos', 'Zoos and Botanical Gardens', 'Zoos and Botanical Gardens', 'zoos-and-botanical-gardens', 'entertainment-providers', 39),
  ('Entertainment Providers', 'Musicians', NULL, 'Musicians', 'musicians', 'entertainment-providers', 40),
  ('Entertainment Providers', 'Performing Arts and Spectator Sports', NULL, 'Performing Arts and Spectator Sports', 'performing-arts-and-spectator-sports', 'entertainment-providers', 41),
  ('Entertainment Providers', 'Performing Arts and Spectator Sports', 'Circuses and Magic Shows', 'Circuses and Magic Shows', 'circuses-and-magic-shows', 'entertainment-providers', 42),
  ('Entertainment Providers', 'Performing Arts and Spectator Sports', 'Dance Companies', 'Dance Companies', 'dance-companies', 'entertainment-providers', 43),
  ('Entertainment Providers', 'Performing Arts and Spectator Sports', 'Performing Arts', 'Performing Arts', 'performing-arts', 'entertainment-providers', 44),
  ('Entertainment Providers', 'Performing Arts and Spectator Sports', 'Theater Companies', 'Theater Companies', 'theater-companies', 'entertainment-providers', 45),
  ('Entertainment Providers', 'Recreational Facilities', NULL, 'Recreational Facilities', 'recreational-facilities', 'entertainment-providers', 46),
  ('Entertainment Providers', 'Recreational Facilities', 'Amusement Parks and Arcades', 'Amusement Parks and Arcades', 'amusement-parks-and-arcades', 'entertainment-providers', 47),
  ('Entertainment Providers', 'Recreational Facilities', 'Gambling Facilities and Casinos', 'Gambling Facilities and Casinos', 'gambling-facilities-and-casinos', 'entertainment-providers', 48),
  ('Entertainment Providers', 'Recreational Facilities', 'Golf Courses and Country Clubs', 'Golf Courses and Country Clubs', 'golf-courses-and-country-clubs', 'entertainment-providers', 49),
  ('Entertainment Providers', 'Recreational Facilities', 'Skiing Facilities', 'Skiing Facilities', 'skiing-facilities', 'entertainment-providers', 50),
  ('Entertainment Providers', 'Recreational Facilities', 'Wellness and Fitness Services', 'Wellness and Fitness Services', 'wellness-and-fitness-services', 'entertainment-providers', 51),
  ('Entertainment Providers', 'Spectator Sports', NULL, 'Spectator Sports', 'spectator-sports', 'entertainment-providers', 52),
  ('Entertainment Providers', 'Spectator Sports', 'Racetracks', 'Racetracks', 'racetracks', 'entertainment-providers', 53),
  ('Entertainment Providers', 'Spectator Sports', 'Sports Teams and Clubs', 'Sports Teams and Clubs', 'sports-teams-and-clubs', 'entertainment-providers', 54),
  ('Farming, Ranching, Forestry', 'Farming', NULL, 'Farming', 'farming', 'farming-ranching-forestry', 55),
  ('Farming, Ranching, Forestry', 'Ranching and Fisheries', NULL, 'Ranching and Fisheries', 'ranching-and-fisheries', 'farming-ranching-forestry', 56),
  ('Farming, Ranching, Forestry', 'Forestry and Logging', NULL, 'Forestry and Logging', 'forestry-and-logging', 'farming-ranching-forestry', 57),
  ('Financial Services', 'Capital Markets', NULL, 'Capital Markets', 'capital-markets', 'financial-services', 58),
  ('Financial Services', 'Capital Markets', 'Investment Advice', 'Investment Advice', 'investment-advice', 'financial-services', 59),
  ('Financial Services', 'Capital Markets', 'Investment Banking', 'Investment Banking', 'investment-banking', 'financial-services', 60),
  ('Financial Services', 'Capital Markets', 'Investment Management', 'Investment Management', 'investment-management', 'financial-services', 61),
  ('Financial Services', 'Capital Markets', 'Securities and Commodity Exchanges', 'Securities and Commodity Exchanges', 'securities-and-commodity-exchanges', 'financial-services', 62),
  ('Financial Services', 'Capital Markets', 'Venture Capital and Private Equity Principals', 'Venture Capital and Private Equity Principals', 'venture-capital-and-private-equity-principals', 'financial-services', 63),
  ('Financial Services', 'Credit Intermediation', NULL, 'Credit Intermediation', 'credit-intermediation', 'financial-services', 64),
  ('Financial Services', 'Credit Intermediation', 'Banking', 'Banking', 'banking', 'financial-services', 65),
  ('Financial Services', 'Credit Intermediation', 'International Trade and Development', 'International Trade and Development', 'international-trade-and-development', 'financial-services', 66),
  ('Financial Services', 'Credit Intermediation', 'Loan Brokers', 'Loan Brokers', 'loan-brokers', 'financial-services', 67),
  ('Financial Services', 'Credit Intermediation', 'Savings Institutions', 'Savings Institutions', 'savings-institutions', 'financial-services', 68),
  ('Financial Services', 'Funds and Trusts', NULL, 'Funds and Trusts', 'funds-and-trusts', 'financial-services', 69),
  ('Financial Services', 'Funds and Trusts', 'Insurance and Employee Benefit Funds', 'Insurance and Employee Benefit Funds', 'insurance-and-employee-benefit-funds', 'financial-services', 70),
  ('Financial Services', 'Funds and Trusts', 'Pension Funds', 'Pension Funds', 'pension-funds', 'financial-services', 71),
  ('Financial Services', 'Funds and Trusts', 'Trusts and Estates', 'Trusts and Estates', 'trusts-and-estates', 'financial-services', 72),
  ('Financial Services', 'Insurance', NULL, 'Insurance', 'insurance', 'financial-services', 73),
  ('Financial Services', 'Insurance', 'Claims Adjusting, Actuarial Services', 'Claims Adjusting, Actuarial Services', 'claims-adjusting-actuarial-services', 'financial-services', 74),
  ('Financial Services', 'Insurance', 'Insurance Agencies and Brokerages', 'Insurance Agencies and Brokerages', 'insurance-agencies-and-brokerages', 'financial-services', 75),
  ('Financial Services', 'Insurance', 'Insurance Carriers', 'Insurance Carriers', 'insurance-carriers', 'financial-services', 76),
  ('Government Administration', 'Administration of Justice', NULL, 'Administration of Justice', 'administration-of-justice', 'government-administration', 77),
  ('Government Administration', 'Administration of Justice', 'Correctional Institutions', 'Correctional Institutions', 'correctional-institutions', 'government-administration', 78),
  ('Government Administration', 'Administration of Justice', 'Courts of Law', 'Courts of Law', 'courts-of-law', 'government-administration', 79),
  ('Government Administration', 'Administration of Justice', 'Fire Protection', 'Fire Protection', 'fire-protection', 'government-administration', 80),
  ('Government Administration', 'Administration of Justice', 'Law Enforcement', 'Law Enforcement', 'law-enforcement', 'government-administration', 81),
  ('Government Administration', 'Administration of Justice', 'Public Safety', 'Public Safety', 'public-safety', 'government-administration', 82),
  ('Government Administration', 'Economic Programs', NULL, 'Economic Programs', 'economic-programs', 'government-administration', 83),
  ('Government Administration', 'Economic Programs', 'Transportation Programs', 'Transportation Programs', 'transportation-programs', 'government-administration', 84),
  ('Government Administration', 'Economic Programs', 'Utilities Administration', 'Utilities Administration', 'utilities-administration', 'government-administration', 85),
  ('Government Administration', 'Environmental Quality Programs', NULL, 'Environmental Quality Programs', 'environmental-quality-programs', 'government-administration', 86),
  ('Government Administration', 'Environmental Quality Programs', 'Air, Water, and Waste Program Management', 'Air, Water, and Waste Program Management', 'air-water-and-waste-program-management', 'government-administration', 87),
  ('Government Administration', 'Environmental Quality Programs', 'Conservation Programs', 'Conservation Programs', 'conservation-programs', 'government-administration', 88),
  ('Government Administration', 'Health and Human Services', NULL, 'Health and Human Services', 'health-and-human-services', 'government-administration', 89),
  ('Government Administration', 'Health and Human Services', 'Education Administration Programs', 'Education Administration Programs', 'education-administration-programs', 'government-administration', 90),
  ('Government Administration', 'Health and Human Services', 'Public Assistance Programs', 'Public Assistance Programs', 'public-assistance-programs', 'government-administration', 91),
  ('Government Administration', 'Health and Human Services', 'Public Health', 'Public Health', 'public-health', 'government-administration', 92),
  ('Government Administration', 'Housing and Community Development', NULL, 'Housing and Community Development', 'housing-and-community-development', 'government-administration', 93),
  ('Government Administration', 'Housing and Community Development', 'Community Development and Urban Planning', 'Community Development and Urban Planning', 'community-development-and-urban-planning', 'government-administration', 94),
  ('Government Administration', 'Housing and Community Development', 'Housing Programs', 'Housing Programs', 'housing-programs', 'government-administration', 95),
  ('Government Administration', 'Military and International Affairs', NULL, 'Military and International Affairs', 'military-and-international-affairs', 'government-administration', 96),
  ('Government Administration', 'Military and International Affairs', 'Armed Forces', 'Armed Forces', 'armed-forces', 'government-administration', 97),
  ('Government Administration', 'Military and International Affairs', 'International Affairs', 'International Affairs', 'international-affairs', 'government-administration', 98),
  ('Government Administration', 'Public Policy', NULL, 'Public Policy', 'public-policy', 'government-administration', 99),
  ('Government Administration', 'Public Policy Offices', NULL, 'Public Policy Offices', 'public-policy-offices', 'government-administration', 100),
  ('Government Administration', 'Public Policy Offices', 'Executive Offices', 'Executive Offices', 'executive-offices', 'government-administration', 101),
  ('Government Administration', 'Public Policy Offices', 'Legislative Offices', 'Legislative Offices', 'legislative-offices', 'government-administration', 102),
  ('Government Administration', 'Space Research and Technology', NULL, 'Space Research and Technology', 'space-research-and-technology', 'government-administration', 103),
  ('Holding Companies', 'Holding Companies', NULL, 'Holding Companies', 'holding-companies', 'holding-companies', 104),
  ('Hospitals and Health Care', 'Community Services', NULL, 'Community Services', 'community-services', 'hospitals-and-health-care', 105),
  ('Hospitals and Health Care', 'Hospitals, Individual and Family Services', NULL, 'Hospitals, Individual and Family Services', 'hospitals-individual-and-family-services', 'hospitals-and-health-care', 106),
  ('Hospitals and Health Care', 'Medical Practices', NULL, 'Medical Practices', 'medical-practices', 'hospitals-and-health-care', 107),
  ('Hospitals and Health Care', 'Nursing Homes and Residential Care Facilities', NULL, 'Nursing Homes and Residential Care Facilities', 'nursing-homes-and-residential-care-facilities', 'hospitals-and-health-care', 108),
  ('Manufacturing', 'Apparel Manufacturing', NULL, 'Apparel Manufacturing', 'apparel-manufacturing', 'manufacturing', 109),
  ('Manufacturing', 'Apparel Manufacturing', 'Fashion Accessories Manufacturing', 'Fashion Accessories Manufacturing', 'fashion-accessories-manufacturing', 'manufacturing', 110),
  ('Manufacturing', 'Appliances, Electrical, and Electronics Manufacturing', NULL, 'Appliances, Electrical, and Electronics Manufacturing', 'appliances-electrical-and-electronics-manufacturing', 'manufacturing', 111),
  ('Manufacturing', 'Appliances, Electrical, and Electronics Manufacturing', 'Electric Lighting Equipment Manufacturing', 'Electric Lighting Equipment Manufacturing', 'electric-lighting-equipment-manufacturing', 'manufacturing', 112),
  ('Manufacturing', 'Appliances, Electrical, and Electronics Manufacturing', 'Electrical Equipment Manufacturing', 'Electrical Equipment Manufacturing', 'electrical-equipment-manufacturing', 'manufacturing', 113),
  ('Manufacturing', 'Appliances, Electrical, and Electronics Manufacturing', 'Household Appliance Manufacturing', 'Household Appliance Manufacturing', 'household-appliance-manufacturing', 'manufacturing', 114),
  ('Manufacturing', 'Chemical Manufacturing', NULL, 'Chemical Manufacturing', 'chemical-manufacturing', 'manufacturing', 115),
  ('Manufacturing', 'Chemical Manufacturing', 'Agricultural Chemical Manufacturing', 'Agricultural Chemical Manufacturing', 'agricultural-chemical-manufacturing', 'manufacturing', 116),
  ('Manufacturing', 'Chemical Manufacturing', 'Artificial Rubber and Synthetic Fiber Manufacturing', 'Artificial Rubber and Synthetic Fiber Manufacturing', 'artificial-rubber-and-synthetic-fiber-manufacturing', 'manufacturing', 117),
  ('Manufacturing', 'Chemical Manufacturing', 'Chemical Raw Materials Manufacturing', 'Chemical Raw Materials Manufacturing', 'chemical-raw-materials-manufacturing', 'manufacturing', 118),
  ('Manufacturing', 'Chemical Manufacturing', 'Paint, Coating, and Adhesive Manufacturing', 'Paint, Coating, and Adhesive Manufacturing', 'paint-coating-and-adhesive-manufacturing', 'manufacturing', 119),
  ('Manufacturing', 'Chemical Manufacturing', 'Personal Care Product Manufacturing', 'Personal Care Product Manufacturing', 'personal-care-product-manufacturing', 'manufacturing', 120),
  ('Manufacturing', 'Chemical Manufacturing', 'Pharmaceutical Manufacturing', 'Pharmaceutical Manufacturing', 'pharmaceutical-manufacturing', 'manufacturing', 121),
  ('Manufacturing', 'Chemical Manufacturing', 'Soap and Cleaning Product Manufacturing', 'Soap and Cleaning Product Manufacturing', 'soap-and-cleaning-product-manufacturing', 'manufacturing', 122),
  ('Manufacturing', 'Computers and Electronics Manufacturing', NULL, 'Computers and Electronics Manufacturing', 'computers-and-electronics-manufacturing', 'manufacturing', 123),
  ('Manufacturing', 'Computers and Electronics Manufacturing', 'Audio and Video Equipment Manufacturing', 'Audio and Video Equipment Manufacturing', 'audio-and-video-equipment-manufacturing', 'manufacturing', 124),
  ('Manufacturing', 'Computers and Electronics Manufacturing', 'Communications Equipment Manufacturing', 'Communications Equipment Manufacturing', 'communications-equipment-manufacturing', 'manufacturing', 125),
  ('Manufacturing', 'Computers and Electronics Manufacturing', 'Computer Hardware Manufacturing', 'Computer Hardware Manufacturing', 'computer-hardware-manufacturing', 'manufacturing', 126),
  ('Manufacturing', 'Computers and Electronics Manufacturing', 'Magnetic and Optical Media Manufacturing', 'Magnetic and Optical Media Manufacturing', 'magnetic-and-optical-media-manufacturing', 'manufacturing', 127),
  ('Manufacturing', 'Computers and Electronics Manufacturing', 'Measuring and Control Instrument Manufacturing', 'Measuring and Control Instrument Manufacturing', 'measuring-and-control-instrument-manufacturing', 'manufacturing', 128),
  ('Manufacturing', 'Computers and Electronics Manufacturing', 'Semiconductor Manufacturing', 'Semiconductor Manufacturing', 'semiconductor-manufacturing', 'manufacturing', 129),
  ('Manufacturing', 'Fabricated Metal Products', NULL, 'Fabricated Metal Products', 'fabricated-metal-products', 'manufacturing', 130),
  ('Manufacturing', 'Fabricated Metal Products', 'Architectural and Structural Metal Manufacturing', 'Architectural and Structural Metal Manufacturing', 'architectural-and-structural-metal-manufacturing', 'manufacturing', 131),
  ('Manufacturing', 'Fabricated Metal Products', 'Boilers, Tanks, and Shipping Container Manufacturing', 'Boilers, Tanks, and Shipping Container Manufacturing', 'boilers-tanks-and-shipping-container-manufacturing', 'manufacturing', 132),
  ('Manufacturing', 'Fabricated Metal Products', 'Construction Hardware Manufacturing', 'Construction Hardware Manufacturing', 'construction-hardware-manufacturing', 'manufacturing', 133),
  ('Manufacturing', 'Fabricated Metal Products', 'Cutlery and Handtool Manufacturing', 'Cutlery and Handtool Manufacturing', 'cutlery-and-handtool-manufacturing', 'manufacturing', 134),
  ('Manufacturing', 'Fabricated Metal Products', 'Metal Treatments', 'Metal Treatments', 'metal-treatments', 'manufacturing', 135),
  ('Manufacturing', 'Fabricated Metal Products', 'Metal Valve, Ball, and Roller Manufacturing', 'Metal Valve, Ball, and Roller Manufacturing', 'metal-valve-ball-and-roller-manufacturing', 'manufacturing', 136),
  ('Manufacturing', 'Fabricated Metal Products', 'Spring and Wire Product Manufacturing', 'Spring and Wire Product Manufacturing', 'spring-and-wire-product-manufacturing', 'manufacturing', 137),
  ('Manufacturing', 'Fabricated Metal Products', 'Turned Products and Fastener Manufacturing', 'Turned Products and Fastener Manufacturing', 'turned-products-and-fastener-manufacturing', 'manufacturing', 138),
  ('Manufacturing', 'Food and Beverage Manufacturing', NULL, 'Food and Beverage Manufacturing', 'food-and-beverage-manufacturing', 'manufacturing', 139),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Animal Feed Manufacturing', 'Animal Feed Manufacturing', 'animal-feed-manufacturing', 'manufacturing', 140),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Baked Goods Manufacturing', 'Baked Goods Manufacturing', 'baked-goods-manufacturing', 'manufacturing', 141),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Beverage Manufacturing', 'Beverage Manufacturing', 'beverage-manufacturing', 'manufacturing', 142),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Dairy Product Manufacturing', 'Dairy Product Manufacturing', 'dairy-product-manufacturing', 'manufacturing', 143),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Fruit and Vegetable Preserves Manufacturing', 'Fruit and Vegetable Preserves Manufacturing', 'fruit-and-vegetable-preserves-manufacturing', 'manufacturing', 144),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Meat Products Manufacturing', 'Meat Products Manufacturing', 'meat-products-manufacturing', 'manufacturing', 145),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Seafood Product Manufacturing', 'Seafood Product Manufacturing', 'seafood-product-manufacturing', 'manufacturing', 146),
  ('Manufacturing', 'Food and Beverage Manufacturing', 'Sugar and Confectionery Product Manufacturing', 'Sugar and Confectionery Product Manufacturing', 'sugar-and-confectionery-product-manufacturing', 'manufacturing', 147),
  ('Manufacturing', 'Furniture and Home Furnishings Manufacturing', NULL, 'Furniture and Home Furnishings Manufacturing', 'furniture-and-home-furnishings-manufacturing', 'manufacturing', 148),
  ('Manufacturing', 'Furniture and Home Furnishings Manufacturing', 'Household and Institutional Furniture Manufacturing', 'Household and Institutional Furniture Manufacturing', 'household-and-institutional-furniture-manufacturing', 'manufacturing', 149),
  ('Manufacturing', 'Furniture and Home Furnishings Manufacturing', 'Mattress and Blinds Manufacturing', 'Mattress and Blinds Manufacturing', 'mattress-and-blinds-manufacturing', 'manufacturing', 150),
  ('Manufacturing', 'Furniture and Home Furnishings Manufacturing', 'Office Furniture and Fixtures Manufacturing', 'Office Furniture and Fixtures Manufacturing', 'office-furniture-and-fixtures-manufacturing', 'manufacturing', 151),
  ('Manufacturing', 'Glass, Ceramics and Concrete Manufacturing', NULL, 'Glass, Ceramics and Concrete Manufacturing', 'glass-ceramics-and-concrete-manufacturing', 'manufacturing', 152),
  ('Manufacturing', 'Glass, Ceramics and Concrete Manufacturing', 'Abrasives and Nonmetallic Minerals Manufacturing', 'Abrasives and Nonmetallic Minerals Manufacturing', 'abrasives-and-nonmetallic-minerals-manufacturing', 'manufacturing', 153),
  ('Manufacturing', 'Glass, Ceramics and Concrete Manufacturing', 'Clay and Refractory Products Manufacturing', 'Clay and Refractory Products Manufacturing', 'clay-and-refractory-products-manufacturing', 'manufacturing', 154),
  ('Manufacturing', 'Glass, Ceramics and Concrete Manufacturing', 'Glass Product Manufacturing', 'Glass Product Manufacturing', 'glass-product-manufacturing', 'manufacturing', 155),
  ('Manufacturing', 'Glass, Ceramics and Concrete Manufacturing', 'Lime and Gypsum Products Manufacturing', 'Lime and Gypsum Products Manufacturing', 'lime-and-gypsum-products-manufacturing', 'manufacturing', 156),
  ('Manufacturing', 'Leather Product Manufacturing', NULL, 'Leather Product Manufacturing', 'leather-product-manufacturing', 'manufacturing', 157),
  ('Manufacturing', 'Leather Product Manufacturing', 'Footwear Manufacturing', 'Footwear Manufacturing', 'footwear-manufacturing', 'manufacturing', 158),
  ('Manufacturing', 'Leather Product Manufacturing', 'Women''s Handbag Manufacturing', 'Women''s Handbag Manufacturing', 'women-s-handbag-manufacturing', 'manufacturing', 159),
  ('Manufacturing', 'Machinery Manufacturing', NULL, 'Machinery Manufacturing', 'machinery-manufacturing', 'manufacturing', 160),
  ('Manufacturing', 'Machinery Manufacturing', 'Agriculture, Construction, Mining Machinery Manufacturing', 'Agriculture, Construction, Mining Machinery Manufacturing', 'agriculture-construction-mining-machinery-manufacturing', 'manufacturing', 161),
  ('Manufacturing', 'Machinery Manufacturing', 'Automation Machinery Manufacturing', 'Automation Machinery Manufacturing', 'automation-machinery-manufacturing', 'manufacturing', 162),
  ('Manufacturing', 'Machinery Manufacturing', 'Commercial and Service Industry Machinery Manufacturing', 'Commercial and Service Industry Machinery Manufacturing', 'commercial-and-service-industry-machinery-manufacturing', 'manufacturing', 163),
  ('Manufacturing', 'Machinery Manufacturing', 'Engines and Power Transmission Equipment Manufacturing', 'Engines and Power Transmission Equipment Manufacturing', 'engines-and-power-transmission-equipment-manufacturing', 'manufacturing', 164),
  ('Manufacturing', 'Machinery Manufacturing', 'HVAC and Refrigeration Equipment Manufacturing', 'HVAC and Refrigeration Equipment Manufacturing', 'hvac-and-refrigeration-equipment-manufacturing', 'manufacturing', 165),
  ('Manufacturing', 'Machinery Manufacturing', 'Industrial Machinery Manufacturing', 'Industrial Machinery Manufacturing', 'industrial-machinery-manufacturing', 'manufacturing', 166),
  ('Manufacturing', 'Machinery Manufacturing', 'Metalworking Machinery Manufacturing', 'Metalworking Machinery Manufacturing', 'metalworking-machinery-manufacturing', 'manufacturing', 167),
  ('Manufacturing', 'Medical Equipment Manufacturing', NULL, 'Medical Equipment Manufacturing', 'medical-equipment-manufacturing', 'manufacturing', 168),
  ('Manufacturing', 'Oil and Coal Product Manufacturing', NULL, 'Oil and Coal Product Manufacturing', 'oil-and-coal-product-manufacturing', 'manufacturing', 169),
  ('Manufacturing', 'Paper and Forest Product Manufacturing', NULL, 'Paper and Forest Product Manufacturing', 'paper-and-forest-product-manufacturing', 'manufacturing', 170),
  ('Manufacturing', 'Plastics and Rubber Product Manufacturing', NULL, 'Plastics and Rubber Product Manufacturing', 'plastics-and-rubber-product-manufacturing', 'manufacturing', 171),
  ('Manufacturing', 'Plastics and Rubber Product Manufacturing', 'Packaging and Containers Manufacturing', 'Packaging and Containers Manufacturing', 'packaging-and-containers-manufacturing', 'manufacturing', 172),
  ('Manufacturing', 'Plastics and Rubber Product Manufacturing', 'Plastics Manufacturing', 'Plastics Manufacturing', 'plastics-manufacturing', 'manufacturing', 173),
  ('Manufacturing', 'Plastics and Rubber Product Manufacturing', 'Rubber Products Manufacturing', 'Rubber Products Manufacturing', 'rubber-products-manufacturing', 'manufacturing', 174),
  ('Manufacturing', 'Primary Metal Manufacturing', NULL, 'Primary Metal Manufacturing', 'primary-metal-manufacturing', 'manufacturing', 175),
  ('Manufacturing', 'Printing Services', NULL, 'Printing Services', 'printing-services', 'manufacturing', 176),
  ('Manufacturing', 'Sporting Goods Manufacturing', NULL, 'Sporting Goods Manufacturing', 'sporting-goods-manufacturing', 'manufacturing', 177),
  ('Manufacturing', 'Textile Manufacturing', NULL, 'Textile Manufacturing', 'textile-manufacturing', 'manufacturing', 178),
  ('Manufacturing', 'Tobacco Manufacturing', NULL, 'Tobacco Manufacturing', 'tobacco-manufacturing', 'manufacturing', 179),
  ('Manufacturing', 'Transportation Equipment Manufacturing', NULL, 'Transportation Equipment Manufacturing', 'transportation-equipment-manufacturing', 'manufacturing', 180),
  ('Manufacturing', 'Transportation Equipment Manufacturing', 'Aviation and Aerospace Component Manufacturing', 'Aviation and Aerospace Component Manufacturing', 'aviation-and-aerospace-component-manufacturing', 'manufacturing', 181),
  ('Manufacturing', 'Transportation Equipment Manufacturing', 'Defense and Space Manufacturing', 'Defense and Space Manufacturing', 'defense-and-space-manufacturing', 'manufacturing', 182),
  ('Manufacturing', 'Transportation Equipment Manufacturing', 'Motor Vehicle Manufacturing', 'Motor Vehicle Manufacturing', 'motor-vehicle-manufacturing', 'manufacturing', 183),
  ('Manufacturing', 'Transportation Equipment Manufacturing', 'Motor Vehicle Parts Manufacturing', 'Motor Vehicle Parts Manufacturing', 'motor-vehicle-parts-manufacturing', 'manufacturing', 184),
  ('Manufacturing', 'Transportation Equipment Manufacturing', 'Railroad Equipment Manufacturing', 'Railroad Equipment Manufacturing', 'railroad-equipment-manufacturing', 'manufacturing', 185),
  ('Manufacturing', 'Transportation Equipment Manufacturing', 'Shipbuilding', 'Shipbuilding', 'shipbuilding', 'manufacturing', 186),
  ('Manufacturing', 'Wood Product Manufacturing', NULL, 'Wood Product Manufacturing', 'wood-product-manufacturing', 'manufacturing', 187),
  ('Oil, Gas, and Mining', 'Mining', NULL, 'Mining', 'mining', 'oil-gas-and-mining', 188),
  ('Oil, Gas, and Mining', 'Oil and Gas', NULL, 'Oil and Gas', 'oil-and-gas', 'oil-gas-and-mining', 189),
  ('Professional Services', 'Accounting', NULL, 'Accounting', 'accounting', 'professional-services', 190),
  ('Professional Services', 'Advertising Services', NULL, 'Advertising Services', 'advertising-services', 'professional-services', 191),
  ('Professional Services', 'Advertising Services', 'Government Relations Services', 'Government Relations Services', 'government-relations-services', 'professional-services', 192),
  ('Professional Services', 'Advertising Services', 'Market Research', 'Market Research', 'market-research', 'professional-services', 193),
  ('Professional Services', 'Advertising Services', 'Photography', 'Photography', 'photography', 'professional-services', 194),
  ('Professional Services', 'Advertising Services', 'Public Relations and Communications Services', 'Public Relations and Communications Services', 'public-relations-and-communications-services', 'professional-services', 195),
  ('Professional Services', 'Architecture and Planning', NULL, 'Architecture and Planning', 'architecture-and-planning', 'professional-services', 196),
  ('Professional Services', 'Business Consulting and Services', NULL, 'Business Consulting and Services', 'business-consulting-and-services', 'professional-services', 197),
  ('Professional Services', 'Business Consulting and Services', 'Environmental Services', 'Environmental Services', 'environmental-services', 'professional-services', 198),
  ('Professional Services', 'Business Consulting and Services', 'Human Resources Services', 'Human Resources Services', 'human-resources-services', 'professional-services', 199),
  ('Professional Services', 'Business Consulting and Services', 'Marketing Services', 'Marketing Services', 'marketing-services', 'professional-services', 200),
  ('Professional Services', 'Business Consulting and Services', 'Operations Consulting', 'Operations Consulting', 'operations-consulting', 'professional-services', 201),
  ('Professional Services', 'Business Consulting and Services', 'Outsourcing and Offshoring Consulting', 'Outsourcing and Offshoring Consulting', 'outsourcing-and-offshoring-consulting', 'professional-services', 202),
  ('Professional Services', 'Business Consulting and Services', 'Strategic Management Services', 'Strategic Management Services', 'strategic-management-services', 'professional-services', 203),
  ('Professional Services', 'Design Services', NULL, 'Design Services', 'design-services', 'professional-services', 204),
  ('Professional Services', 'Design Services', 'Graphic Design', 'Graphic Design', 'graphic-design', 'professional-services', 205),
  ('Professional Services', 'Design Services', 'Interior Design', 'Interior Design', 'interior-design', 'professional-services', 206),
  ('Professional Services', 'Engineering Services', NULL, 'Engineering Services', 'engineering-services', 'professional-services', 207),
  ('Professional Services', 'IT Services and IT Consulting', NULL, 'IT Services and IT Consulting', 'it-services-and-it-consulting', 'professional-services', 208),
  ('Professional Services', 'IT Services and IT Consulting', 'Computer and Network Security', 'Computer and Network Security', 'computer-and-network-security', 'professional-services', 209),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Custom Software Development', 'IT System Custom Software Development', 'it-system-custom-software-development', 'professional-services', 210),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Data Services', 'IT System Data Services', 'it-system-data-services', 'professional-services', 211),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Design Services', 'IT System Design Services', 'it-system-design-services', 'professional-services', 212),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Installation and Disposal', 'IT System Installation and Disposal', 'it-system-installation-and-disposal', 'professional-services', 213),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Operations and Maintenance', 'IT System Operations and Maintenance', 'it-system-operations-and-maintenance', 'professional-services', 214),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Testing and Evaluation', 'IT System Testing and Evaluation', 'it-system-testing-and-evaluation', 'professional-services', 215),
  ('Professional Services', 'IT Services and IT Consulting', 'IT System Training and Support', 'IT System Training and Support', 'it-system-training-and-support', 'professional-services', 216),
  ('Professional Services', 'Legal Services', NULL, 'Legal Services', 'legal-services', 'professional-services', 217),
  ('Professional Services', 'Legal Services', 'Alternative Dispute Resolution', 'Alternative Dispute Resolution', 'alternative-dispute-resolution', 'professional-services', 218),
  ('Professional Services', 'Legal Services', 'Law Practice', 'Law Practice', 'law-practice', 'professional-services', 219),
  ('Professional Services', 'Research Services', NULL, 'Research Services', 'research-services', 'professional-services', 220),
  ('Professional Services', 'Research Services', 'Biotechnology Research', 'Biotechnology Research', 'biotechnology-research', 'professional-services', 221),
  ('Professional Services', 'Research Services', 'Nanotechnology Research', 'Nanotechnology Research', 'nanotechnology-research', 'professional-services', 222),
  ('Professional Services', 'Research Services', 'Think Tanks', 'Think Tanks', 'think-tanks', 'professional-services', 223),
  ('Professional Services', 'Services for Renewable Energy', NULL, 'Services for Renewable Energy', 'services-for-renewable-energy', 'professional-services', 224),
  ('Professional Services', 'Veterinary Services', NULL, 'Veterinary Services', 'veterinary-services', 'professional-services', 225),
  ('Real Estate and Equipment Rental Services', 'Equipment Rental Services', NULL, 'Equipment Rental Services', 'equipment-rental-services', 'real-estate-and-equipment-rental-services', 226),
  ('Real Estate and Equipment Rental Services', 'Real Estate', NULL, 'Real Estate', 'real-estate', 'real-estate-and-equipment-rental-services', 227),
  ('Retail', 'Food and Beverage Retail', NULL, 'Food and Beverage Retail', 'food-and-beverage-retail', 'retail', 228),
  ('Retail', 'Online and Mail Order Retail', NULL, 'Online and Mail Order Retail', 'online-and-mail-order-retail', 'retail', 229),
  ('Retail', 'Retail Apparel and Fashion', NULL, 'Retail Apparel and Fashion', 'retail-apparel-and-fashion', 'retail', 230),
  ('Retail', 'Retail Appliances, Electrical, and Electronic Equipment', NULL, 'Retail Appliances, Electrical, and Electronic Equipment', 'retail-appliances-electrical-and-electronic-equipment', 'retail', 231),
  ('Retail', 'Retail Art Dealers', NULL, 'Retail Art Dealers', 'retail-art-dealers', 'retail', 232),
  ('Retail', 'Retail Art Supplies', NULL, 'Retail Art Supplies', 'retail-art-supplies', 'retail', 233),
  ('Retail', 'Retail Books and Printed News', NULL, 'Retail Books and Printed News', 'retail-books-and-printed-news', 'retail', 234),
  ('Retail', 'Retail Building Materials and Garden Equipment', NULL, 'Retail Building Materials and Garden Equipment', 'retail-building-materials-and-garden-equipment', 'retail', 235),
  ('Retail', 'Retail Florists', NULL, 'Retail Florists', 'retail-florists', 'retail', 236),
  ('Retail', 'Retail Furniture and Home Furnishings', NULL, 'Retail Furniture and Home Furnishings', 'retail-furniture-and-home-furnishings', 'retail', 237),
  ('Retail', 'Retail Gasoline', NULL, 'Retail Gasoline', 'retail-gasoline', 'retail', 238),
  ('Retail', 'Retail Health and Personal Care Products', NULL, 'Retail Health and Personal Care Products', 'retail-health-and-personal-care-products', 'retail', 239),
  ('Retail', 'Retail Luxury Goods and Jewelry', NULL, 'Retail Luxury Goods and Jewelry', 'retail-luxury-goods-and-jewelry', 'retail', 240),
  ('Retail', 'Retail Motor Vehicles', NULL, 'Retail Motor Vehicles', 'retail-motor-vehicles', 'retail', 241),
  ('Retail', 'Retail Musical Instruments', NULL, 'Retail Musical Instruments', 'retail-musical-instruments', 'retail', 242),
  ('Retail', 'Retail Office Equipment', NULL, 'Retail Office Equipment', 'retail-office-equipment', 'retail', 243),
  ('Retail', 'Retail Office Supplies and Gifts', NULL, 'Retail Office Supplies and Gifts', 'retail-office-supplies-and-gifts', 'retail', 244),
  ('Retail', 'Retail Recyclable Materials and Used Merchandise', NULL, 'Retail Recyclable Materials and Used Merchandise', 'retail-recyclable-materials-and-used-merchandise', 'retail', 245),
  ('Technology, Information and Media', 'Book and Periodical Publishing', NULL, 'Book and Periodical Publishing', 'book-and-periodical-publishing', 'technology-information-and-media', 246),
  ('Technology, Information and Media', 'Broadcast Media Production and Distribution', NULL, 'Broadcast Media Production and Distribution', 'broadcast-media-production-and-distribution', 'technology-information-and-media', 247),
  ('Technology, Information and Media', 'Data Infrastructure and Analytics', NULL, 'Data Infrastructure and Analytics', 'data-infrastructure-and-analytics', 'technology-information-and-media', 248),
  ('Technology, Information and Media', 'Information Services', NULL, 'Information Services', 'information-services', 'technology-information-and-media', 249),
  ('Technology, Information and Media', 'Internet Marketplace Platforms', NULL, 'Internet Marketplace Platforms', 'internet-marketplace-platforms', 'technology-information-and-media', 250),
  ('Technology, Information and Media', 'Movies, Videos, and Sound', NULL, 'Movies, Videos, and Sound', 'movies-videos-and-sound', 'technology-information-and-media', 251),
  ('Technology, Information and Media', 'Social Networking Platforms', NULL, 'Social Networking Platforms', 'social-networking-platforms', 'technology-information-and-media', 252),
  ('Technology, Information and Media', 'Software Development', NULL, 'Software Development', 'software-development', 'technology-information-and-media', 253),
  ('Technology, Information and Media', 'Software Development', 'Computer Games', 'Computer Games', 'computer-games', 'technology-information-and-media', 254),
  ('Technology, Information and Media', 'Telecommunications', NULL, 'Telecommunications', 'telecommunications', 'technology-information-and-media', 255),
  ('Transportation, Logistics, Supply Chain and Storage', 'Airlines and Aviation', NULL, 'Airlines and Aviation', 'airlines-and-aviation', 'transportation-logistics-supply-chain-and-storage', 256),
  ('Transportation, Logistics, Supply Chain and Storage', 'Freight and Package Transportation', NULL, 'Freight and Package Transportation', 'freight-and-package-transportation', 'transportation-logistics-supply-chain-and-storage', 257),
  ('Transportation, Logistics, Supply Chain and Storage', 'Ground Passenger Transportation', NULL, 'Ground Passenger Transportation', 'ground-passenger-transportation', 'transportation-logistics-supply-chain-and-storage', 258),
  ('Transportation, Logistics, Supply Chain and Storage', 'Maritime Transportation', NULL, 'Maritime Transportation', 'maritime-transportation', 'transportation-logistics-supply-chain-and-storage', 259),
  ('Transportation, Logistics, Supply Chain and Storage', 'Pipeline Transportation', NULL, 'Pipeline Transportation', 'pipeline-transportation', 'transportation-logistics-supply-chain-and-storage', 260),
  ('Transportation, Logistics, Supply Chain and Storage', 'Postal Services', NULL, 'Postal Services', 'postal-services', 'transportation-logistics-supply-chain-and-storage', 261),
  ('Transportation, Logistics, Supply Chain and Storage', 'Rail Transportation', NULL, 'Rail Transportation', 'rail-transportation', 'transportation-logistics-supply-chain-and-storage', 262),
  ('Transportation, Logistics, Supply Chain and Storage', 'Truck Transportation', NULL, 'Truck Transportation', 'truck-transportation', 'transportation-logistics-supply-chain-and-storage', 263),
  ('Transportation, Logistics, Supply Chain and Storage', 'Warehousing and Storage', NULL, 'Warehousing and Storage', 'warehousing-and-storage', 'transportation-logistics-supply-chain-and-storage', 264),
  ('Utilities', 'Electric Power Generation', NULL, 'Electric Power Generation', 'electric-power-generation', 'utilities', 265),
  ('Utilities', 'Electric Power Transmission, Control, and Distribution', NULL, 'Electric Power Transmission, Control, and Distribution', 'electric-power-transmission-control-and-distribution', 'utilities', 266),
  ('Utilities', 'Natural Gas Distribution', NULL, 'Natural Gas Distribution', 'natural-gas-distribution', 'utilities', 267),
  ('Utilities', 'Water, Waste, Steam, and Air Conditioning Services', NULL, 'Water, Waste, Steam, and Air Conditioning Services', 'water-waste-steam-and-air-conditioning-services', 'utilities', 268),
  ('Wholesale', 'Wholesale Alcoholic Beverages', NULL, 'Wholesale Alcoholic Beverages', 'wholesale-alcoholic-beverages', 'wholesale', 269),
  ('Wholesale', 'Wholesale Apparel and Sewing Supplies', NULL, 'Wholesale Apparel and Sewing Supplies', 'wholesale-apparel-and-sewing-supplies', 'wholesale', 270),
  ('Wholesale', 'Wholesale Appliances, Electrical, and Electronics', NULL, 'Wholesale Appliances, Electrical, and Electronics', 'wholesale-appliances-electrical-and-electronics', 'wholesale', 271),
  ('Wholesale', 'Wholesale Building Materials', NULL, 'Wholesale Building Materials', 'wholesale-building-materials', 'wholesale', 272),
  ('Wholesale', 'Wholesale Chemical and Allied Products', NULL, 'Wholesale Chemical and Allied Products', 'wholesale-chemical-and-allied-products', 'wholesale', 273),
  ('Wholesale', 'Wholesale Computer Equipment', NULL, 'Wholesale Computer Equipment', 'wholesale-computer-equipment', 'wholesale', 274),
  ('Wholesale', 'Wholesale Drugs and Sundries', NULL, 'Wholesale Drugs and Sundries', 'wholesale-drugs-and-sundries', 'wholesale', 275),
  ('Wholesale', 'Wholesale Food and Beverage', NULL, 'Wholesale Food and Beverage', 'wholesale-food-and-beverage', 'wholesale', 276),
  ('Wholesale', 'Wholesale Footwear', NULL, 'Wholesale Footwear', 'wholesale-footwear', 'wholesale', 277),
  ('Wholesale', 'Wholesale Furniture and Home Furnishings', NULL, 'Wholesale Furniture and Home Furnishings', 'wholesale-furniture-and-home-furnishings', 'wholesale', 278),
  ('Wholesale', 'Wholesale Hardware, Plumbing, Heating Equipment', NULL, 'Wholesale Hardware, Plumbing, Heating Equipment', 'wholesale-hardware-plumbing-heating-equipment', 'wholesale', 279),
  ('Wholesale', 'Wholesale Import and Export', NULL, 'Wholesale Import and Export', 'wholesale-import-and-export', 'wholesale', 280),
  ('Wholesale', 'Wholesale Luxury Goods and Jewelry', NULL, 'Wholesale Luxury Goods and Jewelry', 'wholesale-luxury-goods-and-jewelry', 'wholesale', 281),
  ('Wholesale', 'Wholesale Machinery', NULL, 'Wholesale Machinery', 'wholesale-machinery', 'wholesale', 282),
  ('Wholesale', 'Wholesale Metals and Minerals', NULL, 'Wholesale Metals and Minerals', 'wholesale-metals-and-minerals', 'wholesale', 283),
  ('Wholesale', 'Wholesale Motor Vehicles and Parts', NULL, 'Wholesale Motor Vehicles and Parts', 'wholesale-motor-vehicles-and-parts', 'wholesale', 284),
  ('Wholesale', 'Wholesale Paper Products', NULL, 'Wholesale Paper Products', 'wholesale-paper-products', 'wholesale', 285),
  ('Wholesale', 'Wholesale Petroleum and Petroleum Products', NULL, 'Wholesale Petroleum and Petroleum Products', 'wholesale-petroleum-and-petroleum-products', 'wholesale', 286),
  ('Wholesale', 'Wholesale Photography Equipment and Supplies', NULL, 'Wholesale Photography Equipment and Supplies', 'wholesale-photography-equipment-and-supplies', 'wholesale', 287),
  ('Wholesale', 'Wholesale Raw Farm Products', NULL, 'Wholesale Raw Farm Products', 'wholesale-raw-farm-products', 'wholesale', 288),
  ('Wholesale', 'Wholesale Recyclable Materials', NULL, 'Wholesale Recyclable Materials', 'wholesale-recyclable-materials', 'wholesale', 289)
;

-- Done: 289 rows seeded
