-- Mentors remediation WS-C: logo.dev company domains on experience tiles.
-- Adds a `domain` key to each experience_tiles entry whose company resolves to a
-- known domain, and strips any legacy placeholder logo. The frontend builds the
-- logo.dev image URL from this domain (monogram fallback when absent).
-- Self-contained, idempotent, re-runnable. Resolution is high-confidence
-- (well-known + web-confirmed) plus medium-confidence (plausible org domains);
-- logo.dev degrades to a monogram on any miss. Applied to prod 2026-06-16.
WITH dom(name, domain) AS (
  VALUES
  ('20Cube Logistics', '20cube.com'),
  ('Academy of Entrepreneurs', 'academyofentrepreneurs.com.au'),
  ('ACCIÓ', 'accio.gencat.cat'),
  ('Acclime', 'acclime.com'),
  ('Acclime Australia', 'acclime.com'),
  ('ACS (Australian Computer Society)', 'acs.org.au'),
  ('Afterpay', 'afterpay.com'),
  ('AfterWork Ventures', 'afterwork.vc'),
  ('AgriTech New Zealand', 'agritechnz.org.nz'),
  ('Airbnb', 'airbnb.com'),
  ('Airtasker', 'airtasker.com'),
  ('Airtree', 'airtree.vc'),
  ('AirTree Ventures', 'airtree.vc'),
  ('Airwallex', 'airwallex.com'),
  ('Amazon', 'amazon.com'),
  ('AmCham Australia', 'amcham.com.au'),
  ('Antler', 'antler.co'),
  ('Applied Marks', 'appliedmarks.com.au'),
  ('ASB Bank', 'asb.co.nz'),
  ('ASIC', 'asic.gov.au'),
  ('AT&T', 'att.com'),
  ('Atlassian', 'atlassian.com'),
  ('Aurivo Co-operative Society Limited', 'aurivo.ie'),
  ('Aussie Angels', 'aussieangels.com'),
  ('Australia Post', 'auspost.com.au'),
  ('Australian British Chamber of Commerce', 'britishchamber.com.au'),
  ('Australian FinTech', 'australianfintech.com.au'),
  ('Australian Payments Network (AusPayNet)', 'auspaynet.com.au'),
  ('Australian Trade and Investment Commission (Austrade)', 'austrade.gov.au'),
  ('Avant Group', 'avantgroup.com.au'),
  ('AWS', 'aws.amazon.com'),
  ('Banjo - Business Loans', 'banjoloans.com'),
  ('Basque Trade & Investment / Agencia Vasca de Internacionalización', 'basquetrade.spri.eus'),
  ('Beyond Bank Australia', 'beyondbank.com.au'),
  ('BHP', 'bhp.com'),
  ('Blackbird Ventures', 'blackbird.vc'),
  ('Blake, Cassels & Graydon LLP', 'blakes.com'),
  ('BootstrapLabs, an Ares company', 'bootstraplabs.com'),
  ('BT Group', 'bt.com'),
  ('Bus Stop Films', 'busstopfilms.com.au'),
  ('Business Blueprint', 'businessblueprint.com'),
  ('Canva', 'canva.com'),
  ('Carrara Capital', 'carraracapital.com.au'),
  ('Catalonia Trade & Investment', 'catalonia.com'),
  ('Catalysr - Accelerator for Migrants & Refugees', 'catalysr.com.au'),
  ('Certus Recruitment Group', 'certusrecruitment.com'),
  ('Cicada Innovations', 'cicadainnovations.com'),
  ('Clayton Utz', 'claytonutz.com'),
  ('Cochlear', 'cochlear.com'),
  ('Commonwealth Bank', 'commbank.com.au'),
  ('Cox Purtell Staffing Services', 'coxpurtell.com.au'),
  ('Credisense', 'credisense.com'),
  ('Credisense Australia', 'credisense.com'),
  ('Cremorne Digital Hub', 'cremornedigitalhub.com'),
  ('CSL', 'csl.com'),
  ('Department of Internal Affairs (NZ)', 'dia.govt.nz'),
  ('Department of Jobs, Skills, Industry and Regions', 'djsir.vic.gov.au'),
  ('Digital Irish', 'digitalirish.com'),
  ('Dosh New Zealand', 'dosh.nz'),
  ('DXC Practice for Oracle', 'dxc.com'),
  ('eBay', 'ebay.com'),
  ('Efficiency Leaders', 'efficiencyleaders.com.au'),
  ('Employment Hero', 'employmenthero.com'),
  ('Enterprise Ireland', 'enterprise-ireland.com'),
  ('Enterprise Ireland Australia & New Zealand', 'enterprise-ireland.com'),
  ('Enterprise Singapore', 'enterprisesg.gov.sg'),
  ('Everlab', 'everlab.com'),
  ('Expandys', 'expandys.com'),
  ('Export Development Canada', 'edc.ca'),
  ('Export Development Canada | Exportation et développement Canada', 'edc.ca'),
  ('EY', 'ey.com'),
  ('FACCI - French-Australian Chamber of Commerce & Industry', 'facci.com.au'),
  ('Facebook', 'facebook.com'),
  ('Farmers2Founders', 'farmers2founders.com'),
  ('Fenergo', 'fenergo.com'),
  ('Furthr', 'furthr.ie'),
  ('Global Affairs Canada | Affaires mondiales Canada', 'international.gc.ca'),
  ('Global Victoria', 'global.vic.gov.au'),
  ('Google', 'google.com'),
  ('GOW Recruitment', 'gowrecruitment.com.au'),
  ('Great Lakes St. Lawrence Governors & Premiers', 'gsgp.org'),
  ('Halcyon Knights', 'halcyonknights.com.au'),
  ('Haymarket HQ', 'haymarkethq.com'),
  ('hipages Group', 'hipages.com.au'),
  ('Hong Kong Trade Development Council', 'hktdc.com'),
  ('HotDoc', 'hotdoc.com.au'),
  ('HSBC', 'hsbc.com'),
  ('i4T Global', 'i4tglobal.com'),
  ('IDA Ireland', 'idaireland.com'),
  ('Insurtech Australia', 'insurtechaustralia.org.au'),
  ('Intapp', 'intapp.com'),
  ('International Civil Aviation Organization', 'icao.int'),
  ('Invest Northern Ireland', 'investni.com'),
  ('Invest Victoria', 'invest.vic.gov.au'),
  ('Investment NSW', 'investment.nsw.gov.au'),
  ('Israel Trade and Economic Commission Australia', 'israeltrade.gov.il'),
  ('King & Wood Mallesons', 'kwm.com'),
  ('KOTRA', 'kotra.or.kr'),
  ('KOTRA Sydney AU', 'kotra.or.kr'),
  ('LAB Group', 'labgroup.com.au'),
  ('Lendi Group', 'lendi.com.au'),
  ('Lendlease', 'lendlease.com'),
  ('Lion', 'lionco.com'),
  ('ListReady', 'listready.com.au'),
  ('LOKE - Branded Ordering, Delivery & Loyalty Apps', 'loke.global'),
  ('Lotus People', 'lotuspeople.com.au'),
  ('Lumi', 'lumi.com.au'),
  ('Mad Mex', 'madmex.com.au'),
  ('McKinsey & Company', 'mckinsey.com'),
  ('MFS Investment Management', 'mfs.com'),
  ('Microsoft', 'microsoft.com'),
  ('MONEYME', 'moneyme.com.au'),
  ('NAB', 'nab.com.au'),
  ('New Zealand Trade and Enterprise', 'nzte.govt.nz'),
  ('NSW Treasury', 'treasury.nsw.gov.au'),
  ('NZ Hi-Tech Awards', 'hitech.org.nz'),
  ('OFX', 'ofx.com'),
  ('OKX', 'okx.com'),
  ('Orange Business', 'orange-business.com'),
  ('Paytron', 'paytron.com'),
  ('PINTEC', 'pintec.com'),
  ('Polish Investment and Trade Agency (PAIH)', 'paih.gov.pl'),
  ('Practice Connections Advisory', 'practiceconnections.com.au'),
  ('Premier''s Department NSW', 'nsw.gov.au'),
  ('Professionals in International Trade (PIT)', 'pit.org.au'),
  ('Public Sector Network', 'publicsectornetwork.com'),
  ('Publift', 'publift.com'),
  ('RateSetter', 'ratesetter.com.au'),
  ('SAP', 'sap.com'),
  ('Scottish Development International', 'sdi.co.uk'),
  ('Seek', 'seek.com.au'),
  ('Sharesies', 'sharesies.com'),
  ('Shirofune', 'shirofune.com'),
  ('Shopify', 'shopify.com'),
  ('Sleek', 'sleek.com'),
  ('SMEC', 'smec.com'),
  ('SpaDays.com.au', 'spadays.com.au'),
  ('Square Peg Capital', 'squarepeg.vc'),
  ('Startmate', 'startmate.com'),
  ('Startupbootcamp', 'startupbootcamp.org'),
  ('Stats NZ', 'stats.govt.nz'),
  ('Stone & Chalk', 'stoneandchalk.com.au'),
  ('Stone Real Estate.', 'stonerealestate.com.au'),
  ('Strategica.io', 'strategica.io'),
  ('Stripe', 'stripe.com'),
  ('Suncorp Group', 'suncorpgroup.com.au'),
  ('Sunnyhaven Disability Services Ltd', 'sunnyhaven.org.au'),
  ('TalentWeb | B Corp', 'talentweb.com.au'),
  ('Tech Council of Australia', 'techcouncil.com.au'),
  ('Techboard', 'techboard.com.au'),
  ('Techvisa', 'techvisa.com.au'),
  ('Tenacious Ventures', 'tenacious.ventures'),
  ('Tesco', 'tesco.com'),
  ('TGA', 'tga.gov.au'),
  ('The Australian National University', 'anu.edu.au'),
  ('The digiDirect Group', 'digidirect.com.au'),
  ('The Fred Hollows Foundation', 'hollows.org'),
  ('TikTok', 'tiktok.com'),
  ('Toll Group', 'tollgroup.com'),
  ('Tractor Ventures', 'tractor.ventures'),
  ('Trade Commissioner Service', 'tradecommissioner.gc.ca'),
  ('Trade Ledger', 'tradeledger.io'),
  ('Traders4Traders', 'traders4traders.com'),
  ('Tribe Global Ventures', 'tribeglobal.vc'),
  ('Urban Rest', 'urbanrest.com'),
  ('Wagepay', 'wagepay.com.au'),
  ('WeMoney', 'wemoney.com.au'),
  ('Woolworths', 'woolworths.com.au')
)
UPDATE public.community_members cm
SET experience_tiles = (
  SELECT jsonb_agg(
    CASE WHEN d.domain IS NOT NULL
         THEN (tile - 'logo') || jsonb_build_object('domain', d.domain)
         ELSE (tile - 'logo') END)
  FROM jsonb_array_elements(cm.experience_tiles) tile
  LEFT JOIN dom d ON lower(d.name) = lower(tile->>'name')
)
WHERE cm.is_active
  AND jsonb_typeof(experience_tiles) = 'array'
  AND jsonb_array_length(experience_tiles) > 0;
