-- ============================================================================
-- PALANTIR CASE STUDY DEEP REWRITE
-- ============================================================================

UPDATE public.content_items SET
  title = 'How Palantir Technologies Entered the Australian Market',
  subtitle = 'From $7.1 million Defence contracts to IRAP PROTECTED certification and a $100 million Future Fund stake: how the controversial data analytics firm embedded itself in Australian government and enterprise',
  read_time = 12,
  meta_description = 'Deep-dive case study on how Palantir entered Australia with Defence contracts, achieved IRAP PROTECTED certification, signed Coles, and navigated political scrutiny.',
  sector_tags = ARRAY['data-analytics', 'ai', 'defense', 'technology', 'government', 'national-security'],
  updated_at = NOW()
WHERE slug = 'palantir-australia-market-entry';

UPDATE public.content_company_profiles SET
  industry = 'Data Analytics, AI, and National Security',
  business_model = 'B2B/B2G Enterprise Software / Subscription Platform'
WHERE content_id = (SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry');

DELETE FROM public.content_sections WHERE content_id = (SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry');
DELETE FROM public.content_bodies WHERE content_id = (SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry');

INSERT INTO public.content_sections (content_id, title, slug, sort_order, is_active) VALUES
((SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry'), 'Entry Strategy', 'entry-strategy', 1, true),
((SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry'), 'Success Factors', 'success-factors', 2, true),
((SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry'), 'Key Metrics & Performance', 'key-metrics', 3, true),
((SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry'), 'Challenges Faced', 'challenges-faced', 4, true),
((SELECT id FROM public.content_items WHERE slug = 'palantir-australia-market-entry'), 'Lessons Learned', 'lessons-learned', 5, true);

INSERT INTO public.content_bodies (section_id, body_text, sort_order, content_type) VALUES
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>Palantir has been working with Australian government agencies since 2013, accumulating over $50 million in government contracts largely across defence and national security agencies. The company deployed the Palantir Platform Australia (PPA) to deliver advanced cloud services including Foundry and AIP, hosted in Australian AWS regions. The initial entry was through defence and intelligence — the most difficult but most lucrative government sector — establishing Palantir as a trusted provider of data analytics for national security applications. Mike Kelly leads Palantir''s Australian operations.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.defenceconnect.com.au/industry/17697-palantir-secures-7-6-million-defence-contract-to-supply-ict-system-platform" target="_blank" rel="noopener noreferrer">Defence Connect</a>, <a href="https://honisoit.com/2026/02/australias-100-million-investment-in-palantir-technology-giant-and-partner-of-us-and-israeli-defence-forces/" target="_blank" rel="noopener noreferrer">Honi Soit</a></em></p>', 1, 'paragraph'),
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>The pivotal milestone came in November 2025, when Palantir achieved IRAP PROTECTED level certification — a key requirement for handling sensitive government information. The assessment was conducted by an independent third-party assessor in line with Australian Signals Directorate (ASD) requirements. Kelly described it as "a key milestone for Palantir in Australia and a testament to our deep and ongoing commitment to security." The certification unlocked a broader range of Australian government agencies and commercial organisations as potential customers for the Foundry and AIP platforms.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Source: <a href="https://investors.palantir.com/news-details/2025/Palantir-Achieves-Information-Security-Registered-Assessors-Program-IRAP-PROTECTED-Level-Unlocking-New-Opportunities-in-Australia/" target="_blank" rel="noopener noreferrer">Palantir Investors</a></em></p>', 2, 'paragraph'),
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>Palantir pursued a dual-track strategy serving both government and commercial customers. In October 2024, it secured a new three-year contract with the Department of Defence valued at AUD $7.15 million, covering data analytics and services through December 2027. Simultaneously, the company expanded into commercial enterprise — most notably signing a three-year deal with Coles in 2024 to optimise workforce management across 840+ supermarkets using Foundry to analyse over 10 billion rows of operational data.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.canberratimes.com.au/story/9178631/defence-awards-palantir-76m-defence-contract/" target="_blank" rel="noopener noreferrer">Canberra Times</a>, <a href="https://www.crikey.com.au/2026/03/09/palantir-defence-contract-australia-embedding-staff-data-mining/" target="_blank" rel="noopener noreferrer">Crikey</a></em></p>', 3, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'success-factors'),
'<p>Palantir''s success in Australia rests on its ability to handle massive, complex datasets that traditional analytics tools cannot manage. The Coles deployment — analysing 10 billion rows of data across 840+ stores for workforce optimisation, cost reduction, and merchandising — demonstrates the platform''s scalability for commercial use cases. The IRAP PROTECTED certification, while primarily enabling government work, also provides commercial customers with assurance about the platform''s security posture.</p>', 1, 'paragraph'),
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'success-factors'),
'<p>The rapid adoption of AI drove strong returns for investors. The 2024 financial report of Palantir Technologies Australia Pty Ltd shows $25.5 million in revenue from customer contracts. Australia''s Future Fund — the sovereign wealth fund — held 498,339 shares of Palantir valued at $103.6 million as of June 2025, having grown nearly 100 times from approximately $1.6 million in February 2023. This institutional endorsement from Australia''s own sovereign fund created a powerful credibility signal.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://honisoit.com/2026/02/australias-100-million-investment-in-palantir-technology-giant-and-partner-of-us-and-israeli-defence-forces/" target="_blank" rel="noopener noreferrer">Honi Soit</a>, <a href="https://ryxel.ai/news/technology/2025/11/20/palantir-stock-gains-australian-irap-security-approval" target="_blank" rel="noopener noreferrer">Ryxel</a></em></p>', 2, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'key-metrics'),
'<p>Palantir has secured over $50 million in Australian government contracts since 2013. The Australian subsidiary reported $25.5 million in revenue from customer contracts in 2024. Australia''s Future Fund holds $103.6 million in Palantir shares (June 2025). Key contracts include a $7.15 million three-year Defence deal (2024-2027), a three-year Coles partnership covering 840+ stores and 10 billion data rows, and IRAP PROTECTED certification achieved November 2025. Palantir''s stock surged 4.6% on the IRAP news, reflecting market recognition of the Australian opportunity.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://investors.palantir.com/news-details/2025/Palantir-Achieves-Information-Security-Registered-Assessors-Program-IRAP-PROTECTED-Level-Unlocking-New-Opportunities-in-Australia/" target="_blank" rel="noopener noreferrer">Palantir Investors</a>, <a href="https://www.defenceconnect.com.au/industry/17697-palantir-secures-7-6-million-defence-contract-to-supply-ict-system-platform" target="_blank" rel="noopener noreferrer">Defence Connect</a></em></p>', 1, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'challenges-faced'),
'<p>Palantir faces intense political scrutiny in Australia. The Greens called for an immediate freeze on government contracts with the company, citing its international operations and relationships with US and Israeli defence forces. Crikey reported that Palantir embeds staff within Defence and mines Australian data under its contracts. In July 2025, the company hired lobbying firm CMAX Advisory — founded by a former chief of staff to Labor Defence Minister Joel Fitzgibbon — to manage political relationships. Defence skipped competitive tender processes for some Palantir contracts, drawing additional criticism.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://michaelwest.com.au/we-kill-enemies-spy-firm-palantir-secures-top-australian-security-clearance/" target="_blank" rel="noopener noreferrer">Michael West Media</a>, <a href="https://www.crikey.com.au/2026/03/09/palantir-defence-contract-australia-embedding-staff-data-mining/" target="_blank" rel="noopener noreferrer">Crikey</a></em></p>', 1, 'paragraph'),
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'challenges-faced'),
'<p>Vendor lock-in concerns are a persistent challenge for both government and commercial customers. Once an organisation builds operational processes around Palantir''s Foundry platform, switching costs become substantial. Critics argue this dependency creates an unhealthy reliance on a single vendor for critical data infrastructure. The company''s opaque pricing model and the fact that its Australian financial reports are not audited add to transparency concerns. Balancing commercial expansion (Coles) with government security requirements also creates reputational complexity.</p>', 2, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>Security certifications are the gateway to government revenue.</strong> IRAP PROTECTED certification unlocked an entire tier of Australian government agencies. The 13-year journey from first Defence contract to PROTECTED certification shows that government trust is earned incrementally. Companies targeting Australian government work should begin the compliance journey years before they expect to bid on contracts.</p>', 1, 'paragraph'),
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>A dual government-commercial strategy diversifies risk.</strong> Palantir''s expansion from Defence contracts to the Coles partnership demonstrates that government credibility can be leveraged for commercial customer acquisition. The security standards required for government work provide assurance that commercial customers value — Coles chose a platform trusted by Defence to handle its own sensitive operational data.</p>', 2, 'paragraph'),
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'palantir-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>Prepare for political and media scrutiny proportional to your government exposure.</strong> Palantir''s government contracts attracted Greens opposition, investigative journalism, and public debate about data sovereignty and vendor dependency. Companies entering the Australian government market should invest in government relations, transparent reporting, and proactive stakeholder engagement — the political scrutiny is a feature of the market, not a bug.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://michaelwest.com.au/we-kill-enemies-spy-firm-palantir-secures-top-australian-security-clearance/" target="_blank" rel="noopener noreferrer">Michael West Media</a>, <a href="https://investors.palantir.com/news-details/2025/Palantir-Achieves-Information-Security-Registered-Assessors-Program-IRAP-PROTECTED-Level-Unlocking-New-Opportunities-in-Australia/" target="_blank" rel="noopener noreferrer">Palantir Investors</a></em></p>', 3, 'paragraph');
