-- ============================================================================
-- Report template improvements based on audit findings:
-- 1. Add {{additional_notes}} as high-priority user request in key sections
-- 2. Wire {{target_customer_description}} into relevant templates
-- 3. Wire {{key_challenges}} into swot_analysis and action_plan
-- 4. Make action plan timeline-adaptive
-- 5. Add deduplication instructions to overlapping sections
-- 6. Wire {{revenue_stage}} for startup persona
-- ============================================================================

-- ── 1. Executive Summary ──────────────────────────────────────────────
-- Add: additional_notes (high priority), target_customer_description, revenue_stage
-- Add: dedup instruction (don't repeat detailed SWOT or action plan content)
UPDATE report_templates
SET
  prompt_body = E'Write an executive summary for {{company_name}}''s growth strategy in the Australian market.\n\nEnriched company profile:\n{{enriched_company_profile}}\n\nCompany context:\n- Stage: {{company_stage}}\n- Industry: {{industry_sector}}\n- Origin: {{country_of_origin}}\n- Target regions: {{target_regions}}\n- Services needed: {{services_needed}}\n- Timeline: {{timeline}}\n- Budget: {{budget_level}}\n- Goals: {{primary_goals}}\n- Challenges: {{key_challenges}}\n- Target customer profile: {{target_customer_description}}\n- Revenue stage: {{revenue_stage}}\n\n--- MARKET LANDSCAPE ---\n{{market_research_landscape}}\n\n--- BILATERAL TRADE / FUNDING LANDSCAPE ---\n{{market_research_bilateral_trade}}\n\n--- GOVERNMENT GRANTS & INCENTIVES ---\n{{market_research_grants}}\n\n--- END BUYER INSIGHTS ---\n{{end_buyer_research}}\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST (give this high priority) ---\nThe user has specifically asked for the report to cover: {{additional_notes}}\nAddress this directly in the executive summary.\n{{/additional_notes}}\n\nWrite a compelling 3-4 paragraph executive summary that:\n1. Opens with a clear statement of {{company_name}}''s value proposition and market opportunity in Australia (use the enriched profile data for specifics)\n2. Summarizes the key market conditions, opportunity size, and any relevant bilateral trade advantages between {{country_of_origin}} and Australia\n3. Highlights key government incentives or grants the company should leverage\n4. Outlines the recommended approach and timeline\n5. Concludes with expected outcomes and next steps\n\nNOTE: Keep this section as a high-level overview. Do NOT include detailed SWOT points, competitor analysis, or step-by-step action plans — those belong in their dedicated sections.\n\nUse **bold** for key statistics and important terms. Reference specific products, clients, or USPs from the enriched profile where available.\n\nSources:\n{{market_research_citations}}',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'target_regions', 'services_needed', 'timeline', 'budget_level', 'primary_goals', 'key_challenges', 'target_customer_description', 'revenue_stage', 'enriched_company_profile', 'market_research_landscape', 'market_research_bilateral_trade', 'market_research_grants', 'end_buyer_research', 'additional_notes', 'market_research_citations'],
  updated_at = now()
WHERE section_name = 'executive_summary' AND is_active = true;

-- ── 2. SWOT Analysis ──────────────────────────────────────────────────
-- Add: key_challenges (into Weaknesses/Threats), additional_notes, target_customer_description
-- Add: dedup instruction
UPDATE report_templates
SET
  prompt_body = E'Generate a SWOT analysis for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering Australia targeting {{target_regions}}.\n\nCompany context: {{enriched_summary}}\nTarget customer profile: {{target_customer_description}}\nRevenue stage: {{revenue_stage}}\n\n--- REAL MARKET RESEARCH DATA ---\nMarket Landscape:\n{{market_research_landscape}}\n\nRegulatory & Compliance:\n{{market_research_regulatory}}\n\nRecent News & Developments:\n{{market_research_news}}\n\n--- BILATERAL TRADE / FUNDING LANDSCAPE ---\n{{market_research_bilateral_trade}}\n\n--- COST OF DOING BUSINESS ---\nOperational costs in {{target_regions}}:\n{{market_research_cost_of_business}}\n\n--- USER''S SPECIFIC CHALLENGES ---\nThe company has identified these specific challenges and concerns:\n{{key_challenges}}\nIncorporate these into the Weaknesses and/or Threats sections where relevant.\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nAddress this in the SWOT analysis where relevant.\n{{/additional_notes}}\n\nStrengths: based on company context and capabilities. Include any bilateral trade advantages (e.g. free trade agreements, existing trade corridors) between {{country_of_origin}} and Australia.\nWeaknesses: common challenges for {{country_of_origin}} companies in {{industry_sector}}. Consider the user''s specific challenges above. Consider cost factors from the cost-of-business data.\nOpportunities: use the market landscape research above to identify specific, data-backed opportunities in the Australian market. Reference any bilateral trade facilitation or incentive programs.\nThreats: use the regulatory research above to identify specific compliance risks, plus competitive, cost, and cultural factors from the news and cost data.\n\nFormat as 4 sections with 3-4 bullet points each. Be specific to the company and market. Reference real data points from the research above.\n\nNOTE: Focus on strategic analysis. Do NOT list service providers, events, or step-by-step action items — those are in dedicated sections.\n\nSources:\n{{market_research_citations}}',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'target_regions', 'enriched_summary', 'target_customer_description', 'revenue_stage', 'key_challenges', 'additional_notes', 'market_research_landscape', 'market_research_regulatory', 'market_research_news', 'market_research_bilateral_trade', 'market_research_cost_of_business', 'market_research_citations'],
  updated_at = now()
WHERE section_name = 'swot_analysis' AND is_active = true;

-- ── 3. Competitor Landscape ───────────────────────────────────────────
-- Add: additional_notes, target_customer_description
UPDATE report_templates
SET
  prompt_body = E'You are analyzing the competitive landscape for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering the Australian market targeting {{target_regions}}.\n\nCompany profile:\n{{enriched_company_profile}}\n\nTarget customer profile: {{target_customer_description}}\n\nHere are real competitors identified in the Australian market:\n{{competitor_analysis_json}}\n\nMarket research context:\n{{market_research_landscape}}\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nAddress this in the competitive analysis where relevant.\n{{/additional_notes}}\n\nWrite a competitive landscape analysis that:\n1. Identifies the top 3-5 competitors in the Australian market (use ONLY the competitors listed above — do not invent or guess additional competitors)\n2. For each competitor, describe their market position, strengths, and potential weaknesses\n3. Compares {{company_name}}''s unique strengths against these competitors\n4. Identifies market gaps and opportunities that {{company_name}} can exploit\n5. Provides a strategic positioning recommendation\n\nIf the competitor list is empty, state that no direct competitors were identified through our research and instead provide general guidance on the competitive dynamics of the {{industry_sector}} sector in Australia based on the market research data.\n\nUse ### for subsection headings, **bold** for company names and key terms, and bullet points for comparisons.',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'target_regions', 'enriched_company_profile', 'target_customer_description', 'competitor_analysis_json', 'market_research_landscape', 'additional_notes'],
  updated_at = now()
WHERE section_name = 'competitor_landscape' AND is_active = true;

-- ── 4. Service Providers ──────────────────────────────────────────────
-- Add: target_customer_description, additional_notes
UPDATE report_templates
SET
  prompt_body = E'You are recommending service providers for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering the Australian market.\n\nCompany profile:\n{{enriched_company_profile}}\n\nServices needed: {{services_needed}}\nTarget regions: {{target_regions}}\nBudget level: {{budget_level}}\nTarget customer profile: {{target_customer_description}}\n\nHere are VERIFIED service providers from our directory (with enriched descriptions where available):\n{{matched_providers_json}}\n\nIMPORTANT: Only recommend providers from the list above. Do NOT invent, guess, or hallucinate additional providers not in this list. If the list is empty or contains no relevant providers, state clearly: "We did not find matching service providers in our directory for your specific needs. We recommend browsing our full Service Providers directory at /service-providers for the latest listings."\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nHighlight any providers particularly relevant to this request.\n{{/additional_notes}}\n\nFor each matched provider:\n1. Explain specifically why they are relevant to {{company_name}}''s needs (reference their enriched_description if available)\n2. Highlight which of {{company_name}}''s required services ({{services_needed}}) they can address\n3. Note their location and how it aligns with the target regions\n\nNOTE: Do NOT repeat the full market overview or competitive landscape — focus on provider recommendations.\n\nUse ### for subsection headings and **bold** for provider names.',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'services_needed', 'target_regions', 'budget_level', 'target_customer_description', 'enriched_company_profile', 'matched_providers_json', 'additional_notes'],
  updated_at = now()
WHERE section_name = 'service_providers' AND is_active = true;

-- ── 5. Action Plan ────────────────────────────────────────────────────
-- Add: additional_notes (high priority), target_customer_description, key_challenges
-- Make timeline-adaptive, add dedup instruction
UPDATE report_templates
SET
  prompt_body = E'Create a phased action plan for {{company_name}} to enter Australia.\n\nCompany: {{company_stage}} {{industry_sector}} from {{country_of_origin}}, targeting {{target_regions}}.\nServices needed: {{services_needed}}\nGoals: {{primary_goals}}\nKey challenges: {{key_challenges}}\nTarget customer profile: {{target_customer_description}}\nTimeline: {{timeline}}\nBudget: {{budget_level}}\nRevenue stage: {{revenue_stage}}\n\n--- REGULATORY & COMPLIANCE REQUIREMENTS ---\n{{market_research_regulatory}}\n\n--- MARKET LANDSCAPE ---\n{{market_research_landscape}}\n\n--- RECENT DEVELOPMENTS ---\n{{market_research_news}}\n\n--- BILATERAL TRADE / FUNDING LANDSCAPE ---\n{{market_research_bilateral_trade}}\n\n--- COST OF DOING BUSINESS ---\n{{market_research_cost_of_business}}\n\n--- GOVERNMENT GRANTS & INCENTIVES ---\n{{market_research_grants}}\n\n--- END BUYER INSIGHTS ---\n{{end_buyer_research}}\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST (give this high priority) ---\nThe user has specifically asked the report to cover: {{additional_notes}}\nEnsure this is addressed in the action plan.\n{{/additional_notes}}\n\nADAPT the plan to the company''s stated timeline of "{{timeline}}":\n- "Immediate (0-3 months)": Create a compressed 3-month sprint plan with parallel workstreams.\n- "Short-term (3-6 months)": Standard 3-phase plan over 6 months.\n- "Medium-term (6-12 months)": Detailed 4-phase plan with strategic milestones and decision gates.\n- "Exploratory (12+ months)": Research-first approach with market validation before commitment.\n- "Not specified": Default to a flexible 6-month plan.\n\nEach phase should include:\n1. Specific actions with responsible parties\n2. Estimated costs based on the cost-of-business data above\n3. Key milestones and decision points\n4. Risk mitigation for the user''s stated challenges: {{key_challenges}}\n\nAddress how to approach target customers ({{target_customer_description}}) using end buyer procurement insights.\n\nReference matched service providers where relevant: {{matched_providers_summary}}.\n\nNOTE: Do NOT repeat the executive summary or SWOT analysis. Focus on actionable steps, timelines, and specific next steps.\n\nSources:\n{{market_research_citations}}',
  variables = ARRAY['company_name', 'timeline', 'budget_level', 'company_stage', 'industry_sector', 'country_of_origin', 'target_regions', 'services_needed', 'primary_goals', 'key_challenges', 'target_customer_description', 'revenue_stage', 'additional_notes', 'matched_providers_summary', 'market_research_regulatory', 'market_research_landscape', 'market_research_news', 'market_research_bilateral_trade', 'market_research_cost_of_business', 'market_research_grants', 'end_buyer_research', 'market_research_citations'],
  updated_at = now()
WHERE section_name = 'action_plan' AND is_active = true;

-- ── 6. Lead List ──────────────────────────────────────────────────────
-- Add: target_customer_description, end_buyer_industries, additional_notes
UPDATE report_templates
SET
  prompt_body = E'You are recommending market data and leads for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering the Australian market.\n\nTarget customer profile: {{target_customer_description}}\nTarget customer industries: {{end_buyer_industries}}\nServices needed: {{services_needed}}\nTarget regions: {{target_regions}}\n\nHere are relevant data leads from our directory:\n{{matched_leads_json}}\n\nHere are relevant industry contacts from our network:\n{{matched_lemlist_contacts_json}}\n\nIMPORTANT: Only reference leads from the lists above. Do NOT invent fictional data sources or leads.\n\nIf the lists are empty, state: "We did not find matching data leads for your specific industry. We recommend browsing our Leads directory at /leads for the latest market data offerings."\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nAddress this in lead recommendations where relevant.\n{{/additional_notes}}\n\nFor each matched lead, explain its relevance to {{company_name}}''s market research needs and target customer profile.\n\nAlso suggest 2-3 additional lead generation strategies specific to {{industry_sector}} in Australia, tailored to reaching {{target_customer_description}}.\n\nUse ### for subsection headings and bullet points for recommendations.',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'services_needed', 'target_regions', 'target_customer_description', 'end_buyer_industries', 'matched_leads_json', 'matched_lemlist_contacts_json', 'additional_notes'],
  updated_at = now()
WHERE section_name = 'lead_list' AND is_active = true;

-- ── 7. Mentor Recommendations ─────────────────────────────────────────
-- Add: additional_notes
UPDATE report_templates
SET
  prompt_body = E'You are recommending mentors and community connections for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering the Australian market.\n\nCompany profile:\n{{enriched_company_profile}}\n\nServices needed: {{services_needed}}\nTarget regions: {{target_regions}}\n\nHere are VERIFIED community members from our directory:\n{{matched_mentors_json}}\n\nIMPORTANT: Only recommend mentors from the list above. Do NOT invent or hallucinate additional people. If the list is empty, state: "We did not find matching mentors in our community directory for your specific needs. We recommend browsing our Community page at /community to connect with experienced professionals."\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nHighlight any mentors particularly relevant to this request.\n{{/additional_notes}}\n\nFor each matched mentor, explain why their expertise is relevant to {{company_name}}''s market entry needs.\n\nUse ### for subsection headings and **bold** for mentor names.',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'services_needed', 'target_regions', 'enriched_company_profile', 'matched_mentors_json', 'additional_notes'],
  updated_at = now()
WHERE section_name = 'mentor_recommendations' AND is_active = true;

-- ── 8. Investor Recommendations ───────────────────────────────────────
-- Add: additional_notes, revenue_stage
UPDATE report_templates
SET
  prompt_body = E'You are recommending Australian investors for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering the Australian market.\n\nCompany profile:\n{{enriched_company_profile}}\n\nTheir primary goals: {{primary_goals}}\nBudget level: {{budget_level}}\nTimeline: {{timeline}}\nRevenue stage: {{revenue_stage}}\n\nHere are VERIFIED investors from our directory that match this company''s profile:\n{{matched_investors_json}}\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nAddress this in investor recommendations where relevant.\n{{/additional_notes}}\n\nINSTRUCTIONS:\n1. Only recommend investors from the list above. Do NOT invent or hallucinate investor names.\n2. Group recommendations by investor type (VCs, Angels/Syndicates, Accelerators, Grants, Venture Debt).\n3. For each investor, explain WHY they are a good fit for this specific company (stage alignment, sector overlap, check size match).\n4. Consider the company''s revenue stage ({{revenue_stage}}) when making recommendations.\n5. Suggest a recommended approach order — which investors to contact first based on the company''s current stage and needs.\n6. If the company is very early-stage, prioritise grants, accelerators and angels. If growth-stage, prioritise VCs and venture debt.\n7. Include any relevant tips about the Australian fundraising landscape.\n\nFormat as clean markdown with:\n- H3 headers for each investor type group\n- Bullet points for each investor with name, why they are a fit, and suggested check size range\n- A "Recommended Approach Order" section at the end with numbered steps',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'enriched_company_profile', 'primary_goals', 'budget_level', 'timeline', 'revenue_stage', 'matched_investors_json', 'additional_notes'],
  updated_at = now()
WHERE section_name = 'investor_recommendations' AND is_active = true;

-- ── 9. Events & Resources ─────────────────────────────────────────────
-- Add: additional_notes, dedup instruction
UPDATE report_templates
SET
  prompt_body = E'You are recommending events and resources for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering the Australian market targeting {{target_regions}}.\n\nCompany profile:\n{{enriched_company_profile}}\n\nHere are relevant events from our directory (note: check dates as some may be past editions — they represent recurring event types relevant to your industry):\n{{matched_events_json}}\n\nHere are relevant content resources and case studies:\n{{matched_content_json}}\n\nIMPORTANT: Only reference events and content from the lists above. Do NOT invent fictional events or resources.\n\n{{#additional_notes}}\n--- IMPORTANT: USER''S SPECIFIC REQUEST ---\nThe user has asked the report to cover: {{additional_notes}}\nHighlight events or resources particularly relevant to this request.\n{{/additional_notes}}\n\nWrite recommendations that:\n1. Highlight the most relevant events for networking and market entry\n2. Suggest relevant content resources for preparation\n3. Provide practical advice on how to maximize value from these events\n4. If no events are listed, recommend general industry event types to search for in {{target_regions}}\n\nNOTE: Do NOT repeat service provider or mentor recommendations — focus on events and content resources.\n\nUse ### for subsection headings, **bold** for event/resource names, and bullet points for action items.',
  variables = ARRAY['company_name', 'company_stage', 'industry_sector', 'country_of_origin', 'target_regions', 'enriched_company_profile', 'matched_events_json', 'matched_content_json', 'additional_notes'],
  updated_at = now()
WHERE section_name = 'events_resources' AND is_active = true;
