-- Migration: Seed 21 locations (AU + NZ) via UPSERT, then backfill parent_location_id
-- Updates existing 5 rows (NSW, VIC, QLD, Sydney, Melbourne), inserts 16 new

INSERT INTO public.locations (
  name, slug, description, location_type, parent_location, country,
  hero_title, hero_description,
  government_agency_name, government_agency_contact, government_agency_website,
  business_environment_score, startup_ecosystem_strength,
  key_industries, population, economic_indicators,
  keywords, content_keywords, service_keywords, event_keywords, lead_keywords,
  featured, sort_order, active
) VALUES

-- ============================================================
-- AUSTRALIAN STATES (6)
-- ============================================================
(
  'New South Wales', 'new-south-wales',
  'Australia''s most populous state and economic powerhouse, home to Sydney''s global financial centre and diverse regional economies.',
  'state', NULL, 'Australia',
  'New South Wales Market Entry',
  'Australia''s largest economy with world-class infrastructure and diverse business opportunities across Sydney and regional NSW.',
  'Investment NSW', 'info@investnsw.com.au', 'https://www.invest.nsw.gov.au',
  92, 'Strong',
  ARRAY['Financial Services', 'Technology', 'Healthcare', 'Tourism', 'Agriculture', 'Mining'],
  8200000,
  '{"gdp_aud_billions": 690, "unemployment_rate": 3.4, "avg_weekly_earnings_aud": 1850}'::jsonb,
  ARRAY['nsw', 'new south wales', 'sydney', 'newcastle', 'wollongong'],
  ARRAY['nsw', 'new south wales', 'sydney', 'financial services', 'technology'],
  ARRAY['nsw', 'new south wales', 'sydney', 'financial', 'tech'],
  ARRAY['nsw', 'new south wales', 'sydney', 'fintech', 'startup'],
  ARRAY['nsw', 'new south wales', 'sydney', 'investment'],
  true, 1, true
),
(
  'Victoria', 'victoria',
  'Australia''s cultural and innovation hub centered around Melbourne, with strong manufacturing, education, and startup ecosystems.',
  'state', NULL, 'Australia',
  'Victoria Market Entry',
  'Home to Australia''s cultural capital Melbourne, with strong manufacturing, education, and startup ecosystems.',
  'Invest Victoria', 'info@invest.vic.gov.au', 'https://www.invest.vic.gov.au',
  89, 'Strong',
  ARRAY['Manufacturing', 'Education', 'Healthcare', 'Technology', 'Food & Beverage', 'Creative Industries'],
  6700000,
  '{"gdp_aud_billions": 480, "unemployment_rate": 3.6, "avg_weekly_earnings_aud": 1780}'::jsonb,
  ARRAY['victoria', 'melbourne', 'geelong', 'ballarat'],
  ARRAY['victoria', 'melbourne', 'manufacturing', 'education', 'healthcare'],
  ARRAY['victoria', 'melbourne', 'manufacturing', 'education'],
  ARRAY['victoria', 'melbourne', 'startup', 'innovation'],
  ARRAY['victoria', 'melbourne', 'manufacturing', 'investment'],
  true, 2, true
),
(
  'Queensland', 'queensland',
  'The Sunshine State with growing tech, resources, and tourism sectors, preparing for the 2032 Brisbane Olympics.',
  'state', NULL, 'Australia',
  'Queensland Market Entry',
  'Tropical business environment with strong mining, agriculture, tourism, and emerging technology sectors.',
  'Trade and Investment Queensland', 'info@tiq.qld.gov.au', 'https://www.tiq.qld.gov.au',
  85, 'Growing',
  ARRAY['Mining', 'Agriculture', 'Tourism', 'Technology', 'Renewable Energy', 'Aerospace'],
  5400000,
  '{"gdp_aud_billions": 380, "unemployment_rate": 3.8, "avg_weekly_earnings_aud": 1720}'::jsonb,
  ARRAY['queensland', 'brisbane', 'gold coast', 'sunshine coast', 'cairns'],
  ARRAY['queensland', 'brisbane', 'mining', 'agriculture', 'tourism'],
  ARRAY['queensland', 'brisbane', 'mining', 'agriculture'],
  ARRAY['queensland', 'brisbane', 'mining', 'startup'],
  ARRAY['queensland', 'brisbane', 'mining', 'investment'],
  true, 3, true
),
(
  'Western Australia', 'western-australia',
  'Australia''s resource-rich state driving the national mining and energy economy, with Perth as a growing technology hub.',
  'state', NULL, 'Australia',
  'Western Australia Market Entry',
  'World-leading mining and energy sector with Perth as the closest Australian capital to Asian markets.',
  'Invest and Trade Western Australia', 'info@jtsi.wa.gov.au', 'https://www.investandtrade.wa.gov.au',
  78, 'Growing',
  ARRAY['Mining', 'Oil & Gas', 'Agriculture', 'Defence', 'Space', 'Renewable Energy'],
  2800000,
  '{"gdp_aud_billions": 340, "unemployment_rate": 3.2, "avg_weekly_earnings_aud": 1920}'::jsonb,
  ARRAY['western australia', 'perth', 'wa', 'pilbara', 'kimberley'],
  ARRAY['western australia', 'perth', 'mining', 'energy', 'resources'],
  ARRAY['western australia', 'perth', 'mining', 'energy'],
  ARRAY['western australia', 'perth', 'mining', 'resources'],
  ARRAY['western australia', 'perth', 'mining', 'investment'],
  false, 4, true
),
(
  'South Australia', 'south-australia',
  'A growing innovation hub with strengths in defence, space, wine, and renewable energy centered around Adelaide.',
  'state', NULL, 'Australia',
  'South Australia Market Entry',
  'Adelaide-centred economy with leading defence, space, and renewable energy industries.',
  'Investment Attraction South Australia', 'info@invest.sa.gov.au', 'https://www.invest.sa.gov.au',
  74, 'Emerging',
  ARRAY['Defence', 'Space', 'Wine & Agriculture', 'Renewable Energy', 'Health & Medical', 'Technology'],
  1800000,
  '{"gdp_aud_billions": 130, "unemployment_rate": 4.0, "avg_weekly_earnings_aud": 1650}'::jsonb,
  ARRAY['south australia', 'adelaide', 'sa', 'barossa'],
  ARRAY['south australia', 'adelaide', 'defence', 'space', 'wine'],
  ARRAY['south australia', 'adelaide', 'defence', 'space'],
  ARRAY['south australia', 'adelaide', 'defence', 'innovation'],
  ARRAY['south australia', 'adelaide', 'defence', 'investment'],
  false, 5, true
),
(
  'ACT', 'australian-capital-territory',
  'Australia''s capital territory and centre of government, policy, defence, and cyber security.',
  'state', NULL, 'Australia',
  'ACT Market Entry',
  'National capital with strong government procurement, defence, and cyber security industries.',
  'Canberra Business Chamber', 'info@canberrabusiness.com', 'https://www.canberrabusiness.com',
  70, 'Growing',
  ARRAY['Government', 'Defence', 'Cyber Security', 'Education', 'Space', 'Technology'],
  460000,
  '{"gdp_aud_billions": 45, "unemployment_rate": 3.5, "avg_weekly_earnings_aud": 1900}'::jsonb,
  ARRAY['act', 'canberra', 'australian capital territory'],
  ARRAY['act', 'canberra', 'government', 'defence', 'cyber', 'policy'],
  ARRAY['act', 'canberra', 'government', 'defence', 'cyber'],
  ARRAY['act', 'canberra', 'government', 'defence', 'cyber'],
  ARRAY['act', 'canberra', 'government', 'defence', 'investment'],
  false, 6, true
),

-- ============================================================
-- AUSTRALIAN CITIES (7)
-- ============================================================
(
  'Sydney', 'sydney',
  'Australia''s largest city and financial capital with a global outlook, home to the largest concentration of multinational headquarters in the Asia-Pacific.',
  'city', 'New South Wales', 'Australia',
  'Sydney Market Entry',
  'Global financial centre with world-class business infrastructure and the largest startup ecosystem in Australia.',
  'Investment NSW', 'info@investnsw.com.au', 'https://www.invest.nsw.gov.au',
  95, 'Strong',
  ARRAY['Financial Services', 'Technology', 'Professional Services', 'Tourism', 'Real Estate', 'Media'],
  5300000,
  '{"gdp_aud_billions": 430, "office_vacancy_rate_pct": 10.2, "avg_weekly_rent_aud": 750}'::jsonb,
  ARRAY['sydney', 'nsw', 'harbour city', 'cbd'],
  ARRAY['sydney', 'financial services', 'technology', 'fintech'],
  ARRAY['sydney', 'financial', 'tech', 'professional'],
  ARRAY['sydney', 'fintech', 'startup', 'innovation'],
  ARRAY['sydney', 'financial', 'investment', 'headquarters'],
  true, 10, true
),
(
  'Melbourne', 'melbourne',
  'Australia''s cultural and startup capital, consistently ranked among the world''s most liveable cities with a thriving innovation ecosystem.',
  'city', 'Victoria', 'Australia',
  'Melbourne Market Entry',
  'Thriving startup ecosystem, strong manufacturing base, and world-class education institutions.',
  'Invest Victoria', 'info@invest.vic.gov.au', 'https://www.invest.vic.gov.au',
  91, 'Strong',
  ARRAY['Manufacturing', 'Education', 'Healthcare', 'Creative Industries', 'Food & Beverage', 'Technology'],
  5100000,
  '{"gdp_aud_billions": 350, "office_vacancy_rate_pct": 12.5, "avg_weekly_rent_aud": 620}'::jsonb,
  ARRAY['melbourne', 'victoria', 'cultural capital'],
  ARRAY['melbourne', 'manufacturing', 'education', 'startup'],
  ARRAY['melbourne', 'manufacturing', 'education', 'creative'],
  ARRAY['melbourne', 'startup', 'innovation', 'creative'],
  ARRAY['melbourne', 'manufacturing', 'education', 'investment'],
  true, 11, true
),
(
  'Brisbane', 'brisbane',
  'Queensland''s capital and a fast-growing business hub preparing for the 2032 Olympics with booming infrastructure investment.',
  'city', 'Queensland', 'Australia',
  'Brisbane Market Entry',
  'Fast-growing city with strong liveability, emerging tech sector, and Olympic-driven infrastructure boom.',
  'Trade and Investment Queensland', 'info@tiq.qld.gov.au', 'https://www.tiq.qld.gov.au',
  84, 'Growing',
  ARRAY['Technology', 'Mining Services', 'Aviation', 'Tourism', 'Education', 'Renewable Energy'],
  2600000,
  '{"gdp_aud_billions": 180, "office_vacancy_rate_pct": 11.0, "avg_weekly_rent_aud": 580}'::jsonb,
  ARRAY['brisbane', 'queensland', 'river city'],
  ARRAY['brisbane', 'technology', 'mining', 'aviation', 'olympics'],
  ARRAY['brisbane', 'technology', 'mining', 'aviation'],
  ARRAY['brisbane', 'startup', 'innovation', 'olympics'],
  ARRAY['brisbane', 'technology', 'mining', 'investment'],
  false, 12, true
),
(
  'Perth', 'perth',
  'Western Australia''s capital and gateway to Asia with the closest time zone alignment to Asian markets of any Australian city.',
  'city', 'Western Australia', 'Australia',
  'Perth Market Entry',
  'Resources capital of Australia with growing technology sector and closest proximity to Asian markets.',
  'Invest and Trade Western Australia', 'info@jtsi.wa.gov.au', 'https://www.investandtrade.wa.gov.au',
  77, 'Growing',
  ARRAY['Mining', 'Oil & Gas', 'Technology', 'Defence', 'Agriculture', 'Tourism'],
  2100000,
  '{"gdp_aud_billions": 210, "office_vacancy_rate_pct": 14.0, "avg_weekly_rent_aud": 560}'::jsonb,
  ARRAY['perth', 'western australia', 'wa'],
  ARRAY['perth', 'mining', 'energy', 'resources', 'defence'],
  ARRAY['perth', 'mining', 'energy', 'defence'],
  ARRAY['perth', 'mining', 'resources', 'startup'],
  ARRAY['perth', 'mining', 'energy', 'investment'],
  false, 13, true
),
(
  'Adelaide', 'adelaide',
  'South Australia''s capital with Australia''s largest defence and space precinct and a growing innovation economy.',
  'city', 'South Australia', 'Australia',
  'Adelaide Market Entry',
  'Affordable business hub with Australia''s largest defence and space precinct and thriving food and wine sector.',
  'Investment Attraction South Australia', 'info@invest.sa.gov.au', 'https://www.invest.sa.gov.au',
  73, 'Emerging',
  ARRAY['Defence', 'Space', 'Wine & Food', 'Health & Medical', 'Creative Industries', 'Technology'],
  1400000,
  '{"gdp_aud_billions": 90, "office_vacancy_rate_pct": 15.0, "avg_weekly_rent_aud": 450}'::jsonb,
  ARRAY['adelaide', 'south australia', 'sa'],
  ARRAY['adelaide', 'defence', 'space', 'wine', 'medical'],
  ARRAY['adelaide', 'defence', 'space', 'medical'],
  ARRAY['adelaide', 'defence', 'space', 'innovation'],
  ARRAY['adelaide', 'defence', 'space', 'investment'],
  false, 14, true
),
(
  'Gold Coast', 'gold-coast',
  'Queensland''s second city known for tourism, health, education, and a growing digital innovation scene.',
  'city', 'Queensland', 'Australia',
  'Gold Coast Market Entry',
  'Tourism powerhouse with growing health, education, and digital sectors on Australia''s east coast.',
  'Trade and Investment Queensland', 'info@tiq.qld.gov.au', 'https://www.tiq.qld.gov.au',
  72, 'Emerging',
  ARRAY['Tourism', 'Health & Medical', 'Education', 'Film & Creative', 'Marine Science', 'Technology'],
  700000,
  '{"gdp_aud_billions": 42, "office_vacancy_rate_pct": 9.5, "avg_weekly_rent_aud": 520}'::jsonb,
  ARRAY['gold coast', 'queensland', 'surfers paradise'],
  ARRAY['gold coast', 'tourism', 'health', 'education', 'creative'],
  ARRAY['gold coast', 'tourism', 'health', 'education'],
  ARRAY['gold coast', 'tourism', 'health', 'innovation'],
  ARRAY['gold coast', 'tourism', 'health', 'investment'],
  false, 15, true
),
(
  'Canberra', 'canberra',
  'Australia''s capital city and centre of government procurement, defence, and cyber security with a highly educated workforce.',
  'city', 'ACT', 'Australia',
  'Canberra Market Entry',
  'National capital with strong government procurement pipelines, defence industry, and the highest average incomes in Australia.',
  'Canberra Business Chamber', 'info@canberrabusiness.com', 'https://www.canberrabusiness.com',
  69, 'Growing',
  ARRAY['Government', 'Defence', 'Cyber Security', 'Education', 'Space', 'Technology'],
  460000,
  '{"gdp_aud_billions": 45, "office_vacancy_rate_pct": 8.0, "avg_weekly_rent_aud": 590}'::jsonb,
  ARRAY['canberra', 'act', 'australian capital territory'],
  ARRAY['canberra', 'government', 'defence', 'cyber', 'policy'],
  ARRAY['canberra', 'government', 'defence', 'cyber'],
  ARRAY['canberra', 'government', 'defence', 'cyber'],
  ARRAY['canberra', 'government', 'defence', 'investment'],
  false, 16, true
),

-- ============================================================
-- NEW ZEALAND REGIONS (4)
-- ============================================================
(
  'Auckland Region', 'auckland-region',
  'New Zealand''s most populous region and commercial capital, driving the country''s technology, finance, and international trade.',
  'region', NULL, 'New Zealand',
  'Auckland Region Market Entry',
  'New Zealand''s largest economic region with a diverse, internationally connected business environment.',
  'Auckland Unlimited', 'info@aucklandnz.com', 'https://www.aucklandnz.com',
  88, 'Strong',
  ARRAY['Technology', 'Financial Services', 'Film & Creative', 'Food & Beverage', 'Marine', 'Tourism'],
  1700000,
  '{"gdp_nzd_billions": 120, "unemployment_rate": 3.9, "avg_weekly_earnings_nzd": 1350}'::jsonb,
  ARRAY['auckland', 'auckland region', 'new zealand', 'nz'],
  ARRAY['auckland', 'technology', 'finance', 'film', 'food'],
  ARRAY['auckland', 'technology', 'finance', 'creative'],
  ARRAY['auckland', 'technology', 'startup', 'innovation'],
  ARRAY['auckland', 'technology', 'finance', 'investment'],
  true, 20, true
),
(
  'Wellington Region', 'wellington-region',
  'New Zealand''s capital region and centre of government, creative industries, and technology innovation.',
  'region', NULL, 'New Zealand',
  'Wellington Region Market Entry',
  'Compact capital region with thriving government, tech, and creative sectors including world-famous film industry.',
  'WellingtonNZ', 'info@wellingtonnz.com', 'https://www.wellingtonnz.com',
  82, 'Growing',
  ARRAY['Government', 'Technology', 'Film & Creative', 'Education', 'Professional Services', 'Tourism'],
  540000,
  '{"gdp_nzd_billions": 45, "unemployment_rate": 3.7, "avg_weekly_earnings_nzd": 1400}'::jsonb,
  ARRAY['wellington', 'wellington region', 'new zealand', 'nz'],
  ARRAY['wellington', 'government', 'technology', 'film', 'creative'],
  ARRAY['wellington', 'government', 'technology', 'creative'],
  ARRAY['wellington', 'government', 'tech', 'innovation'],
  ARRAY['wellington', 'government', 'technology', 'investment'],
  true, 21, true
),
(
  'Canterbury', 'canterbury',
  'New Zealand''s largest region by area with Christchurch as its rebuilt, modern urban centre and strong agritech sector.',
  'region', NULL, 'New Zealand',
  'Canterbury Market Entry',
  'Post-earthquake rebuild has created a modern city with strong agritech, engineering, and renewable energy sectors.',
  'ChristchurchNZ', 'info@christchurchnz.com', 'https://www.christchurchnz.com',
  75, 'Growing',
  ARRAY['Agriculture', 'Engineering', 'Technology', 'Tourism', 'Renewable Energy', 'Manufacturing'],
  640000,
  '{"gdp_nzd_billions": 38, "unemployment_rate": 3.5, "avg_weekly_earnings_nzd": 1280}'::jsonb,
  ARRAY['canterbury', 'christchurch', 'new zealand', 'nz'],
  ARRAY['canterbury', 'christchurch', 'agriculture', 'engineering', 'technology'],
  ARRAY['canterbury', 'christchurch', 'agriculture', 'engineering'],
  ARRAY['canterbury', 'christchurch', 'agritech', 'innovation'],
  ARRAY['canterbury', 'christchurch', 'agriculture', 'investment'],
  false, 22, true
),
(
  'Waikato', 'waikato',
  'New Zealand''s agricultural heartland with Hamilton as its growing urban centre and emerging agritech innovation hub.',
  'region', NULL, 'New Zealand',
  'Waikato Market Entry',
  'Rich agricultural region with emerging agritech, dairy innovation, and strong university research links.',
  'Te Waka (Waikato Economic Development)', 'info@tewaka.nz', 'https://www.tewaka.nz',
  68, 'Emerging',
  ARRAY['Agriculture', 'Dairy', 'Agritech', 'Education', 'Manufacturing', 'Tourism'],
  510000,
  '{"gdp_nzd_billions": 28, "unemployment_rate": 3.8, "avg_weekly_earnings_nzd": 1220}'::jsonb,
  ARRAY['waikato', 'hamilton', 'new zealand', 'nz'],
  ARRAY['waikato', 'hamilton', 'agriculture', 'dairy', 'agritech'],
  ARRAY['waikato', 'hamilton', 'agriculture', 'dairy'],
  ARRAY['waikato', 'hamilton', 'agritech', 'innovation'],
  ARRAY['waikato', 'hamilton', 'agriculture', 'investment'],
  false, 23, true
),

-- ============================================================
-- NEW ZEALAND CITIES (4)
-- ============================================================
(
  'Auckland', 'auckland',
  'New Zealand''s largest city and primary gateway for international business, with a diverse Asia-Pacific connected economy.',
  'city', 'Auckland Region', 'New Zealand',
  'Auckland Market Entry',
  'Asia-Pacific gateway city with diverse economy spanning technology, food and beverage, and financial services.',
  'Auckland Council', 'info@aucklandcouncil.govt.nz', 'https://www.aucklandcouncil.govt.nz',
  90, 'Strong',
  ARRAY['Technology', 'Financial Services', 'Film & Creative', 'Food & Beverage', 'Marine', 'Healthcare'],
  1650000,
  '{"office_vacancy_rate_pct": 11.0, "avg_weekly_rent_nzd": 650}'::jsonb,
  ARRAY['auckland', 'auckland city', 'new zealand', 'nz'],
  ARRAY['auckland', 'technology', 'finance', 'film', 'food'],
  ARRAY['auckland', 'technology', 'finance', 'creative'],
  ARRAY['auckland', 'technology', 'startup', 'innovation'],
  ARRAY['auckland', 'technology', 'finance', 'investment'],
  false, 30, true
),
(
  'Wellington', 'wellington',
  'New Zealand''s capital city, creative tech hub, and home to world-class film post-production and government procurement.',
  'city', 'Wellington Region', 'New Zealand',
  'Wellington Market Entry',
  'Compact capital with world-class film industry, thriving cafe culture, and strong government procurement pipelines.',
  'Wellington City Council', 'info@wcc.govt.nz', 'https://wellington.govt.nz',
  83, 'Growing',
  ARRAY['Government', 'Technology', 'Film & Post-production', 'Education', 'Professional Services', 'Creative'],
  215000,
  '{"office_vacancy_rate_pct": 8.5, "avg_weekly_rent_nzd": 580}'::jsonb,
  ARRAY['wellington', 'wellington city', 'new zealand', 'nz'],
  ARRAY['wellington', 'government', 'technology', 'film', 'creative'],
  ARRAY['wellington', 'government', 'technology', 'creative'],
  ARRAY['wellington', 'government', 'tech', 'innovation'],
  ARRAY['wellington', 'government', 'technology', 'investment'],
  false, 31, true
),
(
  'Christchurch', 'christchurch',
  'Canterbury''s rebuilt city with modern infrastructure, cutting-edge engineering sector, and strong innovation culture.',
  'city', 'Canterbury', 'New Zealand',
  'Christchurch Market Entry',
  'New Zealand''s most modern urban centre, rebuilt after the earthquakes with cutting-edge infrastructure and growing tech scene.',
  'ChristchurchNZ', 'info@christchurchnz.com', 'https://www.christchurchnz.com',
  74, 'Growing',
  ARRAY['Engineering', 'Technology', 'Agriculture', 'Tourism', 'Renewable Energy', 'Manufacturing'],
  390000,
  '{"office_vacancy_rate_pct": 12.0, "avg_weekly_rent_nzd": 450}'::jsonb,
  ARRAY['christchurch', 'canterbury', 'new zealand', 'nz'],
  ARRAY['christchurch', 'engineering', 'technology', 'agriculture'],
  ARRAY['christchurch', 'engineering', 'technology', 'agriculture'],
  ARRAY['christchurch', 'engineering', 'tech', 'innovation'],
  ARRAY['christchurch', 'engineering', 'technology', 'investment'],
  false, 32, true
),
(
  'Hamilton', 'hamilton',
  'Waikato''s main city and New Zealand''s agritech innovation centre with strong university research links.',
  'city', 'Waikato', 'New Zealand',
  'Hamilton Market Entry',
  'Fast-growing city with strong university research links, agritech innovation hub, and affordable business costs.',
  'Hamilton City Council', 'info@hcc.govt.nz', 'https://www.hamilton.govt.nz',
  67, 'Emerging',
  ARRAY['Agriculture', 'Dairy Processing', 'Agritech', 'Education', 'Manufacturing', 'Healthcare'],
  180000,
  '{"office_vacancy_rate_pct": 10.0, "avg_weekly_rent_nzd": 420}'::jsonb,
  ARRAY['hamilton', 'waikato', 'new zealand', 'nz'],
  ARRAY['hamilton', 'agriculture', 'dairy', 'agritech', 'education'],
  ARRAY['hamilton', 'agriculture', 'dairy', 'agritech'],
  ARRAY['hamilton', 'agritech', 'dairy', 'innovation'],
  ARRAY['hamilton', 'agriculture', 'dairy', 'investment'],
  false, 33, true
)

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  location_type = EXCLUDED.location_type,
  parent_location = EXCLUDED.parent_location,
  country = EXCLUDED.country,
  hero_title = EXCLUDED.hero_title,
  hero_description = EXCLUDED.hero_description,
  government_agency_name = EXCLUDED.government_agency_name,
  government_agency_contact = EXCLUDED.government_agency_contact,
  government_agency_website = EXCLUDED.government_agency_website,
  business_environment_score = EXCLUDED.business_environment_score,
  startup_ecosystem_strength = EXCLUDED.startup_ecosystem_strength,
  key_industries = EXCLUDED.key_industries,
  population = EXCLUDED.population,
  economic_indicators = EXCLUDED.economic_indicators,
  keywords = EXCLUDED.keywords,
  content_keywords = EXCLUDED.content_keywords,
  service_keywords = EXCLUDED.service_keywords,
  event_keywords = EXCLUDED.event_keywords,
  lead_keywords = EXCLUDED.lead_keywords,
  featured = EXCLUDED.featured,
  sort_order = EXCLUDED.sort_order,
  active = EXCLUDED.active,
  updated_at = now();

-- ============================================================
-- Backfill parent_location_id by matching text parent_location to parent name
-- ============================================================
UPDATE public.locations child
SET parent_location_id = parent.id
FROM public.locations parent
WHERE child.parent_location IS NOT NULL
  AND child.parent_location = parent.name
  AND child.parent_location_id IS NULL;
