-- ============================================================================
-- ZOOM CASE STUDY DEEP REWRITE
-- Enriched with multi-source research, March 2026
-- ============================================================================

-- 1. Update content_items metadata
UPDATE public.content_items
SET
  title = 'How Zoom Entered the Australian Market',
  subtitle = 'From Australia''s first employee in 2017 to 134% ANZ revenue growth: how Zoom rode a pandemic adoption surge, built a 10-year education partnership, and pivoted to an AI-first platform to survive the post-lockdown slowdown',
  read_time = 14,
  meta_description = 'Deep-dive case study on how Zoom grew 134% in ANZ revenue, partnered with AARNet to reach two-thirds of Australian universities, survived Zoombombing and post-pandemic layoffs, and pivoted to AI Companion and Zoom Workplace.',
  sector_tags = ARRAY['technology', 'communications', 'video-conferencing', 'saas', 'cloud-computing', 'remote-work', 'education', 'unified-communications'],
  updated_at = NOW()
WHERE slug = 'zoom-australia-market-entry';

-- 2. Update company profile
UPDATE public.content_company_profiles
SET
  industry = 'Unified Communications and AI-First Collaboration Platform',
  origin_country = 'United States',
  target_market = 'Australia',
  entry_date = '2017',
  outcome = 'successful',
  business_model = 'B2B/B2C SaaS / Subscription Platform (Freemium)'
WHERE content_id = (SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry');

-- 3. Delete existing sections and bodies
DELETE FROM public.content_sections
WHERE content_id = (SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry');

DELETE FROM public.content_bodies
WHERE content_id = (SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry');

-- 4. Insert new sections
INSERT INTO public.content_sections (content_id, title, slug, sort_order, is_active) VALUES
((SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry'), 'Entry Strategy', 'entry-strategy', 1, true),
((SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry'), 'Success Factors', 'success-factors', 2, true),
((SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry'), 'Key Metrics & Performance', 'key-metrics', 3, true),
((SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry'), 'Challenges Faced', 'challenges-faced', 4, true),
((SELECT id FROM public.content_items WHERE slug = 'zoom-australia-market-entry'), 'Lessons Learned', 'lessons-learned', 5, true);

-- 5. Insert enriched content bodies

-- ===================== ENTRY STRATEGY =====================
INSERT INTO public.content_bodies (section_id, body_text, sort_order, content_type) VALUES

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>Zoom''s Australian presence began in April 2017 when Michael Chetner joined as the company''s first employee in the region, taking the role of Head of Australia and New Zealand. Chetner — previously at Cisco — built a sales and support office in Sydney and established a local data centre through Equinix facilities in both Sydney and Melbourne, ensuring low-latency performance and data residency for Australian customers. Australia was designated as its own distinct data centre region within Zoom''s global infrastructure, allowing paying customers to select Australia for data processing and storage — a critical requirement for enterprise and government accounts operating under the Privacy Act 1988 and Australian Privacy Principles.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.arnnet.com.au/article/705793/zoom-anz-head-michael-chetner-resigns/" target="_blank" rel="noopener noreferrer">ARN</a>, <a href="https://datacenterlocations.com/zoom/" target="_blank" rel="noopener noreferrer">Data Center Locations</a></em></p>', 1, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>Zoom''s initial go-to-market strategy targeted organisations contending with Australia''s dispersed population and connectivity challenges — positioning video communications as a solution to the geographic barriers that had long constrained collaboration across the country''s vast distances. In its first 18 months, Zoom built strategic partnerships with Slack, Box, and Okta in Australia to provide integrated collaboration and security, and partnered with Workplace by Facebook and Crestron for hardware integration in meeting rooms. Chetner was promoted to Head of Australia and Asia Pacific in November 2018, overseeing expansion across the broader APAC region from Sydney.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Source: <a href="https://blog.zoom.us/zoom-announces-134-percent-revenue-growth-australia-new-zealand/" target="_blank" rel="noopener noreferrer">Zoom Blog</a></em></p>', 2, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>On July 23, 2019, Zoom launched Zoom Phone in Australia — its cloud phone service offering native PSTN access with local phone numbers, Metered and Unlimited Calling Plans, and a Bring Your Own Carrier (BYOC) option allowing organisations to retain existing SIP trunks while migrating to the Zoom platform. Frost &amp; Sullivan analyst Elka Popova called it "a bold foray into the UCaaS market." This flexible deployment model was critical for the Australian market, where enterprises had deep existing relationships with incumbent telcos (Telstra, Optus) and were reluctant to rip and replace established telephony infrastructure. In May 2021, Zoom appointed Dicker Data as its first distributor in Australia and New Zealand, giving its channel partners access to the full product range alongside competing Microsoft Teams and Cisco Webex offerings already in Dicker Data''s portfolio.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.globenewswire.com/news-release/2019/07/23/1886725/0/en/Zoom-Announces-Zoom-Phone-Launch-in-Australia-and-the-United-Kingdom.html" target="_blank" rel="noopener noreferrer">GlobeNewsWire</a>, <a href="https://www.arnnet.com.au/article/688298/dicker-data-inks-nz-distie-deal-zoom/" target="_blank" rel="noopener noreferrer">ARN</a></em></p>', 3, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'entry-strategy'),
'<p>Zoom''s most significant Australian channel partnership preceded its own office. In 2014 — three years before Chetner''s hire — AARNet (Australia''s Academic and Research Network) visited Zoom''s San Jose headquarters to investigate its then-new video conferencing technology and subsequently became the first organisation in Australia to provide licensing and support for Zoom. AARNet, whose shareholders are 38 Australian universities and the CSIRO, provided Zoom with immediate access to over two million end users across Australia''s research and education sector. By hosting Zoom servers on its own network, AARNet delivered a high-bandwidth, high-quality experience with local support and cloud recording integration — effectively giving Zoom an enterprise-grade Australian distribution channel before it had a single employee in the country.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Source: <a href="https://www.aarnet.edu.au/aarnet-and-zoom-mark-10-years-transforming-communication-and-collaboration-in-education" target="_blank" rel="noopener noreferrer">AARNet</a></em></p>', 4, 'paragraph'),

-- ===================== SUCCESS FACTORS =====================
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'success-factors'),
'<p>COVID-19 transformed Zoom from a business communications tool into essential infrastructure for work, education, and social connection across Australia. During lockdowns, Zoom usage across AARNet''s education network peaked at 70 times higher than 2019 levels, exceeding 1.2 billion meeting minutes in a single month at the height of eastern states lockdowns. Virtually every Australian organisation — from government departments to schools to aged care facilities — became a Zoom user almost overnight. The platform''s reputation for being easy to deploy, straightforward to use without training, and reliable under extreme demand loads cemented its position as the default video conferencing platform during the most critical adoption window in the history of remote work.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Source: <a href="https://www.aarnet.edu.au/zooming-beyond-covid-did-the-pace-of-learning-really-zoom-or-just-the-tools" target="_blank" rel="noopener noreferrer">AARNet</a></em></p>', 1, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'success-factors'),
'<p>The AARNet partnership proved transformative for education adoption. By 2024 — the 10-year anniversary of the partnership, celebrated at Zoom''s San Jose headquarters during an Australian American Leadership Dialogue event — AARNet served around two-thirds of Australia''s universities, over 100 K-12 schools, and numerous research institutions as a Zoom reseller. AARNet became Zoom''s first Platinum Partner in Australia. Western Sydney University reported over 10,000 staff and student Zoom users with monthly meeting minutes peaking at over 850,000 minutes. Central Queensland University adopted Zoom for distance education, and the University of Tasmania used it to rethink hybrid learning during and after COVID. Even post-pandemic, education usage remained 10 to 15 times higher than pre-COVID levels.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.aarnet.edu.au/aarnet-and-zoom-mark-10-years-transforming-communication-and-collaboration-in-education" target="_blank" rel="noopener noreferrer">AARNet</a>, <a href="https://www.aarnet.edu.au/transforming-online-collaboration-for-australian-universities" target="_blank" rel="noopener noreferrer">AARNet</a></em></p>', 2, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'success-factors'),
'<p>Chetner''s go-to-market strategy targeted Australian tech startups first — winning Canva, Atlassian, and Safety Culture as early customers — before moving upmarket. Winning National Australia Bank (NAB) as an early enterprise adopter provided critical credibility in financial services. Key enterprise customers grew to include REA Group (1,100 regular users, 20 Zoom Rooms, over 6,000 meetings logged), SEEK, The Movember Foundation, and Planet Innovation. Zoom rapidly expanded from pure video conferencing into a unified communications platform encompassing Zoom Phone, Zoom Rooms, Zoom Webinars, and Zoom Contact Center — which launched across ANZ in 2023, entering the contact centre as a service (CCaaS) market with Phil Zammit appointed as Head of Zoom Customer Experience for Asia Pacific and Japan. Zoom Virtual Agent, an AI-powered conversational chatbot, launched alongside. For Australian enterprises, the ability to consolidate multiple communication tools onto a single platform — replacing legacy PBX phone systems, separate webinar tools, and standalone contact centre software — created significant operational savings.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://blog.zoom.us/zoom-announces-134-percent-revenue-growth-australia-new-zealand/" target="_blank" rel="noopener noreferrer">Zoom Blog</a>, <a href="https://itbrief.com.au/story/zoom-virtual-agent-launch-promises-big-things-for-anz-businesses" target="_blank" rel="noopener noreferrer">IT Brief</a></em></p>', 3, 'paragraph'),

-- ===================== KEY METRICS & PERFORMANCE =====================
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'key-metrics'),
'<p>Zoom achieved 134% revenue growth and a 105% increase in its customer base across Australia and New Zealand following its Australian launch, fuelled by what CEO Eric Yuan described as "a demand for easy and secure meeting experiences." Under Chetner''s leadership (2017-2023), the APAC business grew from approximately US$200,000 to triple-digit millions in annual recurring revenue — over 500x growth. APAC accounted for 13% of Zoom''s global revenue at US$140.9 million in FY2023. The Sydney office grew to over 150 employees. During the pandemic peak, AARNet''s education network alone recorded 1.2 billion Zoom meeting minutes in a single month — 70 times the pre-COVID baseline — with post-pandemic usage stabilising at 10-15x pre-COVID levels. Zoom held approximately 56% of the global video conferencing market share in 2025, compared to Microsoft Teams'' 32%, though Teams leads in daily active users (320 million vs 300 million) due to its Microsoft 365 bundling.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://blog.zoom.us/zoom-announces-134-percent-revenue-growth-australia-new-zealand/" target="_blank" rel="noopener noreferrer">Zoom Blog</a>, <a href="https://electroiq.com/stats/zoom-vs-microsoft-teams-statistics/" target="_blank" rel="noopener noreferrer">ElectroIQ</a></em></p>', 1, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'key-metrics'),
'<p>Globally, Zoom''s annual revenue reached US$4.665 billion in FY2025 (ending January 2025), with Q3 FY2026 revenue of US$1.23 billion (up 4.4% year-over-year) and enterprise revenue of US$741.4 million. The company reported 4,363 customers contributing more than US$100,000 in trailing 12-month revenue — a 9.2% increase year-over-year — and over 504,900 business customers worldwide. However, total business customers declined from 220,000 in 2023 to 192,600 in late 2024, reflecting the post-pandemic churn of smaller accounts. Zoom''s stock trajectory told the full story: from a US$36 IPO in April 2019 to a US$568 pandemic peak in October 2020 (US$139 billion market cap), then a 90% decline to US$55 in August 2024 (US$18 billion) before recovering to US$77 by March 2026. The product portfolio expanded to include Zoom Workplace, Zoom Phone (native PSTN in 49+ countries), Zoom Contact Center, Zoom Rooms, Zoom Events, and AI Companion — included at no additional cost for paid users, with a Custom AI Add-on at US$12/user/month.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.globenewswire.com/news-release/2025/02/24/3031536/0/en/Zoom-Communications-Reports-Fourth-Quarter-and-Fiscal-Year-2025-Financial-Results.html" target="_blank" rel="noopener noreferrer">GlobeNewsWire</a>, <a href="https://www.macrotrends.net/stocks/charts/ZM/zoom-communications/revenue" target="_blank" rel="noopener noreferrer">MacroTrends</a></em></p>', 2, 'paragraph'),

-- ===================== CHALLENGES FACED =====================
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'challenges-faced'),
'<p>Microsoft Teams — bundled at no additional cost with Microsoft 365 — represented Zoom''s most formidable competitive threat in Australia. Many organisations defaulted to Teams simply because they already paid for it, and with 93% of Fortune 100 companies using Teams and strong Australian enterprise adoption, Zoom faced a structural pricing disadvantage in every account where Microsoft 365 was already deployed. Australian Parliamentary Services explicitly banned Zoom and adopted Microsoft Office 365 as its "collaborative platform that has conference facilities." Cisco Webex maintained deep relationships with Australian enterprises, and incumbent telcos (Telstra, Optus) offered their own managed video conferencing solutions with existing billing relationships and local support. As Bede Hackney, who succeeded Chetner as ANZ head in June 2023, acknowledged: "Everyone associates Zoom with just meetings. One of our challenges is to help people see that we''re just so much more than that today."</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.arnnet.com.au/article/1253750/zoom-a-nz-lead-video-conferencing-is-our-greatest-strength-and-greatest-challenge.html" target="_blank" rel="noopener noreferrer">ARN</a>, <a href="https://www.demandsage.com/microsoft-teams-statistics/" target="_blank" rel="noopener noreferrer">DemandSage</a></em></p>', 1, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'challenges-faced'),
'<p>Security concerns erupted in early 2020 when rapid consumer adoption outpaced security controls, leading to "Zoombombing" incidents in Australian schools and organisations — uninvited attendees hijacking sessions with offensive material. The Australian Defence Force banned Zoom entirely. AARNet published guidance for Australian education institutions, noting that all customers on their hosted Zoom platform had encryption keys maintained within Australia on AARNet infrastructure. The University of Toronto''s Citizen Lab raised questions about server routing, though Zoom''s infrastructure maintained geo-fencing around China — using a facility owned by Telstra. Zoom responded with 100 new safety features in 90 days, including default meeting passwords, waiting rooms, and enhanced encryption, but the reputational damage required sustained effort to overcome in security-conscious enterprise and government accounts.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://news.aarnet.edu.au/aarnet-response-to-zoom-security-issues/" target="_blank" rel="noopener noreferrer">AARNet</a>, <a href="https://en.wikipedia.org/wiki/Zoombombing" target="_blank" rel="noopener noreferrer">Wikipedia</a></em></p>', 2, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'challenges-faced'),
'<p>The post-pandemic correction hit Zoom hard. In February 2023, the company cut 1,300 employees globally — 15% of its workforce — after tripling headcount during the pandemic without, as CEO Yuan admitted, taking "as much time as we should have to thoroughly analyse our teams." Yuan took a 98% salary cut and forfeited his bonus; the executive team took 20% cuts. In Australia, ANZ head Michael Chetner resigned during the same period, and NZ regional sales manager Jaron Burbidge was among those made redundant. Ricky Kapur (APAC head) managed the ANZ region until Bede Hackney — previously Regional VP ANZ at Databricks — was appointed in June 2023. Hackney subsequently expanded the team beyond Sydney to Melbourne and Brisbane, appointed Mike Johnson as Head of Channel for ANZ, and refocused on enterprise upsell and AI-powered platform differentiation. Hackney himself later departed for Sigma Computing, underscoring the leadership instability that characterised Zoom''s post-pandemic transition.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://www.crn.com.au/news/zoom-australia-and-new-zealand-boss-quits-591268" target="_blank" rel="noopener noreferrer">CRN Australia</a>, <a href="https://www.crn.com.au/news/zoom-names-bede-hackney-as-anz-chief-596488" target="_blank" rel="noopener noreferrer">CRN Australia</a>, <a href="https://fortune.com/2023/02/07/zoom-layoffs-1300-jobs-cut-pandemic-hiring-spree/" target="_blank" rel="noopener noreferrer">Fortune</a></em></p>', 3, 'paragraph'),

-- ===================== LESSONS LEARNED =====================
((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>A channel partner can build your market before you arrive.</strong> AARNet''s 2014 partnership gave Zoom access to over two million Australian education users three years before it hired its first local employee. By the time Zoom established its Sydney office in 2017, it had an established, paying customer base across two-thirds of Australian universities with locally hosted infrastructure and support. Companies entering Australia should identify sector-specific distributors — like AARNet for education or Telstra for enterprise — who can provide licensing, support, and infrastructure before committing to a local office.</p>', 1, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>Product simplicity creates adoption velocity that feature breadth cannot replicate.</strong> Zoom''s core advantage — being genuinely easy to use without training — enabled viral adoption during COVID-19 that competitors with more complex products could not match. Usage across AARNet''s network grew 3,000% in a single month. Microsoft Teams had more features and was bundled free with Office 365, but Zoom''s simplicity won the adoption race when speed mattered most. For companies entering Australia, optimising for immediate usability creates adoption velocity that no amount of feature engineering can replicate — especially in crisis-driven adoption scenarios.</p>', 2, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>Expand the platform before the growth wave crests, not after.</strong> Zoom''s expansion into Phone, Contact Center, Virtual Agent, and AI Companion ensured that pandemic-driven customers had reasons to stay and spend more as initial video conferencing demand normalised. The BYOC option for Zoom Phone — allowing organisations to retain existing SIP trunks — removed the biggest barrier to platform consolidation in risk-averse Australian enterprises. Companies entering Australia should plan their product expansion roadmap before the initial growth wave plateaus, and always offer gradual migration paths rather than requiring rip-and-replace.</p>', 3, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>Pandemic-scale growth requires pandemic-scale discipline — or the correction will be brutal.</strong> Zoom tripled its workforce during COVID without adequate workforce planning, then cut 15% globally in February 2023. In Australia, the ANZ head resigned, staff were made redundant, and leadership turned over twice in two years. CEO Yuan''s candid admission — "we didn''t take as much time as we should have to thoroughly analyse our teams" — is a cautionary tale for any company experiencing hypergrowth in Australia. Scaling hiring to match demand is essential, but building sustainable team structures matters more than speed. Companies that over-hire during a demand spike will face painful, reputation-damaging layoffs when conditions normalise.</p>', 4, 'paragraph'),

((SELECT cs.id FROM public.content_sections cs JOIN public.content_items ci ON cs.content_id = ci.id WHERE ci.slug = 'zoom-australia-market-entry' AND cs.slug = 'lessons-learned'),
'<p><strong>Security incidents in one market become global reputation events — prepare defences before you scale.</strong> Zoombombing incidents in Australian schools and the Australian Defence Force''s ban on Zoom created reputational damage that required sustained effort to overcome in security-conscious enterprise and government accounts. Zoom shipped 100 security fixes in 90 days, but the damage was already done. Companies entering Australia — particularly those serving education and government — should anticipate that security incidents will be amplified by media coverage and regulatory scrutiny, and should invest in security defaults (not just security features) before rapid adoption exposes vulnerabilities at scale.</p>
<p class="text-sm text-muted-foreground mt-4"><em>Sources: <a href="https://blog.zoom.us/zoom-announces-134-percent-revenue-growth-australia-new-zealand/" target="_blank" rel="noopener noreferrer">Zoom Blog</a>, <a href="https://www.aarnet.edu.au/aarnet-and-zoom-mark-10-years-transforming-communication-and-collaboration-in-education" target="_blank" rel="noopener noreferrer">AARNet</a>, <a href="https://www.arnnet.com.au/article/1253750/zoom-a-nz-lead-video-conferencing-is-our-greatest-strength-and-greatest-challenge.html" target="_blank" rel="noopener noreferrer">ARN</a>, <a href="https://fortune.com/2023/02/07/zoom-layoffs-1300-jobs-cut-pandemic-hiring-spree/" target="_blank" rel="noopener noreferrer">Fortune</a></em></p>', 5, 'paragraph');
