-- MES-110 Phase B step 1: canonical LinkedIn sector reference (additive, no consumers yet).
--
-- Adds the pinned legacy LinkedIn industry-codes table (147 entries, stable numeric
-- codes) as the platform's stable-identifier layer, plus the crosswalk from the 152
-- LinkedIn V2 industry groups (the live intake/tagging vocabulary in
-- linkedin_industries / src/constants/linkedinTaxonomy.ts) to those codes.
-- Source of truth: docs/audits/mes-110/linkedin-industry-codes-147.csv and
-- docs/audits/mes-110/mapping-v2-industry-groups-to-147.csv (approved in PR #320).
-- Reference data only — no PII; clients read, service role writes.

create table if not exists public.sectors (
  code integer primary key,
  description text not null unique,
  groups text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.sectors is
  'Canonical LinkedIn industry codes (legacy 147-entry table, MES-110). code is the stable identifier; description is the canonical sector name, verbatim.';

create table if not exists public.sector_group_crosswalk (
  v2_industry_group text primary key,
  v2_sector_slug text not null,
  linkedin_code integer not null references public.sectors(code),
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  note text
);

comment on table public.sector_group_crosswalk is
  'MES-110 crosswalk: LinkedIn V2 industry group (intake vocabulary) -> canonical 147-entry LinkedIn code. v2_sector_slug matches the sector_tags slugs used by the report matcher.';

alter table public.sectors enable row level security;
alter table public.sector_group_crosswalk enable row level security;

drop policy if exists "Sectors are publicly readable" on public.sectors;
create policy "Sectors are publicly readable"
  on public.sectors for select using (true);

drop policy if exists "Sector crosswalk is publicly readable" on public.sector_group_crosswalk;
create policy "Sector crosswalk is publicly readable"
  on public.sector_group_crosswalk for select using (true);

-- SEC-01: reference tables are service-role-write-only; scope the broad default grants away.
revoke insert, update, delete, truncate on public.sectors from anon, authenticated;
revoke insert, update, delete, truncate on public.sector_group_crosswalk from anon, authenticated;

insert into public.sectors (code, description, groups) values
  (1, 'Defense & Space', array['gov', 'tech']::text[]),
  (3, 'Computer Hardware', array['tech']::text[]),
  (4, 'Computer Software', array['tech']::text[]),
  (5, 'Computer Networking', array['tech']::text[]),
  (6, 'Internet', array['tech']::text[]),
  (7, 'Semiconductors', array['tech']::text[]),
  (8, 'Telecommunications', array['gov', 'tech']::text[]),
  (9, 'Law Practice', array['leg']::text[]),
  (10, 'Legal Services', array['leg']::text[]),
  (11, 'Management Consulting', array['corp']::text[]),
  (12, 'Biotechnology', array['gov', 'hlth', 'tech']::text[]),
  (13, 'Medical Practice', array['hlth']::text[]),
  (14, 'Hospital & Health Care', array['hlth']::text[]),
  (15, 'Pharmaceuticals', array['hlth', 'tech']::text[]),
  (16, 'Veterinary', array['hlth']::text[]),
  (17, 'Medical Devices', array['hlth']::text[]),
  (18, 'Cosmetics', array['good']::text[]),
  (19, 'Apparel & Fashion', array['good']::text[]),
  (20, 'Sporting Goods', array['good', 'rec']::text[]),
  (21, 'Tobacco', array['good']::text[]),
  (22, 'Supermarkets', array['good']::text[]),
  (23, 'Food Production', array['good', 'man', 'serv']::text[]),
  (24, 'Consumer Electronics', array['good', 'man']::text[]),
  (25, 'Consumer Goods', array['good', 'man']::text[]),
  (26, 'Furniture', array['good', 'man']::text[]),
  (27, 'Retail', array['good', 'man']::text[]),
  (28, 'Entertainment', array['med', 'rec']::text[]),
  (29, 'Gambling & Casinos', array['rec']::text[]),
  (30, 'Leisure, Travel & Tourism', array['rec', 'serv', 'tran']::text[]),
  (31, 'Hospitality', array['rec', 'serv', 'tran']::text[]),
  (32, 'Restaurants', array['rec', 'serv']::text[]),
  (33, 'Sports', array['rec']::text[]),
  (34, 'Food & Beverages', array['rec', 'serv']::text[]),
  (35, 'Motion Pictures and Film', array['art', 'med', 'rec']::text[]),
  (36, 'Broadcast Media', array['med', 'rec']::text[]),
  (37, 'Museums and Institutions', array['art', 'med', 'rec']::text[]),
  (38, 'Fine Art', array['art', 'med', 'rec']::text[]),
  (39, 'Performing Arts', array['art', 'med', 'rec']::text[]),
  (40, 'Recreational Facilities and Services', array['rec', 'serv']::text[]),
  (41, 'Banking', array['fin']::text[]),
  (42, 'Insurance', array['fin']::text[]),
  (43, 'Financial Services', array['fin']::text[]),
  (44, 'Real Estate', array['cons', 'fin', 'good']::text[]),
  (45, 'Investment Banking', array['fin']::text[]),
  (46, 'Investment Management', array['fin']::text[]),
  (47, 'Accounting', array['corp', 'fin']::text[]),
  (48, 'Construction', array['cons']::text[]),
  (49, 'Building Materials', array['cons']::text[]),
  (50, 'Architecture & Planning', array['cons']::text[]),
  (51, 'Civil Engineering', array['cons', 'gov']::text[]),
  (52, 'Aviation & Aerospace', array['gov', 'man']::text[]),
  (53, 'Automotive', array['man']::text[]),
  (54, 'Chemicals', array['man']::text[]),
  (55, 'Machinery', array['man']::text[]),
  (56, 'Mining & Metals', array['man']::text[]),
  (57, 'Oil & Energy', array['man']::text[]),
  (58, 'Shipbuilding', array['man']::text[]),
  (59, 'Utilities', array['man']::text[]),
  (60, 'Textiles', array['man']::text[]),
  (61, 'Paper & Forest Products', array['man']::text[]),
  (62, 'Railroad Manufacture', array['man']::text[]),
  (63, 'Farming', array['agr']::text[]),
  (64, 'Ranching', array['agr']::text[]),
  (65, 'Dairy', array['agr']::text[]),
  (66, 'Fishery', array['agr']::text[]),
  (67, 'Primary/Secondary Education', array['edu']::text[]),
  (68, 'Higher Education', array['edu']::text[]),
  (69, 'Education Management', array['edu']::text[]),
  (70, 'Research', array['edu', 'gov']::text[]),
  (71, 'Military', array['gov']::text[]),
  (72, 'Legislative Office', array['gov', 'leg']::text[]),
  (73, 'Judiciary', array['gov', 'leg']::text[]),
  (74, 'International Affairs', array['gov']::text[]),
  (75, 'Government Administration', array['gov']::text[]),
  (76, 'Executive Office', array['gov']::text[]),
  (77, 'Law Enforcement', array['gov', 'leg']::text[]),
  (78, 'Public Safety', array['gov']::text[]),
  (79, 'Public Policy', array['gov']::text[]),
  (80, 'Marketing and Advertising', array['corp', 'med']::text[]),
  (81, 'Newspapers', array['med', 'rec']::text[]),
  (82, 'Publishing', array['med', 'rec']::text[]),
  (83, 'Printing', array['med', 'rec']::text[]),
  (84, 'Information Services', array['med', 'serv']::text[]),
  (85, 'Libraries', array['med', 'rec', 'serv']::text[]),
  (86, 'Environmental Services', array['org', 'serv']::text[]),
  (87, 'Package/Freight Delivery', array['serv', 'tran']::text[]),
  (88, 'Individual & Family Services', array['org', 'serv']::text[]),
  (89, 'Religious Institutions', array['org', 'serv']::text[]),
  (90, 'Civic & Social Organization', array['org', 'serv']::text[]),
  (91, 'Consumer Services', array['org', 'serv']::text[]),
  (92, 'Transportation/Trucking/Railroad', array['tran']::text[]),
  (93, 'Warehousing', array['tran']::text[]),
  (94, 'Airlines/Aviation', array['man', 'tech', 'tran']::text[]),
  (95, 'Maritime', array['tran']::text[]),
  (96, 'Information Technology and Services', array['tech']::text[]),
  (97, 'Market Research', array['corp']::text[]),
  (98, 'Public Relations and Communications', array['corp']::text[]),
  (99, 'Design', array['art', 'med']::text[]),
  (100, 'Non-Profit Organization Management', array['org']::text[]),
  (101, 'Fund-Raising', array['org']::text[]),
  (102, 'Program Development', array['corp', 'org']::text[]),
  (103, 'Writing and Editing', array['art', 'med', 'rec']::text[]),
  (104, 'Staffing and Recruiting', array['corp']::text[]),
  (105, 'Professional Training & Coaching', array['corp']::text[]),
  (106, 'Venture Capital & Private Equity', array['fin', 'tech']::text[]),
  (107, 'Political Organization', array['gov', 'org']::text[]),
  (108, 'Translation and Localization', array['corp', 'gov', 'serv']::text[]),
  (109, 'Computer Games', array['med', 'rec']::text[]),
  (110, 'Events Services', array['corp', 'rec', 'serv']::text[]),
  (111, 'Arts and Crafts', array['art', 'med', 'rec']::text[]),
  (112, 'Electrical/Electronic Manufacturing', array['good', 'man']::text[]),
  (113, 'Online Media', array['med']::text[]),
  (114, 'Nanotechnology', array['gov', 'man', 'tech']::text[]),
  (115, 'Music', array['art', 'rec']::text[]),
  (116, 'Logistics and Supply Chain', array['corp', 'tran']::text[]),
  (117, 'Plastics', array['man']::text[]),
  (118, 'Computer & Network Security', array['tech']::text[]),
  (119, 'Wireless', array['tech']::text[]),
  (120, 'Alternative Dispute Resolution', array['leg', 'org']::text[]),
  (121, 'Security and Investigations', array['corp', 'org', 'serv']::text[]),
  (122, 'Facilities Services', array['corp', 'serv']::text[]),
  (123, 'Outsourcing/Offshoring', array['corp']::text[]),
  (124, 'Health, Wellness and Fitness', array['hlth', 'rec']::text[]),
  (125, 'Alternative Medicine', array['hlth']::text[]),
  (126, 'Media Production', array['med', 'rec']::text[]),
  (127, 'Animation', array['art', 'med']::text[]),
  (128, 'Commercial Real Estate', array['cons', 'corp', 'fin']::text[]),
  (129, 'Capital Markets', array['fin']::text[]),
  (130, 'Think Tanks', array['gov', 'org']::text[]),
  (131, 'Philanthropy', array['org']::text[]),
  (132, 'E-Learning', array['edu', 'org']::text[]),
  (133, 'Wholesale', array['good']::text[]),
  (134, 'Import and Export', array['corp', 'good', 'tran']::text[]),
  (135, 'Mechanical or Industrial Engineering', array['cons', 'gov', 'man']::text[]),
  (136, 'Photography', array['art', 'med', 'rec']::text[]),
  (137, 'Human Resources', array['corp']::text[]),
  (138, 'Business Supplies and Equipment', array['corp', 'man']::text[]),
  (139, 'Mental Health Care', array['hlth']::text[]),
  (140, 'Graphic Design', array['art', 'med']::text[]),
  (141, 'International Trade and Development', array['gov', 'org', 'tran']::text[]),
  (142, 'Wine and Spirits', array['good', 'man', 'rec']::text[]),
  (143, 'Luxury Goods & Jewelry', array['good']::text[]),
  (144, 'Renewables & Environment', array['gov', 'man', 'org']::text[]),
  (145, 'Glass, Ceramics & Concrete', array['cons', 'man']::text[]),
  (146, 'Packaging and Containers', array['good', 'man']::text[]),
  (147, 'Industrial Automation', array['cons', 'man']::text[]),
  (148, 'Government Relations', array['gov']::text[])
on conflict (code) do update
  set description = excluded.description, groups = excluded.groups;

insert into public.sector_group_crosswalk (v2_industry_group, v2_sector_slug, linkedin_code, confidence, note) values
  ('Food and Beverage Services', 'accommodation-and-food-services', 34, 'high', null),
  ('Hospitality', 'accommodation-and-food-services', 31, 'high', null),
  ('Collection Agencies', 'administrative-and-support-services', 43, 'low', 'No 147 entry for debt collection; financial-services-adjacent'),
  ('Events Services', 'administrative-and-support-services', 110, 'high', null),
  ('Facilities Services', 'administrative-and-support-services', 122, 'high', null),
  ('Fundraising', 'administrative-and-support-services', 101, 'high', null),
  ('Office Administration', 'administrative-and-support-services', 123, 'low', 'No 147 entry for office administration; nearest business-support entry'),
  ('Security and Investigations', 'administrative-and-support-services', 121, 'high', null),
  ('Telephone Call Centers', 'administrative-and-support-services', 123, 'medium', null),
  ('Staffing and Recruiting', 'administrative-and-support-services', 104, 'high', null),
  ('Translation and Localization', 'administrative-and-support-services', 108, 'high', null),
  ('Travel Arrangements', 'administrative-and-support-services', 30, 'high', null),
  ('Writing and Editing', 'administrative-and-support-services', 103, 'high', null),
  ('Building Construction', 'construction', 48, 'high', null),
  ('Civil Engineering', 'construction', 51, 'high', null),
  ('Specialty Trade Contractors', 'construction', 48, 'high', null),
  ('Civic and Social Organizations', 'consumer-services', 90, 'high', null),
  ('Household Services', 'consumer-services', 91, 'high', null),
  ('Non-profit Organizations', 'consumer-services', 100, 'high', null),
  ('Personal and Laundry Services', 'consumer-services', 91, 'high', null),
  ('Philanthropic Fundraising Services', 'consumer-services', 131, 'high', null),
  ('Religious Institutions', 'consumer-services', 89, 'high', null),
  ('Repair and Maintenance', 'consumer-services', 91, 'medium', null),
  ('E-Learning Providers', 'education', 132, 'high', null),
  ('Higher Education', 'education', 68, 'high', null),
  ('Primary and Secondary Education', 'education', 67, 'high', null),
  ('Professional Training and Coaching', 'education', 105, 'high', null),
  ('Technical and Vocational Training', 'education', 105, 'medium', 'No 147 vocational-training entry'),
  ('Artists and Writers', 'entertainment-providers', 38, 'medium', 'Split concept; 103 Writing and Editing secondary'),
  ('Museums, Historical Sites, and Zoos', 'entertainment-providers', 37, 'high', null),
  ('Musicians', 'entertainment-providers', 115, 'high', null),
  ('Performing Arts and Spectator Sports', 'entertainment-providers', 39, 'medium', '33 Sports secondary'),
  ('Recreational Facilities', 'entertainment-providers', 40, 'high', null),
  ('Spectator Sports', 'entertainment-providers', 33, 'high', null),
  ('Farming', 'farming-ranching-forestry', 63, 'high', null),
  ('Ranching and Fisheries', 'farming-ranching-forestry', 64, 'medium', '66 Fishery secondary'),
  ('Forestry and Logging', 'farming-ranching-forestry', 61, 'medium', null),
  ('Capital Markets', 'financial-services', 129, 'high', null),
  ('Credit Intermediation', 'financial-services', 41, 'high', null),
  ('Funds and Trusts', 'financial-services', 46, 'high', null),
  ('Insurance', 'financial-services', 42, 'high', null),
  ('Administration of Justice', 'government-administration', 73, 'medium', '77 Law Enforcement secondary'),
  ('Economic Programs', 'government-administration', 75, 'medium', '141 International Trade and Development secondary'),
  ('Environmental Quality Programs', 'government-administration', 86, 'medium', null),
  ('Health and Human Services', 'government-administration', 75, 'medium', '88 Individual & Family Services secondary'),
  ('Housing and Community Development', 'government-administration', 75, 'medium', null),
  ('Military and International Affairs', 'government-administration', 71, 'medium', '74 International Affairs secondary'),
  ('Public Policy', 'government-administration', 79, 'high', null),
  ('Public Policy Offices', 'government-administration', 79, 'medium', '130 Think Tanks secondary'),
  ('Space Research and Technology', 'government-administration', 1, 'high', null),
  ('Holding Companies', 'holding-companies', 46, 'low', 'No 147 holding-companies entry — flag for decision'),
  ('Community Services', 'hospitals-and-health-care', 88, 'medium', null),
  ('Hospitals, Individual and Family Services', 'hospitals-and-health-care', 14, 'high', null),
  ('Medical Practices', 'hospitals-and-health-care', 13, 'high', null),
  ('Nursing Homes and Residential Care Facilities', 'hospitals-and-health-care', 14, 'medium', null),
  ('Apparel Manufacturing', 'manufacturing', 19, 'high', null),
  ('Appliances, Electrical, and Electronics Manufacturing', 'manufacturing', 112, 'high', null),
  ('Chemical Manufacturing', 'manufacturing', 54, 'high', null),
  ('Computers and Electronics Manufacturing', 'manufacturing', 3, 'medium', '24 Consumer Electronics secondary'),
  ('Fabricated Metal Products', 'manufacturing', 55, 'low', 'No 147 fabricated-metal entry; 56 Mining & Metals secondary'),
  ('Food and Beverage Manufacturing', 'manufacturing', 23, 'high', null),
  ('Furniture and Home Furnishings Manufacturing', 'manufacturing', 26, 'high', null),
  ('Glass, Ceramics and Concrete Manufacturing', 'manufacturing', 145, 'high', null),
  ('Leather Product Manufacturing', 'manufacturing', 19, 'low', null),
  ('Machinery Manufacturing', 'manufacturing', 55, 'high', null),
  ('Medical Equipment Manufacturing', 'manufacturing', 17, 'high', null),
  ('Oil and Coal Product Manufacturing', 'manufacturing', 57, 'medium', null),
  ('Paper and Forest Product Manufacturing', 'manufacturing', 61, 'high', null),
  ('Plastics and Rubber Product Manufacturing', 'manufacturing', 117, 'high', null),
  ('Primary Metal Manufacturing', 'manufacturing', 56, 'medium', null),
  ('Printing Services', 'manufacturing', 83, 'high', null),
  ('Sporting Goods Manufacturing', 'manufacturing', 20, 'high', null),
  ('Textile Manufacturing', 'manufacturing', 60, 'high', null),
  ('Tobacco Manufacturing', 'manufacturing', 21, 'high', null),
  ('Transportation Equipment Manufacturing', 'manufacturing', 53, 'medium', '62 Railroad Manufacture / 58 Shipbuilding secondary'),
  ('Wood Product Manufacturing', 'manufacturing', 61, 'medium', null),
  ('Mining', 'oil-gas-and-mining', 56, 'high', null),
  ('Oil and Gas', 'oil-gas-and-mining', 57, 'high', null),
  ('Accounting', 'professional-services', 47, 'high', null),
  ('Advertising Services', 'professional-services', 80, 'high', null),
  ('Architecture and Planning', 'professional-services', 50, 'high', null),
  ('Business Consulting and Services', 'professional-services', 11, 'high', null),
  ('Design Services', 'professional-services', 99, 'high', null),
  ('Engineering Services', 'professional-services', 135, 'medium', null),
  ('IT Services and IT Consulting', 'professional-services', 96, 'high', null),
  ('Legal Services', 'professional-services', 10, 'high', null),
  ('Research Services', 'professional-services', 70, 'high', null),
  ('Services for Renewable Energy', 'professional-services', 144, 'high', null),
  ('Veterinary Services', 'professional-services', 16, 'high', null),
  ('Equipment Rental Services', 'real-estate-and-equipment-rental-services', 138, 'low', 'No 147 rental entry — flag for decision'),
  ('Real Estate', 'real-estate-and-equipment-rental-services', 44, 'high', null),
  ('Food and Beverage Retail', 'retail', 22, 'medium', null),
  ('Online and Mail Order Retail', 'retail', 27, 'medium', '6 Internet secondary (e-commerce)'),
  ('Retail Apparel and Fashion', 'retail', 19, 'high', null),
  ('Retail Appliances, Electrical, and Electronic Equipment', 'retail', 24, 'medium', null),
  ('Retail Art Dealers', 'retail', 38, 'medium', null),
  ('Retail Art Supplies', 'retail', 111, 'medium', null),
  ('Retail Books and Printed News', 'retail', 27, 'medium', '82 Publishing secondary'),
  ('Retail Building Materials and Garden Equipment', 'retail', 49, 'medium', null),
  ('Retail Florists', 'retail', 27, 'medium', null),
  ('Retail Furniture and Home Furnishings', 'retail', 26, 'medium', null),
  ('Retail Gasoline', 'retail', 57, 'low', null),
  ('Retail Health and Personal Care Products', 'retail', 27, 'medium', '18 Cosmetics secondary'),
  ('Retail Luxury Goods and Jewelry', 'retail', 143, 'high', null),
  ('Retail Motor Vehicles', 'retail', 53, 'medium', null),
  ('Retail Musical Instruments', 'retail', 27, 'medium', null),
  ('Retail Office Equipment', 'retail', 138, 'medium', null),
  ('Retail Office Supplies and Gifts', 'retail', 138, 'medium', null),
  ('Retail Recyclable Materials and Used Merchandise', 'retail', 27, 'medium', null),
  ('Book and Periodical Publishing', 'technology-information-and-media', 82, 'high', null),
  ('Broadcast Media Production and Distribution', 'technology-information-and-media', 36, 'high', null),
  ('Data Infrastructure and Analytics', 'technology-information-and-media', 84, 'medium', 'Primary anchor for AI/data cluster; 4 Computer Software secondary'),
  ('Information Services', 'technology-information-and-media', 84, 'high', null),
  ('Internet Marketplace Platforms', 'technology-information-and-media', 6, 'high', null),
  ('Movies, Videos, and Sound', 'technology-information-and-media', 35, 'high', null),
  ('Social Networking Platforms', 'technology-information-and-media', 6, 'medium', '113 Online Media secondary'),
  ('Software Development', 'technology-information-and-media', 4, 'high', null),
  ('Telecommunications', 'technology-information-and-media', 8, 'high', null),
  ('Airlines and Aviation', 'transportation-logistics-supply-chain-and-storage', 94, 'high', null),
  ('Freight and Package Transportation', 'transportation-logistics-supply-chain-and-storage', 87, 'high', null),
  ('Ground Passenger Transportation', 'transportation-logistics-supply-chain-and-storage', 92, 'medium', null),
  ('Maritime Transportation', 'transportation-logistics-supply-chain-and-storage', 95, 'high', null),
  ('Pipeline Transportation', 'transportation-logistics-supply-chain-and-storage', 57, 'low', null),
  ('Postal Services', 'transportation-logistics-supply-chain-and-storage', 87, 'medium', null),
  ('Rail Transportation', 'transportation-logistics-supply-chain-and-storage', 92, 'high', null),
  ('Truck Transportation', 'transportation-logistics-supply-chain-and-storage', 92, 'high', null),
  ('Warehousing and Storage', 'transportation-logistics-supply-chain-and-storage', 93, 'high', null),
  ('Electric Power Generation', 'utilities', 59, 'high', null),
  ('Electric Power Transmission, Control, and Distribution', 'utilities', 59, 'high', null),
  ('Natural Gas Distribution', 'utilities', 59, 'medium', '57 Oil & Energy secondary'),
  ('Water, Waste, Steam, and Air Conditioning Services', 'utilities', 59, 'medium', '86 Environmental Services secondary'),
  ('Wholesale Alcoholic Beverages', 'wholesale', 142, 'medium', '133 Wholesale secondary'),
  ('Wholesale Apparel and Sewing Supplies', 'wholesale', 133, 'high', null),
  ('Wholesale Appliances, Electrical, and Electronics', 'wholesale', 133, 'high', null),
  ('Wholesale Building Materials', 'wholesale', 133, 'high', '49 Building Materials secondary'),
  ('Wholesale Chemical and Allied Products', 'wholesale', 133, 'high', null),
  ('Wholesale Computer Equipment', 'wholesale', 133, 'high', null),
  ('Wholesale Drugs and Sundries', 'wholesale', 133, 'high', null),
  ('Wholesale Food and Beverage', 'wholesale', 133, 'high', null),
  ('Wholesale Footwear', 'wholesale', 133, 'high', null),
  ('Wholesale Furniture and Home Furnishings', 'wholesale', 133, 'high', null),
  ('Wholesale Hardware, Plumbing, Heating Equipment', 'wholesale', 133, 'high', null),
  ('Wholesale Import and Export', 'wholesale', 134, 'high', null),
  ('Wholesale Luxury Goods and Jewelry', 'wholesale', 133, 'high', '143 Luxury Goods & Jewelry secondary'),
  ('Wholesale Machinery', 'wholesale', 133, 'high', null),
  ('Wholesale Metals and Minerals', 'wholesale', 133, 'high', null),
  ('Wholesale Motor Vehicles and Parts', 'wholesale', 133, 'high', null),
  ('Wholesale Paper Products', 'wholesale', 133, 'high', null),
  ('Wholesale Petroleum and Petroleum Products', 'wholesale', 133, 'high', null),
  ('Wholesale Photography Equipment and Supplies', 'wholesale', 133, 'high', null),
  ('Wholesale Raw Farm Products', 'wholesale', 133, 'high', null),
  ('Wholesale Recyclable Materials', 'wholesale', 133, 'high', null)
on conflict (v2_industry_group) do update
  set v2_sector_slug = excluded.v2_sector_slug,
      linkedin_code = excluded.linkedin_code,
      confidence = excluded.confidence,
      note = excluded.note;
