
-- Update executive_summary: add bilateral trade, grants, and end buyer research
UPDATE report_templates 
SET 
  variables = array_cat(variables, ARRAY['market_research_bilateral_trade', 'market_research_grants', 'end_buyer_research']),
  prompt_body = E'Write an executive summary for {{company_name}}''s market entry into Australia.\n\nEnriched company profile:\n{{enriched_company_profile}}\n\nCompany context:\n- Stage: {{company_stage}}\n- Industry: {{industry_sector}}\n- Origin: {{country_of_origin}}\n- Target regions: {{target_regions}}\n- Services needed: {{services_needed}}\n- Timeline: {{timeline}}\n- Budget: {{budget_level}}\n- Goals: {{primary_goals}}\n- Challenges: {{key_challenges}}\n\n--- MARKET LANDSCAPE ---\n{{market_research_landscape}}\n\n--- BILATERAL TRADE CORRIDOR ---\nTrade relationship between {{country_of_origin}} and Australia:\n{{market_research_bilateral_trade}}\n\n--- GOVERNMENT GRANTS & INCENTIVES ---\nAvailable funding and support programs:\n{{market_research_grants}}\n\n--- END BUYER INSIGHTS ---\nTarget customer procurement intelligence:\n{{end_buyer_research}}\n\nWrite a compelling 3-4 paragraph executive summary that:\n1. Opens with a clear statement of {{company_name}}''s value proposition and market opportunity in Australia (use the enriched profile data for specifics)\n2. Summarizes the key market conditions, opportunity size, and any relevant bilateral trade advantages between {{country_of_origin}} and Australia\n3. Highlights key government incentives or grants the company should leverage\n4. Outlines the recommended approach and timeline\n5. Concludes with expected outcomes and next steps\n\nUse **bold** for key statistics and important terms. Reference specific products, clients, or USPs from the enriched profile where available.',
  updated_at = now()
WHERE section_name = 'executive_summary' AND is_active = true;

-- Update swot_analysis: add bilateral trade and cost of business
UPDATE report_templates 
SET 
  variables = array_cat(variables, ARRAY['market_research_bilateral_trade', 'market_research_cost_of_business']),
  prompt_body = E'Generate a SWOT analysis for {{company_name}}, a {{company_stage}} {{industry_sector}} company from {{country_of_origin}} entering Australia targeting {{target_regions}}.\n\nCompany context: {{enriched_summary}}\n\n--- REAL MARKET RESEARCH DATA ---\nMarket Landscape:\n{{market_research_landscape}}\n\nRegulatory & Compliance:\n{{market_research_regulatory}}\n\nRecent News & Developments:\n{{market_research_news}}\n\n--- BILATERAL TRADE CORRIDOR ---\nTrade relationship between {{country_of_origin}} and Australia:\n{{market_research_bilateral_trade}}\n\n--- COST OF DOING BUSINESS ---\nOperational costs in {{target_regions}}:\n{{market_research_cost_of_business}}\n\nStrengths: based on company context and capabilities. Include any bilateral trade advantages (e.g. free trade agreements, existing trade corridors) between {{country_of_origin}} and Australia.\nWeaknesses: common challenges for {{country_of_origin}} companies in {{industry_sector}}. Consider cost factors from the cost-of-business data.\nOpportunities: use the market landscape research above to identify specific, data-backed opportunities in the Australian market. Reference any bilateral trade facilitation or incentive programs.\nThreats: use the regulatory research above to identify specific compliance risks, plus competitive, cost, and cultural factors from the news and cost data.\n\nFormat as 4 sections with 3-4 bullet points each. Be specific to the company and market. Reference real data points from the research above.\n\nSources:\n{{market_research_citations}}',
  updated_at = now()
WHERE section_name = 'swot_analysis' AND is_active = true;

-- Update action_plan: add bilateral trade, cost of business, grants, end buyer research
UPDATE report_templates 
SET 
  variables = array_cat(variables, ARRAY['market_research_bilateral_trade', 'market_research_cost_of_business', 'market_research_grants', 'end_buyer_research']),
  prompt_body = E'Create a phased action plan for {{company_name}} to enter Australia within their {{timeline}} timeline on a {{budget_level}} budget.\n\nCompany: {{company_stage}} {{industry_sector}} from {{country_of_origin}}, targeting {{target_regions}}.\nServices needed: {{services_needed}}\nGoals: {{primary_goals}}\n\n--- REGULATORY & COMPLIANCE REQUIREMENTS ---\nUse the following real regulatory research to inform Phase 1 requirements:\n{{market_research_regulatory}}\n\n--- MARKET LANDSCAPE ---\nUse the following market data to inform Phase 3 go-to-market strategy:\n{{market_research_landscape}}\n\n--- RECENT DEVELOPMENTS ---\n{{market_research_news}}\n\n--- BILATERAL TRADE CORRIDOR ---\nTrade relationship and agreements between {{country_of_origin}} and Australia:\n{{market_research_bilateral_trade}}\n\n--- COST OF DOING BUSINESS ---\nOperational costs and setup expenses in {{target_regions}}:\n{{market_research_cost_of_business}}\n\n--- GOVERNMENT GRANTS & INCENTIVES ---\nAvailable funding, grants, and support programs:\n{{market_research_grants}}\n\n--- END BUYER INSIGHTS ---\nTarget customer procurement intelligence:\n{{end_buyer_research}}\n\nPhase 1 - Foundation (Month 1-2): Legal entity setup, banking, compliance, visa requirements. Reference specific regulatory requirements from the research above. Include estimated setup costs from the cost-of-business data. Highlight any government grants or incentives the company should apply for immediately.\nPhase 2 - Establish (Month 2-4): Office space, initial team, partnerships, local network. Use cost-of-business data for budgeting (rent, salaries, super). Leverage bilateral trade organisations and programs.\nPhase 3 - Launch (Month 4-6): Go-to-market strategy informed by market trends above, lead generation, PR, growth. Use end buyer procurement insights to inform sales approach and channel strategy.\n\nInclude specific next steps. Reference the matched service providers where relevant: {{matched_providers_summary}}. Be specific and actionable with real regulatory, cost, and market data.\n\nSources:\n{{market_research_citations}}',
  updated_at = now()
WHERE section_name = 'action_plan' AND is_active = true;
