// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhziwveaiuhzdoutpgrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoeml3dmVhaXVoemRvdXRwZ3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDkwNTQsImV4cCI6MjA2NTAyNTA1NH0.nuQeyhR_vwrdsFG7SQHdQtQQ_KpjFRxqyZTr-krpGaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);